'use client';
import ObjectWorkspace from '@/components/phase3/object-workspace';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';import ExportButton from '@/components/phase4/export-button';
type Row=Record<string,any>;
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function Work({objectId}:{objectId:string}){const {data,error,reload}=useApi<Row>('/api/v1/circular/overview?objectId='+objectId);if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取物料记录…</p>;
 const common={stableKey:true,onSaved:()=>void reload()},hidden=<input type="hidden" name="objectId" value={objectId}/>,lots=data.lots.filter((r:Row)=>r.unit==='kg').map((r:Row)=>({id:r.id,name:r.product+' / '+r.code+' / '+r.basis})),batches=data.batches.map((r:Row)=>({id:r.lot_id,name:r.product+' / '+r.code}));
 return <div className="stack"><p className="hint">每类显示最近200条。先在<a href="/inventory">库存与批次</a>登记kg批次和仓位；检测与放行从<a href="/traceability">质量与溯源</a>办理。称量入库会直接写库存，不要重复手工入库。</p>
 <details><summary>登记循环物料来源</summary><ActionForm path="/api/v1/circular/batches" {...common}><Pick name="lotId" label="已有物料批次" options={lots}/><Pick name="materialKind" label="物料类别" options={['silt','manure','straw','mushroom','compost','other'].map((id,i)=>({id,name:['淤泥','粪肥','秸秆','菌菇剩余物','堆肥','其他'][i]}))}/><Field name="originRef" label="来源批、原始资料与用途依据"/></ActionForm></details>
 <details><summary>接收称量并入库</summary><ActionForm path="/api/v1/circular/receipts" {...common} times={['occurredAt']}><Pick name="lotId" label="接收批次" options={batches}/><Pick name="locationId" label="接收仓位" options={data.locations}/><Field name="grossKg" label="毛重kg"/><Field name="tareKg" label="皮重kg"/><Field name="netKg" label="净重kg"/><Pick name="basis" label="称量口径" options={[{id:'wet',name:'湿基'},{id:'dry',name:'干基'},{id:'as_is',name:'原样'}]}/><Field name="moisturePct" label="实测含水率%（未知留空）" required={false}/><Field name="voucher" label="称量凭证号"/><Field name="occurredAt" label="实际接收时间" type="datetime-local"/><Field name="evidence" label="称量仪器、来源和原单依据"/></ActionForm></details>
 <details><summary>处理与筛分返料</summary><p>输入须当前已放行；输出须新待检批次。返料建立新批次，不能回写原来源批。</p><ActionForm path="/api/v1/circular/processes" {...common} times={['occurredAt']} jsonFields={['inputs','outputs']}>{hidden}<Field name="code" label="长期处理编号"/><Pick name="processKind" label="处理类型" options={[{id:'treatment',name:'处理'},{id:'screening',name:'筛分'},{id:'rework',name:'返料再处理'}]}/><label>输入批次与数量JSON<textarea name="inputs" required placeholder='[{"lotId":"批次ID","locationId":"仓位ID","quantity":"10"}]'/></label><label>输出批次与数量JSON<textarea name="outputs" required placeholder='[{"lotId":"新批次ID","locationId":"仓位ID","quantity":"9"}]'/></label><Field name="occurredAt" label="实际处理时间" type="datetime-local"/><Field name="reason" label="损耗、鲜干基或计量差异说明" required={false}/><Field name="evidence" label="处理原始依据"/></ActionForm></details>
 <StockTable rows={data.batches} columns={[[ 'code','批号'],['material_kind','物料'],['basis','口径'],['state','审核状态'],['origin_ref','来源'],['lot_id','批次引用']]}/><StockTable rows={data.weighings} columns={[[ 'voucher','凭证'],['gross_kg','毛重kg'],['tare_kg','皮重kg'],['net_kg','净重kg'],['moisture_pct','含水率%'],['dry_kg','辅助干重kg'],['basis','口径']]}/><StockTable rows={data.processes} columns={[[ 'process_kind','处理'],['metadata','差额与依据'],['evidence','原始依据']]}/><StockTable rows={data.balances} columns={[[ 'code','库存批号'],['location_name','仓位'],['quantity','余额'],['basis','口径']]}/><p>去向、发货与实际签收见库存与批次；上下游追查和当前检测有效性见质量与溯源。</p><ExportButton path={'/api/v1/circular/export?objectId='+objectId} name="循环物料与库存关系"/></div>;}
