'use client';
import ResourceShare from '@/components/phase3/resource-share';
import {useState} from 'react';import ObjectWorkspace from '@/components/phase3/object-workspace';import GeometryPreview from '@/components/phase3/geometry-preview';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';
type Row=Record<string,any>;const options=(pairs:[string,string][])=>pairs.map(([id,name])=>({id,name}));
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function Work({objectId}:{objectId:string}){
 const {data,error,reload}=useApi<Row>('/api/v1/protection/overview?objectId='+objectId),[detail,setDetail]=useState('');
 if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取植保资料…</p>;
 const common={stableKey:true,onSaved:()=>void reload()},hidden=<input type="hidden" name="objectId" value={objectId}/>,plans=data.plans.map((r:Row)=>({id:r.id,name:r.title+' / 版本'+r.version})),lots=data.lots.map((r:Row)=>({id:r.id,name:r.product+' / '+r.unit,code:r.code})),maps=data.prescriptions.map((r:Row)=>({id:r.id,name:'版本'+r.version+' / '+r.state+' / '+r.basis})),executions=data.executions.map((r:Row)=>({id:r.id,name:r.operator+' / '+r.started_at})),media=data.media.map((r:Row)=>({id:r.id,name:r.name}));
 const plan=<Pick name="planId" label="植保计划" options={plans}/>,at=<Field name="occurredAt" label="实际发生时间" type="datetime-local"/>,evidence=<Field name="evidence" label="原始依据"/>;
 return <div className="stack"><p className="hint">每类显示最近100条。先从<a href="/inventory">库存与批次</a>登记投入品，从<a href="/imagery">监控与航次</a>导入原件。</p>
 <StockTable rows={data.plans} columns={[[ 'title','计划'],['crop','作物'],['stage','阶段'],['target','目标'],['version','版本'],['id','导入引用']]}/>
 <details><summary>登记植保计划</summary><ActionForm path="/api/v1/protection/plans" {...common} jsonFields={['boundary','sensitiveAreas']}>{hidden}<Field name="title" label="计划名称"/><Field name="crop" label="作物"/><Field name="target" label="作业目标"/><Field name="stage" label="现场已核生育阶段"/><Pick name="inputLotId" label="投入品批次" options={lots}/><Field name="taskId" label="关联任务（可选）" required={false}/><label>已核地块边界GeoJSON<textarea name="boundary" required placeholder='{"type":"Polygon","coordinates":[...]}'/></label><Field name="obstacles" label="障碍及位置说明"/><label>敏感邻区清单GeoJSON<textarea name="sensitiveAreas" defaultValue="[]"/></label><Field name="sensitiveNote" label="敏感邻区核实说明（未知须写明）"/><Field name="conditions" label="执行条件及专业依据"/><Field name="source" label="计划来源"/><Pick name="supersedesId" label="修订原计划（可选）" options={plans} required={false}/></ActionForm></details>
 <details><summary>处方分区与专业审核</summary><ActionForm path="/api/v1/protection/prescriptions" {...common} jsonFields={['zones']}>{plan}<Pick name="sourceAssetId" label="来源影像（可选）" options={media} required={false}/><Field name="sourceAnalysisId" label="来源指数产品（可选）" required={false}/><label>1至5层处方分区<textarea name="zones" required placeholder='[{"name":"分区一","rate":"专业填写每亩剂量","geometry":{"type":"Polygon","coordinates":[...]}}]'/></label><Pick name="doseUnit" label="每亩剂量单位" options={options([['kg/亩','kg/亩'],['L/亩','L/亩'],['g/亩','g/亩'],['mL/亩','mL/亩']])}/><Field name="basis" label="剂量、适用条件及来源依据"/></ActionForm><ActionForm path="/api/v1/protection/prescription-review" {...common}><Pick name="id" label="处方版本" options={maps}/><Pick name="action" label="专业审核动作" options={options([['approve','独立审核通过'],['withdraw','撤回']])}/>{evidence}</ActionForm><StockTable rows={data.prescriptions} columns={[[ 'version','版本'],['dose_unit','剂量单位'],['state','审核状态'],['basis','依据']]}/></details>
 <details><summary>记录处方分享、下载或施用事实</summary><ActionForm path="/api/v1/protection/prescription-events" {...common} times={['occurredAt']}><Pick name="prescriptionId" label="已审核处方" options={maps}/><Pick name="action" label="实际完成事项" options={options([['shared','已分享'],['downloaded','已下载'],['applied','已施用']])}/><Pick name="executionId" label="施用对应实际作业（施用时必选）" options={executions} required={false}/><Field name="party" label="相关主体"/>{at}{evidence}</ActionForm><StockTable rows={data.events} columns={[[ 'action','事实'],['party','主体'],['occurred_at','时间'],['evidence','依据']]}/></details>
 <details><summary>登记实际作业与补作</summary><ActionForm path="/api/v1/protection/executions" {...common} times={['startedAt','endedAt']} numbers={['swathM','maxGapSeconds']} jsonFields={['track']}>{plan}<Pick name="prescriptionId" label="实际使用处方（可选）" options={maps} required={false}/><Field name="operator" label="实际操作者"/><Field name="startedAt" label="实际开始" type="datetime-local"/><Field name="endedAt" label="实际结束" type="datetime-local"/><label>轨迹、启停及流量（未知可为空数组）<textarea name="track" defaultValue="[]"/></label><Field name="swathM" label="已核喷幅米（未知留空）" type="number" required={false}/><Field name="maxGapSeconds" label="已核连续间隔上限秒（未知留空）" type="number" required={false}/><Field name="materialQuantity" label="实际材料量（未知留空）" required={false}/><Pick name="unit" label="材料单位" options={options([['kg','kg'],['L','L'],['piece','件']])}/><Field name="resultCheck" label="已有复查说明（可选）" required={false}/><Pick name="remediationOf" label="补作原作业（可选）" options={executions} required={false}/><Pick name="cause" label="补作原因类型" options={options([['data_equipment','数据或设备'],['environment','环境或现场'],['organization','操作或组织']])} required={false}/><Field name="remediationCost" label="补作费用CNY（未知留空）" required={false}/>{evidence}</ActionForm></details>
 <details><summary>离线批量导入作业</summary><ImportForm objectId={objectId} reload={reload}/><StockTable rows={data.imports} columns={[[ 'source_ref','来源'],['result_rows','逐行结果'],['created_at','导入时间']]}/></details>
 <section><h2>实际作业与缺口</h2><StockTable rows={data.executions} columns={[[ 'operator','操作者'],['started_at','开始'],['covered_m2','疑似覆盖m²'],['missed_m2','疑似漏作m²'],['overlap_m2','疑似重作m²'],['missing','缺口'],['material_quantity','材料量'],['unit','单位']]}/><label>查看作业范围与定位<select aria-label="查看作业范围与定位" value={detail} onChange={e=>setDetail(e.target.value)}><option value="">请选择作业</option>{executions.map((r:Row)=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label>{detail&&<ExecutionDetail id={detail}/>}</section>
 <details><summary>服务商交付与结果复查</summary><ActionForm path="/api/v1/protection/deliveries" {...common} times={['occurredAt']} jsonFields={['assetIds']}>{plan}<Field name="provider" label="服务商"/><Pick name="kind" label="交付内容" options={options([['raw_images','采像原件'],['processed','加工成果'],['work_order','作业单'],['track','轨迹'],['arrival','到场确认'],['followup','复查']])}/><label>已入库文件ID数组<textarea name="assetIds" defaultValue="[]"/></label><Field name="missing" label="完整性或缺项说明"/><Field name="receivedBy" label="实际接收人"/>{at}{evidence}</ActionForm><ActionForm path="/api/v1/protection/followups" {...common} times={['occurredAt']}><Pick name="executionId" label="复查原作业" options={executions}/><Field name="observation" label="现场观察"/><Field name="judgment" label="人员判断"/><Field name="action" label="后续动作或无动作说明"/>{at}{evidence}</ActionForm><StockTable rows={data.deliveries} columns={[[ 'provider','服务商'],['kind','交付'],['missing','缺项'],['received_by','接收人']]}/><StockTable rows={data.followups} columns={[[ 'observation','观察'],['judgment','判断'],['action','后续动作']]}/></details>
 <ResourceShare objectId={objectId} resources={[...data.plans.map((r:Row)=>({id:r.id,type:'protection_plan',name:r.title+' / 计划版本'+r.version,url:'/protection/plans/'+r.id})),...data.prescriptions.map((r:Row)=>({id:r.id,type:'prescription_map',name:'处方版本'+r.version,url:'/protection/prescriptions/'+r.id}))]}/>
 </div>;
}
function ImportForm({objectId,reload}:{objectId:string;reload:()=>Promise<void>}){const [rows,setRows]=useState('[]'),[error,setError]=useState('');return <><p>上传标准JSON行数组，每行需externalId、planId及实际作业字段。每批最多100行/1MiB；错误行可核对后用新提交重试，外部记录号保持不变。</p><label>选择离线JSON文件<input type="file" accept=".json,application/json" onChange={async e=>{setError('');try{const f=e.target.files?.[0];if(!f)return;if(f.size>1024*1024)throw Error('文件超过1MiB');const v=JSON.parse(await f.text());if(!Array.isArray(v))throw Error('根内容须为行数组');setRows(JSON.stringify(v));}catch(err){setError(err instanceof Error?err.message:'文件无效');}}}/></label>{error&&<p role="alert">{error}</p>}<ActionForm path="/api/v1/protection/imports" stableKey jsonFields={['rows']} onSaved={()=>void reload()}><input type="hidden" name="objectId" value={objectId}/><Field name="sourceRef" label="稳定来源或设备编号"/><label>导入内容预览<textarea name="rows" value={rows} onChange={e=>setRows(e.target.value)} required/></label></ActionForm></>;}
function ExecutionDetail({id}:{id:string}){const {data,error}=useApi<Row>('/api/v1/protection/execution?id='+id);if(error)return <p role="alert">{error}</p>;if(!data)return <p>正在读取定位…</p>;const c=data.execution.coverage;return <><GeometryPreview boundary={data.plan.boundary} missing={c.missingGeometry} overlap={c.overlapGeometry}/>{c.limitations.map((s:string)=><p className="hint" key={s}>{s}</p>)}<StockTable rows={c.gaps} columns={[[ 'from','中断起点'],['to','终点'],['position','可用定位'],['reason','原因']]}/></>;}

