'use client';
import {useState} from 'react';
import {useApi} from '@/components/platform/use-api';
import ActionForm from '@/components/platform/action-form';
import {Field} from '@/components/platform/fields';
type Hit={chunkId:string;title:string;version:string;text:string;citationUrl:string};
export default function KnowledgePanel(){const docs=useApi<{items:{id:string;title:string;version:string;state:string;source_ref:string;evidence_nature:string;chunks:number;indexed:number}[]}>('/api/v1/knowledge'),[hits,setHits]=useState<Hit[]>([]),[message,setMessage]=useState('');return <><p className="hint">只有审核且未撤回的资料进入检索。扫描件须先完成识别和校核；原文引用继续检查当前权限。</p><form className="business-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setMessage('正在检索…');try{const r=await fetch('/api/v1/knowledge/search?q='+encodeURIComponent(String(f.get('q')))+'&mode='+f.get('mode')),v=await r.json();if(!r.ok)throw new Error(v.message);setHits(v.items);setMessage(v.items.length?'找到'+v.items.length+'条出处；'+v.limitations.join('；'):'没有匹配的审核资料。');}catch(e){setHits([]);setMessage(e instanceof Error?e.message:'检索未完成');}}}><Field name="q" label="检索问题或关键词"/><label>检索方式<select name="mode"><option value="hybrid">关键词＋语义</option><option value="keyword">关键词</option><option value="vector">语义</option></select></label><button>检索审核资料</button><p role="status">{message}</p></form>{hits.map(h=><section className="rule-card" key={h.chunkId}><h2><a href={h.citationUrl} target="_blank" rel="noreferrer">{h.title} · {h.version}</a></h2><p style={{whiteSpace:'pre-wrap'}}>{h.text}</p></section>)}
 <h2>版本与有效状态</h2>{docs.error&&<p className="form-error">{docs.error}</p>}{docs.data?.items.map(d=><section className="rule-card" key={d.id}><h2>{d.title} · {d.version}</h2><p>{d.state==='approved'?'已审核':d.state==='withdrawn'?'已撤回':'草稿'}；语义索引{d.indexed}/{d.chunks}；来源{d.source_ref}</p><p>{d.evidence_nature}</p>{d.state!=='withdrawn'&&<ActionForm path="/api/v1/knowledge" method="PATCH" booleans={['withdraw']} onSaved={()=>void docs.reload()} label="保存资料审核"><input type="hidden" name="id" value={d.id}/><label><input name="withdraw" type="checkbox"/>撤回版本（不勾选为审核通过）</label></ActionForm>}</section>)}
 <details><summary>登记权威资料只读副本</summary><ActionForm path="/api/v1/knowledge" jsonFields={['objectIds']} onSaved={()=>void docs.reload()}><Field name="title" label="资料标题"/><Field name="version" label="权威资料版本"/><Field name="sourceRef" label="权威原件位置或报告依据"/><Field name="sourceUrl" label="公开来源链接（可空）" required={false}/><Field name="evidenceNature" label="证据性质、适用条件和限制"/><label>适用对象ID列表<textarea name="objectIds" required placeholder='["对象ID"]'/></label><label>已经识别并校核的正文<textarea name="body" required rows={10}/></label><input type="hidden" name="format" value="markdown"/></ActionForm></details></>;}
