import type { PoolClient } from 'pg';
import type { Actor } from '../../platform/types';
import { AppError } from '../../platform/error';
import { choice,text,time,integer } from '../../platform/validation';
import { uuid } from '../identity/common';
import { existingObject,scope,visible,lockKey,payloadHash,sameHash } from '../field/common';
export async function createTask(c:PoolClient,a:Actor,b:Record<string,unknown>){
 const o=await existingObject(c,a,b),key=text(b.requestKey,'草稿标识',120),input={objectId:o.id,title:text(b.title,'任务标题',200),instructions:text(b.instructions,'工作内容和限制',4000),kind:choice(b.kind,['inspection','farm_work','irrigation'] as const,'任务类型'),dueAt:b.dueAt?time(b.dueAt):null,batchId:b.batchId??null,calendarId:b.calendarId??null,alertId:b.alertId??null};
 for(const [field,table]of [['batchId','production_batches'],['calendarId','calendar_versions'],['alertId','alerts']] as const){if(input[field]){uuid(input[field]);const ref=(await c.query('SELECT object_id FROM '+table+' WHERE id=$1',[input[field]])).rows[0];if(ref?.object_id!==o.id)throw new AppError(422,'TASK_REFERENCE','关联批次、日历或告警必须属于同一对象');}}
 if(input.calendarId){const cal=(await c.query('SELECT approved_at,retired_at FROM calendar_versions WHERE id=$1',[input.calendarId])).rows[0];if(!cal?.approved_at||cal.retired_at)throw new AppError(422,'CALENDAR_UNAPPROVED','日历尚未审核或已撤回');}
 await lockKey(c,a,'task-create',key);const hash=payloadHash(input),prior=(await c.query('SELECT * FROM field_tasks WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(prior){sameHash(prior.content_hash,hash);return prior;}
 return (await c.query('INSERT INTO field_tasks(object_id,title,instructions,kind,due_at,batch_id,calendar_id,alert_id,created_by,request_key,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[o.id,input.title,input.instructions,input.kind,input.dueAt,input.batchId,input.calendarId,input.alertId,a.id,key,hash])).rows[0];
}
export async function transitionTask(c:PoolClient,a:Actor,b:Record<string,unknown>){
 uuid(b.id);const action=choice(b.action,['dispatch','claim','report','review','handover','cancel','amend'] as const,'任务操作'),key=text(b.requestKey,'操作标识',120),note=text(b.note,'操作依据',3000),version=integer(b.version,'任务版本');
 await lockKey(c,a,'task-action',key);const r=(await c.query('SELECT * FROM field_tasks WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!r)throw new AppError(404,'TASK_NOT_FOUND','任务不存在');await scope(c,a,r.object_id,['dispatch','cancel','amend'].includes(action)?'dispatch':action==='review'?'review':action==='claim'?'claim':'record','task',r.id);
 const hash=payloadHash(b),prior=(await c.query('SELECT * FROM field_task_events WHERE actor_id=$1 AND request_key=$2',[a.id,key])).rows[0];if(prior){sameHash(prior.content_hash,hash);return r;}if(r.version!==version)throw new AppError(409,'VERSION_CONFLICT','任务已由其他人变更，请刷新后继续');
 let state=r.state,assignee=r.assignee_id,claimed=r.claimed_by,instructions=r.instructions;
 if(action==='dispatch'){if(state!=='draft'||b.confirm!==true)throw new AppError(409,'DISPATCH_CONFIRM','仅草稿可经人工确认派发');uuid(b.assigneeId);const user=(await c.query('SELECT role,enabled FROM users WHERE id=$1',[b.assigneeId])).rows[0];if(!user?.enabled||!['worker','technician','owner','maintainer'].includes(user.role))throw new AppError(422,'ASSIGNEE_SCOPE','执行人不可用');await scope(c,{id:b.assigneeId,role:user.role,enabled:true,mfaVerified:true},r.object_id,'record');assignee=b.assigneeId;state='dispatched';}
 if(action==='claim'){if(state!=='dispatched'||assignee!==a.id)throw new AppError(409,'TASK_CLAIM','仅指定执行人可领取已派发任务');state='claimed';claimed=a.id;}
 if(action==='report'){if(state!=='claimed'||claimed!==a.id)throw new AppError(409,'TASK_REPORT','仅当前领任务人员可提交反馈');const occurred=time(b.occurredAt);let recordId=b.recordId??null;if(recordId){uuid(recordId);const rec=(await c.query('SELECT object_id FROM farm_records WHERE id=$1',[recordId])).rows[0];if(rec?.object_id!==r.object_id)throw new AppError(422,'TASK_REFERENCE','农事记录不属于此对象');}
 await c.query('INSERT INTO inspection_reports(object_id,task_id,observation,judgment,action_taken,occurred_at,record_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[r.object_id,r.id,text(b.observation,'观测',4000),text(b.judgment,'判断，未知请明确填写',2000),text(b.actionTaken,'实际动作或未执行原因',2000),occurred,recordId,a.id]);state='reported';}
 if(action==='review'){if(state!=='reported')throw new AppError(409,'TASK_REVIEW','需先提交反馈');state='reviewed';}
 if(action==='handover'){if(state!=='claimed'||claimed!==a.id)throw new AppError(409,'TASK_HANDOVER','仅当前领取人可交班');claimed=null;state='dispatched';}
 if(action==='cancel'){if(['reviewed','cancelled'].includes(state))throw new AppError(409,'TASK_STATE','已结束任务不能再次取消');state='cancelled';claimed=null;}
 if(action==='amend'){if(['reported','reviewed','cancelled'].includes(state))throw new AppError(409,'TASK_STATE','已反馈或结束任务须另建修订');instructions=text(b.instructions,'修改后的任务内容',4000);}
 await c.query('UPDATE field_tasks SET state=$2,assignee_id=$3,claimed_by=$4,instructions=$5,version=version+1 WHERE id=$1',[r.id,state,assignee,claimed,instructions]);await c.query('INSERT INTO field_task_events(task_id,version,action,actor_id,payload,request_key,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7)',[r.id,version+1,action,a.id,{note,priorState:r.state,state,previousInstructions:r.instructions,instructions,assigneeId:assignee,claimedBy:claimed},key,hash]);return (await c.query('SELECT * FROM field_tasks WHERE id=$1',[r.id])).rows[0];
}
export async function irrigationStep(c:PoolClient,a:Actor,b:Record<string,unknown>){
 uuid(b.taskId);const r=(await c.query('SELECT * FROM field_tasks WHERE id=$1 FOR UPDATE',[b.taskId])).rows[0];if(!r||r.kind!=='irrigation')throw new AppError(404,'IRRIGATION_TASK','请选择人工灌排任务');const step=choice(b.step,['application','confirmation','execution','result','not_executed'] as const,'灌排步骤');await scope(c,a,r.object_id,step==='confirmation'?'dispatch':'record');if(['execution','result','not_executed'].includes(step)&&(r.claimed_by!==a.id||!['claimed','reported'].includes(r.state)))throw new AppError(403,'IRRIGATION_ASSIGNEE','仅当前领取人可登记执行');
 const previous=(await c.query('SELECT step FROM irrigation_entries WHERE task_id=$1',[r.id])).rows.map(v=>v.step),needed={application:null,confirmation:'application',execution:'confirmation',result:'execution',not_executed:'confirmation'}[step];if((needed&&!previous.includes(needed))||(step==='execution'&&previous.includes('not_executed'))||(step==='not_executed'&&previous.includes('execution')))throw new AppError(409,'IRRIGATION_SEQUENCE','灌排步骤不完整或已经登记另一执行结果');const details=text(b.details,'现场记录和结果',4000),occurred=time(b.occurredAt);const prior=(await c.query('SELECT * FROM irrigation_entries WHERE task_id=$1 AND step=$2',[r.id,step])).rows[0];if(prior){sameHash(payloadHash({details:prior.details,occurred:prior.occurred_at.toISOString()}),payloadHash({details,occurred}));return prior;}
 return (await c.query('INSERT INTO irrigation_entries(object_id,task_id,step,details,occurred_at,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[r.object_id,r.id,step,details,occurred,a.id])).rows[0];
}
export async function listTasks(c:PoolClient,a:Actor){const v=await visible(c,a,'task');const items=(await c.query('SELECT * FROM field_tasks WHERE object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR id=ANY($2)) ORDER BY created_at DESC LIMIT 200',[v.objects,v.resources])).rows,ids=items.map(r=>r.id);return {items,events:(await c.query('SELECT * FROM field_task_events WHERE task_id=ANY($1::uuid[]) ORDER BY created_at',[ids])).rows,reports:(await c.query('SELECT * FROM inspection_reports WHERE task_id=ANY($1::uuid[]) ORDER BY created_at',[ids])).rows,irrigation:(await c.query('SELECT * FROM irrigation_entries WHERE task_id=ANY($1::uuid[]) ORDER BY created_at',[ids])).rows};}
