'use client';
import {useState} from 'react';
import {useApi} from '@/components/platform/use-api';
import ActionForm from '@/components/platform/action-form';
import {Field,Pick} from '@/components/platform/fields';
type RecordRow={id:string;object_id:string;kind:string;occurred_at:string;recorded_at:string;version:number;status:string;superseded:boolean;content:{observation:string;judgment:string|null;action:string|null;amount:number|null;unit:string|null;material:string|null};attachments:{id:string;name:string;backupState:string}[];reviews:{note:string;createdAt:string}[]};
export default function RecordsPanel(){const records=useApi<{items:RecordRow[]}>('/api/v1/records'),objects=useApi<{items:{id:string;name:string;version:number}[]}>('/api/v1/objects?limit=200'),[importResult,setResult]=useState('');return <><p><a className="health-link" href="/field.html">打开现场记录与本机草稿</a></p><p className="hint">原件与压缩预览分别保存，更正追加历史。备份完成只表示文件复制校验，生产异地恢复另验。</p>{records.error&&<p className="form-error">{records.error}</p>}{records.data?.items.map(r=><section className="rule-card" key={r.id}><h2>{r.content.observation} · {r.superseded?'已有更正':r.status==='reviewed'?'已核查':'已提交'}</h2><p className="hint">发生 {new Date(r.occurred_at).toLocaleString()}；录入 {new Date(r.recorded_at).toLocaleString()}；版本{r.version}</p><p>用量：{r.content.amount===null?'未知':r.content.amount+' '+r.content.unit}；判断：{r.content.judgment||'未记录'}；动作：{r.content.action||'未记录'}</p><ul>{r.attachments.map(m=><li key={m.id}><a href={'/api/v1/media/'+m.id} target="_blank" rel="noreferrer">{m.name}</a> · {m.backupState==='verified'?'备份已校验':m.backupState==='failed'?'备份失败':'备份待完成'}</li>)}</ul><ul>{r.reviews.map((v,i)=><li key={i}>{v.note}</li>)}</ul><details><summary>核查与更正</summary><ActionForm path="/api/v1/records" method="PATCH" label="保存核查意见" onSaved={()=>void records.reload()}><input type="hidden" name="id" value={r.id}/><Field name="note" label="核查意见"/></ActionForm>{!r.superseded&&objects.data&&<ActionForm path="/api/v1/records" numbers={['objectVersion','expectedVersion']} times={['occurredAt']} jsonFields={['content','attachmentIds']} onSaved={()=>void records.reload()} label="追加更正版本"><input type="hidden" name="objectId" value={r.object_id}/><input type="hidden" name="objectVersion" value={objects.data.items.find(o=>o.id===r.object_id)?.version??1}/><input type="hidden" name="submissionId" value={'correction-'+r.id}/><input type="hidden" name="supersedesId" value={r.id}/><input type="hidden" name="expectedVersion" value={r.version}/><input type="hidden" name="kind" value={r.kind}/><input type="hidden" name="attachmentIds" value="[]"/><Field name="occurredAt" label="更正发生时间" type="datetime-local"/><label>更正后的内容JSON<textarea name="content" defaultValue={JSON.stringify(r.content,null,2)} required rows={6}/></label><Field name="correctionReason" label="更正理由"/></ActionForm>}</details></section>)}{records.data?.items.length===0&&<p className="empty-state">尚无农事记录。</p>}
 <details><summary>表格逐行补录</summary><p>上传CSV，列为line、objectId、objectVersion、kind、occurredAt、observation、material、amount、unit；时间带时区。导入批次标识和原行号保持不变，修正失败行后重试。</p><form className="business-form" onSubmit={async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),file=f.get('file') as File,rows=parseCsv(await file.text());const r=await fetch('/api/v1/records/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({importId:f.get('importId'),rows})}),data=await r.json();if(!r.ok)throw new Error(data.message);setResult(data.results.map((x:{line:number;state:string;message?:string})=>`第${x.line}行：${x.state==='saved'?'已保存':x.message}`).join('\n'));void records.reload();}catch(x){setResult(x instanceof Error?x.message:'导入未完成');}}}><Field name="importId" label="稳定导入批次标识"/><label>CSV文件<input type="file" name="file" accept=".csv,text/csv" required/></label><button>逐行导入</button><pre className="import-result">{importResult}</pre></form></details></>;}
function parseCsv(s:string){const grid:string[][]=[[]];let value='',quoted=false;for(let i=0;i<s.length;i++){const ch=s[i];if(ch==='"'){if(quoted&&s[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){grid.at(-1)!.push(value);value='';}else if(ch==='\n'&&!quoted){grid.at(-1)!.push(value.replace(/\r$/,''));value='';grid.push([]);}else value+=ch;}if(quoted)throw new Error('CSV引号未闭合');if(value||grid.at(-1)!.length)grid.at(-1)!.push(value.replace(/\r$/,''));const headers=grid.shift()!.map(h=>h.replace(/^\uFEFF/,''));return grid.filter(r=>r.some(Boolean)).map((r,index)=>{const v=Object.fromEntries(headers.map((h,i)=>[h,r[i]??'']));return {line:v.line?Number(v.line):index+2,objectId:v.objectId,objectVersion:Number(v.objectVersion),kind:v.kind,occurredAt:v.occurredAt,content:{observation:v.observation,material:v.material||null,amount:v.amount?Number(v.amount):null,unit:v.unit||null}};});}
