import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text,optionalText,time,choice} from '../../platform/validation';import {uuid} from '../identity/common';
import {access,request,independent,type Body} from '../phase4/common';import {positive} from '../inventory/quantity';import {money,cents,pricedAmount} from './money';import {assertMachineAccepted} from '../machinery/evidence';
import {financeAccess,financialRole} from './access';
import {payloadHash} from '../field/common';
const links={input_purchase:'input_purchases',protection_execution:'protection_executions',machine_order:'machinery_orders',research_protocol:'research_protocols',research_result:'research_results'} as const;
export async function expense(c:PoolClient,a:Actor,id:unknown,action:'read'|'record'|'review'='read'){financialRole(a);uuid(id);const r=(await c.query('SELECT * FROM business_expenses WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)throw new AppError(404,'EXPENSE_NOT_FOUND','费用记录不存在');await access(c,a,r.object_id,action);return r;}
export async function assertExpense(c:PoolClient,id:string){const r=(await c.query(`SELECT e.*,COALESCE((SELECT action='approve' FROM expense_reviews WHERE expense_id=e.id ORDER BY seq DESC LIMIT 1),false) AND NOT EXISTS(SELECT 1 FROM business_expenses n WHERE n.supersedes_id=e.id) AS eligible FROM business_expenses e WHERE e.id=$1 FOR SHARE OF e`,[id])).rows[0];if(!r?.eligible||r.amount_cny===null)throw new AppError(409,'EXPENSE_NOT_APPROVED','费用未独立核实、金额未知、已更正或撤回');if(r.link_kind==='machine_order')await assertMachineAccepted(c,r.link_id);return r;}
export async function recordExpense(c:PoolClient,a:Actor,b:Body){await financeAccess(c,a,b.objectId,'record');return request(c,a,b,'business.expense',b.objectId as string,async()=>{
 if(b.currency!==undefined&&b.currency!=='CNY')throw new AppError(422,'EXPENSE_CURRENCY','当前台账只登记人民币');
 const quantity=b.quantity==null||b.quantity===''?null:positive(b.quantity),unit=optionalText(b.unit,'计费单位',40),price=b.unitPrice==null||b.unitPrice===''?null:money(b.unitPrice),amount=b.amountCny==null||b.amountCny===''?null:money(b.amountCny);
 if(quantity!==null&&!unit||price!==null&&quantity===null)throw new AppError(422,'EXPENSE_UNIT','填写数量或单价须有完整计量口径');if(quantity!==null&&price!==null&&(amount===null||cents(pricedAmount(quantity,price))!==cents(amount)))throw new AppError(422,'EXPENSE_AMOUNT','金额须等于数量乘单价并四舍五入至分');
 const kind=choice(b.linkKind,['manual',...Object.keys(links)] as ('manual'|keyof typeof links)[],'来源业务');if(kind!=='manual'){uuid(b.linkId);const linked=(await c.query('SELECT object_id FROM '+links[kind]+' WHERE id=$1',[b.linkId])).rows[0];if(linked?.object_id!==b.objectId)throw new AppError(422,'EXPENSE_SCOPE','关联业务不存在或不属于当前对象');}
 const payer=text(b.payer,'付款主体'),payee=text(b.payee,'收款主体'),voucher=text(b.voucher,'费用凭证号',200),normalize=(v:string)=>v.normalize('NFKC').replace(/\s+/g,' ').toLowerCase(),identity=payloadHash({payer:normalize(payer),payee:normalize(payee),voucher:normalize(voucher)});await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['expense:'+identity]);
 if(kind==='research_protocol')await import('../research/protocols').then(m=>m.researchProtocol(c,a,b.linkId));if(kind==='research_result')await import('../research/results').then(m=>m.researchResult(c,a,b.linkId as string));
 const old=(await c.query('SELECT * FROM business_expenses WHERE identity_key=$1 ORDER BY version DESC LIMIT 1',[identity])).rows[0];if(old&&old.object_id!==b.objectId)throw new AppError(409,'EXPENSE_DUPLICATE_SCOPE','相同付款方、收款方和凭证已在其他范围登记，请由负责人核查，不重复建账');
 if(old&&b.supersedesId!==old.id||!old&&b.supersedesId)throw new AppError(409,'EXPENSE_VERSION','凭证已登记，更正须引用当前同主体凭证版本');
 if(old){await expense(c,a,old.id,'record');const paid=(await c.query("SELECT COALESCE(sum(CASE WHEN direction='pay' THEN amount_cny ELSE -amount_cny END),0)::text AS n FROM expense_payments WHERE expense_id=$1",[old.id])).rows[0].n;if(cents(paid)>0n||(await c.query('SELECT 1 FROM subsidy_expenses WHERE expense_id=$1 AND active',[old.id])).rowCount)throw new AppError(409,'EXPENSE_DEPENDENCIES','须先处理原付款或补贴占用再更正费用');}
 return(await c.query('INSERT INTO business_expenses(object_id,category,quantity,unit,unit_price,amount_cny,payer,payee,voucher,occurred_at,link_kind,link_id,evidence,supersedes_id,version,created_by,identity_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *',[b.objectId,choice(b.category,['material','service','remediation','research','other'] as const,'费用类别'),quantity,unit,price,amount,payer,payee,voucher,time(b.occurredAt),kind,kind==='manual'?null:b.linkId,text(b.evidence,'费用用途与凭据',4000),old?.id??null,(old?.version??0)+1,a.id,identity])).rows[0];
 });}
export async function reviewExpense(c:PoolClient,a:Actor,b:Body){const r=await expense(c,a,b.id,'review');return request(c,a,b,'business.expense-review',r.object_id,async()=>{independent(a,r.created_by);const action=choice(b.action,['approve','withdraw'] as const,'核实动作');if(action==='approve'){if(r.amount_cny===null||(await c.query('SELECT 1 FROM business_expenses WHERE supersedes_id=$1',[r.id])).rowCount)throw new AppError(422,'EXPENSE_NOT_APPROVED','未知金额或旧版本不能核实通过');if(r.link_kind==='machine_order')await assertMachineAccepted(c,r.link_id);}return(await c.query('INSERT INTO expense_reviews(object_id,expense_id,action,evidence,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[r.object_id,r.id,action,text(b.evidence,'独立核实依据',4000),a.id])).rows[0];});}
export async function recordPayment(c:PoolClient,a:Actor,b:Body){const r=await expense(c,a,b.expenseId,'record');return request(c,a,b,'business.payment',r.object_id,async()=>{
 const direction=choice(b.direction,['pay','reverse'] as const,'付款记录方向'),amount=money(b.amountCny,false);let reversed:any=null;
 if(direction==='pay'){await assertExpense(c,r.id);const paid=(await c.query("SELECT COALESCE(sum(CASE WHEN direction='pay' THEN amount_cny ELSE -amount_cny END),0)::text n FROM expense_payments WHERE expense_id=$1",[r.id])).rows[0].n;if(cents(paid)+cents(amount)>cents(r.amount_cny))throw new AppError(409,'PAYMENT_EXCEEDS','累计实付超过已核费用');}
 else {await access(c,a,r.object_id,'review');uuid(b.reversesId);reversed=(await c.query('SELECT * FROM expense_payments WHERE id=$1',[b.reversesId])).rows[0];if(reversed?.expense_id!==r.id||reversed.direction!=='pay'||cents(reversed.amount_cny)!==cents(amount)||(await c.query('SELECT 1 FROM expense_payments WHERE reverses_id=$1',[reversed.id])).rowCount)throw new AppError(409,'PAYMENT_REVERSAL','冲销须全额对应尚未冲销的原付款');}
 const at=time(b.occurredAt);if(new Date(at)<r.occurred_at||reversed&&new Date(at)<reversed.occurred_at)throw new AppError(422,'PAYMENT_TIME','实际付款或冲销时间早于原记录');
 return(await c.query('INSERT INTO expense_payments(object_id,expense_id,direction,amount_cny,voucher,occurred_at,evidence,reverses_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[r.object_id,r.id,direction,amount,text(b.voucher,'实际付款或冲销凭证号',200),at,text(b.evidence,'实际凭据与说明',4000),reversed?.id??null,a.id])).rows[0];
 });}
