import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text,time,choice,optionalText} from '../../platform/validation';import {uuid} from '../identity/common';import {arrayIds} from '../field/common';
import {access,request,independent,period,type Body} from '../phase4/common';import {expense,assertExpense} from './expenses';import {money,cents} from './money';
import {financeAccess,financialRole} from './access';
export async function createSubsidyClaim(c:PoolClient,a:Actor,b:Body){await financeAccess(c,a,b.objectId,'record');return request(c,a,b,'business.subsidy',b.objectId as string,async()=>{
 const ids=arrayIds(b.expenseIds,50).sort();if(!ids.length)throw new AppError(422,'SUBSIDY_EXPENSE','须关联至少一项已核费用');const {start,end}=period(b.periodFrom,b.periodTo,3660);let total=0n;
 for(const id of ids){const r=await expense(c,a,id,'read');if(r.object_id!==b.objectId||r.occurred_at<new Date(start)||r.occurred_at>=new Date(end))throw new AppError(422,'SUBSIDY_SCOPE','费用须属于当前对象和申请期间');await assertExpense(c,id);if((await c.query('SELECT 1 FROM subsidy_expenses WHERE expense_id=$1 AND active',[id])).rowCount)throw new AppError(409,'SUBSIDY_DUPLICATE','费用已被有效补贴记录占用，不能跨类别重复使用');total+=cents(r.amount_cny);}
 const amount=money(b.amountCny,false);if(cents(amount)>total)throw new AppError(422,'SUBSIDY_AMOUNT','申请金额超过关联已核费用');
 const r=(await c.query('INSERT INTO subsidy_claims(object_id,category,policy_ref,policy_version,beneficiary,period_from,period_to,amount_cny,evidence,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[b.objectId,choice(b.category,['purchase','replacement','service'] as const,'补贴类别'),text(b.policyRef,'具体政策与适用地区依据',4000),text(b.policyVersion,'政策版本'),text(b.beneficiary,'受益主体'),start,end,amount,text(b.evidence,'申请范围与原始依据',4000),a.id])).rows[0];
 for(const id of ids)await c.query('INSERT INTO subsidy_expenses(object_id,claim_id,expense_id) VALUES($1,$2,$3)',[b.objectId,r.id,id]);return r;
 });}
export async function subsidyEvent(c:PoolClient,a:Actor,b:Body){financialRole(a);uuid(b.id);const r=(await c.query('SELECT * FROM subsidy_claims WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!r)throw new AppError(404,'SUBSIDY_NOT_FOUND','补贴记录不存在');await access(c,a,r.object_id);return request(c,a,b,'business.subsidy-event',r.object_id,async()=>{
 const action=choice(b.action,['review','submit','award','received','refund','reject','withdraw','correct'] as const,'登记动作'),evidence=text(b.evidence,'实际凭证或处理依据',4000),occurredAt=['review','withdraw'].includes(action)?new Date().toISOString():b.occurredAt?time(b.occurredAt):null;let amount:string|null=null,external=optionalText(b.externalRef,'外部受理、审批或收付凭证号',200),reversed:any=null,state=r.state,award=r.awarded_cny,corrected:string|null=null;
 const received=(await c.query("SELECT COALESCE(sum(CASE WHEN action='received' THEN amount_cny WHEN action='refund' THEN -amount_cny ELSE 0 END),0)::text n FROM subsidy_events WHERE claim_id=$1",[r.id])).rows[0].n;
 if(['review','award','reject','withdraw','refund','correct'].includes(action))await access(c,a,r.object_id,'review');
 if(action==='correct'){uuid(b.correctsId);const original=(await c.query('SELECT * FROM subsidy_events WHERE id=$1',[b.correctsId])).rows[0];if(original?.claim_id!==r.id||!['submit','award','received','refund','reject'].includes(original.action))throw new AppError(422,'SUBSIDY_CORRECTION','请选择本申请的原外部事实记录，时间更正不改变金额和原编号');corrected=original.id;external=null;}
 if(action==='review'||action==='award'){independent(a,r.created_by);const items=(await c.query('SELECT expense_id FROM subsidy_expenses WHERE claim_id=$1 ORDER BY expense_id',[r.id])).rows;for(const item of items)await assertExpense(c,item.expense_id);}
 if(action==='review'){if(r.state!=='draft')throw new AppError(409,'SUBSIDY_STATE','只有草稿可以内部复核');state='reviewed';}
 if(action==='submit'){if(r.state!=='reviewed'||!external)throw new AppError(409,'SUBSIDY_STATE','先内部复核，再登记真实受理编号');state='submitted';}
 if(action==='award'){amount=money(b.amountCny);if(r.state!=='submitted'||!external||cents(amount)>cents(r.amount_cny))throw new AppError(409,'SUBSIDY_STATE','批准记录须有受理、审批编号且金额不超申请');state='awarded';award=amount;}
 if(action==='received'){amount=money(b.amountCny,false);if(r.state!=='awarded'||!external)throw new AppError(409,'SUBSIDY_STATE','到账须有已登记批准和实际收款凭证');if(cents(received)+cents(amount)>cents(r.awarded_cny))throw new AppError(409,'SUBSIDY_RECEIPT_EXCEEDS','累计到账超过已登记批准金额');}
 if(action==='refund'){uuid(b.reversesId);reversed=(await c.query('SELECT * FROM subsidy_events WHERE id=$1',[b.reversesId])).rows[0];amount=money(b.amountCny,false);if(reversed?.claim_id!==r.id||reversed.action!=='received'||cents(reversed.amount_cny)!==cents(amount)||!external||(await c.query('SELECT 1 FROM subsidy_events WHERE reverses_id=$1',[reversed.id])).rowCount)throw new AppError(409,'SUBSIDY_REFUND','退回须全额对应尚未退回的到账记录及实际凭证');}
 if(action==='reject'||action==='withdraw'){if(['rejected','withdrawn'].includes(r.state)||cents(received)>0n)throw new AppError(409,'SUBSIDY_STATE','有未退回到账或已经结束，不能直接撤销');state=action==='reject'?'rejected':'withdrawn';await c.query('UPDATE subsidy_expenses SET active=false WHERE claim_id=$1',[r.id]);}
 const event=(await c.query('INSERT INTO subsidy_events(object_id,claim_id,action,amount_cny,external_ref,evidence,reverses_id,created_by,occurred_at,corrects_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[r.object_id,r.id,action,amount,external,evidence,reversed?.id??null,a.id,occurredAt,corrected])).rows[0];await c.query('UPDATE subsidy_claims SET state=$2,awarded_cny=$3 WHERE id=$1',[r.id,state,award]);return {...event,state,externalActionSent:false};
 });}
