import {AppError} from '../../platform/error';
import {readModelBody} from '../../modules/assistant/provider';
export interface WecomSettings{corpId:string;secret:string;agentId:number;userinfoPath:'/cgi-bin/auth/getuserinfo'|'/cgi-bin/user/getuserinfo'}
export class WecomClient{
 private cached?:{value:string;until:number};private refreshing?:Promise<string>;
 constructor(private readonly settings:WecomSettings,private readonly fetcher:typeof fetch=fetch){if(!/^[a-zA-Z0-9_-]{3,100}$/.test(settings.corpId)||!settings.secret||settings.secret.length>2048||!Number.isSafeInteger(settings.agentId)||settings.agentId<1||!['/cgi-bin/auth/getuserinfo','/cgi-bin/user/getuserinfo'].includes(settings.userinfoPath))throw new AppError(503,'WECOM_CONFIG','企业微信服务配置未核实');}
 private async request(path:string,query:Record<string,string>,body?:Record<string,unknown>){const url=new URL(path,'https://qyapi.weixin.qq.com');for(const [k,v]of Object.entries(query))url.searchParams.set(k,v);const signal=AbortSignal.timeout(15000);let r:Response;try{r=await this.fetcher(url,{method:body?'POST':'GET',body:body?JSON.stringify(body):undefined,headers:{'Content-Type':'application/json'},redirect:'error',signal});}catch{throw new AppError(503,'WECOM_NETWORK_UNKNOWN','企业微信请求未完成，结果未知，不重复发送');}if(!r.ok)throw new AppError(503,'WECOM_HTTP','企业微信接口拒绝请求');let x:any;try{x=JSON.parse(await readModelBody(r,signal));}catch{throw new AppError(503,'WECOM_RESPONSE_UNKNOWN','企业微信响应未完整核实，不返回原文');}if([40014,42001,40001].includes(x.errcode))this.cached=undefined;if(x.errcode!==0)throw new AppError(503,[40014,42001,40001].includes(x.errcode)?'WECOM_TOKEN_EXPIRED':'WECOM_REJECTED','企业微信接口未受理或凭据失效，须核对账户权限');return x;}
 async token(){if(this.cached&&this.cached.until>Date.now())return this.cached.value;if(this.refreshing)return this.refreshing;this.refreshing=(async()=>{const x=await this.request('/cgi-bin/gettoken',{corpid:this.settings.corpId,corpsecret:this.settings.secret});if(typeof x.access_token!=='string'||!x.access_token||x.access_token.length>16384||!Number.isSafeInteger(x.expires_in)||x.expires_in<180||x.expires_in>86400)throw new AppError(502,'WECOM_TOKEN_INVALID','访问凭据响应未通过核对');this.cached={value:x.access_token,until:Date.now()+(x.expires_in-120)*1000};return x.access_token;})();try{return await this.refreshing;}finally{this.refreshing=undefined;}}
 async member(code:string){if(!code||code.length>512)throw new AppError(400,'WECOM_CODE','授权码无效');const x=await this.request(this.settings.userinfoPath,{access_token:await this.token(),code}),id=x.UserId??x.userid;if(typeof id!=='string'||!id||id.length>256)throw new AppError(403,'WECOM_MEMBER_REQUIRED','仅已开通的企业成员可登录，不把外部联系人或OpenId当平台账号');return {corpId:this.settings.corpId,userId:id};}
 async sendText(userId:string,text:string,requestKey:string){if(!/^[a-zA-Z0-9_.@-]{1,256}$/.test(userId)||userId==='@all'||text.length>2000)throw new AppError(422,'WECOM_RECIPIENT','仅向单个已核成员发送标题及受控链接');const x=await this.request('/cgi-bin/message/send',{access_token:await this.token()},{touser:userId,agentid:this.settings.agentId,msgtype:'text',text:{content:text},safe:0,climsgid:requestKey});if(x.invaliduser||x.invalidparty||x.invalidtag)throw new AppError(503,'WECOM_RECIPIENT_REJECTED','成员不在此应用允许范围');return {requestId:typeof x.msgid==='string'?x.msgid:null,state:'accepted' as const};}
}
export function configuredWecomClient(env:NodeJS.ProcessEnv=process.env){if(env.WECOM_ENABLED!=='1'||env.WECOM_CONTRACT_VERIFIED!=='1'||!env.WECOM_EVIDENCE)throw new AppError(503,'WECOM_NOT_READY','企业配置、可信域名及接口许可未核实，真实读取/发送关闭');if(!['sdk-legacy','verified-modern'].includes(env.WECOM_USERINFO_CONTRACT??''))throw new AppError(503,'WECOM_IDENTITY_CONTRACT','须选择已核实身份接口版本');return new WecomClient({corpId:env.WECOM_CORP_ID??'',secret:env.WECOM_APP_SECRET??'',agentId:Number(env.WECOM_AGENT_ID),userinfoPath:env.WECOM_USERINFO_CONTRACT==='sdk-legacy'?'/cgi-bin/user/getuserinfo':'/cgi-bin/auth/getuserinfo'});}
