'use client';
import {useEffect} from 'react';import {useApi} from '@/components/platform/use-api';import ActionForm from '@/components/platform/action-form';import {Pick,type Option} from '@/components/platform/fields';
type Connection={id:string;object_id:string;source_id:string;source_name:string;version:number;processor_id:string;settings:{bindings:{deviceId:string;deviceSerial:string;channel:number}[];offsetMinutes:number;clockEvidence:string;imageMime:string;autoImages:boolean};evidence:string;enabled:boolean;readonly_confirmed:boolean;reminder_handover_confirmed:boolean;callbackPath:string};
const states:Record<string,string>={queued:'已接收，待处理',processed:'已关联原告警',awaiting_contract:'待核实消息契约或映射，未建警',blocked:'条件变化，已停止处理',failed:'处理失败，原消息保留'};
export default function EzvizConnections(){const me=useApi<{actor:{id:string};scopes:{action:string;objectIds:string[]}[]}>('/api/v1/me');const ids=me.data?.scopes.find(s=>s.action==='configure')?.objectIds??[];return ids.length?<Panel ids={ids} processor={me.data!.actor.id}/>:null;}
function Panel({ids,processor}:{ids:string[];processor:string}){const data=useApi<{connections:Connection[];receipts:{id:string;connectionId:string;messageId:string;messageType:string;state:string;errorCode:string|null;imageState:string;imageError:string|null;cameraEventId:string|null;alertId:string|null;receivedAt:string}[];globalEnabled:boolean;signatureConfigured:boolean}>('/api/v1/connections/ezviz'),objects=useApi<{items:Option[]}>('/api/v1/objects?limit=200'),sources=useApi<(Option&{provider:string;verified:boolean})[]>('/api/v1/sources');useEffect(()=>{if(data.data?.receipts.some(r=>r.state==='queued')){const timer=setInterval(()=>void data.reload(),3000);return()=>clearInterval(timer);}},[data.data]);return <details><summary>萤石签名消息连接</summary><p>开通厂家推送会停止原萤石APP提醒，关闭后也不能自动恢复。先确认原提醒交接及厂家协议，再安排实际联调；不要直接切换现场值守。</p>{data.error&&<p className="form-error">{data.error}</p>}{data.data&&<p>全局接收{data.data.globalEnabled?'启用':'关闭'}；签名密钥{data.data.signatureConfigured?'已配置，实际账户待验证':'未配置'}。</p>}
 {data.data?.connections.map(c=><section className="rule-card" key={c.id}><h2>{c.source_name} · {c.enabled?'启用':'停用'} · 版本{c.version}</h2><p className="hint" style={{overflowWrap:'anywhere'}}>回调路径：{c.callbackPath}</p><p>消息可靠接收不代表已建警；ISAPI及未核实通道保留待处理。</p><details><summary>修改消息连接与启停</summary><ConnectionForm c={c} objects={[]} sources={[]} processor={processor} saved={()=>void data.reload()}/></details><ul>{data.data!.receipts.filter(r=>r.connectionId===c.id).map(r=><li key={r.id} style={{overflowWrap:'anywhere'}}>{states[r.state]??r.state} · {r.messageType} · {new Date(r.receivedAt).toLocaleString()}；图片{({complete:'原件已保存',none:'无图片',pending:'尚未确认',queued:'已排队',encrypted:'加密或状态不明，待核实',disabled:'自动获取关闭',failed:'获取条件不足'} as Record<string,string>)[r.imageState]??r.imageState}{r.errorCode?'；'+r.errorCode:''}{r.imageError?'；'+r.imageError:''}{r.cameraEventId&&<a href={'/alerts/'+r.alertId}>查看原告警</a>}</li>)}</ul></section>)}
 <details><summary>登记新萤石消息连接</summary><ConnectionForm objects={objects.data?.items.filter(o=>ids.includes(o.id))??[]} sources={sources.data?.filter(s=>s.provider==='ezviz'&&s.verified)??[]} processor={processor} saved={()=>void data.reload()}/></details></details>;}
function ConnectionForm({c,objects,sources,processor,saved}:{c?:Connection;objects:Option[];sources:Option[];processor:string;saved:()=>void}){return <ActionForm path="/api/v1/connections/ezviz" numbers={['version','offsetMinutes']} booleans={['readOnlyConfirmed','appReminderHandoverConfirmed','enabled','autoImages']} jsonFields={['bindings']} onSaved={saved} label="保存萤石消息连接">{c?<><input type="hidden" name="id" value={c.id}/><input type="hidden" name="version" value={c.version}/><input type="hidden" name="objectId" value={c.object_id}/><input type="hidden" name="sourceId" value={c.source_id}/></>:<><Pick name="objectId" label="消息连接对象" options={objects}/><Pick name="sourceId" label="已核实的ezviz来源" options={sources}/></>}
 <label>后台执行账号ID<input name="processorId" defaultValue={c?.processor_id??processor} required/></label><label>已核实设备时区偏移（分钟）<input name="offsetMinutes" type="number" min="-840" max="840" defaultValue={c?.settings.offsetMinutes??480} required/></label><label>设备时钟核实依据<textarea name="clockEvidence" defaultValue={c?.settings.clockEvidence} required/></label><label>设备通道映射JSON（deviceId、deviceSerial、channel）<textarea name="bindings" rows={5} defaultValue={c?JSON.stringify(c.settings.bindings,null,2):undefined} required/></label><label>已核实告警原图格式<select name="imageMime" aria-label="已核实告警原图格式" defaultValue={c?.settings.imageMime??'image/jpeg'}>{['image/jpeg','image/png','image/webp','image/tiff'].map(m=><option key={m}>{m}</option>)}</select></label><label>只读范围及原提醒交接依据<textarea name="evidence" defaultValue={c?.evidence} required/></label><label><input name="readOnlyConfirmed" type="checkbox" defaultChecked={c?.readonly_confirmed}/>已确认来源、消息范围及只读使用权限</label><label><input name="appReminderHandoverConfirmed" type="checkbox" defaultChecked={c?.reminder_handover_confirmed}/>已明确原APP提醒停止后的交接方案</label><label><input name="autoImages" type="checkbox" defaultChecked={c?.settings.autoImages}/>已核实格式与CDN，自动补第一张明确未加密图片</label><label><input name="enabled" type="checkbox" defaultChecked={c?.enabled}/>启用此连接（全局入口仍单独控制）</label></ActionForm>;}
