'use client';
import {useApi} from '@/components/platform/use-api';
import ActionForm from '@/components/platform/action-form';
import {Field,Pick,type Option} from '@/components/platform/fields';
import RemoteImports from './remote-imports';
import AnnotationForm from './annotation-form';
import LargeUpload from './large-upload';
import EzvizConnections from './ezviz-connections';
import FlightHubConnections from './flighthub-connections';
export default function ImageryPanel(){const camera=useApi<{items:{id:string;alert_id:string;event_type:string;occurred_at:string;image_state:string;provider_image_state:string|null;model_state:string|null;model_queue_error:string|null;asset_id:string|null}[]}>('/api/v1/cameras'),flight=useApi<{items:{id:string;external_id:string;aircraft_model:string;dock_model:string;provider_version:string;crs:string;complete:boolean;backupComplete:boolean}[];files:{id:string;flight_id:string;name:string;kind:string;asset_id:string|null;backup_state:string|null}[];annotations:{id:string;flight_id:string;note:string;file_id:string|null;location:unknown;source_ref:string|null;version:number}[]}>('/api/v1/flights'),objects=useApi<{items:Option[]}>('/api/v1/objects?limit=200');return <><p className="hint">监控先形成告警与通知任务，图片后补。航次逐文件核对清单，缺原件不能标全部完成。厂家实际连接尚待真实契约联调。</p>{camera.error&&<p className="form-error">{camera.error}</p>}<p><a href="/image-review">图片复核与分环节抽查</a></p><h2>监控事件</h2>{camera.data?.items.map(e=><section className="rule-card" key={e.id}><h2>{e.event_type}</h2><p>{new Date(e.occurred_at).toLocaleString()} · <a href={'/alerts/'+e.alert_id}>查看原告警及人工核查</a></p>{e.asset_id?<a href={'/api/v1/media/'+e.asset_id}>查看受控图片</a>:<p>{e.provider_image_state==='none'?'厂家本次消息未提供图片。':e.provider_image_state==='encrypted'?'图片加密或状态不明，须核实官方解密链。':e.provider_image_state==='disabled'?'自动取图关闭；如需图片，请核对只读来源后补。':'图片待获取，自动复核未完成。'}</p>}<p>自动复核：{e.model_state??(e.model_queue_error?'未排队：'+e.model_queue_error:'图片尚未完整')}</p><ActionForm path="/api/v1/cameras" method="PATCH" onSaved={()=>void camera.reload()} label="将完整图片补入原事件"><input type="hidden" name="id" value={e.id}/><Field name="assetId" label="同对象已上传图片ID"/></ActionForm></section>)}<details><summary>人工导入厂家告警样本</summary><ActionForm path="/api/v1/cameras" times={['occurredAt']} onSaved={()=>void camera.reload()}><Field name="deviceId" label="已核实设备/通道ID"/><Field name="externalEventId" label="厂家稳定事件ID"/><Field name="contractVersion" label="厂家消息契约版本"/><Field name="occurredAt" label="事件发生时间" type="datetime-local"/><Field name="eventType" label="厂家事件类型"/></ActionForm></details>
 <h2>无人机航次与成果</h2>{flight.error&&<p className="form-error">{flight.error}</p>}{flight.data?.items.map(f=><section className="rule-card" key={f.id}><h2>{f.external_id} · {f.complete?'文件完整':'缺失文件'}</h2><p>{f.dock_model} / {f.aircraft_model}；接口{f.provider_version}；基准{f.crs}；{f.backupComplete?'文件备份已校验':'备份未完整'}</p><ul>{flight.data!.files.filter(x=>x.flight_id===f.id).map(x=><li key={x.id}>{x.kind}：{x.asset_id?<a href={'/api/v1/media/'+x.asset_id}>{x.name}</a>:x.name+'（待上传）'}{!x.asset_id&&<ActionForm path="/api/v1/flights" method="PATCH" onSaved={()=>void flight.reload()} label="关联原件"><input type="hidden" name="fileId" value={x.id}/><Field name="assetId" label="已上传原件ID"/></ActionForm>}</li>)}</ul><ul>{flight.data!.annotations.filter(x=>x.flight_id===f.id).map(x=><li key={x.id}>注记v{x.version}：{x.note}；{x.location?'已有定位':'位置未知'}；{x.source_ref??'仅文字说明'}</li>)}</ul><AnnotationForm flightId={f.id} files={flight.data!.files.filter(x=>x.flight_id===f.id)} onSaved={()=>void flight.reload()}/><ActionForm path="/api/v1/flights/annotations" stableKey jsonFields={['location']} onSaved={()=>void flight.reload()} label="登记影像疑点"><input type="hidden" name="flightId" value={f.id}/><Field name="fileId" label="具体文件ID（未确定时可空）" required={false}/><label>已核位置JSON；未确定填null<textarea name="location" defaultValue="null"/></label><Field name="sourceRef" label="定位依据（有定位时必填）" required={false}/><Field name="note" label="疑点、拍摄条件及限制"/></ActionForm></section>)}<details><summary>导入航次清单</summary><ActionForm path="/api/v1/flights" times={['startedAt','finishedAt']} jsonFields={['files','captureConditions','payloads']} onSaved={()=>void flight.reload()}><Pick name="objectId" label="关联对象" options={objects.data?.items??[]}/><Field name="sourceId" label="厂家来源ID"/><Field name="externalId" label="航次稳定ID"/><Field name="startedAt" label="开始时间" type="datetime-local"/><Field name="finishedAt" label="结束时间" type="datetime-local"/><Field name="aircraftModel" label="飞行器型号"/><Field name="dockModel" label="机场型号" required={false}/><Field name="providerVersion" label="司空或厂家接口版本"/><Field name="sourceRef" label="原始清单依据"/><Field name="crs" label="坐标系及垂直基准"/><label>采集条件JSON<textarea name="captureConditions" defaultValue="{}"/></label><label>载荷JSON<textarea name="payloads" defaultValue="[]"/></label><label>文件清单JSON（externalId、name、kind、version、checksum、parents）<textarea name="files" required rows={6}/></label></ActionForm></details><LargeUpload/><EzvizConnections/><FlightHubConnections onChanged={()=>void flight.reload()}/><RemoteImports targets={[...(camera.data?.items.filter(e=>!e.asset_id).map(e=>({kind:'camera_event' as const,id:e.id,label:'监控事件：'+e.event_type}))??[]),...(flight.data?.files.filter(f=>!f.asset_id).map(f=>({kind:'flight_file' as const,id:f.id,label:'航次文件：'+f.name}))??[])]} onChanged={()=>{void camera.reload();void flight.reload();}}/></>;}
