'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useApi} from '@/components/platform/use-api';
import {Field} from '@/components/platform/fields';
export interface MediaTarget{kind:'camera_event'|'flight_file';id:string;label:string}
const states:Record<string,string>={queued:'待下载',running:'下载中',complete:'原件已保存',failed:'下载失败',blocked:'已停止处理',unknown:'执行结果未知，需人工核对'};
export default function RemoteImports({targets,onChanged}:{targets:MediaTarget[];onChanged:()=>void}){
 const data=useApi<{items:{id:string;targetKind:string;targetId:string;name:string;state:string;errorCode:string|null;assetId:string|null;host:string;actualChecksum:string|null;byteLength:number|null}[];globalReadsEnabled:boolean;allowedHosts:string[]}>('/api/v1/media-imports'),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),key=useRef<string|null>(null);
 useEffect(()=>{if(data.data?.items.some(r=>['queued','running'].includes(r.state))){const timer=setInterval(()=>{void data.reload();onChanged();},3000);return()=>clearInterval(timer);}},[data.data,onChanged]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');setMessage('');try{const values=Object.fromEntries(new FormData(form)),[targetKind,targetId]=String(values.target).split(':');key.current??=crypto.randomUUID();const response=await fetch('/api/v1/media-imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetKind,targetId,url:values.url,mime:values.mime,name:values.name,evidence:values.evidence,readOnlyConfirmed:values.readOnlyConfirmed==='on',plaintextConfirmed:values.plaintextConfirmed==='on',requestKey:key.current})}),r=await response.json();if(!response.ok)throw new Error(r.message??'提交未完成');setMessage('下载任务已保存，请查看执行状态。');key.current=null;form.reset();setSelected('');await data.reload();onChanged();}catch(e){setError(e instanceof TypeError?'网络不可用，尚未确认保存；恢复后用原提交重试。':e instanceof Error?e.message:'提交未完成');}finally{setBusy(false);}}
 const camera=selected.startsWith('camera_event:');
 return <details><summary>下载链接转入私有原件库</summary><p>仅处理20MiB以内已解密文件。航次文件按原清单SHA-256核对；告警图片没有厂家校验值时只记录实下载校验值。图片下载不会重发原告警。</p>{data.error&&<p className="form-error">{data.error}</p>}{data.data&&<p className="hint">远程下载{data.data.globalReadsEnabled?'已启用':'关闭'}；已批准域名：{data.data.allowedHosts.join('、')||'尚未配置'}。停用或来源撤回时任务停止。</p>}
 {data.data&&targets.length>0&&<form className="business-form" onSubmit={submit}><label>关联已有事件或航次文件<select name="target" aria-label="关联已有事件或航次文件" value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">请选择</option>{targets.map(t=><option key={t.kind+':'+t.id} value={t.kind+':'+t.id}>{t.label}</option>)}</select></label><label>原件下载链接<input name="url" type="password" autoComplete="off" required maxLength={8192}/></label>{camera&&<Field name="name" label="告警图片名称"/>}<label>已解密文件格式<select name="mime" aria-label="已解密文件格式" required>{(camera?['image/jpeg','image/png','image/webp','image/tiff']:['image/jpeg','image/png','image/webp','image/tiff','video/mp4','application/pdf','text/plain','text/csv']).map(m=><option key={m}>{m}</option>)}</select></label><Field name="evidence" label="只读下载与文件使用依据"/><label><input type="checkbox" name="readOnlyConfirmed" required/>已确认此原件链接的只读下载权限及使用范围</label><label><input type="checkbox" name="plaintextConfirmed" required/>文件已解密，能够按所选格式读取</label><button disabled={busy}>{busy?'正在提交…':'保存原件下载任务'}</button>{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</form>}
 {data.data?.items.map(r=><section className="rule-card" key={r.id}><h3>{r.name} · {states[r.state]??r.state}</h3><p className="hint">{r.host}；{r.errorCode??'按原事件或文件关联'}</p>{r.assetId&&<a href={'/api/v1/media/'+r.assetId}>查看已入库受控原件</a>}{r.actualChecksum&&<p className="hint" style={{overflowWrap:'anywhere'}}>SHA-256：{r.actualChecksum}；大小{r.byteLength}字节</p>}{['failed','blocked','unknown'].includes(r.state)&&<p>请先核对原事件、来源和下载结果；需要换链接时提交新任务，系统不自动重复读取。</p>}</section>)}</details>;
}
