import type {Pool,PoolClient} from 'pg';
import {database,transaction} from '../../db/pool';
import {assertLease,withLease} from '../jobs/execution';
import type {JobLease} from '../jobs/repository';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {text,choice} from '../../platform/validation';
import {uuid} from '../identity/common';
import {arrayIds,scope,visible,payloadHash} from '../field/common';
import {enqueue} from '../jobs/repository';
import {EMBEDDING_VERSION,embedTexts} from '../models/process';
import {chunkMarkdown,terms} from './chunks';
export async function createDocument(c:PoolClient,a:Actor,b:Record<string,unknown>){const ids=arrayIds(b.objectIds,20);if(!ids.length)throw new AppError(400,'DOCUMENT_SCOPE','资料必须明确适用对象');for(const id of ids)await scope(c,a,id,'configure');const body=text(b.body,'已识别并校核的资料正文',200000),title=text(b.title,'标题',200),version=text(b.version,'资料版本',100),source=text(b.sourceRef,'权威来源',2000),format=choice(b.format,['markdown','text'] as const,'文本格式');let url=b.sourceUrl?text(b.sourceUrl,'来源链接',2000):null;if(url){const u=new URL(url);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.search||u.hash)throw new AppError(400,'SOURCE_URL','来源链接不能包含凭据、查询参数或临时地址');}
 const hash=payloadHash(body);const prior=(await c.query('SELECT * FROM knowledge_documents WHERE source_ref=$1 AND version=$2',[source,version])).rows[0];if(prior){if(prior.source_checksum!==hash||prior.title!==title||payloadHash(prior.object_ids)!==payloadHash(ids)||prior.source_url!==url)throw new AppError(409,'DOCUMENT_VERSION_CONFLICT','同一来源版本已有不同内容，须追加新版本');return {id:prior.id,state:prior.state};}
 const r=(await c.query('INSERT INTO knowledge_documents(title,version,object_ids,source_ref,source_url,source_checksum,body,format,evidence_nature,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,state',[title,version,ids,source,url,hash,body,format,text(b.evidenceNature,'证据性质及限制',1000),a.id])).rows[0];for(const [i,chunk]of chunkMarkdown(body).entries())await c.query('INSERT INTO knowledge_chunks(document_id,position,heading,text,keywords) VALUES($1,$2,$3,$4,$5)',[r.id,i,chunk.heading,chunk.text,terms(chunk.text)]);return r;
}
export async function reviewDocument(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const d=(await c.query('SELECT * FROM knowledge_documents WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!d)throw new AppError(404,'DOCUMENT_NOT_FOUND','资料不存在');for(const id of d.object_ids)await scope(c,a,id,'review','knowledge',d.id);if(b.withdraw===true){await c.query("UPDATE knowledge_documents SET state='withdrawn',withdrawn_at=COALESCE(withdrawn_at,now()) WHERE id=$1",[d.id]);return {id:d.id,state:'withdrawn'};}if(d.state==='withdrawn')throw new AppError(409,'DOCUMENT_WITHDRAWN','已撤回资料须新建修订，不复活旧上下文');await c.query("UPDATE knowledge_documents SET state='approved',approved_by=$2,approved_at=COALESCE(approved_at,now()) WHERE id=$1",[d.id,a.id]);const jobId=await enqueue(c,{kind:'knowledge.index',businessKey:'knowledge-index:'+d.id+':'+EMBEDDING_VERSION,payload:{documentId:d.id},dueAt:new Date().toISOString()});await c.query("UPDATE jobs SET state='queued',attempts=0,error_code=NULL,due_at=now(),finished_at=NULL WHERE id=$1 AND kind='knowledge.index' AND state='failed' AND external_started_at IS NULL",[jobId]);return {id:d.id,state:'approved'};}
export async function indexDocument(pool:Pool,id:string,embedding:(texts:string[])=>Promise<number[][]>=embedTexts,lease?:JobLease){
 uuid(id);return withLease(pool,'knowledge-index:'+id+':'+EMBEDDING_VERSION,lease,async current=>{
 const snapshot=await database(async c=>{await assertLease(c,current);const d=(await c.query("SELECT id,source_checksum,state FROM knowledge_documents WHERE id=$1",[id])).rows[0];if(d?.state!=='approved')return null;const chunks=(await c.query('SELECT id,text FROM knowledge_chunks WHERE document_id=$1 AND(embedding_model IS DISTINCT FROM $2 OR embedding IS NULL) ORDER BY position',[id,EMBEDDING_VERSION])).rows;return {d,chunks};},pool);
 if(!snapshot)return {skipped:true};let indexed=0;
 for(let i=0;i<snapshot.chunks.length;i+=8){
  await transaction(c=>assertLease(c,current),pool);const batch=snapshot.chunks.slice(i,i+8),vectors=await embedding(batch.map(x=>x.text));
  if(vectors.length!==batch.length||vectors.some(v=>v.length!==512||v.some(n=>!Number.isFinite(n))))throw new AppError(503,'VECTOR_INVALID','向量维度或内容无效');
  const saved=await transaction(async c=>{await assertLease(c,current);const d=(await c.query("SELECT id FROM knowledge_documents WHERE id=$1 AND state='approved' AND source_checksum=$2 FOR SHARE",[id,snapshot.d.source_checksum])).rows[0];if(!d)return false;for(let j=0;j<batch.length;j++)await c.query('UPDATE knowledge_chunks SET embedding=$2::public.vector,embedding_model=$3 WHERE id=$1 AND document_id=$4',[batch[j].id,JSON.stringify(vectors[j]),EMBEDDING_VERSION,id]);return true;},pool);
  if(!saved)return {skipped:true,indexed};indexed+=batch.length;
 }return {indexed,model:EMBEDDING_VERSION};});
}
export async function listDocuments(c:PoolClient,a:Actor){const v=await visible(c,a,'knowledge');return {items:(await c.query(`SELECT d.id,d.title,d.version,d.object_ids,d.source_ref,d.evidence_nature,d.state,d.approved_at,d.withdrawn_at,
 (SELECT count(*) FROM knowledge_chunks x WHERE x.document_id=d.id)::int AS chunks,(SELECT count(*) FROM knowledge_chunks x WHERE x.document_id=d.id AND x.embedding_model=$3 AND x.embedding IS NOT NULL)::int AS indexed
 FROM knowledge_documents d WHERE d.object_ids<@$1::uuid[] AND($2::uuid[] IS NULL OR d.id=ANY($2)) ORDER BY d.created_at DESC LIMIT 200`,[v.objects,v.resources,EMBEDDING_VERSION])).rows};}
export interface Evidence{documentId:string;version:string;chunkId:string;title:string;heading:string;text:string;evidenceNature?:string;scopeObjectIds:string[];sourceUrl:string|null;sourceRef:string;score:number;citationUrl:string}
export async function searchKnowledge(c:PoolClient,a:Actor,question:string,options:{mode?:'keyword'|'vector'|'hybrid';vector?:number[];objectIds?:string[];limit?:number}={}){
 const started=performance.now(),query=text(question,'问题',2000),v=await visible(c,a,'knowledge');let ids=v.objects;if(options.objectIds){for(const id of options.objectIds){uuid(id);if(!ids.includes(id))throw new AppError(403,'ACCESS_DENIED','问题包含未授权对象');}ids=options.objectIds;}
 const mode=options.mode??'hybrid',limit=Math.min(10,Math.max(1,options.limit??5)),queryTerms=terms(query),vector=options.vector;if(vector&&(vector.length!==512||vector.some(n=>!Number.isFinite(n))))throw new AppError(400,'VECTOR_INVALID','查询向量维度或数值错误');
 const eligible=`FROM knowledge_chunks x JOIN knowledge_documents d ON d.id=x.document_id WHERE d.state='approved' AND d.object_ids<@$1::uuid[] AND($2::uuid[] IS NULL OR d.id=ANY($2))`;
 const columns='x.id,x.document_id,x.heading,x.text,d.title,d.version,d.object_ids,d.source_url,d.source_ref,d.evidence_nature';
 const keyword=mode==='vector'?[]:(await c.query(`SELECT ${columns},(SELECT count(*)::float8 FROM unnest(x.keywords) term WHERE term=ANY($3::text[])) AS rank ${eligible} AND x.keywords&&$3::text[] ORDER BY rank DESC,x.id LIMIT 20`,[ids,v.resources,queryTerms])).rows;
 const semantic=mode==='keyword'||!vector?[]:(await c.query(`SELECT ${columns},1-(x.embedding OPERATOR(public.<=>) $3::public.vector) AS similarity ${eligible} AND x.embedding IS NOT NULL AND x.embedding_model=$4 ORDER BY x.embedding OPERATOR(public.<=>) $3::public.vector,x.id LIMIT 20`,[ids,v.resources,JSON.stringify(vector),EMBEDDING_VERSION])).rows.filter(r=>r.similarity>=.45);
 const results=new Map<string,{row:any;score:number}>();for(const list of [keyword,semantic])list.forEach((row,index)=>{const prior=results.get(row.id);results.set(row.id,{row,score:(prior?.score??0)+1/(60+index+1)});});
 const items:Evidence[]=[...results.values()].sort((a,b)=>b.score-a.score||a.row.id.localeCompare(b.row.id)).slice(0,limit).map(({row:r,score})=>({documentId:r.document_id,version:r.version,chunkId:r.id,title:r.title,heading:r.heading,text:r.text,evidenceNature:r.evidence_nature,scopeObjectIds:r.object_ids,sourceUrl:r.source_url,sourceRef:r.source_ref,score,citationUrl:'/api/v1/knowledge/chunks/'+r.id}));return {items,mode,vectorUsed:!!vector&&mode!=='keyword',retrievalVersion:'zh-bigram-rrf-v1',embeddingVersion:EMBEDDING_VERSION,elapsedMs:performance.now()-started,limitations:mode!=='keyword'&&!vector?['语义向量未就绪，本次仅关键词检索']:[]};
}
export async function getCitation(c:PoolClient,a:Actor,id:string){uuid(id);const r=(await c.query('SELECT x.*,d.title,d.version,d.object_ids,d.source_ref,d.state FROM knowledge_chunks x JOIN knowledge_documents d ON d.id=x.document_id WHERE x.id=$1',[id])).rows[0];if(!r)throw new AppError(404,'CITATION_NOT_FOUND','引用不存在');for(const objectId of r.object_ids)await scope(c,a,objectId,'read','knowledge',r.document_id);return r.state==='approved'?{id:r.id,title:r.title,version:r.version,heading:r.heading,text:r.text,sourceRef:r.source_ref,status:'active'}:{id:r.id,title:r.title,version:r.version,status:'source_inactive',message:'来源未经审核或已撤回，不能用于新回答'};}
