'use client';
import ObjectWorkspace from '@/components/phase3/object-workspace';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';
type Row=Record<string,any>;const opts=(pairs:[string,string][])=>pairs.map(([id,name])=>({id,name}));
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function Work({objectId}:{objectId:string}){
 const {data,error,reload}=useApi<Row>('/api/v1/control-records/overview?objectId='+objectId);if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取控制准备资料…</p>;
 const common={stableKey:true,onSaved:()=>void reload()},devices=data.devices.map((r:Row)=>({id:r.id,name:r.name})),rules=data.rules.map((r:Row)=>({id:r.id,name:r.purpose+' / 版本'+r.version+' / '+r.state})),requests=data.requests.map((r:Row)=>({id:r.id,name:r.purpose+' / '+r.created_at})),device=<Pick name="deviceId" label="设备" options={devices}/>,evidence=<Field name="evidence" label="实际依据"/>;
 return <div className="stack"><p className="empty-state">{data.limits}</p>
 <details><summary>设备三态与断网停电说明</summary><ActionForm path="/api/v1/control-records/profiles" {...common} times={['validUntil']}>{device}<Pick name="permission" label="操作许可" options={opts([['unknown','未核实'],['allowed','已获许可'],['denied','禁止']])}/><Pick name="mode" label="设备手动或远程模式" options={opts([['unknown','未知'],['manual','手动'],['remote','远程']])}/><Pick name="protection" label="现场保护" options={opts([['unknown','未知'],['active','保护生效'],['clear','已核未触发']])}/><Field name="loadType" label="具体负载类型"/><Field name="offlineBehavior" label="断网行为（未核实须说明）"/><Field name="powerLossBehavior" label="停电行为（未核实须说明）"/><Field name="powerReturnBehavior" label="复电行为（未核实须说明）"/><Field name="protocolRef" label="实际协议依据或缺口"/><Field name="feedbackRef" label="反馈含义依据或缺口"/><Field name="validUntil" label="本次核实有效截止" type="datetime-local"/></ActionForm><StockTable rows={data.profiles} columns={[[ 'version','版本'],['permission','许可'],['mode','模式'],['protection','现场保护'],['load_type','负载'],['valid_until','核实截止']]}/></details>
 <details><summary>专业规则及版本</summary><ActionForm path="/api/v1/control-records/rules" {...common}>{device}<Field name="purpose" label="规则用途"/><Field name="species" label="适用物种"/><Field name="stage" label="适用阶段"/><Field name="conditions" label="触发、停止及人工接管条件"/><Field name="sourceRef" label="专业依据"/></ActionForm><ActionForm path="/api/v1/control-records/rule-review" {...common}><Pick name="id" label="待核规则" options={rules}/><Pick name="action" label="规则审核动作" options={opts([['approve','独立审核通过'],['withdraw','撤回']])}/>{evidence}</ActionForm></details>
 <details><summary>登记控制申请（不会下发）</summary><ActionForm path="/api/v1/control-records/requests" {...common}>{device}<Pick name="ruleId" label="专业规则（未有可留空）" options={rules} required={false}/><Field name="purpose" label="本次申请目的"/><Field name="authorizationRef" label="本次授权依据"/><Field name="conditions" label="本次现场条件"/></ActionForm></details>
 <section><h2>申请与五层反馈</h2>{data.requests.length?data.requests.map((r:Row)=><article className="rule-card" key={r.id}><h3>{r.purpose}</h3><p>申请已登记，未下发。{r.blocked_reasons.join('；')}</p><StockTable rows={r.layers} columns={[[ 'layer','层级'],['result','结果'],['value','反馈值'],['source','来源'],['observed_at','观测时间']]}/></article>):<p>尚无申请。</p>}</section>
 <details><summary>记录外部凭证或现场观测</summary><p>此处记录外部设备回执或现场观察，不能证明平台曾下发命令；未取得的层级保持未知。</p><ActionForm path="/api/v1/control-records/feedback" {...common} times={['observedAt']}><Pick name="requestId" label="相关申请" options={requests}/><Pick name="layer" label="反馈层级" options={opts([['device_received','设备收到'],['electrical','电气动作'],['mechanical','机械到位'],['effect','实际效果']])}/><Pick name="result" label="观测结果" options={opts([['observed','已观测'],['not_observed','未观测到'],['unknown','未知']])}/><Field name="value" label="实际反馈值（未知留空）" required={false}/><Pick name="source" label="凭证来源" options={opts([['vendor_receipt','外部设备回执'],['field_observation','现场人员观测']])}/><Field name="observedAt" label="实际观测时间" type="datetime-local"/>{evidence}</ActionForm></details>
 <details><summary>人工接管记录</summary><ActionForm path="/api/v1/control-records/takeovers" {...common} times={['occurredAt']}>{device}<Pick name="requestId" label="关联申请（可选）" options={requests} required={false}/><Field name="person" label="实际到场人员"/><Field name="manualDevice" label="使用的手动装置"/><Field name="conditions" label="到场时条件"/><Field name="occurredAt" label="实际接管时间" type="datetime-local"/>{evidence}</ActionForm><StockTable rows={data.takeovers} columns={[[ 'person','到场人'],['manual_device','手动装置'],['conditions','现场条件'],['occurred_at','接管时间']]}/></details>
 </div>;
}

