import type {Pool,PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {text,integer,finite,time} from '../../platform/validation';
import {uuid} from '../identity/common';
import {arrayIds,scope,visible,lockKey,payloadHash,sameHash} from '../field/common';
import {transaction,database} from '../../db/pool';
import {enqueue,type JobLease} from '../jobs/repository';
import {assertLease,externalStarted,withLease} from '../jobs/execution';
import {sourcesActive} from '../analysis/evidence';
import {recordUsage} from '../operations/budget';
import {searchKnowledge,getCitation,type Evidence} from '../knowledge/service';
import {embedTexts} from '../models/process';
import {redact,validateAnswer,PROMPT_VERSION,type Fact} from './validate';
import {httpModel,type TextProvider} from './provider';
async function assistantScope(c:PoolClient,a:Actor,id:string){const {assertAccess}=await import('../identity/access');await assertAccess(c,a,{objectId:id,action:'read',at:new Date().toISOString()});if(a.role==='expert'&&!(await c.query("SELECT 1 FROM resource_grants WHERE user_id=$1 AND object_id=$2 AND resource_type IN('knowledge','metric') AND revoked_at IS NULL AND expires_at>now() LIMIT 1",[a.id,id])).rowCount)throw new AppError(403,'ITEM_SCOPE_DENIED','专家问答需要明确授权的知识或指标');}
export async function saveModelPolicy(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.objectId);await scope(c,a,b.objectId,'configure');const input=b.inputPricePerMillion==null||b.inputPricePerMillion===''?null:finite(b.inputPricePerMillion,'输入单价'),output=b.outputPricePerMillion==null||b.outputPricePerMillion===''?null:finite(b.outputPricePerMillion,'输出单价');if((input!==null&&input<0)||(output!==null&&output<0))throw new AppError(400,'MODEL_PRICE','价格不能为负数');return(await c.query('INSERT INTO model_policies(object_id,external_enabled,allow_backup,max_month_tokens,max_month_calls,input_price_per_million,output_price_per_million,price_source,approved_scope,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(object_id) DO UPDATE SET external_enabled=excluded.external_enabled,allow_backup=excluded.allow_backup,max_month_tokens=excluded.max_month_tokens,max_month_calls=excluded.max_month_calls,input_price_per_million=excluded.input_price_per_million,output_price_per_million=excluded.output_price_per_million,price_source=excluded.price_source,approved_scope=excluded.approved_scope,updated_by=excluded.updated_by RETURNING object_id,external_enabled,allow_backup,max_month_tokens,max_month_calls',[b.objectId,b.externalEnabled===true,b.allowBackup===true,integer(b.maxMonthTokens,'月token上限',1),integer(b.maxMonthCalls,'月调用上限',1),input,output,input!==null&&output!==null?text(b.priceSource,'单价依据',2000):null,text(b.approvedScope,'已批准的数据发送范围与许可依据',3000),a.id])).rows[0];}
export async function requestAssistant(c:PoolClient,a:Actor,b:Record<string,unknown>){const ids=arrayIds(b.objectIds,20);if(!ids.length)throw new AppError(400,'ASSISTANT_SCOPE','请选择问题范围');for(const id of ids)await assistantScope(c,a,id);const key=text(b.requestKey,'问答请求标识',120),question=redact(text(b.question,'问题',2000)),hash=payloadHash({ids,question});await lockKey(c,a,'assistant',key);const old=(await c.query('SELECT * FROM assistant_runs WHERE actor_id=$1 AND request_key=$2',[a.id,key])).rows[0];if(old){sameHash(old.input_hash,hash);return {id:old.id,state:old.state};}const user=(await c.query('SELECT auth_version FROM users WHERE id=$1',[a.id])).rows[0],r=(await c.query('INSERT INTO assistant_runs(actor_id,auth_version,object_ids,question,request_key,input_hash,prompt_version,retrieval_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,state',[a.id,user.auth_version,ids,question,key,hash,PROMPT_VERSION,'zh-bigram-rrf-v1'])).rows[0];await enqueue(c,{kind:'assistant.generate',businessKey:'assistant:'+r.id,payload:{runId:r.id},dueAt:new Date().toISOString()});return r;}
async function actorFor(c:PoolClient,run:any):Promise<Actor>{const u=(await c.query('SELECT role,enabled,auth_version FROM users WHERE id=$1',[run.actor_id])).rows[0];if(!u?.enabled||u.auth_version!==run.auth_version)throw new AppError(403,'ASSISTANT_AUTH_CHANGED','问答创建后的账号或授权已变更');const a:Actor={id:run.actor_id,role:u.role,enabled:true,mfaVerified:true};for(const id of run.object_ids)await assistantScope(c,a,id);return a;}
export async function runAssistant(pool:Pool,id:string,provider:TextProvider=httpModel,embedding=embedTexts,lease?:JobLease){
 return withLease(pool,'assistant:'+id,lease,async current=>{
 uuid(id);const run=await transaction(async c=>{await assertLease(c,current);const r=(await c.query('SELECT * FROM assistant_runs WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r||r.state!=='queued')return null;await actorFor(c,r);await c.query("UPDATE assistant_runs SET state='running',started_at=now(),execution_token=$2 WHERE id=$1",[id,current.leaseToken]);return r;},pool);if(!run)return;const started=performance.now();let result:Record<string,unknown>={answer:'程序事实准备未完成',limitations:[]},state='program_only',context:Record<string,unknown>={},model:string|null=null,usage:any=null,errorCode:string|null=null,reserved=false,attempts=0;
 try{
 let vector:number[]|undefined;try{vector=(await embedding([run.question]))[0];}catch{}const prepared=await database(async c=>{await assertLease(c,current);const a=await actorFor(c,run),retrieval=await searchKnowledge(c,a,run.question,{objectIds:run.object_ids,vector}),v=await visible(c,a,'metric');const facts:Fact[]=(await c.query(`SELECT DISTINCT ON(m.definition_id,m.window_start,m.window_end) m.id,m.object_id,m.value,m.unit,m.status,m.limitations,m.definition_version,m.window_start,m.window_end,m.calculated_at,m.coverage,d.name FROM metric_results m JOIN metric_definitions d ON d.id=m.definition_id WHERE m.object_id=ANY($1::uuid[]) AND d.approved_at IS NOT NULL AND d.retired_at IS NULL AND($2::uuid[] IS NULL OR m.id=ANY($2)) ORDER BY m.definition_id,m.window_start,m.window_end,m.version DESC LIMIT 20`,[run.object_ids,v.resources])).rows.map(r=>({id:r.id,objectCode:'O'+(run.object_ids.indexOf(r.object_id)+1),value:r.value,unit:r.unit,status:r.status,limitations:r.limitations,name:r.name,definitionVersion:r.definition_version,windowStart:r.window_start.toISOString(),windowEnd:r.window_end.toISOString(),calculatedAt:r.calculated_at.toISOString(),coverage:r.coverage}));const names=(await c.query('SELECT DISTINCT display_name FROM users WHERE id=$1 OR id IN(SELECT user_id FROM grants WHERE object_id=ANY($2::uuid[])) UNION SELECT name FROM objects WHERE id=ANY($2::uuid[])',[a.id,run.object_ids])).rows.map(r=>r.display_name);for(const f of facts){if(f.name)f.name=redact(f.name,names);f.limitations=f.limitations.map(l=>redact(l,names));}const evidence=retrieval.items.map(e=>({...e,text:redact(e.text,names),title:redact(e.title,names),evidenceNature:e.evidenceNature?redact(e.evidenceNature,names):undefined,sourceUrl:null,scopeObjectIds:[]}));const focusItems=(await c.query('SELECT i.id,i.object_id,i.original_text,i.limitations,i.fact_refs FROM briefing_explanation_runs l JOIN briefing_items i ON i.briefing_id=l.briefing_id WHERE l.run_id=$1',[run.id])).rows.map(i=>({id:i.id,objectCode:'O'+(run.object_ids.indexOf(i.object_id)+1),text:redact(i.original_text,names),limitations:i.limitations,factRefs:i.fact_refs}));for(const i of focusItems)facts.push({id:i.id,objectCode:i.objectCode,kind:'briefing_item',text:i.text,status:i.text.includes('暂不能判断')||i.limitations.some((l:string)=>l.includes('暂不能判断'))?'insufficient':'usable',value:null,unit:'',limitations:i.limitations});return {evidence,facts,retrieval,focusItems,question:redact(run.question,names)};},pool);
 context={focusItems:prepared.focusItems,question:prepared.question,facts:prepared.facts,evidence:prepared.evidence.map(e=>({chunkId:e.chunkId,text:e.text,version:e.version,evidenceNature:e.evidenceNature})),limitations:prepared.retrieval.limitations};result={answer:'以下为程序查询到的事实与审核资料摘录，尚未形成模型解释。',facts:prepared.facts,evidence:prepared.evidence,limitations:prepared.retrieval.limitations};
 if(!prepared.evidence.length&&!prepared.facts.length){state='no_evidence';result.answer='当前授权范围没有可用依据，暂不能回答。';}
 else{
 const tokenReservation=(JSON.stringify(context).length*4+4096)*2,policy=await transaction(async c=>{await assertLease(c,current);await actorFor(c,run);const policies=[];for(const objectId of [...run.object_ids].sort()){await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['model-budget:'+objectId]);const p=(await c.query('SELECT * FROM model_policies WHERE object_id=$1 FOR SHARE',[objectId])).rows[0];if(!p?.external_enabled)return null;const budget=(await c.query(`SELECT COALESCE(sum(COALESCE(actual_tokens,reserved_tokens)),0)::float8 AS tokens,COALESCE(sum(COALESCE(actual_calls,reserved_calls)),0)::int AS calls FROM model_reservations WHERE object_id=$1 AND month=date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')::date AND state<>'cancelled'`,[objectId])).rows[0];if(budget.tokens+tokenReservation>Number(p.max_month_tokens)||budget.calls+2>p.max_month_calls)throw new AppError(429,'MODEL_BUDGET_LIMIT','模型月度用量上限已达到，保留程序结果');const money=(await c.query("SELECT b.limit_amount::float8,COALESCE((SELECT sum(amount) FROM usage_events WHERE object_id=b.object_id AND category='model' AND date_trunc('month',occurred_at AT TIME ZONE 'Asia/Shanghai')::date=b.month),0)::float8 AS spent FROM budgets b WHERE object_id=$1 AND category='model' AND month=date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')::date",[objectId])).rows[0];if(money){if(p.input_price_per_million===null||p.output_price_per_million===null)throw new AppError(429,'MODEL_PRICE_UNKNOWN','模型费用上限已配置但单价未知，暂不外发');const reserveCost=tokenReservation*Math.max(Number(p.input_price_per_million),Number(p.output_price_per_million))/1e6;if(money.spent+Number((await c.query("SELECT COALESCE(sum(reserved_cost),0) AS n FROM model_reservations WHERE object_id=$1 AND month=date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')::date AND state IN('reserved','unknown')",[objectId])).rows[0].n)+reserveCost>money.limit_amount)throw new AppError(429,'MODEL_BUDGET_LIMIT','模型费用上限不足本次保守预留，保留程序结果');}policies.push(p);}
 if(process.env.MODEL_EXTERNAL_ENABLED!=='1'&&provider===httpModel)return null;
 for(const objectId of run.object_ids)await c.query("INSERT INTO model_reservations(run_id,object_id,month,reserved_tokens,reserved_cost) VALUES($1,$2,date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')::date,$3,$4) ON CONFLICT(run_id,object_id) DO UPDATE SET state='reserved',reserved_tokens=excluded.reserved_tokens,actual_calls=NULL,actual_tokens=NULL WHERE model_reservations.state='cancelled'",[id,objectId,tokenReservation,policies.find(p=>p.object_id===objectId)!.input_price_per_million===null?null:tokenReservation*Math.max(Number(policies.find(p=>p.object_id===objectId)!.input_price_per_million),Number(policies.find(p=>p.object_id===objectId)!.output_price_per_million))/1e6]);return policies;},pool);
 if(policy){reserved=true;
 const callModel=async(backup:boolean)=>{
  const attempt=await transaction(async c=>{
   await assertLease(c,current);const a=await actorFor(c,run);for(const e of prepared.evidence)if((await getCitation(c,a,e.chunkId)).status!=='active')throw new AppError(409,'SOURCE_INACTIVE','来源已撤回，不再发送');if(!await sourcesActive(c,prepared.facts.map(f=>({kind:f.kind??'metric',id:f.id}))))throw new AppError(409,'SOURCE_INACTIVE','指标或简报来源已失效');
   if(provider===httpModel&&process.env.MODEL_EXTERNAL_ENABLED!=='1')throw new AppError(403,'MODEL_EXTERNAL_DISABLED','模型外发已关闭');
   const month=(await c.query("SELECT date_trunc('month',clock_timestamp() AT TIME ZONE 'Asia/Shanghai')::date::text AS month")).rows[0].month,prices:Record<string,unknown>={};
   for(const objectId of [...run.object_ids].sort()){
    await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['model-budget:'+objectId]);const p=(await c.query('SELECT * FROM model_policies WHERE object_id=$1 FOR SHARE',[objectId])).rows[0];
    if(!p?.external_enabled||(backup&&!p.allow_backup))throw new AppError(403,'MODEL_PERMISSION_CHANGED','当前外发或备用许可已撤回');
    const reservation=(await c.query('SELECT *,month::text AS month_text FROM model_reservations WHERE run_id=$1 AND object_id=$2 FOR UPDATE',[id,objectId])).rows[0];
    if(!reservation||reservation.month_text!==month)throw new AppError(429,'MODEL_MONTH_CHANGED','调用跨月，先核对原预留再重新申请');
    const totals=(await c.query("SELECT COALESCE(sum(COALESCE(actual_tokens,reserved_tokens)),0)::float8 AS tokens,COALESCE(sum(COALESCE(actual_calls,reserved_calls)),0)::int AS calls FROM model_reservations WHERE object_id=$1 AND month=$2 AND state<>'cancelled'",[objectId,month])).rows[0];
    if(totals.tokens>Number(p.max_month_tokens)||totals.calls>p.max_month_calls)throw new AppError(429,'MODEL_BUDGET_LIMIT','当前上限不足，不再调用');
    const money=(await c.query("SELECT limit_amount::float8 FROM budgets WHERE object_id=$1 AND month=$2 AND category='model'",[objectId,month])).rows[0];
    const reserveCost=p.input_price_per_million==null||p.output_price_per_million==null?null:Math.max(Number(reservation.reserved_cost??0),tokenReservation*Math.max(Number(p.input_price_per_million),Number(p.output_price_per_million))/1e6);
    if(money){if(reserveCost==null)throw new AppError(429,'MODEL_PRICE_UNKNOWN','单价未知，停止外发');const spent=Number((await c.query("SELECT COALESCE(sum(amount),0) AS n FROM usage_events WHERE object_id=$1 AND category='model' AND date_trunc('month',occurred_at AT TIME ZONE 'Asia/Shanghai')::date=$2",[objectId,month])).rows[0].n),held=Number((await c.query("SELECT COALESCE(sum(reserved_cost),0) AS n FROM model_reservations WHERE object_id=$1 AND month=$2 AND state IN('reserved','unknown') AND run_id<>$3",[objectId,month,id])).rows[0].n);if(spent+held+reserveCost>money.limit_amount)throw new AppError(429,'MODEL_BUDGET_LIMIT','当前费用上限不足');}
    await c.query('UPDATE model_reservations SET reserved_cost=$3 WHERE run_id=$1 AND object_id=$2',[id,objectId,reserveCost]);prices[objectId]={input:p.input_price_per_million,output:p.output_price_per_million,source:p.price_source,approvedScope:p.approved_scope};
   }
   await externalStarted(c,current);return (await c.query('INSERT INTO model_attempts(run_id,execution_token,backup,month,price_snapshot) VALUES($1,$2,$3,$4,$5) RETURNING id',[id,current.leaseToken,backup,month,JSON.stringify(prices)])).rows[0];
  },pool);attempts++;
  try{const response=await provider(context,backup);await transaction(async c=>{await assertLease(c,current);await c.query("UPDATE model_attempts SET outcome='response',model=$2,usage=$3,completed_at=now() WHERE id=$1",[attempt.id,response.model,response.usage]);},pool);return response;}
  catch(e){if(e instanceof AppError&&e.code==='LEASE_LOST')throw e;await transaction(async c=>{await assertLease(c,current);await c.query('UPDATE model_attempts SET error_code=$2,completed_at=now() WHERE id=$1',[attempt.id,e instanceof AppError?e.code:'MODEL_FAILED']);},pool);throw e;}
 };
 let response;try{response=await callModel(false);}catch(e){if(e instanceof AppError&&e.code==='MODEL_HTTP_FAILED')response=await callModel(true);else throw e;}
model=response.model;usage=response.usage;if(response.truncated)throw new AppError(502,'MODEL_TRUNCATED','模型响应被截断，未生成可用解释');const checked=validateAnswer(response.output,prepared.evidence,prepared.facts);if(prepared.focusItems.length){const claims=Array.isArray((response.output as any)?.claims)?(response.output as any).claims:[],expected=new Set(prepared.focusItems.map(i=>i.id)),covered=new Set<string>();for(const claim of claims){if(!claim||!Array.isArray(claim.itemIds)||claim.itemIds.some((id:string)=>!expected.has(id)))checked.errors.push('简报事项ID不完整或不在本次范围');else for(const itemId of claim.itemIds){covered.add(itemId);for(const limit of prepared.focusItems.find(i=>i.id===itemId)!.limitations)if(!Array.isArray(claim.limitations)||!claim.limitations.includes(limit))checked.errors.push('遗漏简报事项必需限制');}}if(covered.size!==expected.size)checked.errors.push('模型遗漏程序事项，保留程序简报');checked.valid=checked.errors.length===0;}if(!checked.valid){state='validation_failed';result.validationErrors=checked.errors;}else{state='answered';result={...result,answer:'模型解释待人工核对',claims:(response.output as Record<string,unknown>).claims};}
 }else result.limitations=[...prepared.retrieval.limitations,'真实模型外发未启用，当前为程序结果'];
 }
 }catch(e){if(e instanceof AppError&&e.code==='LEASE_LOST')throw e;errorCode=e instanceof AppError?e.code:'MODEL_FAILED';state=errorCode==='MODEL_TIMEOUT'||errorCode==='MODEL_RESPONSE_TOO_LARGE'?'result_unknown':errorCode==='SOURCE_INACTIVE'?'source_inactive':errorCode.includes('BUDGET')||errorCode==='MODEL_PRICE_UNKNOWN'?'budget_limited':errorCode.includes('AUTH')||errorCode.includes('SCOPE')||errorCode==='ACCESS_DENIED'?'access_revoked':'service_unavailable';result={...result,answer:e instanceof AppError?e.message:'问答服务不可用，不能当作正常回答',limitations:[...(Array.isArray(result.limitations)?result.limitations:[]),'自动解释未完成，请查看原始资料和程序指标']};}
 await transaction(async c=>{await assertLease(c,current);try{await actorFor(c,run);}catch{state='access_revoked';result={answer:'当前授权已失效，禁止返回生成内容'};context={};}if(Array.isArray(result!.evidence)){for(const evidence of result!.evidence as Evidence[]){try{const a=await actorFor(c,run);if((await getCitation(c,a,evidence.chunkId)).status!=='active'){state='source_inactive';result={answer:'生成期间来源已撤回，不返回旧模型内容'};break;}}catch{state='access_revoked';result={answer:'生成期间资料授权已失效，不返回生成内容'};break;}}}if(Array.isArray(result!.facts)&&!await sourcesActive(c,(result!.facts as Fact[]).map(f=>({kind:f.kind??'metric',id:f.id})))){state='source_inactive';result={answer:'生成期间程序事实来源已失效，不返回旧结论',sourceInactive:true};}if(reserved){const logged=(await c.query('SELECT * FROM model_attempts WHERE run_id=$1 ORDER BY started_at,id',[id])).rows,known=logged.length>0&&logged.every(x=>x.outcome==='response'&&x.usage);const total=known?{inputTokens:logged.reduce((n,x)=>n+x.usage.inputTokens,0),outputTokens:logged.reduce((n,x)=>n+x.usage.outputTokens,0)}:null;
 for(const objectId of run.object_ids){await c.query('UPDATE model_reservations SET state=$3,actual_tokens=$4,actual_calls=$5 WHERE run_id=$1 AND object_id=$2',[id,objectId,!logged.length?'cancelled':known?'settled':'unknown',total?total.inputTokens+total.outputTokens:null,logged.length]);if(!logged.length)continue;const priced=known&&logged.every(x=>x.price_snapshot[objectId]?.input!=null&&x.price_snapshot[objectId]?.output!=null&&run.object_ids.every((o:string)=>Number(x.price_snapshot[o]?.input)===Number(x.price_snapshot[objectId].input)&&Number(x.price_snapshot[o]?.output)===Number(x.price_snapshot[objectId].output))),amount=priced?logged.reduce((n,x)=>{const p=x.price_snapshot[objectId];return n+(x.usage.inputTokens*Number(p.input)+x.usage.outputTokens*Number(p.output))/1e6/run.object_ids.length;},0):null;await recordUsage(c,{objectId,category:'model',businessKey:'model-run:'+id+':'+objectId,occurredAt:logged[0].started_at.toISOString(),units:total?total.inputTokens+total.outputTokens:0,amount,priceSource:amount!==null?[...new Set(logged.map(x=>x.price_snapshot[objectId].source))].join(';'):undefined});}}

 await c.query('UPDATE assistant_runs SET state=$2,model=$3,context=$4,result=$5,completed_at=now(),error_code=$6,usage=$7,elapsed_ms=$8 WHERE id=$1',[id,state,model,context,result!,errorCode,usage?{...usage,attempts,wholeRunUsageKnown:attempts===1}:{attempts,wholeRunUsageKnown:false},performance.now()-started]);},pool);
 });
}
export async function listAssistant(c:PoolClient,a:Actor){const ids=await visible(c,a,'assistant_scope'),rows=(await c.query('SELECT id,object_ids,question,state,result,model,prompt_version,retrieval_version,error_code,usage,elapsed_ms,created_at,completed_at FROM assistant_runs WHERE actor_id=$1 AND object_ids<@$2::uuid[] ORDER BY created_at DESC LIMIT 50',[a.id,ids.objects])).rows;for(const r of rows){for(const objectId of r.object_ids)await assistantScope(c,a,objectId);const refs=r.result?.evidence??[];let inactive=false;for(const e of refs as Evidence[]){try{if((await getCitation(c,a,e.chunkId)).status!=='active')inactive=true;}catch{inactive=true;}}if(r.result?.facts){if(!await sourcesActive(c,(r.result.facts as Fact[]).map(f=>({kind:f.kind??'metric',id:f.id}))))inactive=true;const current=await visible(c,a,'metric');if(current.resources&&r.result.facts.some((f:Fact)=>!current.resources!.includes(f.id)))inactive=true;}if(inactive){r.result={answer:'原回答来源已撤回或授权失效，旧结论不再可用',sourceInactive:true};}if(r.state==='running'&&Date.now()-new Date(r.created_at).getTime()>120000)r.state='result_unknown';}return {items:rows};}
export async function runReadTool(c:PoolClient,a:Actor,name:string,args:Record<string,unknown>){if(Object.keys(args).some(k=>!['objectId','from','to'].includes(k)))throw new AppError(400,'TOOL_ARGUMENTS','工具参数含未允许字段');uuid(args.objectId);await assistantScope(c,a,args.objectId);switch(name){case'metrics':{const v=await visible(c,a,'metric'),from=args.from?time(args.from):null,to=args.to?time(args.to):null;if((from===null)!==(to===null)||(from&&to&&from>=to))throw new AppError(400,'TOOL_PERIOD','查询时间须成对且先后有效');return (await c.query('SELECT m.id,m.value,m.unit,m.status,m.limitations,m.definition_id,m.definition_version,m.window_start,m.window_end,m.calculated_at FROM metric_results m JOIN metric_definitions d ON d.id=m.definition_id WHERE m.object_id=$1 AND d.approved_at IS NOT NULL AND d.retired_at IS NULL AND($2::uuid[] IS NULL OR m.id=ANY($2)) AND($3::timestamptz IS NULL OR(m.window_start>=$3 AND m.window_end<=$4)) ORDER BY m.calculated_at DESC LIMIT 20',[args.objectId,v.resources,from,to])).rows;}case'knowledge':return searchKnowledge(c,a,'农事',{objectIds:[args.objectId]});default:throw new AppError(403,'TOOL_NOT_ALLOWED','只允许预定义只读查询，不能执行SQL、派单、控制或外发');}}
