import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text,time,choice,optionalText} from '../../platform/validation';import {uuid} from '../identity/common';import {arrayIds,scope} from '../field/common';import {access,request,type Body} from '../phase4/common';import {quantity,decimal,signedMicros} from '../inventory/quantity';import {researchProtocol,assertResearchProtocol} from './protocols';
export function researchValue(v:unknown){const s=typeof v==='number'?String(v):typeof v==='string'?v:'';if(!/^-?\d+(\.\d{1,6})?$/.test(s))throw new AppError(400,'RESEARCH_VALUE','观测值须为最多六位小数的十进制数');quantity(s.startsWith('-')?s.slice(1):s);return decimal(signedMicros(s));}
export async function recordResearchObservation(c:PoolClient,a:Actor,b:Body){const p=await researchProtocol(c,a,b.protocolId,'record');return request(c,a,b,'research.observation',p.object_id,async()=>{
 await c.query('SELECT id FROM research_protocols WHERE id=$1 FOR UPDATE',[p.id]);await assertResearchProtocol(c,p.id);uuid(b.plotObjectId);if(!p.plots.some((plot:any)=>plot.objectId===b.plotObjectId))throw new AppError(422,'RESEARCH_PLOT','对象不属于当前协议小区');await access(c,a,b.plotObjectId,'record');
 const metric=p.metrics.find((m:any)=>m.code===b.metric);if(!metric||b.method!==metric.method||b.unit!==undefined&&b.unit!==metric.unit)throw new AppError(422,'RESEARCH_METRIC','指标、方法和单位须与协议一致');const at=time(b.observedAt);if(new Date(at)<p.starts_at||new Date(at)>p.ends_at)throw new AppError(422,'RESEARCH_PERIOD','观测时间不在协议窗口内');
 const value=b.value==null||b.value===''?null:researchValue(b.value),missing=optionalText(b.missingReason,'缺测原因',2000);if(value===null&&!missing)throw new AppError(422,'RESEARCH_MISSING_REASON','未知值须登记缺测原因');const ids=arrayIds(b.assetIds??[],20),kind=choice(b.kind,['field','lab_report'] as const,'观测类别'),agency=optionalText(b.agency,'报告机构',200),report=optionalText(b.reportRef,'报告编号及版本',2000);
 for(const id of ids){const m=(await c.query('SELECT * FROM media_assets WHERE id=$1',[id])).rows[0];if(!m||![p.object_id,b.plotObjectId].includes(m.object_id)||m.ingest_state!=='complete')throw new AppError(422,'RESEARCH_ASSET','原件须完整入库并属于试验或当前小区');await scope(c,a,m.object_id,'read','media',id);}
 if(kind==='lab_report'&&(!agency||!report||!ids.length))throw new AppError(422,'RESEARCH_LAB_REPORT','第三方报告须有机构、编号版本和已入库原件');
 const sample=text(b.sampleKey,'观察记录号',120),old=(await c.query('SELECT * FROM research_observations WHERE protocol_id=$1 AND plot_object_id=$2 AND metric=$3 AND sample_key=$4 ORDER BY version DESC LIMIT 1',[p.id,b.plotObjectId,metric.code,sample])).rows[0];if(old&&b.supersedesId!==old.id||!old&&b.supersedesId)throw new AppError(409,'RESEARCH_OBSERVATION_VERSION','同一观察记录已有内容，更正须引用当前版本');
 return(await c.query('INSERT INTO research_observations(object_id,protocol_id,plot_object_id,metric,sample_key,value,unit,observed_at,method,kind,agency,report_ref,missing_reason,evidence,asset_ids,version,supersedes_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) RETURNING *',[p.object_id,p.id,b.plotObjectId,metric.code,sample,value,metric.unit,at,metric.method,kind,agency,report,missing,text(b.evidence,'原始观测依据',4000),ids,(old?.version??0)+1,old?.id??null,a.id])).rows[0];
 });}
