import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text,choice,integer} from '../../platform/validation';import {uuid} from '../identity/common';import {scope} from '../field/common';import {access,request,independent,period,type Body} from '../phase4/common';
export async function researchProtocol(c:PoolClient,a:Actor,id:unknown,action:'read'|'record'|'review'='read'){uuid(id);const r=(await c.query('SELECT * FROM research_protocols WHERE id=$1',[id])).rows[0];if(!r)throw new AppError(404,'RESEARCH_PROTOCOL','试验协议不存在');await scope(c,a,r.object_id,'read','research_protocol',r.id);if(action!=='read')await access(c,a,r.object_id,action);if(a.role!=='expert')for(const plot of r.plots)await access(c,a,plot.objectId,'read');return r;}
export async function assertResearchProtocol(c:PoolClient,id:string){const r=(await c.query(`SELECT p.*,COALESCE((SELECT action='approve' FROM research_reviews WHERE protocol_id=p.id ORDER BY seq DESC LIMIT 1),false) AND NOT EXISTS(SELECT 1 FROM research_protocols n WHERE n.supersedes_id=p.id) AS eligible FROM research_protocols p WHERE id=$1 FOR SHARE OF p`,[id])).rows[0];if(!r?.eligible)throw new AppError(409,'RESEARCH_NOT_APPROVED','试验协议未独立核实、已修订或撤回');return r;}
export async function createResearchProtocol(c:PoolClient,a:Actor,b:Body){await access(c,a,b.objectId);return request(c,a,b,'research.protocol',b.objectId as string,async()=>{
 if(!Array.isArray(b.plots)||b.plots.length<2||b.plots.length>20||!Array.isArray(b.metrics)||!b.metrics.length||b.metrics.length>20)throw new AppError(422,'RESEARCH_DESIGN','须2至20个小区和1至20项指标');
 const plots=[];for(const p of b.plots){uuid(p?.objectId);await access(c,a,p.objectId,'read');const obj=(await c.query('SELECT id,name,code,version,boundary_status FROM objects WHERE id=$1',[p.objectId])).rows[0];if(!obj)throw new AppError(422,'RESEARCH_PLOT','试验小区不存在');if(p.batchId){uuid(p.batchId);if((await c.query('SELECT object_id FROM production_batches WHERE id=$1',[p.batchId])).rows[0]?.object_id!==obj.id)throw new AppError(422,'RESEARCH_BATCH','生产批次不属于该小区');}plots.push({objectId:obj.id,label:text(p.label,'小区名称',100),group:choice(p.group,['control','treatment'] as const,'分组'),batchId:p.batchId||null,objectVersion:obj.version,boundaryStatus:obj.boundary_status});}
 if(new Set(plots.map(p=>p.objectId)).size!==plots.length||!plots.some(p=>p.group==='control')||!plots.some(p=>p.group==='treatment'))throw new AppError(422,'RESEARCH_CONTROL','处理与对照须为不同对象，不能重复使用同一小区');
 const metrics=b.metrics.map((m:any)=>{const code=text(m?.code,'指标代号',40);if(!/^[a-z][a-z0-9_]{0,39}$/.test(code))throw new AppError(422,'RESEARCH_METRIC','指标代号使用小写字母、数字和下划线');return{code,name:text(m.name,'指标名称',100),unit:text(m.unit,'指标单位',40),method:text(m.method,'观测方法',1000),expectedSamples:integer(m.expectedSamples,'每小区计划观测条数',1,100000)};});if(new Set(metrics.map(m=>m.code)).size!==metrics.length)throw new AppError(422,'RESEARCH_METRIC','指标代号重复');
 const {start,end}=period(b.startsAt,b.endsAt,3660);let old:any=null;if(b.supersedesId){old=await researchProtocol(c,a,b.supersedesId,'record');await c.query('SELECT id FROM research_protocols WHERE id=$1 FOR UPDATE',[old.id]);if(old.object_id!==b.objectId||(await c.query('SELECT 1 FROM research_protocols WHERE supersedes_id=$1',[old.id])).rowCount)throw new AppError(409,'RESEARCH_VERSION','原协议已修订或对象不符');}
 return(await c.query('INSERT INTO research_protocols(object_id,title,question,baseline,plots,metrics,starts_at,ends_at,testing_plan,stop_rules,source_ref,version,supersedes_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *',[b.objectId,text(b.title,'试验标题'),text(b.question,'研究问题',4000),text(b.baseline,'基线依据',4000),JSON.stringify(plots),JSON.stringify(metrics),start,end,text(b.testingPlan,'第三方检测计划',4000),text(b.stopRules,'停止条件',4000),text(b.sourceRef,'协议依据',4000),(old?.version??0)+1,old?.id??null,a.id])).rows[0];
 });}
export async function reviewResearchProtocol(c:PoolClient,a:Actor,b:Body){const p=await researchProtocol(c,a,b.id,'review');return request(c,a,b,'research.protocol-review',p.object_id,async()=>{await c.query('SELECT id FROM research_protocols WHERE id=$1 FOR UPDATE',[p.id]);independent(a,p.created_by);const action=choice(b.action,['approve','withdraw'] as const,'协议审核动作');if(action==='approve'&&(await c.query('SELECT 1 FROM research_protocols WHERE supersedes_id=$1',[p.id])).rowCount)throw new AppError(409,'RESEARCH_VERSION','旧协议已有修订版本');return(await c.query('INSERT INTO research_reviews(object_id,protocol_id,action,evidence,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[p.object_id,p.id,action,text(b.evidence,'独立审核依据',4000),a.id])).rows[0];});}
