import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {access,exportTables} from '../phase4/common';import {listAccessibleObjects} from '../identity/access';import {researchResult} from './results';
export const researchTables=['research_protocols','research_reviews','research_observations','research_results','research_result_reviews'] as const;
export async function researchOverview(c:PoolClient,a:Actor,objectId:string){await access(c,a,objectId,'read');const ids=await listAccessibleObjects(c,a,'read'),protocols=(await c.query('SELECT * FROM research_protocols WHERE object_id=$1 ORDER BY created_at DESC,id LIMIT 200',[objectId])).rows.filter(p=>p.plots.every((x:any)=>ids.includes(x.objectId))),pids=protocols.map(p=>p.id),result:Record<string,any>={limit:200,protocols};
 result.plots=(await c.query('SELECT id,name,code,boundary_status FROM objects WHERE id=ANY($1::uuid[]) ORDER BY name,id LIMIT 200',[ids])).rows;
 result.observations=(await c.query('SELECT o.*,NOT EXISTS(SELECT 1 FROM research_observations n WHERE n.supersedes_id=o.id) AS current FROM research_observations o WHERE protocol_id=ANY($1::uuid[]) ORDER BY created_at DESC,id LIMIT 200',[pids])).rows;
 result.results=(await c.query('SELECT id FROM research_results WHERE protocol_id=ANY($1::uuid[]) ORDER BY created_at DESC,id LIMIT 200',[pids])).rows;result.results=await Promise.all(result.results.map((r:any)=>researchResult(c,a,r.id)));
 result.expenses=['owner','technician','admin'].includes(a.role)?(await c.query("SELECT id,voucher,amount_cny,link_kind,link_id,evidence FROM business_expenses e WHERE object_id=$1 AND NOT EXISTS(SELECT 1 FROM business_expenses n WHERE n.supersedes_id=e.id) AND ((link_kind='research_protocol' AND link_id=ANY($2::uuid[])) OR (link_kind='research_result' AND link_id=ANY($3::uuid[]))) ORDER BY created_at DESC,id LIMIT 200",[objectId,pids,result.results.map((r:any)=>r.id)])).rows:null;
 result.media=(await c.query("SELECT id,name,object_id FROM media_assets WHERE object_id=ANY($1::uuid[]) AND ingest_state='complete' ORDER BY created_at DESC,id LIMIT 200",[[objectId,...protocols.flatMap(p=>p.plots.map((x:any)=>x.objectId))]])).rows;
 return result;
}
export async function exportResearch(c:PoolClient,a:Actor,objectId:string){await access(c,a,objectId,'export');const protocols=(await c.query('SELECT plots FROM research_protocols WHERE object_id=$1',[objectId])).rows;for(const p of protocols)for(const plot of p.plots){await access(c,a,plot.objectId,'read');await access(c,a,plot.objectId,'export');}return exportTables(c,a,objectId,researchTables);}
