import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdir} from 'node:fs/promises';import {chromium} from 'playwright';import {withDb} from '../support/db';import {withApp} from '../support/app';import {phase4Fixture} from '../support/phase4';import {permit} from '../support/fixtures';
test('C46 真实页面协议小区、独立审核、观察快照与管理worker',{timeout:150000},()=>withDb(async pool=>{
 const f=await phase4Fixture(pool),plots:string[]=[];for(const label of ['合成对照小区','合成处理小区']){const id=randomUUID();await pool.query("INSERT INTO objects(id,parent_id,code,name,kind,source,created_by) VALUES($1::uuid,$2,$1::text,$3,'field','合成工程试验',$4)",[id,f.objectId,label,f.actor.id]);for(const a of [f.actor,f.reviewer])await permit(pool,a.id,id,['read','record','review','export']);plots.push(id);}
 await withApp(pool,async app=>{const browser=await chromium.launch(),ctx=await browser.newContext({timezoneId:'UTC',viewport:{width:1280,height:900}}),other=await browser.newContext({timezoneId:'UTC'}),page=await ctx.newPage(),review=await other.newPage();try{
 await ctx.addCookies([{name:'agri_session',value:await app.authenticate(f.actor),url:app.origin}]);await other.addCookies([{name:'agri_session',value:await app.authenticate(f.reviewer),url:app.origin}]);await page.goto(app.origin+'/research');await page.getByLabel('当前对象',{exact:true}).selectOption(f.objectId);await page.getByText('建立试验协议与小区',{exact:true}).click();const p=page.locator('form').filter({has:page.getByLabel('试验协议名称')});
 for(const [label,value] of [['试验协议名称','合成浏览器试验'],['要回答的研究问题','软件记录能否保留历史'],['基线与原始依据','合成基线'],['指标代号（小写字母、数字、下划线）','height'],['指标名称','株高'],['指标单位','cm'],['统一观测方法','合成尺量v1'],['每小区计划观测条数','1'],['第三方检测机构、方法、范围与计划','仅合成计划，未委托机构'],['停止或调整条件','工程测试结束'],['协议来源与版本依据','合成方案']])await p.getByLabel(label,{exact:true}).fill(value);
 await p.getByLabel('对照小区（可多选）').selectOption([plots[0]]);await p.getByLabel('处理小区（可多选）').selectOption([plots[1]]);await p.getByLabel('试验窗口开始').fill('2026-10-01T00:00');await p.getByLabel('试验窗口结束').fill('2026-11-01T00:00');await p.getByRole('button',{name:'保存',exact:true}).click();await p.getByText('已保存',{exact:true}).waitFor();
 await review.goto(app.origin+'/research');await review.getByLabel('当前对象',{exact:true}).selectOption(f.objectId);await review.getByText('独立审核当前协议',{exact:true}).click();const check=review.locator('form').filter({has:review.getByLabel('协议审核动作')});await check.getByLabel('协议审核动作').selectOption('approve');await check.getByLabel('协议审核依据').fill('独立工程核实');await check.getByRole('button',{name:'保存',exact:true}).click();await check.getByText('已保存',{exact:true}).waitFor();
 await page.getByText('登记观测或第三方报告',{exact:true}).click();const obs=page.locator('form').filter({has:page.getByLabel('稳定观察记录号')});for(const [i,id] of plots.entries()){await obs.getByLabel('观测小区').selectOption(id);await obs.getByLabel('稳定观察记录号').fill('OBS-1');await obs.getByLabel('观测值（未知留空，0需实测）').fill(String(10+i));await obs.getByLabel('实际观测时间').fill('2026-10-03T00:00');await obs.getByLabel('观测资料性质').selectOption('field');await obs.getByLabel('观测或更正原始依据').fill('合成观测，不是实际农业样本');await obs.getByRole('button',{name:'保存',exact:true}).click();await obs.getByText('已保存',{exact:true}).waitFor();}
 await page.getByText('生成固定结果证据包',{exact:true}).click();const result=page.locator('form').filter({has:page.getByLabel('结果证据包名称')});await result.getByLabel('结果证据包名称').fill('合成结果包');await result.getByLabel('成果说明、缺口与限制').fill('只验证软件链');await result.getByLabel('成果证据性质').selectOption('self_reported');await result.getByLabel('成果来源或正式口径依据').fill('合成工程记录');await result.getByRole('button',{name:'保存',exact:true}).click();await result.getByText('已保存',{exact:true}).waitFor();assert.equal((await pool.query('SELECT summary FROM research_results')).rows[0].summary.groups.length,2);
 await page.getByRole('link',{name:'合成结果包 · 版本1',exact:true}).click();await page.getByRole('heading',{name:'合成结果包',exact:true}).waitFor();
 await page.goto(app.origin+'/management');await page.getByLabel('当前对象',{exact:true}).selectOption(f.objectId);await page.getByText('生成一份管理报告',{exact:true}).click();const report=page.locator('form').filter({has:page.getByLabel('本次统计范围与用途')});await report.getByLabel('统计窗口开始').fill('2026-10-01T00:00');await report.getByLabel('统计窗口结束（不含）').fill('2026-11-01T00:00');await report.getByLabel('本次统计范围与用途').fill('合成综合指标报告');await report.getByRole('button',{name:'保存',exact:true}).click();await report.getByText('已保存',{exact:true}).waitFor();app.worker('workers/management.ts');await page.getByRole('button',{name:'刷新计算进度',exact:true}).click();await page.getByText(/合成综合指标报告 ·/).click();await page.getByRole('heading',{name:'经营记录',exact:true}).waitFor();assert.equal((await pool.query('SELECT state FROM management_reports')).rows[0].state,'complete');await page.getByText('未知／无分母',{exact:true}).first().waitFor();
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.app-sidebar')!.getBoundingClientRect().right<=1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await mkdir('docs/acceptance/4c',{recursive:true});await page.screenshot({path:'docs/acceptance/4c/综合指标手机合成实测.png',fullPage:true});
 }catch(e){console.log(await page.locator('.form-error').allTextContents());await page.screenshot({path:'.local/4C页面失败.png',fullPage:true});throw e;}finally{await browser.close();}});
}));
