import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm,writeFile,mkdir} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import sharp from 'sharp';import {chromium} from 'playwright';
import {withDb} from '../support/db';import {withApp} from '../support/app';import {telemetryFixture} from '../support/telemetry';import {transaction} from '../../src/db/pool';import {saveBoundary} from '../../src/modules/map/service';import {importFlight,linkFlightAsset} from '../../src/modules/flights/service';import {saveCoverage,queueRaster,runRaster} from '../../src/modules/flights/spatial';import {prepareMedia,uploadMedia} from '../../src/modules/media/service';import {localStore,checksum} from '../../src/modules/media/storage';
test('一期成果浏览器：跨期预览、原片点选定位及21MiB断块续传/后台校验/Range',{timeout:120000},()=>withDb(async pool=>{
 const f=await telemetryFixture(pool),dir=await mkdtemp(join(tmpdir(),'agri-phase1-browser-')),store=localStore(join(dir,'source'),join(dir,'backup')),geometry={type:'Polygon',coordinates:[[[114,30],[114.01,30],[114.01,30.01],[114,30.01],[114,30]]]};
 try{await transaction(c=>saveBoundary(c,f.actor,{objectId:f.objectId,version:1,sourceCrs:4326,status:'verified',source:'合成边界',geometry}),pool);
  const rasters:string[]=[],files:string[]=[];
  for(let i=0;i<2;i++){const image=await sharp({create:{width:32,height:32,channels:3,background:i?'#997755':'#447744'}}).png().toBuffer(),assetId=randomUUID(),sum=checksum(image),flight=await transaction(c=>importFlight(c,f.actor,{objectId:f.objectId,sourceId:f.source.id,externalId:'合成浏览器航次'+i,startedAt:'2026-10-0'+(i+1)+'T00:00:00Z',finishedAt:'2026-10-0'+(i+1)+'T00:10:00Z',aircraftModel:'合成机型',providerVersion:'synthetic',sourceRef:'仅软件验证',crs:'EPSG:4326合成',captureConditions:{nature:'合成采集条件，不是农业变化'},files:[{externalId:'original',name:'合成原片'+i+'.png',version:'1',kind:'original',checksum:sum},{externalId:'ortho',name:'合成正射'+i+'.png',version:'1',kind:'orthophoto',checksum:sum,parents:['original'],processingSource:'合成成果，非现场配准'}]}),pool),file=(await pool.query("SELECT id FROM flight_files WHERE flight_id=$1 AND kind='orthophoto'",[flight.id])).rows[0];files.push(file.id);
   await transaction(c=>prepareMedia(c,f.actor,{objectId:f.objectId,assetId,requestKey:assetId,submissionId:flight.id,checksum:sum,byteLength:image.length,name:'合成正射'+i+'.png',mime:'image/png',source:'非生产测试图'}),pool);await transaction(c=>uploadMedia(c,f.actor,assetId,image,store),pool);await transaction(c=>linkFlightAsset(c,f.actor,{fileId:file.id,assetId}),pool);await transaction(c=>saveCoverage(c,f.actor,{flightId:flight.id,status:'verified',sourceCrs:4326,geometry,sourceRef:'合成覆盖'+i,requestKey:randomUUID()}),pool);const raster=await transaction(c=>queueRaster(c,f.actor,{fileId:file.id,sourceCrs:4326,bounds:[114,30,114.01,30.01],sourceRef:'合成时期'+i,confirm:true,requestKey:randomUUID()}),pool);await runRaster(pool,raster.id,undefined,store);rasters.push(raster.id);
  }
  await withApp(pool,async app=>{const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1280,height:900},locale:'zh-CN'}),page=await context.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));try{await context.addCookies([{name:'agri_session',value:await app.authenticate(f.actor),url:app.origin}]);await page.goto(app.origin+'/map');await page.getByLabel('前一个时期').selectOption(rasters[0]);await page.getByLabel('后一个时期').selectOption(rasters[1]);for(let i=0;i<2;i++){const img=page.getByRole('img',{name:'合成时期'+i,exact:true});await img.waitFor();await page.waitForFunction(label=>{const img=[...document.images].find(i=>i.alt===label);return !!img?.complete&&img.naturalWidth>0;},'合成时期'+i);}await page.getByLabel('航次覆盖',{exact:true}).uncheck();assert.equal(await page.locator('svg path[stroke="#3173a6"]').count(),0);await page.getByLabel('航次覆盖',{exact:true}).check();assert.equal(await page.locator('svg path[stroke="#3173a6"]').count(),2);
   await page.goto(app.origin+'/imagery');const flightCard=page.locator('section.rule-card').filter({has:page.getByRole('heading',{name:/合成浏览器航次0/})});await flightCard.getByText('在具体影像上标注疑点',{exact:true}).click();const annotation=flightCard.locator('form').filter({has:page.getByRole('button',{name:'登记定位疑点'})});await annotation.locator('select').selectOption(files[0]);const image=annotation.getByRole('img',{name:'合成正射0.png'});await image.waitFor();await image.scrollIntoViewIfNeeded();await image.click({position:{x:120,y:100}});await annotation.getByLabel('已选择疑点位置').waitFor();await annotation.getByLabel('疑点和限制').fill('合成原片点击定位，不推地理坐标');await annotation.getByLabel('定位/资料依据').fill('合成软件证据');await annotation.getByRole('button',{name:'登记定位疑点'}).click();await annotation.getByText('疑点已登记；原件与历史注记保留。').waitFor();assert.equal((await pool.query('SELECT location FROM flight_annotations')).rows[0].location.type,'image');
   await page.getByText('大原件分块上传与断点续传',{exact:true}).click();const upload=page.locator('form').filter({has:page.getByRole('button',{name:'上传或继续已有分块'})}),bytes=Buffer.alloc(21*1024*1024,32);bytes.write('%PDF-1.7');await upload.getByLabel('对象ID',{exact:true}).fill(f.objectId);await upload.getByLabel('原文件',{exact:true}).setInputFiles({name:'合成断块原件.pdf',mimeType:'application/pdf',buffer:bytes});await upload.getByLabel('原件来源及归档用途').fill('仅合成浏览器断点验证');await upload.getByLabel('来源SHA-256（有则填写）').fill(checksum(bytes));let broken=false;await context.route('**/api/v1/media/uploads/*/parts/*',async route=>{if(route.request().url().endsWith('/parts/1')&&!broken){broken=true;await route.abort();}else await route.continue();});await upload.getByRole('button',{name:'上传或继续已有分块'}).click();await page.waitForFunction(()=>[...document.querySelectorAll('[role=alert]')].some(e=>!!e.textContent?.trim()),undefined,{timeout:10000});assert.equal((await pool.query('SELECT count(*) FROM media_upload_parts')).rows[0].count,'1',await page.getByRole('alert').allTextContents().then(x=>x.join(' | ')));const session=(await pool.query('SELECT id,asset_id FROM media_upload_sessions')).rows[0];await context.unroute('**/api/v1/media/uploads/*/parts/*');await page.reload();await page.getByText('大原件分块上传与断点续传',{exact:true}).click();await upload.getByLabel('对象ID',{exact:true}).fill(f.objectId);await upload.getByLabel('原文件',{exact:true}).setInputFiles({name:'合成断块原件.pdf',mimeType:'application/pdf',buffer:bytes});await upload.getByLabel('原件来源及归档用途').fill('仅合成浏览器断点验证');await upload.getByLabel('恢复会话ID（可空）').fill(session.id);await upload.getByRole('button',{name:'上传或继续已有分块'}).click();await page.getByText('全部分块已确认，后台流式核验整体SHA；尚未等同原件入库完成。',{exact:true}).waitFor();assert.equal((await pool.query('SELECT count(*) FROM media_upload_sessions')).rows[0].count,'1');assert.equal((await pool.query('SELECT count(*) FROM media_upload_parts')).rows[0].count,'5');for(let i=0;i<10;i++)app.worker('workers/media.ts');await page.getByRole('button',{name:'刷新核验与备份状态'}).click();await page.getByText(/已存分块5；原件完整保存/).waitFor();const response=await context.request.get(app.origin+'/api/v1/media/'+session.asset_id,{headers:{Range:'bytes=0-7'}});assert.equal(response.status(),206);assert.equal((await response.body()).toString(),'%PDF-1.7');assert.deepEqual(errors,[]);await mkdir('.local/一期浏览器验收',{recursive:true});await writeFile('.local/一期浏览器验收/成果与大原件.json',JSON.stringify({checkedAt:new Date().toISOString(),environment:'agri_test合成原片与21MiB文件',checks:{twoPeriodPrivatePreviews:true,coverageLayer:true,imageClickAnnotation:true,partialResumeAfterReload:true,oneSessionFiveParts:true,workerWholeChecksum:true,privateRange:true,noScriptErrors:true},actualFlight:false},null,2));
  }finally{await browser.close();}},{mediaRoot:dir});
 }finally{await rm(dir,{recursive:true,force:true});}
}));
