import {artifactPath} from '../support/artifacts';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {chromium} from 'playwright';import {withDb} from '../support/db';import {withApp} from '../support/app';import {phase4Fixture} from '../support/phase4';
test('B46 真实费用与补贴页面独立审核、多选原费用、未知值和手机布局',{timeout:120000},()=>withDb(async pool=>{
 const f=await phase4Fixture(pool);await withApp(pool,async app=>{const browser=await chromium.launch(),context=await browser.newContext({timezoneId:'UTC'}),reviewContext=await browser.newContext({timezoneId:'UTC'}),page=await context.newPage(),review=await reviewContext.newPage();try{
 await context.addCookies([{name:'agri_session',value:await app.authenticate(f.actor),url:app.origin}]);await reviewContext.addCookies([{name:'agri_session',value:await app.authenticate(f.reviewer),url:app.origin}]);await page.goto(app.origin+'/business');await page.getByText('登记费用或更正',{exact:true}).click();const form=page.locator('form').filter({has:page.getByLabel('费用凭证号',{exact:true})});
 for(const [label,value] of [['计费数量（未知留空）','2'],['计费单位（与原单一致）','kg'],['单价元（未知留空）','10'],['金额元（未知留空）','20'],['付款主体','合成农场'],['收款主体','合成供方'],['费用凭证号','TEST-V1'],['用途和原始凭据依据','隔离浏览器合成单据']])await form.getByLabel(label,{exact:true}).fill(value);
 await form.getByLabel('费用类别').selectOption('material');await form.getByLabel('关联业务类型').selectOption('manual');await form.getByLabel('费用实际发生时间').fill('2026-10-03T00:00');await form.getByRole('button',{name:'保存',exact:true}).click();await form.getByText('已保存',{exact:true}).waitFor();const expense=(await pool.query('SELECT id FROM business_expenses')).rows[0];
 await review.goto(app.origin+'/business');await review.getByText('独立核实费用',{exact:true}).click();const check=review.locator('form').filter({has:review.getByLabel('待核实费用')});await check.getByLabel('待核实费用').selectOption(expense.id);await check.getByLabel('费用审核动作').selectOption('approve');await check.getByLabel('费用核实依据').fill('合成独立核实');await check.getByRole('button',{name:'保存',exact:true}).click();await check.getByText('已保存',{exact:true}).waitFor();
 await page.reload();await page.getByText('登记补贴申请台账',{exact:true}).click();const claim=page.locator('form').filter({has:page.getByLabel('补贴分类')});await claim.getByLabel('补贴分类').selectOption('purchase');for(const [label,value] of [['具体政策、地区和资料来源','合成地区政策测试'],['政策版本','test-v1'],['受益主体','合成农场'],['申请金额元','10'],['申请范围与凭证依据','仅验证内部台账']])await claim.getByLabel(label,{exact:true}).fill(value);await claim.getByLabel('申请期间开始').fill('2026-10-01T00:00');await claim.getByLabel('申请期间结束（不含）').fill('2026-11-01T00:00');await claim.getByLabel('关联已核费用').selectOption([expense.id]);await claim.getByRole('button',{name:'保存',exact:true}).click();await claim.getByText('已保存',{exact:true}).waitFor();
 assert.equal((await pool.query('SELECT count(*) FROM subsidy_expenses WHERE active')).rows[0].count,'1');assert.equal((await pool.query('SELECT state FROM subsidy_claims')).rows[0].state,'draft');
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.app-sidebar')!.getBoundingClientRect().right<=1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:artifactPath('验收/4b/费用补贴手机合成实测.png'),fullPage:true});
 await page.goto(app.origin+'/machinery');await page.getByRole('heading',{name:'农机服务',exact:true}).waitFor();await page.getByText('登记五项接入答复',{exact:true}).click();const contract=page.locator('form').filter({has:page.getByLabel('平台或服务方')});await contract.getByLabel('平台或服务方').fill('合成平台');await contract.getByLabel('资料许可有效至').fill('2027-01-01T00:00');await contract.getByLabel('书面答复来源').fill('尚未齐全的合成资料');await contract.getByRole('button',{name:'保存',exact:true}).click();await contract.getByText('已保存',{exact:true}).waitFor();assert.equal((await pool.query('SELECT exit_ref FROM machinery_contracts')).rows[0].exit_ref,null);
 await contract.getByLabel('平台或服务方').fill('合成完整平台');for(const label of ['账户授权说明（勿填密码）','字段与单位资料','接口或导出说明','历史迁移说明','退出与数据取回说明'])await contract.getByLabel(label).fill('已核合成书面资料');await contract.getByLabel('资料许可有效至').fill('2027-01-01T00:00');await contract.getByLabel('书面答复来源').fill('仅软件工程测试');await contract.getByRole('button',{name:'保存',exact:true}).click();await contract.getByText('已保存',{exact:true}).waitFor();const fullContract=(await pool.query("SELECT id FROM machinery_contracts WHERE provider='合成完整平台'")).rows[0];
 await review.goto(app.origin+'/machinery');await review.getByText('登记五项接入答复',{exact:true}).click();const contractCheck=review.locator('form').filter({has:review.getByLabel('接入资料版本')});await contractCheck.getByLabel('接入资料版本').selectOption(fullContract.id);await contractCheck.getByLabel('资料审核动作').selectOption('approve');await contractCheck.getByLabel('资料审核依据').fill('合成独立核实');await contractCheck.getByRole('button',{name:'保存',exact:true}).click();await contractCheck.getByText('已保存',{exact:true}).waitFor();
 await page.getByText('绑定机具与终端',{exact:true}).click();const bindingForm=page.locator('form').filter({has:page.getByLabel('已核机具')});await bindingForm.getByLabel('已核机具').selectOption(f.machineId);await bindingForm.getByLabel('已核定位终端').selectOption(f.terminalId);await bindingForm.getByLabel('安装生效时间').fill('2026-10-01T00:00');await bindingForm.getByLabel('绑定有效至').fill('2027-01-01T00:00');await bindingForm.getByLabel('安装对应依据').fill('合成安装记录');await bindingForm.getByRole('button',{name:'保存',exact:true}).click();await bindingForm.getByText('已保存',{exact:true}).waitFor();const binding=(await pool.query('SELECT id FROM machinery_bindings')).rows[0];
 await page.getByText('建立服务单与人工派单',{exact:true}).click();const orderForm=page.locator('form').filter({has:page.getByLabel('服务单名称')});await orderForm.getByLabel('服务接入资料').selectOption(fullContract.id);await orderForm.getByLabel('机具终端绑定').selectOption(binding.id);await orderForm.getByLabel('服务单名称').fill('合成手机服务单');await orderForm.getByLabel('作业种类').fill('仅工程作业');await orderForm.getByLabel('已核作业边界GeoJSON').fill(JSON.stringify({type:'Polygon',coordinates:[[[114,30],[114.001,30],[114.001,30.001],[114,30.001],[114,30]]]}));await orderForm.getByLabel('作业窗口开始').fill('2026-10-03T00:00');await orderForm.getByLabel('作业窗口结束').fill('2026-10-04T00:00');await orderForm.getByLabel('计划计费数量').fill('1');await orderForm.getByLabel('计划计费单位').selectOption('job');await orderForm.getByLabel('计划和边界依据').fill('合成计划');await orderForm.getByRole('button',{name:'保存',exact:true}).click();await orderForm.getByText('已保存',{exact:true}).waitFor();const order=(await pool.query('SELECT id FROM machinery_orders')).rows[0];
 const dispatch=page.locator('form').filter({has:page.getByLabel('待派服务单')});await dispatch.getByLabel('待派服务单').selectOption(order.id);await dispatch.getByLabel('本次派单依据').fill('合成人工派单，不是控制设备');await dispatch.getByRole('button',{name:'确认人工派单',exact:true}).click();await dispatch.getByText('已保存',{exact:true}).waitFor();
 await page.getByText('登记实际作业证据',{exact:true}).click();const evidence=page.locator('form').filter({has:page.getByLabel('实际服务单')});for(const kind of ['track','work_order','arrival','spotcheck']){await evidence.getByLabel('实际服务单').selectOption(order.id);await evidence.getByLabel('证据类别').selectOption(kind);await evidence.getByLabel('证据实际发生时间').fill('2026-10-03T00:30');await evidence.getByLabel('原单、实际数量、确认人和依据').fill('合成证据，实际数量1次');await evidence.getByLabel('标准轨迹行（非轨迹证据填空数组）').fill(JSON.stringify(kind==='track'?[{at:'2026-10-03T00:10:00Z',lng:114.0001,lat:30.0001},{at:'2026-10-03T00:20:00Z',lng:114.0002,lat:30.0002}]:[]));await evidence.getByLabel('已核对该类证据有效').check();await evidence.getByRole('button',{name:'保存',exact:true}).click();await evidence.getByText('已保存',{exact:true}).waitFor();}
 await review.reload();await review.getByText('独立业务验收',{exact:true}).click();const acceptance=review.locator('form').filter({has:review.getByLabel('待验收服务单')});await acceptance.getByLabel('待验收服务单').selectOption(order.id);await acceptance.getByLabel('服务验收动作').selectOption('accept');await acceptance.getByLabel('业务验收依据').fill('合成独立验收');await acceptance.getByRole('button',{name:'保存',exact:true}).click();await acceptance.getByText('已保存',{exact:true}).waitFor();await review.getByText('当前证据有效',{exact:true}).waitFor();
 assert.equal((await pool.query('SELECT count(*) n FROM machinery_evidence')).rows[0].n,'4');assert.equal((await pool.query('SELECT action FROM machinery_reviews')).rows[0].action,'accept');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:artifactPath('验收/4b/农机手机合成实测.png'),fullPage:true});
 assert.equal((await context.request.post(app.origin+'/api/v1/business/constructor',{headers:{origin:app.origin},data:{}})).status(),404);
 }finally{await browser.close();}});
}));
