import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdir} from 'node:fs/promises';import {chromium} from 'playwright';
import {withDb} from '../support/db';import {withApp} from '../support/app';import {actorFixture,objectFixture,permit} from '../support/fixtures';import {transaction} from '../../src/db/pool';import {createLot,createLocation} from '../../src/modules/inventory/catalog';
test('A46 真实页面循环批次称量、错误保留、能源录入与撤权',{timeout:120000},()=>withDb(async pool=>{
 const a=await actorFixture(pool,'technician'),o=await objectFixture(pool,a.id);await permit(pool,a.id,o,['read','record','configure','export']);
 const source=randomUUID(),device=randomUUID();await pool.query("INSERT INTO data_sources(id,object_id,code,name,provider,created_by) VALUES($1::uuid,$2,$1::text,'合成来源','synthetic',$3)",[source,o,a.id]);await pool.query("INSERT INTO devices(id,object_id,source_id,external_id,name,kind,source,created_by) VALUES($1,$2,$3,'ENERGY','合成能源设备','physical','仅测试',$4)",[device,o,source,a.id]);
 const lot=await transaction(c=>createLot(c,a,{objectId:o,code:randomUUID(),product:'合成堆肥',kind:'input',unit:'kg',basis:'wet',source:'仅测试',requestKey:randomUUID()}),pool),location=await transaction(c=>createLocation(c,a,{objectId:o,code:'TEST-W',name:'合成堆肥仓',requestKey:randomUUID()}),pool);
 await withApp(pool,async app=>{const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();try{
 await context.addCookies([{name:'agri_session',value:await app.authenticate(a),url:app.origin}]);await page.goto(app.origin+'/circular');await page.getByText('登记循环物料来源',{exact:true}).click();
 const origin=page.locator('form').filter({has:page.getByLabel('已有物料批次')});await origin.getByLabel('已有物料批次').selectOption(lot.id);await origin.getByLabel('物料类别').selectOption('compost');await origin.getByLabel('来源批、原始资料与用途依据').fill('合成来源批');await origin.getByRole('button',{name:'保存',exact:true}).click();await origin.getByText('已保存',{exact:true}).waitFor();
 await page.getByText('接收称量并入库',{exact:true}).click();const weighing=page.locator('form').filter({has:page.getByLabel('毛重kg',{exact:true})});await weighing.getByLabel('接收批次').selectOption(lot.id);await weighing.getByLabel('接收仓位').selectOption(location.id);for(const [label,value] of [['毛重kg','12'],['皮重kg','2'],['净重kg','9'],['称量凭证号','SYNTH-W1'],['称量仪器、来源和原单依据','合成工程秤单']])await weighing.getByLabel(label,{exact:true}).fill(value);await weighing.getByLabel('称量口径').selectOption('wet');await weighing.getByLabel('实际接收时间').fill('2026-10-03T10:00');
 await weighing.getByRole('button',{name:'保存',exact:true}).click();await weighing.getByRole('alert').filter({hasText:'净重须等于'}).waitFor();assert.equal(await weighing.getByLabel('毛重kg',{exact:true}).inputValue(),'12');await weighing.getByLabel('净重kg',{exact:true}).fill('10');await weighing.getByRole('button',{name:'保存',exact:true}).click();await weighing.getByText('已保存',{exact:true}).waitFor();assert.equal((await pool.query('SELECT sum(delta)::text q FROM stock_entries')).rows[0].q,'10.000000');
 await page.goto(app.origin+'/energy');await page.getByText('登记能源计量档案',{exact:true}).click();const meter=page.locator('form').filter({has:page.getByLabel('档案名称')});await meter.getByLabel('物理设备').selectOption(device);await meter.getByLabel('档案名称').fill('合成用电表');await meter.getByLabel('能源用途').selectOption('load');await meter.getByLabel('已核连续观测最大间隔秒').fill('3600');await meter.getByLabel('型号、计量单位和倍率换算依据').fill('合成表，kWh倍率1');await meter.getByRole('button',{name:'保存',exact:true}).click();await meter.getByText('已保存',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.app-sidebar')!.getBoundingClientRect().right<=1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await mkdir('docs/acceptance/4a',{recursive:true});await page.screenshot({path:'docs/acceptance/4a/能源手机合成实测.png',fullPage:true});
 assert.equal((await context.request.get(app.origin+'/api/v1/energy/export?objectId='+o)).status(),200);await pool.query('UPDATE grants SET revoked_at=now() WHERE user_id=$1',[a.id]);assert.equal((await context.request.get(app.origin+'/api/v1/energy/overview?objectId='+o)).status(),403);
 }finally{await browser.close();}});
}));
