import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdir} from 'node:fs/promises';import {chromium} from 'playwright';import {withDb} from '../support/db';import {withApp} from '../support/app';import {phase4Fixture} from '../support/phase4';
test('B46 真实费用与补贴页面独立审核、多选原费用、未知值和手机布局',{timeout:120000},()=>withDb(async pool=>{
 const f=await phase4Fixture(pool);await withApp(pool,async app=>{const browser=await chromium.launch(),context=await browser.newContext({timezoneId:'UTC'}),reviewContext=await browser.newContext({timezoneId:'UTC'}),page=await context.newPage(),review=await reviewContext.newPage();try{
 await context.addCookies([{name:'agri_session',value:await app.authenticate(f.actor),url:app.origin}]);await reviewContext.addCookies([{name:'agri_session',value:await app.authenticate(f.reviewer),url:app.origin}]);await page.goto(app.origin+'/business');await page.getByText('登记费用或更正',{exact:true}).click();const form=page.locator('form').filter({has:page.getByLabel('费用凭证号',{exact:true})});
 for(const [label,value] of [['计费数量（未知留空）','2'],['计费单位（与原单一致）','kg'],['单价元（未知留空）','10'],['金额元（未知留空）','20'],['付款主体','合成农场'],['收款主体','合成供方'],['费用凭证号','TEST-V1'],['用途和原始凭据依据','隔离浏览器合成单据']])await form.getByLabel(label,{exact:true}).fill(value);
 await form.getByLabel('费用类别').selectOption('material');await form.getByLabel('关联业务类型').selectOption('manual');await form.getByLabel('费用实际发生时间').fill('2026-10-03T00:00');await form.getByRole('button',{name:'保存',exact:true}).click();await form.getByText('已保存',{exact:true}).waitFor();const expense=(await pool.query('SELECT id FROM business_expenses')).rows[0];
 await review.goto(app.origin+'/business');await review.getByText('独立核实费用',{exact:true}).click();const check=review.locator('form').filter({has:review.getByLabel('待核实费用')});await check.getByLabel('待核实费用').selectOption(expense.id);await check.getByLabel('费用审核动作').selectOption('approve');await check.getByLabel('费用核实依据').fill('合成独立核实');await check.getByRole('button',{name:'保存',exact:true}).click();await check.getByText('已保存',{exact:true}).waitFor();
 await page.reload();await page.getByText('登记补贴申请台账',{exact:true}).click();const claim=page.locator('form').filter({has:page.getByLabel('补贴分类')});await claim.getByLabel('补贴分类').selectOption('purchase');for(const [label,value] of [['具体政策、地区和资料来源','合成地区政策测试'],['政策版本','test-v1'],['受益主体','合成农场'],['申请金额元','10'],['申请范围与凭证依据','仅验证内部台账']])await claim.getByLabel(label,{exact:true}).fill(value);await claim.getByLabel('申请期间开始').fill('2026-10-01T00:00');await claim.getByLabel('申请期间结束（不含）').fill('2026-11-01T00:00');await claim.getByLabel('关联已核费用').selectOption([expense.id]);await claim.getByRole('button',{name:'保存',exact:true}).click();await claim.getByText('已保存',{exact:true}).waitFor();
 assert.equal((await pool.query('SELECT count(*) FROM subsidy_expenses WHERE active')).rows[0].count,'1');assert.equal((await pool.query('SELECT state FROM subsidy_claims')).rows[0].state,'draft');
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.app-sidebar')!.getBoundingClientRect().right<=1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await mkdir('docs/acceptance/4b',{recursive:true});await page.screenshot({path:'docs/acceptance/4b/费用补贴手机合成实测.png',fullPage:true});
 await page.goto(app.origin+'/machinery');await page.getByRole('heading',{name:'农机服务',exact:true}).waitFor();await page.getByText('登记五项接入答复',{exact:true}).click();const contract=page.locator('form').filter({has:page.getByLabel('平台或服务方')});await contract.getByLabel('平台或服务方').fill('合成平台');await contract.getByLabel('资料许可有效至').fill('2027-01-01T00:00');await contract.getByLabel('书面答复来源').fill('尚未齐全的合成资料');await contract.getByRole('button',{name:'保存',exact:true}).click();await contract.getByText('已保存',{exact:true}).waitFor();assert.equal((await pool.query('SELECT exit_ref FROM machinery_contracts')).rows[0].exit_ref,null);
 assert.equal((await context.request.post(app.origin+'/api/v1/business/constructor',{headers:{origin:app.origin},data:{}})).status(),404);
 }finally{await browser.close();}});
}));
