import {randomUUID} from 'node:crypto';import type {Pool,PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text} from '../../platform/validation';
import {transaction} from '../../db/pool';import {access,request,period,type Body} from '../phase4/common';import {payloadHash,lockKey} from '../field/common';import {enqueue,type JobLease} from '../jobs/repository';import {withLease,assertLease} from '../jobs/execution';import {cents,yuan} from '../finance/money';import {assertMachineAccepted} from '../machinery/evidence';
import {financeAccess,financialRole} from '../finance/access';
export const managementDefinition='management-records-v1';
export async function queueManagementReport(c:PoolClient,a:Actor,b:Body){await financeAccess(c,a,b.objectId,'record');return request(c,a,b,'management.report',b.objectId as string,async()=>{
 await lockKey(c,a,'management-quota','pending');if(Number((await c.query("SELECT count(*) n FROM management_reports r JOIN jobs j ON j.id=r.job_id WHERE r.created_by=$1 AND r.state IN('queued','running') AND j.state IN('queued','running','retry_wait')",[a.id])).rows[0].n)>=5)throw new AppError(429,'MANAGEMENT_QUEUE_FULL','待处理管理报告已达5份，请等待完成');
 const {start,end}=period(b.fromAt,b.toAt),user=(await c.query('SELECT auth_version FROM users WHERE id=$1',[a.id])).rows[0],id=randomUUID(),job=await enqueue(c,{kind:'management.calculate',businessKey:'management:'+id,payload:{reportId:id},dueAt:new Date().toISOString(),priority:0});
 return(await c.query('INSERT INTO management_reports(id,object_id,from_at,to_at,source_ref,definition_version,job_id,auth_version,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,state',[id,b.objectId,start,end,text(b.sourceRef,'统计范围与用途依据',4000),managementDefinition,job,user.auth_version,a.id])).rows[0];
 });}
async function reportActor(c:PoolClient,r:any){const u=(await c.query('SELECT id,role,enabled,auth_version FROM users WHERE id=$1',[r.created_by])).rows[0];if(!u?.enabled||u.auth_version!==r.auth_version)throw new AppError(403,'MANAGEMENT_AUTH_CHANGED','生成主体已停用或授权身份版本变化');const a:Actor={id:u.id,role:u.role,enabled:true,mfaVerified:true};financialRole(a);await access(c,a,r.object_id);return a;}
export async function calculateManagementReport(c:PoolClient,r:any){const o=r.object_id,from=r.from_at,to=r.to_at,asOf=(await c.query('SELECT clock_timestamp() AS at')).rows[0].at,inputs:Record<string,any>={objectId:o,fromAt:from,toAt:to,asOf,definitionVersion:managementDefinition},deadline=Date.now()+10000;
 async function rows(name:string,sql:string,args:unknown[]=[o,from,to]){const data=(await c.query(sql+' LIMIT 5001',args)).rows;if(data.length>5000||Date.now()>deadline)throw new AppError(413,'MANAGEMENT_INPUT_LIMIT','数据超出单次5000条或10秒计算预算，请缩短时段或分对象核对');inputs[name]=data;}
 await rows('devices','SELECT id,kind,verified,created_at FROM devices WHERE object_id=$1 ORDER BY id',[o]);
 await rows('observations',`SELECT o.id,o.point_id,o.metric,o.unit,o.sampled_at,o.quality,h.conflicted FROM observations o JOIN observation_heads h ON h.canonical_id=o.id WHERE o.object_id=$1 AND o.sampled_at>=$2 AND o.sampled_at<$3 ORDER BY o.id`);
 await rows('records',`SELECT r.id,r.kind,r.occurred_at,r.status,r.version FROM farm_records r WHERE object_id=$1 AND occurred_at>=$2 AND occurred_at<$3 AND NOT EXISTS(SELECT 1 FROM farm_records n WHERE n.supersedes_id=r.id) ORDER BY id`);
 await rows('tasks',`SELECT id,state,due_at,created_at,version FROM field_tasks WHERE object_id=$1 ORDER BY id`,[o]);
 await rows('qualityTests','SELECT id,result,tested_at FROM quality_tests WHERE object_id=$1 AND tested_at>=$2 AND tested_at<$3 ORDER BY id');
 await rows('qualityCases','SELECT id,state,target_quantity,created_at FROM quality_cases WHERE object_id=$1 ORDER BY id',[o]);
 await rows('expenses',`SELECT e.id,e.category,e.amount_cny,e.occurred_at,e.version FROM business_expenses e WHERE object_id=$1 AND occurred_at>=$2 AND occurred_at<$3 AND NOT EXISTS(SELECT 1 FROM business_expenses n WHERE n.supersedes_id=e.id) ORDER BY id`);
 await rows('payments','SELECT id,direction,amount_cny,occurred_at,expense_id FROM expense_payments WHERE object_id=$1 AND occurred_at>=$2 AND occurred_at<$3 ORDER BY id');
 await rows('orders','SELECT id,state,starts_at,ends_at,quantity,unit FROM machinery_orders WHERE object_id=$1 AND starts_at>=$2 AND starts_at<$3 ORDER BY id');
 await rows('alerts','SELECT id,state,severity,kind,opened_at,closed_at FROM alerts WHERE object_id=$1 ORDER BY id',[o]);
 const candidateIds=(await c.query("SELECT DISTINCT ON(order_id) order_id,action,id FROM machinery_reviews WHERE order_id=ANY($1::uuid[]) ORDER BY order_id,seq DESC",[inputs.orders.map((x:any)=>x.id)])).rows.filter(x=>x.action==='accept');
 if(candidateIds.length>500)throw new AppError(413,'MANAGEMENT_INPUT_LIMIT','验收关系超过500项，请缩短服务统计时段');inputs.serviceEligibility=[];
 for(const item of candidateIds){if(Date.now()>deadline)throw new AppError(413,'MANAGEMENT_INPUT_LIMIT','验收核对超过计算预算，请缩短时段');let accepted=false,reason='';try{await assertMachineAccepted(c,item.order_id);accepted=true;}catch(e){if(!(e instanceof AppError))throw e;reason=e.code;}inputs.serviceEligibility.push({orderId:item.order_id,reviewId:item.id,accepted,reason});}
 const observations=inputs.observations,valid=observations.filter((x:any)=>x.quality==='valid'&&!x.conflicted).length,known=inputs.expenses.filter((x:any)=>x.amount_cny!==null),paid=inputs.payments.reduce((n:bigint,p:any)=>n+(p.direction==='pay'?1n:-1n)*cents(p.amount_cny),0n),open=inputs.alerts.filter((x:any)=>x.state!=='closed');
 const result={
 devices:{registeredNow:inputs.devices.length,verifiedNow:inputs.devices.filter((x:any)=>x.verified).length,canonicalObservations:observations.length,validObservations:valid,validObservationRate:observations.length?valid/observations.length:null},
 operations:{recordedInWindow:inputs.records.length,reviewedRecords:inputs.records.filter((x:any)=>x.status==='reviewed').length},
 quality:{reportsInWindow:inputs.qualityTests.length,failedReportRecords:inputs.qualityTests.filter((x:any)=>x.result==='fail').length,openCasesNow:inputs.qualityCases.filter((x:any)=>x.state==='open').length},
 scheduling:{tasksNow:inputs.tasks.length,pendingNow:inputs.tasks.filter((x:any)=>!['reviewed','cancelled'].includes(x.state)).length,overdueNow:inputs.tasks.filter((x:any)=>!['reviewed','cancelled'].includes(x.state)&&x.due_at&&x.due_at<asOf).length,unknownDueDates:inputs.tasks.filter((x:any)=>!x.due_at).length},
 economics:{expenseRecords:inputs.expenses.length,unknownAmountRecords:inputs.expenses.length-known.length,knownRegisteredCny:known.length?yuan(known.reduce((n:bigint,x:any)=>n+cents(x.amount_cny),0n)):null,recordedNetPaidCny:inputs.payments.length?yuan(paid):null},
 service:{plannedOrdersInWindow:inputs.orders.length,currentAccepted:inputs.serviceEligibility.filter((x:any)=>x.accepted).length,cancelledOrders:inputs.orders.filter((x:any)=>x.state==='cancelled').length},
 risk:{openAlertRecordsNow:open.length,severeOpenRecordsNow:open.filter((x:any)=>x.severity==='severe').length,openQualityCaseRecordsNow:inputs.qualityCases.filter((x:any)=>x.state==='open').length},
 limits:['范围仅为当前对象的已登记数据，不包含未授权对象','窗口采用开始包含、结束不包含；Now字段为生成时点的当前记录状态','有效观测率的分母是收到的规范观测数，不是应采样数，不代表在线率或现场完整率','失败检测按窗口内报告事实计数，更正与复核须回原质量模块查看','零告警记录不等于现场无风险；缺测和未接设备仍须核查','登记费用与实际收付分开；未知金额未算作0，不构成利润、节能或补贴资格结论']};
 const snapshot=JSON.parse(JSON.stringify(inputs));if(Buffer.byteLength(JSON.stringify({snapshot,result}))>8*1024*1024)throw new AppError(413,'MANAGEMENT_INPUT_LIMIT','报告快照超过8MiB，请缩小范围');return {inputs:snapshot,result,inputHash:payloadHash(snapshot)};
}
export async function runManagement(pool:Pool,id:string,job?:JobLease){return withLease(pool,'management:'+id,job,async lease=>{try{
 const prepared=await transaction(async c=>{await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');await assertLease(c,lease);const r=(await c.query('SELECT * FROM management_reports WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)throw new AppError(404,'MANAGEMENT_REPORT','报告不存在');if(r.state==='complete')return null;if(r.definition_version!==managementDefinition)throw new AppError(409,'MANAGEMENT_DEFINITION','计算定义版本变化，请新建报告');await reportActor(c,r);await c.query("UPDATE management_reports SET state='running',execution_token=$2,error_code=NULL WHERE id=$1",[id,lease.leaseToken]);return {row:r,...await calculateManagementReport(c,r)};},pool);
 if(!prepared)return;await transaction(async c=>{await assertLease(c,lease);await reportActor(c,prepared.row);const changed=await c.query("UPDATE management_reports SET state='complete',inputs=$3,result=$4,input_hash=$5,finished_at=clock_timestamp(),execution_token=NULL WHERE id=$1 AND execution_token=$2 RETURNING id",[id,lease.leaseToken,JSON.stringify(prepared.inputs),JSON.stringify(prepared.result),prepared.inputHash]);if(!changed.rowCount)throw new AppError(409,'LEASE_LOST','报告已由其他租约接管');},pool);
 }catch(e){await transaction(async c=>{await c.query("UPDATE management_reports SET state='failed',error_code=$3,execution_token=NULL WHERE id=$1 AND state<>'complete' AND EXISTS(SELECT 1 FROM jobs j WHERE j.id=job_id AND j.lease_token=$2 AND j.state='running')",[id,lease.leaseToken,e instanceof AppError?e.code:'MANAGEMENT_FAILED']);},pool);throw e;}});}
export async function recoverManagement(pool:Pool){await transaction(async c=>{await c.query("UPDATE management_reports r SET state=CASE WHEN j.state='failed' THEN 'failed' ELSE 'queued' END,execution_token=NULL,error_code='EXECUTION_INTERRUPTED' FROM jobs j WHERE j.id=r.job_id AND r.state='running' AND j.state IN('retry_wait','failed')");},pool);}
