import type {PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {text,time,choice} from '../../platform/validation';
import {uuid} from '../identity/common';
import {existingObject,scope,visible,payloadHash,sameHash} from '../field/common';
export async function importFlight(c:PoolClient,a:Actor,b:Record<string,unknown>){
 const o=await existingObject(c,a,b);uuid(b.sourceId);const source=(await c.query('SELECT * FROM data_sources WHERE id=$1',[b.sourceId])).rows[0];if(source?.object_id!==o.id)throw new AppError(422,'FLIGHT_SOURCE','航次来源须属于同一对象');
 if(!Array.isArray(b.files)||!b.files.length||b.files.length>500)throw new AppError(400,'FLIGHT_FILES','每次航次清单包含1至500个文件');
 const files=b.files.map(v=>{const f=v as Record<string,unknown>,sum=text(f.checksum,'文件SHA-256',64);if(!/^[a-f0-9]{64}$/.test(sum))throw new AppError(400,'INVALID_CHECKSUM','航次文件需要SHA-256');return {externalId:text(f.externalId,'文件稳定ID',200),name:text(f.name,'文件名',180),kind:choice(f.kind,['original','orthophoto','thermal','multispectral','other'] as const,'成果类型'),version:text(f.version,'成果版本',100),checksum:sum,parents:Array.isArray(f.parents)?f.parents.map(x=>text(x,'父文件ID',200)):[],processingSource:f.processingSource?text(f.processingSource,'处理来源',1000):null,bands:f.bands??[],calibration:f.calibration??{}};});
 const keys=files.map(f=>f.externalId);if(new Set(keys).size!==keys.length||files.some(f=>f.parents.some(p=>!keys.includes(p)||p===f.externalId)))throw new AppError(400,'FLIGHT_LINEAGE','文件标识重复或父成果不在清单内');
 const visiting=new Set<string>(),done=new Set<string>();function walk(id:string){if(visiting.has(id))throw new AppError(400,'FLIGHT_LINEAGE','加工关系存在循环');if(done.has(id))return;visiting.add(id);for(const p of files.find(f=>f.externalId===id)!.parents)walk(p);visiting.delete(id);done.add(id);}for(const id of keys)walk(id);
 const input={objectId:o.id,sourceId:b.sourceId,externalId:text(b.externalId,'航次稳定ID',200),startedAt:time(b.startedAt),finishedAt:time(b.finishedAt),aircraftModel:text(b.aircraftModel,'飞行器型号',200),dockModel:b.dockModel?text(b.dockModel,'机场型号',200):null,providerVersion:text(b.providerVersion,'司空/厂家版本',200),sourceRef:text(b.sourceRef,'原始清单依据',2000),crs:text(b.crs,'平面坐标与垂直基准',200),captureConditions:b.captureConditions??{},payloads:b.payloads??[],files};
 if(input.startedAt>input.finishedAt)throw new AppError(400,'FLIGHT_PERIOD','航次结束时间早于开始');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['flight:'+b.sourceId+':'+input.externalId]);const hash=payloadHash(input),prior=(await c.query('SELECT * FROM flights WHERE source_id=$1 AND external_id=$2',[b.sourceId,input.externalId])).rows[0];if(prior){sameHash(prior.manifest_hash,hash);return prior;}
 const row=(await c.query('INSERT INTO flights(object_id,source_id,external_id,started_at,finished_at,aircraft_model,dock_model,provider_version,source_ref,crs,capture_conditions,payloads,manifest_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *',[o.id,b.sourceId,input.externalId,input.startedAt,input.finishedAt,input.aircraftModel,input.dockModel,input.providerVersion,input.sourceRef,input.crs,JSON.stringify(input.captureConditions),JSON.stringify(input.payloads),hash,a.id])).rows[0];for(const f of files)await c.query('INSERT INTO flight_files(flight_id,external_file_id,name,kind,version,checksum,parent_external_ids,processing_source,bands,calibration) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[row.id,f.externalId,f.name,f.kind,f.version,f.checksum,f.parents,f.processingSource,JSON.stringify(f.bands),JSON.stringify(f.calibration)]);return row;
}
export async function linkFlightAsset(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.fileId);uuid(b.assetId);const f=(await c.query('SELECT x.*,v.object_id FROM flight_files x JOIN flights v ON v.id=x.flight_id WHERE x.id=$1 FOR UPDATE OF x',[b.fileId])).rows[0];if(!f)throw new AppError(404,'FLIGHT_FILE_NOT_FOUND','航次文件不存在');await scope(c,a,f.object_id,'record');const m=(await c.query('SELECT * FROM media_assets WHERE id=$1',[b.assetId])).rows[0];if(m?.object_id!==f.object_id||m.ingest_state!=='complete'||m.checksum!==f.checksum)throw new AppError(422,'FLIGHT_FILE_INTEGRITY','文件对象或校验值不符、或仍未上传完整');if(f.asset_id&&f.asset_id!==m.id)throw new AppError(409,'FLIGHT_FILE_CONFLICT','已关联原件不能替换');await c.query('UPDATE flight_files SET asset_id=$2 WHERE id=$1',[f.id,m.id]);return {id:f.id,assetId:m.id};}
export async function annotateFlight(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.flightId);const f=(await c.query('SELECT object_id FROM flights WHERE id=$1',[b.flightId])).rows[0];if(!f)throw new AppError(404,'FLIGHT_NOT_FOUND','航次不存在');await scope(c,a,f.object_id,'record');return(await c.query('INSERT INTO flight_annotations(flight_id,note,created_by) VALUES($1,$2,$3) RETURNING *',[b.flightId,text(b.note,'影像疑点与限制',3000),a.id])).rows[0];}
export async function listFlights(c:PoolClient,a:Actor){const v=await visible(c,a,'flight'),items=(await c.query('SELECT * FROM flights WHERE object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR id=ANY($2)) ORDER BY started_at DESC LIMIT 100',[v.objects,v.resources])).rows,ids=items.map(f=>f.id),files=(await c.query('SELECT f.*,m.ingest_state,m.backup_state FROM flight_files f LEFT JOIN media_assets m ON m.id=f.asset_id WHERE f.flight_id=ANY($1::uuid[]) ORDER BY f.name',[ids])).rows;return {items:items.map(f=>({...f,complete:files.filter(x=>x.flight_id===f.id).every(x=>x.ingest_state==='complete'),backupComplete:files.filter(x=>x.flight_id===f.id).every(x=>x.backup_state==='verified'),limitations:['真实司空权益与机型兼容尚未联调','跨期拍摄条件未核对时不直接给出变化结论']})),files,annotations:(await c.query('SELECT * FROM flight_annotations WHERE flight_id=ANY($1::uuid[]) ORDER BY created_at',[ids])).rows};}
