import type {Pool,PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {randomUUID} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {createWriteStream} from 'node:fs';import {join} from 'node:path';import {tmpdir} from 'node:os';import {pipeline} from 'node:stream/promises';import sharp from 'sharp';
import {AppError} from '../../platform/error';import {text,integer,choice} from '../../platform/validation';import {uuid} from '../identity/common';
import {scope,payloadHash,sameHash,lockKey} from '../field/common';import {database,transaction} from '../../db/pool';import {enqueue,type JobLease} from '../jobs/repository';import {assertLease,withLease} from '../jobs/execution';
import {checksum,configuredStore,type PrivateStore} from '../media/storage';import {prepareMedia,uploadMedia} from '../media/service';import {normalizePolygon} from '../map/geometry';
export async function saveCoverage(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.flightId);const f=(await c.query('SELECT * FROM flights WHERE id=$1 FOR UPDATE',[b.flightId])).rows[0];if(!f)throw new AppError(404,'FLIGHT_NOT_FOUND','航次不存在');await scope(c,a,f.object_id,'record');const status=choice(b.status,['draft','verified'] as const,'覆盖状态');if(status==='verified')await scope(c,a,f.object_id,'review');const key=text(b.requestKey,'覆盖提交标识',120),source=text(b.sourceRef,'覆盖依据',2000);await lockKey(c,a,'coverage',key);const hash=payloadHash({flight:f.id,geometry:b.geometry,crs:b.sourceCrs,status,source}),prior=(await c.query('SELECT * FROM flight_coverages WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(prior){sameHash(prior.input_hash,hash);return prior;}const crs=integer(b.sourceCrs,'来源EPSG'),shape=await normalizePolygon(c,b.geometry,crs),version=Number((await c.query('SELECT COALESCE(max(version),0) AS v FROM flight_coverages WHERE flight_id=$1',[f.id])).rows[0].v)+1;return (await c.query('INSERT INTO flight_coverages(flight_id,object_id,version,geometry,source_crs,source_ref,status,created_by,request_key,input_hash) VALUES($1,$2,$3,$4::geometry,$5,$6,$7,$8,$9,$10) RETURNING id,version,status',[f.id,f.object_id,version,shape,crs,source,status,a.id,key,hash])).rows[0];}
export async function queueRaster(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.fileId);const f=(await c.query('SELECT x.*,v.object_id FROM flight_files x JOIN flights v ON v.id=x.flight_id WHERE x.id=$1 FOR SHARE OF x',[b.fileId])).rows[0];if(!f?.asset_id||f.kind!=='orthophoto')throw new AppError(422,'ORTHOPHOTO_REQUIRED','只叠加已入库的可视正射成果；原片或未校正影像请并列查看');await scope(c,a,f.object_id,'record');await scope(c,a,f.object_id,'review');const m=(await c.query("SELECT * FROM media_assets WHERE id=$1 AND ingest_state='complete'",[f.asset_id])).rows[0];if(!m?.mime.startsWith('image/'))throw new AppError(422,'RASTER_FORMAT','正射成果必须是已核可视图像');
 if(b.confirm!==true||b.sourceCrs!==4326||!Array.isArray(b.bounds)||b.bounds.length!==4||b.bounds.some(x=>typeof x!=='number'||!Number.isFinite(x))||b.bounds[0]>=b.bounds[2]||b.bounds[1]>=b.bounds[3]||Math.abs(b.bounds[0])>180||Math.abs(b.bounds[2])>180||Math.abs(b.bounds[1])>90||Math.abs(b.bounds[3])>90)throw new AppError(422,'RASTER_REGISTRATION','须确认北向、WGS84矩形正射坐标；其他投影/旋转成果先用原加工工具输出可视预览，不猜配准');
 const key=text(b.requestKey,'预览标识',120),source=text(b.sourceRef,'正射校正/配准依据',2000),hash=payloadHash({fileId:f.id,checksum:m.checksum,bounds:b.bounds,source});await lockKey(c,a,'raster',key);const old=(await c.query('SELECT * FROM flight_rasters WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(old){sameHash(old.input_hash,hash);return old;}const auth=(await c.query('SELECT auth_version FROM users WHERE id=$1',[a.id])).rows[0].auth_version,row=(await c.query('INSERT INTO flight_rasters(file_id,flight_id,object_id,source_asset_id,source_checksum,bounds,source_ref,created_by,auth_version,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[f.id,f.flight_id,f.object_id,m.id,m.checksum,JSON.stringify(b.bounds),source,a.id,auth,key,hash])).rows[0];await enqueue(c,{kind:'flight.raster',businessKey:'flight-raster:'+row.id,payload:{rasterId:row.id},dueAt:new Date().toISOString()});return row;
}
async function rasterActor(c:PoolClient,r:any){const u=(await c.query('SELECT role,enabled,auth_version FROM users WHERE id=$1',[r.created_by])).rows[0];if(!u?.enabled||u.auth_version!==r.auth_version)throw new AppError(403,'RASTER_AUTH_CHANGED','预览主体或授权已变更');const a:Actor={id:r.created_by,role:u.role,enabled:true,mfaVerified:true};await scope(c,a,r.object_id,'record');await scope(c,a,r.object_id,'read','media',r.source_asset_id);await scope(c,a,r.object_id,'review');return a;}
export async function runRaster(pool:Pool,id:string,lease?:JobLease,store:PrivateStore=configuredStore()){
 return withLease(pool,'flight-raster:'+id,lease,async current=>{let error:string|null=null,folder:string|null=null;try{const input=await database(async c=>{await assertLease(c,current);const r=(await c.query("SELECT * FROM flight_rasters WHERE id=$1 AND state='queued'",[id])).rows[0];if(!r)return null;await rasterActor(c,r);const m=(await c.query('SELECT * FROM media_assets WHERE id=$1',[r.source_asset_id])).rows[0];return {r,m};},pool);if(!input)return;
 let source:Buffer|string;if(store.open){folder=await mkdtemp(join(tmpdir(),'agri-raster-'));source=join(folder,'原件');await pipeline(await store.open(input.m.storage_key),createWriteStream(source,{mode:0o600,flags:'wx'}));const {createReadStream}=await import('node:fs'),{streamChecksum}=await import('../media/storage');const verified=await streamChecksum(createReadStream(/*turbopackIgnore: true*/ source));if(verified.checksum!==input.r.source_checksum||verified.length!==Number(input.m.byte_length))throw new AppError(503,'MEDIA_INTEGRITY','正射原件校验失败');}else{if(Number(input.m.byte_length)>20971520)throw new AppError(503,'STORAGE_STREAM_UNAVAILABLE','大栅格需要流式存储');source=await store.get(input.m.storage_key);if(checksum(source)!==input.r.source_checksum)throw new AppError(503,'MEDIA_INTEGRITY','正射原件校验失败');}const preview=await sharp(source,{limitInputPixels:1000000000}).resize({width:1280,height:1280,fit:'inside',withoutEnlargement:true}).png().toBuffer();

 await transaction(async c=>{await assertLease(c,current);const a=await rasterActor(c,input.r),assetId=randomUUID();await prepareMedia(c,a,{objectId:input.r.object_id,assetId,requestKey:assetId,submissionId:input.r.id,checksum:checksum(preview),byteLength:preview.length,mime:'image/png',name:'正射可视预览.png',previewOf:input.r.source_asset_id,source:input.r.source_ref});await uploadMedia(c,a,assetId,preview,store);await assertLease(c,current);await rasterActor(c,input.r);await c.query("UPDATE flight_rasters SET state='complete',preview_asset_id=$2,completed_at=now() WHERE id=$1",[id,assetId]);},pool);
 }catch(e){if(e instanceof AppError&&e.code==='LEASE_LOST')throw e;error=e instanceof AppError?e.code:'RASTER_PREVIEW_FAILED';}finally{if(folder)await rm(folder,{recursive:true,force:true});}if(error)await transaction(async c=>{await assertLease(c,current);await c.query("UPDATE flight_rasters SET state='failed',error_code=$2,completed_at=now() WHERE id=$1",[id,error]);},pool);});
}
