import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text,time,choice,finite} from '../../platform/validation';
import {arrayIds,scope,payloadHash,sameHash} from '../field/common';import {access,request,independent,type Body} from '../phase4/common';import {machineOrder,assertBinding} from './orders';import {assertMachineContract,machineContract} from './contracts';
const kinds=['track','work_order','arrival','spotcheck'] as const;
export async function recordMachineEvidence(c:PoolClient,a:Actor,b:Body){const order=await machineOrder(c,a,b.orderId,'record');return request(c,a,b,'machinery.evidence',order.object_id,async()=>{
 if(order.state!=='dispatched')throw new AppError(409,'MACHINE_ORDER_STATE','须关联已人工派单的服务单');await assertMachineContract(c,order.contract_id);await assertBinding(c,order.binding_id,order.object_id,order.starts_at,order.ends_at);
 const kind=choice(b.kind,kinds,'证据类别'),at=time(b.occurredAt),ids=arrayIds(b.assetIds??[],20);if(typeof b.passed!=='boolean')throw new AppError(400,'MACHINE_EVIDENCE_RESULT','请明确证据是否已核对');
 for(const id of ids){const m=(await c.query('SELECT * FROM media_assets WHERE id=$1',[id])).rows[0];if(m?.object_id!==order.object_id||m.ingest_state!=='complete')throw new AppError(422,'MACHINE_ASSET','原件须完整入库且同对象');await scope(c,a,order.object_id,'read','media',id);}
 const raw=b.track??[];if(!Array.isArray(raw)||raw.length>1000||kind==='track'&&raw.length<2||kind!=='track'&&raw.length)throw new AppError(400,'MACHINE_TRACK','轨迹证据须2至1000点，其他类型不填轨迹');
 const track=raw.map((p:any)=>({at:time(p?.at),lng:finite(p?.lng,'经度'),lat:finite(p?.lat,'纬度')}));
 for(let i=0;i<track.length;i++){const p=track[i];if(Math.abs(p.lng)>180||Math.abs(p.lat)>90||new Date(p.at)<order.starts_at||new Date(p.at)>order.ends_at||i>0&&p.at<=track[i-1].at)throw new AppError(422,'MACHINE_TRACK_PERIOD','轨迹须WGS84、时间递增并在作业窗口内');}
 const old=(await c.query('SELECT * FROM machinery_evidence WHERE order_id=$1 AND kind=$2 ORDER BY version DESC LIMIT 1',[order.id,kind])).rows[0];if(old&&b.supersedesId!==old.id||!old&&b.supersedesId)throw new AppError(409,'MACHINE_EVIDENCE_VERSION','更正须引用当前证据版本');
 return(await c.query('INSERT INTO machinery_evidence(object_id,order_id,kind,passed,occurred_at,evidence,asset_ids,track,version,supersedes_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *',[order.object_id,order.id,kind,b.passed,at,text(b.evidence,'原单、确认人及核对依据',4000),ids,JSON.stringify(track),(old?.version??0)+1,old?.id??null,a.id])).rows[0];
 });}
async function latestEvidence(c:PoolClient,id:string){return(await c.query('SELECT DISTINCT ON(kind) * FROM machinery_evidence WHERE order_id=$1 ORDER BY kind,version DESC',[id])).rows;}
export async function assertMachineAccepted(c:PoolClient,id:string){const order=(await c.query('SELECT * FROM machinery_orders WHERE id=$1 FOR SHARE',[id])).rows[0];if(!order||order.state!=='dispatched')throw new AppError(409,'MACHINE_NOT_ACCEPTED','服务单未验收或已取消');await assertMachineContract(c,order.contract_id);await assertBinding(c,order.binding_id,order.object_id,order.starts_at,order.ends_at);
 const review=(await c.query('SELECT * FROM machinery_reviews WHERE order_id=$1 ORDER BY seq DESC LIMIT 1',[id])).rows[0],evidence=await latestEvidence(c,id);
 if(review?.action!=='accept'||evidence.length!==4||evidence.some(r=>!r.passed||!review.evidence_ids.includes(r.id)))throw new AppError(409,'MACHINE_NOT_ACCEPTED','服务单未独立验收、依据已更正或已撤回');return order;
}
export async function reviewMachineOrder(c:PoolClient,a:Actor,b:Body){const order=await machineOrder(c,a,b.orderId,'review');return request(c,a,b,'machinery.review',order.object_id,async()=>{
 independent(a,order.created_by);const action=choice(b.action,['accept','withdraw'] as const,'验收动作'),rows=await latestEvidence(c,order.id);
 if(action==='accept'){if(order.state!=='dispatched')throw new AppError(409,'MACHINE_ORDER_STATE','服务单未派发或已取消');await assertMachineContract(c,order.contract_id);await assertBinding(c,order.binding_id,order.object_id,order.starts_at,order.ends_at);if(rows.length!==4||rows.some(r=>!r.passed))throw new AppError(422,'MACHINE_EVIDENCE_MISSING','须齐备已核轨迹、作业单、到户确认和抽查');for(const row of rows)independent(a,row.created_by);}
 return(await c.query('INSERT INTO machinery_reviews(object_id,order_id,action,evidence_ids,evidence,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[order.object_id,order.id,action,rows.map(r=>r.id),text(b.evidence,'独立验收依据',4000),a.id])).rows[0];
 });}
export async function importMachineEvidence(c:PoolClient,a:Actor,b:Body){await access(c,a,b.objectId);const contract=await machineContract(c,a,b.contractId);if(contract.object_id!==b.objectId)throw new AppError(422,'MACHINE_SCOPE','接入资料不属于当前对象');await assertMachineContract(c,contract.id);
 if(!Array.isArray(b.rows)||!b.rows.length||b.rows.length>100||Buffer.byteLength(JSON.stringify(b.rows))>1024*1024)throw new AppError(413,'MACHINE_IMPORT_LIMIT','每批1至100行且不超过1MiB');
 return request(c,a,b,'machinery.import',contract.object_id,async()=>{await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['machinery-import-object:'+b.objectId]);const source=text(b.sourceRef,'稳定文件来源',200),results=[];
 for(let i=0;i<(b.rows as any[]).length;i++){const row=(b.rows as any[])[i];await c.query('SAVEPOINT machine_row');try{
 const external=text(row?.externalId,'外部记录号',120),hash=payloadHash(row);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['machine-import:'+contract.id+':'+source+':'+external]);const order=await machineOrder(c,a,row.orderId,'record');if(order.contract_id!==contract.id||order.object_id!==b.objectId)throw new AppError(422,'MACHINE_SCOPE','导入行不属于本次资料契约');
 const old=(await c.query('SELECT * FROM machinery_import_rows WHERE contract_id=$1 AND source_ref=$2 AND external_id=$3',[contract.id,source,external])).rows[0];let id;if(old){sameHash(old.input_hash,hash);id=old.evidence_id;}else{const r=await recordMachineEvidence(c,a,{...row,requestKey:'import:'+payloadHash({contract:contract.id,source,external})});id=r.id;await c.query('INSERT INTO machinery_import_rows(object_id,contract_id,source_ref,external_id,input_hash,evidence_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[b.objectId,contract.id,source,external,hash,id,a.id]);}results.push({row:i+1,ok:true,id});
 }catch(e){await c.query('ROLLBACK TO SAVEPOINT machine_row');results.push({row:i+1,ok:false,code:e instanceof AppError?e.code:'MACHINE_IMPORT_ROW',message:e instanceof AppError?e.message:'行字段或关系无效'});}finally{await c.query('RELEASE SAVEPOINT machine_row');}}
 const record=(await c.query('INSERT INTO machinery_imports(object_id,contract_id,source_ref,input_rows,result_rows,input_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[b.objectId,contract.id,source,JSON.stringify(b.rows),JSON.stringify(results),payloadHash(b.rows),a.id])).rows[0];return {...record,rows:results};
 });}
