import type {PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {AppError} from '../../platform/error';import {text,time,choice} from '../../platform/validation';import {uuid} from '../identity/common';import {access,request,period,type Body} from '../phase4/common';import {positive} from '../inventory/quantity';import {polygon} from '../protection/plans';import {machineContract,assertMachineContract} from './contracts';
export async function machineOrder(c:PoolClient,a:Actor,id:unknown,action:'read'|'record'|'review'|'dispatch'='read'){uuid(id);const r=(await c.query('SELECT * FROM machinery_orders WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)throw new AppError(404,'MACHINE_ORDER','服务单不存在');await access(c,a,r.object_id,action);return r;}
export async function assertBinding(c:PoolClient,id:string,objectId:string,from:Date|string,to:Date|string){const r=(await c.query(`SELECT b.*,m.verified AND t.verified AND m.object_id=b.object_id AND t.object_id=b.object_id AS devices_verified FROM machinery_bindings b JOIN devices m ON m.id=b.machine_device_id JOIN devices t ON t.id=b.terminal_device_id WHERE b.id=$1 FOR SHARE OF b`,[id])).rows[0];if(!r||r.object_id!==objectId||r.revoked_at||!r.devices_verified||r.valid_from>new Date(from)||r.valid_until<new Date(to))throw new AppError(422,'MACHINE_BINDING_INVALID','机具终端绑定未核实、已撤回或不能覆盖作业时段');return r;}
export async function bindMachine(c:PoolClient,a:Actor,b:Body){await access(c,a,b.objectId,'configure');return request(c,a,b,'machinery.binding',b.objectId as string,async()=>{
 uuid(b.machineDeviceId);uuid(b.terminalDeviceId);if(b.machineDeviceId===b.terminalDeviceId)throw new AppError(422,'MACHINE_BINDING_INVALID','机具和终端须分别登记');const {start,end}=period(b.validFrom,b.validUntil,3660),ids=[b.machineDeviceId,b.terminalDeviceId].sort();for(const id of ids)await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['machine-device:'+id]);
 const d=(await c.query("SELECT * FROM devices WHERE id=ANY($1::uuid[]) AND object_id=$2 AND verified AND kind<>'camera_channel'",[ids,b.objectId])).rows;if(d.length!==2)throw new AppError(422,'MACHINE_DEVICE','机具和终端须为当前对象已核设备');
 if((await c.query('SELECT 1 FROM machinery_bindings WHERE (machine_device_id=ANY($1::uuid[]) OR terminal_device_id=ANY($1::uuid[])) AND valid_from<$3 AND LEAST(valid_until,COALESCE(revoked_at,valid_until))>$2',[ids,start,end])).rowCount)throw new AppError(409,'MACHINE_BINDING_OVERLAP','机具或终端在该时段已有绑定');
 return(await c.query('INSERT INTO machinery_bindings(object_id,machine_device_id,terminal_device_id,valid_from,valid_until,evidence,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[b.objectId,b.machineDeviceId,b.terminalDeviceId,start,end,text(b.evidence,'安装与对应依据',4000),a.id])).rows[0];
 });}
export async function revokeMachineBinding(c:PoolClient,a:Actor,b:Body){uuid(b.id);const r=(await c.query('SELECT * FROM machinery_bindings WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!r)throw new AppError(404,'MACHINE_BINDING_INVALID','绑定不存在');await access(c,a,r.object_id,'configure');return request(c,a,b,'machinery.unbind',r.object_id,async()=>{await c.query('INSERT INTO audit_events(actor_id,event_type,target_id,details) VALUES($1,$2,$3,$4)',[a.id,'machine_binding_revoked',r.id,{evidence:text(b.evidence,'解绑依据',4000)}]);return(await c.query('UPDATE machinery_bindings SET revoked_at=COALESCE(revoked_at,clock_timestamp()) WHERE id=$1 RETURNING *',[r.id])).rows[0];});}
export async function createMachineOrder(c:PoolClient,a:Actor,b:Body){await access(c,a,b.objectId);return request(c,a,b,'machinery.order',b.objectId as string,async()=>{
 const contract=await machineContract(c,a,b.contractId);if(contract.object_id!==b.objectId)throw new AppError(422,'MACHINE_SCOPE','接入资料不属于当前对象');uuid(b.bindingId);const {start,end}=period(b.startsAt,b.endsAt,31);await assertBinding(c,b.bindingId,b.objectId as string,start,end);
 if(b.supersedesId){const old=await machineOrder(c,a,b.supersedesId,'record');if(old.object_id!==b.objectId||old.state!=='draft'||(await c.query('SELECT 1 FROM machinery_orders WHERE supersedes_id=$1',[old.id])).rowCount)throw new AppError(409,'MACHINE_ORDER_VERSION','只允许修订当前草稿，已派单请取消并另建');}
 return(await c.query('INSERT INTO machinery_orders(object_id,contract_id,binding_id,title,operation,boundary,starts_at,ends_at,quantity,unit,source_ref,supersedes_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *',[b.objectId,contract.id,b.bindingId,text(b.title,'服务单名称'),text(b.operation,'作业种类'),JSON.stringify(await polygon(c,b.boundary)),start,end,positive(b.quantity),choice(b.unit,['mu','ha','hour','job'] as const,'计量单位'),text(b.sourceRef,'派单计划依据',4000),b.supersedesId||null,a.id])).rows[0];
 });}
export async function dispatchMachineOrder(c:PoolClient,a:Actor,b:Body){const r=await machineOrder(c,a,b.id,'dispatch');return request(c,a,b,'machinery.dispatch',r.object_id,async()=>{
 if(r.state!=='draft'||(await c.query('SELECT 1 FROM machinery_orders WHERE supersedes_id=$1',[r.id])).rowCount)throw new AppError(409,'MACHINE_ORDER_STATE','只有当前草稿可以派单');const contract=await assertMachineContract(c,r.contract_id);if(contract.valid_until<r.ends_at)throw new AppError(422,'MACHINE_CONTRACT_PERIOD','接入许可未覆盖作业窗口');await assertBinding(c,r.binding_id,r.object_id,r.starts_at,r.ends_at);
 return(await c.query("UPDATE machinery_orders SET state='dispatched',dispatched_by=$2,dispatched_at=clock_timestamp(),dispatch_evidence=$3 WHERE id=$1 RETURNING *",[r.id,a.id,text(b.evidence,'人工派单依据',4000)])).rows[0];});}
export async function cancelMachineOrder(c:PoolClient,a:Actor,b:Body){const r=await machineOrder(c,a,b.id,'dispatch');return request(c,a,b,'machinery.cancel',r.object_id,async()=>{await c.query('INSERT INTO audit_events(actor_id,event_type,target_id,details) VALUES($1,$2,$3,$4)',[a.id,'machine_order_cancelled',r.id,{evidence:text(b.evidence,'取消理由',4000)}]);return(await c.query("UPDATE machinery_orders SET state='cancelled' WHERE id=$1 RETURNING *",[r.id])).rows[0];});}
