import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import sharp from 'sharp';
import {withDb} from '../support/db';import {telemetryFixture} from '../support/telemetry';import {actorFixture,permit} from '../support/fixtures';import {transaction,database} from '../../src/db/pool';import {receiveCameraEvent,attachCameraImage} from '../../src/modules/cameras/service';import {prepareMedia,uploadMedia} from '../../src/modules/media/service';import {checksum,localStore} from '../../src/modules/media/storage';import {queueReview,runImageReview,recordFieldSample,labelSample,listImageReviews} from '../../src/modules/image-review/service';
test('T10完整图片自动排一次复核；样本异内容冲突，独立多目标标注与模型统计',()=>withDb(async pool=>{
 const f=await telemetryFixture(pool),reviewer=await actorFixture(pool,'technician');await permit(pool,reviewer.id,f.objectId,['read','review']);await pool.query('UPDATE devices SET verified=true WHERE id=$1',[f.device.id]);const event=await transaction(c=>receiveCameraEvent(c,f.actor,{deviceId:f.device.id,externalEventId:'synthetic-image',contractVersion:'synthetic',occurredAt:'2026-10-01T01:00:00Z',eventType:'合成图片'}),pool),dir=await mkdtemp(join(tmpdir(),'agri-quality-'));
 try{const store=localStore(join(dir,'source'),join(dir,'backup')),png=await sharp({create:{width:8,height:8,channels:3,background:'#888888'}}).png().toBuffer(),id=randomUUID();await transaction(c=>prepareMedia(c,f.actor,{objectId:f.objectId,assetId:id,requestKey:id,submissionId:event.id,checksum:checksum(png),byteLength:png.length,mime:'image/png',name:'合成.png',source:'仅工程测试'}),pool);await transaction(c=>uploadMedia(c,f.actor,id,png,store),pool);await transaction(c=>attachCameraImage(c,f.actor,{id:event.id,assetId:id}),pool);await transaction(c=>attachCameraImage(c,f.actor,{id:event.id,assetId:id}),pool);assert.equal((await pool.query("SELECT count(*) FROM jobs WHERE kind='image.review'")).rows[0].count,'1');
 const request={cameraEventId:event.id,requestKey:randomUUID()},review=await transaction(c=>queueReview(c,f.actor,request),pool);assert.equal((await pool.query('SELECT count(*) FROM image_reviews')).rows[0].count,'1');await runImageReview(pool,review.id,store,async()=>({detections:[{label:'person',score:.8}]}));
 const input={deviceId:f.device.id,cameraEventId:event.id,reviewId:review.id,scene:'day',sourceRef:'合成独立录像',occurredAt:'2026-10-01T01:00:00Z',target:'person',expectedTrigger:true,cameraTriggered:true,platformReceived:true,personReceived:null,requestKey:randomUUID()},sample=await transaction(c=>recordFieldSample(c,f.actor,input),pool);assert.equal((await transaction(c=>recordFieldSample(c,f.actor,input),pool)).id,sample.id);await assert.rejects(()=>transaction(c=>recordFieldSample(c,f.actor,{...input,target:'absent'}),pool),{code:'REQUEST_KEY_CONFLICT'});
 assert.equal((await database(c=>listImageReviews(c,reviewer),pool)).samples[0].model_result,null);await assert.rejects(()=>transaction(c=>labelSample(c,f.actor,{id:sample.id,humanLabels:['person']}),pool),{code:'INDEPENDENT_LABEL_REQUIRED'});await transaction(c=>labelSample(c,reviewer,{id:sample.id,humanLabels:['person','vehicle']}),pool);const result=await database(c=>listImageReviews(c,reviewer),pool),day=result.scenes.find(s=>s.scene==='day')!;assert.equal(day.person.tp,1);assert.equal(day.vehicle.fn,1);assert.equal(day.personNotReceived,0);assert.equal(day.unknownStages,1);assert.equal(result.automaticFiltering,false);
 }finally{await rm(dir,{recursive:true,force:true});}
}));
