import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {withDb} from '../support/db';import {mediaFixture} from '../support/remote-media';import {fhFixture,fhReply} from '../support/flighthub';import {transaction} from '../../src/db/pool';import {requestRemoteImport,runRemoteImport} from '../../src/modules/media/remote-import';import {requestDjiSync,requestDjiFile,runDjiJob} from '../../src/modules/connections/flighthub';import {localStore,checksum} from '../../src/modules/media/storage';
const original=()=>{const bytes=Buffer.alloc(21*1024*1024,32);Buffer.from('89504e470d0a1a0a','hex').copy(bytes);return bytes;};
test('T09监控授权链接与司空大文件走磁盘/流式原件，旧授权响应不入库',()=>withDb(async pool=>{
 const f=await mediaFixture(pool),folder=await mkdtemp(join(tmpdir(),'agri-large-origin-'));try{const store=localStore(join(folder,'source'),join(folder,'backup')),bytes=original(),run=await transaction(c=>requestRemoteImport(c,f.actor,f.body,f.env),pool);
 await runRemoteImport(pool,run.id,{env:f.env,store,fileDownloader:async(_url,path)=>{await writeFile(path,bytes,{mode:0o600});return {path,length:bytes.length,checksum:checksum(bytes)};}});const saved=(await pool.query('SELECT state,asset_id FROM remote_media_imports WHERE id=$1',[run.id])).rows[0];assert.equal(saved.state,'complete');assert.equal(Number((await pool.query('SELECT byte_length FROM media_assets WHERE id=$1',[saved.asset_id])).rows[0].byte_length),bytes.length);
 const d=await fhFixture(pool),taskId=randomUUID(),reply=fhReply(taskId);reply.media.list[0].size=bytes.length;const sync=await transaction(c=>requestDjiSync(c,d.actor,{connectionId:d.connection.id,version:1,taskUuid:taskId,requestKey:randomUUID()}),pool);await runDjiJob(pool,sync.id,{env:d.env,fetcher:reply.fetcher});const resource=(await pool.query('SELECT id FROM dji_resources')).rows[0],file=await transaction(c=>requestDjiFile(c,d.actor,{resourceId:resource.id,requestKey:randomUUID()}),pool);await runDjiJob(pool,file.id,{env:d.env,store,fileDownloader:async(_url,path)=>{await writeFile(path,bytes,{mode:0o600});return {path,length:bytes.length,checksum:checksum(bytes)};}});assert.equal((await pool.query('SELECT state FROM dji_runs WHERE id=$1',[file.id])).rows[0].state,'succeeded');
 const second=await mediaFixture(pool),bad=await transaction(c=>requestRemoteImport(c,second.actor,second.body,second.env),pool),count=(await pool.query('SELECT count(*) FROM media_assets')).rows[0].count;await runRemoteImport(pool,bad.id,{env:second.env,store,fileDownloader:async(_url,path)=>{await writeFile(path,bytes);await pool.query('UPDATE grants SET revoked_at=now() WHERE user_id=$1',[second.actor.id]);return {path,length:bytes.length,checksum:checksum(bytes)};}});assert.equal((await pool.query('SELECT count(*) FROM media_assets')).rows[0].count,count);assert.equal((await pool.query('SELECT state FROM remote_media_imports WHERE id=$1',[bad.id])).rows[0].state,'blocked');
 }finally{await rm(folder,{recursive:true,force:true});}
}));
