import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {withDb} from '../support/db';import {telemetryFixture} from '../support/telemetry';import {actorFixture,permit} from '../support/fixtures';import {transaction} from '../../src/db/pool';import {localStore,checksum} from '../../src/modules/media/storage';import {createUpload,uploadPart,completeUpload,assembleUpload,backupMedia,streamMedia,UPLOAD_CHUNK_BYTES} from '../../src/modules/media/uploads';
test('T09大原件分块/续传/异内容冲突/整体SHA/副本/Range，读流中撤权终止',()=>withDb(async pool=>{
 const f=await telemetryFixture(pool),other=await actorFixture(pool,'worker');await permit(pool,other.id,f.objectId,['read']);const dir=await mkdtemp(join(tmpdir(),'agri-large-'));try{const store=localStore(join(dir,'source'),join(dir,'backup')),bytes=Buffer.alloc(21*1024*1024,32);bytes.write('%PDF-1.7');const b={objectId:f.objectId,requestKey:randomUUID(),name:'合成大原件.pdf',mime:'application/pdf',byteLength:bytes.length,source:'合成数据，非农场原件',checksum:checksum(bytes)},session=await transaction(c=>createUpload(c,f.actor,b),pool);assert.equal((await transaction(c=>createUpload(c,f.actor,b),pool)).id,session.id);
 const first=bytes.subarray(0,UPLOAD_CHUNK_BYTES);await uploadPart(pool,f.actor,session.id,0,first,store);await uploadPart(pool,f.actor,session.id,0,first,store);const changed=Buffer.from(first);changed[10]=65;await assert.rejects(()=>uploadPart(pool,f.actor,session.id,0,changed,store),{code:'REQUEST_KEY_CONFLICT'});await assert.rejects(()=>transaction(c=>completeUpload(c,f.actor,{id:session.id}),pool),{code:'UPLOAD_PARTS_INCOMPLETE'});
 for(let offset=UPLOAD_CHUNK_BYTES,index=1;offset<bytes.length;offset+=UPLOAD_CHUNK_BYTES,index++)await uploadPart(pool,f.actor,session.id,index,bytes.subarray(offset,Math.min(bytes.length,offset+UPLOAD_CHUNK_BYTES)),store);
 await transaction(c=>completeUpload(c,f.actor,{id:session.id}),pool);await assembleUpload(pool,session.id,undefined,store);const row=(await pool.query('SELECT * FROM media_assets WHERE id=$1',[session.assetId])).rows[0];assert.equal(Number(row.byte_length),bytes.length);assert.equal(row.checksum,checksum(bytes));await backupMedia(pool,session.assetId,undefined,store);assert.deepEqual(await store.get(row.storage_key,true),bytes);
 const start=UPLOAD_CHUNK_BYTES-3,end=UPLOAD_CHUNK_BYTES+3,result=await streamMedia(pool,f.actor,session.assetId,'bytes='+start+'-'+end,store),parts:Buffer[]=[];for await(const b of result.stream)parts.push(Buffer.from(b));assert.deepEqual(Buffer.concat(parts),bytes.subarray(start,end+1));assert(result.range.partial);
 const full=await streamMedia(pool,other,session.assetId,null,store),it=full.stream[Symbol.asyncIterator]();assert((await it.next()).value);await pool.query("UPDATE grants SET revoked_at=now() WHERE user_id=$1 AND action='read'",[other.id]);await assert.rejects(async()=>{for await(const _ of it){}},{status:403});
 }finally{await rm(dir,{recursive:true,force:true});}
}));
