import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import type {PoolClient} from 'pg';import {withDb} from '../support/db';import {phase4Fixture} from '../support/phase4';import {permit,actorFixture} from '../support/fixtures';import {transaction,database} from '../../src/db/pool';
import {createResearchProtocol,reviewResearchProtocol} from '../../src/modules/research/protocols';import {recordResearchObservation} from '../../src/modules/research/observations';import {createResearchResult,reviewResearchResult,researchResult} from '../../src/modules/research/results';
import {exportResearch,researchOverview} from '../../src/modules/research/queries';import {recordExpense} from '../../src/modules/finance/expenses';
import {queueManagementReport,runManagement} from '../../src/modules/management/calculate';import {managementDetail} from '../../src/modules/management/queries';import {shareResource,revokeResource} from '../../src/modules/field/shares';
const key=()=>randomUUID(),iso=(n:number)=>new Date(Date.now()+n).toISOString();
test('C41/C42/C43/C44 试验独立审核、对照、历史输入与经费关系',()=>withDb(async pool=>{
 const f=await phase4Fixture(pool),tx=<T>(fn:(c:PoolClient)=>Promise<T>)=>transaction(fn,pool),plots:{objectId:string;group:string;label:string}[]=[];
 for(const group of ['control','treatment']){const id=key();await pool.query("INSERT INTO objects(id,parent_id,code,name,kind,source,created_by) VALUES($1::uuid,$2,$1::text,$3,'field','仅合成试验小区',$4)",[id,f.objectId,'合成'+group,f.actor.id]);for(const a of [f.actor,f.reviewer])await permit(pool,a.id,id,['read','record','review']);plots.push({objectId:id,group,label:group});}
 const protocol=await tx(c=>createResearchProtocol(c,f.actor,{objectId:f.objectId,title:'合成试验',question:'验证软件证据版本',baseline:'仅合成基线',plots,metrics:[{code:'height',name:'株高',unit:'cm',method:'合成尺量v1',expectedSamples:2}],startsAt:iso(-86400000),endsAt:iso(86400000),testingPlan:'第三方检测计划为合成文档，不代表机构承诺',stopRules:'软件测试结束即停止',sourceRef:'仅工程方案',requestKey:key()}));
 await assert.rejects(()=>tx(c=>reviewResearchProtocol(c,f.actor,{id:protocol.id,action:'approve',evidence:'自审',requestKey:key()})),{code:'INDEPENDENT_REVIEW'});await tx(c=>reviewResearchProtocol(c,f.reviewer,{id:protocol.id,action:'approve',evidence:'独立工程核实',requestKey:key()}));
 const observations:any[]=[];for(const [i,p] of plots.entries())observations.push(await tx(c=>recordResearchObservation(c,f.actor,{protocolId:protocol.id,plotObjectId:p.objectId,metric:'height',sampleKey:'sample1',value:String(10+i*2),observedAt:iso(-1000),method:'合成尺量v1',kind:'field',evidence:'合成观察',assetIds:[],requestKey:key()})));
 const result=await tx(c=>createResearchResult(c,f.actor,{protocolId:protocol.id,title:'合成结果一',claim:'只证明工程记录',claimLevel:'self_reported',sourceRef:'合成结果依据',requestKey:key()}));assert.equal(result.summary.groups[0].numericCount,1);assert.equal(result.summary.complete,false);
 await tx(c=>reviewResearchResult(c,f.reviewer,{id:result.id,action:'approve',evidence:'独立审阅工程结果',requestKey:key()}));
 await tx(c=>recordResearchObservation(c,f.actor,{protocolId:protocol.id,plotObjectId:plots[0].objectId,metric:'height',sampleKey:'sample1',value:'15',observedAt:observations[0].observed_at.toISOString(),method:'合成尺量v1',kind:'field',evidence:'合成更正',assetIds:[],supersedesId:observations[0].id,requestKey:key()}));
 const previous=await database(c=>researchResult(c,f.actor,result.id),pool);assert.equal(previous.inputs.observations.find((x:any)=>x.id===observations[0].id).value,'10.000000');assert.equal(previous.sourcesCurrent,false);
 const expense=await tx(c=>recordExpense(c,f.actor,{objectId:f.objectId,category:'research',amountCny:'5',payer:'合成研究主体',payee:'合成检测方',voucher:'RESEARCH-COST',occurredAt:iso(0),linkKind:'research_protocol',linkId:protocol.id,evidence:'合成试验用途',requestKey:key()}));assert((await database(c=>researchOverview(c,f.actor,f.objectId),pool)).expenses.some((e:any)=>e.id===expense.id));
 const expert=await actorFixture(pool,'expert');await permit(pool,expert.id,f.objectId,['read']);const grant=await tx(c=>shareResource(c,f.actor,{objectId:f.objectId,resourceType:'research_result',resourceId:result.id,recipientId:expert.id,expiresAt:iso(600000)}));assert.equal((await database(c=>researchResult(c,expert,result.id),pool)).id,result.id);await tx(c=>revokeResource(c,f.actor,{id:grant.id}));await assert.rejects(()=>database(c=>researchResult(c,expert,result.id),pool));
 await assert.rejects(()=>database(c=>exportResearch(c,f.actor,f.objectId),pool),{status:403});for(const p of plots)await permit(pool,f.actor.id,p.objectId,['export']);assert.equal(((await database(c=>exportResearch(c,f.actor,f.objectId),pool)).tables as any).research_results.length,1);
 await pool.query("UPDATE grants SET revoked_at=now() WHERE user_id=$1 AND object_id=$2 AND action='read'",[f.actor.id,plots[1].objectId]);await assert.rejects(()=>tx(c=>recordExpense(c,f.actor,{objectId:f.objectId,category:'research',amountCny:'1',payer:'合成研究主体',payee:'合成检测方',voucher:'RESEARCH-DENIED',occurredAt:iso(0),linkKind:'research_result',linkId:result.id,evidence:'撤权反例',requestKey:key()})),{status:403});
}));
test('C45 管理报告后台计算超过200条，固定快照、空值与当前授权',()=>withDb(async pool=>{
 const f=await phase4Fixture(pool),from=iso(-86400000),to=iso(86400000),tx=<T>(fn:(c:PoolClient)=>Promise<T>)=>transaction(fn,pool);
 await pool.query("INSERT INTO business_expenses(object_id,category,amount_cny,payer,payee,voucher,identity_key,occurred_at,link_kind,evidence,version,created_by) SELECT $1,'other',1,'合成付款方','合成收款方','snapshot-'||n,repeat(md5('snapshot-'||n),2),clock_timestamp(),'manual','仅规模测试',1,$2 FROM generate_series(1,240) n",[f.objectId,f.actor.id]);
 const input={objectId:f.objectId,fromAt:from,toAt:to,sourceRef:'合成统计窗口',requestKey:key()},report=await tx(c=>queueManagementReport(c,f.actor,input));assert.equal((await tx(c=>queueManagementReport(c,f.actor,input))).id,report.id);await runManagement(pool,report.id);
 const saved=await database(c=>managementDetail(c,f.actor,report.id),pool);assert.equal(saved.state,'complete');assert.equal(saved.result.economics.expenseRecords,240);assert.equal(saved.result.economics.knownRegisteredCny,'240');assert.equal(saved.result.devices.validObservationRate,null);assert.equal(saved.inputs.expenses.length,240);
 const queued=await tx(c=>queueManagementReport(c,f.actor,{...input,requestKey:key()}));await pool.query('UPDATE grants SET revoked_at=now() WHERE user_id=$1',[f.actor.id]);await assert.rejects(()=>runManagement(pool,queued.id));await assert.rejects(()=>database(c=>managementDetail(c,f.actor,report.id),pool));assert.equal((await pool.query('SELECT state FROM management_reports WHERE id=$1',[queued.id])).rows[0].state,'failed');
}));
