import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {withDb} from '../support/db';import {phase4Fixture} from '../support/phase4';import {actorFixture,objectFixture,permit} from '../support/fixtures';import {transaction,database} from '../../src/db/pool';import {recordExpense} from '../../src/modules/finance/expenses';import {financeOverview} from '../../src/modules/finance/queries';import {queueManagementReport} from '../../src/modules/management/calculate';import {createExport,downloadExport} from '../../src/modules/maintenance/exports';import {shareResource} from '../../src/modules/field/shares';
const key=()=>randomUUID(),window=()=>({fromAt:new Date(Date.now()-60000).toISOString(),toAt:new Date(Date.now()+60000).toISOString()});
test('B44/C45 财务不随普通对象读取开放，缓存导出重新核对当前角色',()=>withDb(async pool=>{
 const f=await phase4Fixture(pool),worker=await actorFixture(pool,'worker');await permit(pool,worker.id,f.objectId,['read','record']);await assert.rejects(()=>database(c=>financeOverview(c,worker,f.objectId),pool),{code:'FINANCE_ROLE'});await assert.rejects(()=>transaction(c=>queueManagementReport(c,worker,{objectId:f.objectId,...window(),sourceRef:'拒绝反例',requestKey:key()}),pool),{code:'FINANCE_ROLE'});
 const w=window(),exported=await transaction(c=>createExport(c,f.actor,{objectIds:[f.objectId],from:w.fromAt,to:w.toAt}),pool);await pool.query("UPDATE users SET role='maintainer' WHERE id=$1",[f.actor.id]);await assert.rejects(()=>transaction(c=>downloadExport(c,{...f.actor,role:'maintainer'},exported.id),pool),{code:'FINANCE_ROLE'});
}));
test('B44 相同主体和凭证跨对象不重复建账，归一大小写及全角',()=>withDb(async pool=>{
 const f=await phase4Fixture(pool),other=await objectFixture(pool,f.actor.id);await permit(pool,f.actor.id,other,['read','record']);const b={objectId:f.objectId,category:'other',amountCny:'10',payer:'ABC Ltd',payee:'Supply',voucher:'Invoice-1',occurredAt:new Date().toISOString(),linkKind:'manual',evidence:'合成凭证',requestKey:key()};
 await transaction(c=>recordExpense(c,f.actor,b),pool);await assert.rejects(()=>transaction(c=>recordExpense(c,f.actor,{...b,objectId:other,payer:'ＡＢＣ Ｌｔｄ',payee:'SUPPLY',voucher:'invoice-1',requestKey:key()}),pool),{code:'EXPENSE_DUPLICATE_SCOPE'});assert.equal((await pool.query('SELECT count(*) n FROM business_expenses')).rows[0].n,'1');
}));
test('C45 并发报告请求原子限额且未知分享类型不进入SQL',()=>withDb(async pool=>{
 const f=await phase4Fixture(pool),w=window(),attempts=await Promise.allSettled(Array.from({length:8},()=>transaction(c=>queueManagementReport(c,f.actor,{objectId:f.objectId,...w,sourceRef:'合成并发测试',requestKey:key()}),pool)));assert.equal(attempts.filter(r=>r.status==='fulfilled').length,5);assert.equal((await pool.query('SELECT count(*) n FROM management_reports')).rows[0].n,'5');
 const expert=await actorFixture(pool,'expert');await permit(pool,expert.id,f.objectId,['read']);await assert.rejects(()=>transaction(c=>shareResource(c,f.actor,{objectId:f.objectId,recipientId:expert.id,resourceType:'constructor',resourceId:key(),expiresAt:new Date(Date.now()+600000).toISOString()}),pool),{code:'RESOURCE_TYPE'});
}));
