import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import type {PoolClient} from 'pg';import {withDb} from '../support/db';import {phase4Fixture} from '../support/phase4';import {transaction} from '../../src/db/pool';import {recordExpense,reviewExpense} from '../../src/modules/finance/expenses';import {createSubsidyClaim,subsidyEvent} from '../../src/modules/finance/subsidies';import {financeOverview} from '../../src/modules/finance/queries';
test('B45 补贴实际日期未知不填录入时间，追加时间更正不改原款项',()=>withDb(async pool=>{
 const f=await phase4Fixture(pool),key=()=>randomUUID(),tx=<T>(fn:(c:PoolClient)=>Promise<T>)=>transaction(fn,pool);
 const expense=await tx(c=>recordExpense(c,f.actor,{objectId:f.objectId,category:'other',amountCny:'100',payer:'日期测试付款方',payee:'日期测试收款方',voucher:'TIME-V',occurredAt:new Date().toISOString(),linkKind:'manual',evidence:'合成单据',requestKey:key()}));await tx(c=>reviewExpense(c,f.reviewer,{id:expense.id,action:'approve',evidence:'合成审核',requestKey:key()}));
 const claim=await tx(c=>createSubsidyClaim(c,f.actor,{objectId:f.objectId,category:'purchase',policyRef:'合成日期测试政策',policyVersion:'test',beneficiary:'合成主体',periodFrom:new Date(Date.now()-86400000).toISOString(),periodTo:new Date(Date.now()+86400000).toISOString(),expenseIds:[expense.id],amountCny:'50',evidence:'仅合成申请',requestKey:key()}));
 for(const action of ['review','submit','award'])await tx(c=>subsidyEvent(c,f.reviewer,{id:claim.id,action,amountCny:'40',externalRef:action==='review'?undefined:'SYNTH-'+action,evidence:'合成实际凭据',requestKey:key()}));
 const receipt=await tx(c=>subsidyEvent(c,f.actor,{id:claim.id,action:'received',amountCny:'10',externalRef:'SYNTH-TIME-RECEIPT',evidence:'实际日期待核，未用录入时间代替',requestKey:key()}));assert.equal(receipt.occurred_at,null);
 const at=new Date(Date.now()-3600000).toISOString();await tx(c=>subsidyEvent(c,f.reviewer,{id:claim.id,action:'correct',correctsId:receipt.id,occurredAt:at,evidence:'取得合成原单日期后的追加核对',requestKey:key()}));
 assert.equal((await pool.query('SELECT occurred_at FROM subsidy_events WHERE id=$1',[receipt.id])).rows[0].occurred_at,null);assert.equal((await pool.query("SELECT sum(amount_cny)::text n FROM subsidy_events WHERE claim_id=$1 AND action='received'",[claim.id])).rows[0].n,'10.00');
 const overview=await tx(c=>financeOverview(c,f.actor,f.objectId));assert.equal(overview.events.find((e:any)=>e.id===receipt.id).effective_occurred_at.toISOString(),at);
}));
