import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import sharp from 'sharp';
import {withDb} from '../support/db';import {telemetryFixture} from '../support/telemetry';import {actorFixture,permit} from '../support/fixtures';import {transaction,database} from '../../src/db/pool';import {saveBoundary,listMap} from '../../src/modules/map/service';import {saveCoverage,queueRaster,runRaster} from '../../src/modules/flights/spatial';import {importFlight,linkFlightAsset,annotateFlight} from '../../src/modules/flights/service';import {prepareMedia,uploadMedia} from '../../src/modules/media/service';import {localStore,checksum} from '../../src/modules/media/storage';import {shareResource,revokeResource} from '../../src/modules/field/shares';
test('T07覆盖、私有正射预览、定位注记与专家固定边界版本',()=>withDb(async pool=>{
 const f=await telemetryFixture(pool),expert=await actorFixture(pool,'expert');await permit(pool,f.actor.id,f.objectId,['share']);await permit(pool,expert.id,f.objectId,['read']);const geometry={type:'Polygon',coordinates:[[[114,30],[114.01,30],[114.01,30.01],[114,30.01],[114,30]]]},boundary=await transaction(c=>saveBoundary(c,f.actor,{objectId:f.objectId,version:1,sourceCrs:4326,status:'verified',source:'合成边界',geometry}),pool),dir=await mkdtemp(join(tmpdir(),'agri-spatial-'));
 try{const store=localStore(join(dir,'source'),join(dir,'backup')),png=await sharp({create:{width:16,height:8,channels:3,background:'#88aa66'}}).png().toBuffer(),sum=checksum(png),flight=await transaction(c=>importFlight(c,f.actor,{objectId:f.objectId,sourceId:f.source.id,externalId:'spatial',startedAt:'2026-10-01T00:00:00Z',finishedAt:'2026-10-01T00:10:00Z',aircraftModel:'合成机型',providerVersion:'synthetic',sourceRef:'仅工程测试',crs:'EPSG4326，合成基准',files:[{externalId:'raw',name:'合成.png',version:'1',kind:'original',checksum:sum},{externalId:'ortho',name:'合成正射.png',version:'1',kind:'orthophoto',checksum:sum,parents:['raw'],processingSource:'合成正射，仅验证软件'}]}),pool),file=(await pool.query("SELECT id FROM flight_files WHERE flight_id=$1 AND kind='orthophoto'",[flight.id])).rows[0],assetId=randomUUID();await transaction(c=>prepareMedia(c,f.actor,{objectId:f.objectId,assetId,requestKey:assetId,submissionId:flight.id,checksum:sum,byteLength:png.length,mime:'image/png',name:'合成正射.png',source:'非生产成果'}),pool);await transaction(c=>uploadMedia(c,f.actor,assetId,png,store),pool);await transaction(c=>linkFlightAsset(c,f.actor,{fileId:file.id,assetId}),pool);
 const cb={flightId:flight.id,status:'verified',sourceCrs:4326,geometry,sourceRef:'合成覆盖',requestKey:randomUUID()},coverage=await transaction(c=>saveCoverage(c,f.actor,cb),pool);assert.equal((await transaction(c=>saveCoverage(c,f.actor,cb),pool)).id,coverage.id);
 const raster=await transaction(c=>queueRaster(c,f.actor,{fileId:file.id,sourceCrs:4326,bounds:[114,30,114.01,30.01],sourceRef:'合成北向正射配准',confirm:true,requestKey:randomUUID()}),pool);await runRaster(pool,raster.id,undefined,store);const saved=(await pool.query('SELECT state,preview_asset_id FROM flight_rasters WHERE id=$1',[raster.id])).rows[0];assert.equal(saved.state,'complete');assert(saved.preview_asset_id);
 const note={flightId:flight.id,fileId:file.id,note:'合成疑点',location:{type:'geographic',lng:114.005,lat:30.005},sourceRef:'合成定位依据',requestKey:randomUUID()},annotation=await transaction(c=>annotateFlight(c,f.actor,note),pool);assert.equal((await transaction(c=>annotateFlight(c,f.actor,note),pool)).id,annotation.id);assert.equal(annotation.asset_id,assetId);
 const all=await database(c=>listMap(c,f.actor),pool);assert.equal(all.coverages.length,1);assert.equal(all.rasters.length,1);assert.equal(all.annotations.length,1);assert.equal((await database(c=>listMap(c,expert),pool)).items.length,0);
 const grant=await transaction(c=>shareResource(c,f.actor,{objectId:f.objectId,recipientId:expert.id,resourceType:'map',resourceId:boundary.id,expiresAt:new Date(Date.now()+3600000).toISOString()}),pool);await transaction(c=>saveBoundary(c,f.actor,{objectId:f.objectId,version:2,sourceCrs:4326,status:'draft',source:'新版本仍未分享',geometry:{type:'Polygon',coordinates:[[[114,30],[114.02,30],[114.02,30.02],[114,30.02],[114,30]]]}}),pool);
 const shared=await database(c=>listMap(c,expert),pool);assert.equal(shared.items[0].version,2);assert.equal(shared.coverages.length,0);assert.equal(shared.rasters.length,0);await transaction(c=>revokeResource(c,f.actor,{id:grant.id}),pool);assert.equal((await database(c=>listMap(c,expert),pool)).items.length,0);
 }finally{await rm(dir,{recursive:true,force:true});}
}));
