import type {Pool,PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {choice,text,time} from '../../platform/validation';
import {uuid} from '../identity/common';
import {scope,visible,lockKey,payloadHash,sameHash} from '../field/common';
import {transaction,database} from '../../db/pool';
import {enqueue,type JobLease} from '../jobs/repository';
import {assertLease,withLease} from '../jobs/execution';
import {configuredStore,type PrivateStore,checksum} from '../media/storage';
import {IMAGE_VERSION,infer} from '../models/process';
export async function queueReview(c:PoolClient,a:Actor,b:Record<string,unknown>){
 uuid(b.cameraEventId);const e=(await c.query('SELECT * FROM camera_events WHERE id=$1 FOR UPDATE',[b.cameraEventId])).rows[0];if(!e?.asset_id||e.image_state!=='complete')throw new AppError(409,'IMAGE_PENDING','告警图片尚未完整入库');await scope(c,a,e.object_id,'record');await scope(c,a,e.object_id,'read','media',e.asset_id);
 const key=text(b.requestKey,'复核提交标识',120),asset=(await c.query('SELECT * FROM media_assets WHERE id=$1',[e.asset_id])).rows[0],hash=payloadHash({event:e.id,retryOf:b.retryOf||null,reason:b.reason?text(b.reason,'重试理由',2000):null});await lockKey(c,a,'image-review',key);
 const request=(await c.query('SELECT * FROM image_review_requests WHERE actor_id=$1 AND request_key=$2',[a.id,key])).rows[0];if(request){sameHash(request.content_hash,hash);return (await c.query('SELECT * FROM image_reviews WHERE id=$1',[request.review_id])).rows[0];}
 const legacy=(await c.query('SELECT * FROM image_reviews WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(legacy){sameHash(payloadHash({event:legacy.camera_event_id,retryOf:null,reason:null}),hash);await c.query('INSERT INTO image_review_requests(actor_id,request_key,review_id,content_hash) VALUES($1,$2,$3,$4)',[a.id,key,legacy.id,hash]);return legacy;}
 let row=(await c.query("SELECT * FROM image_reviews WHERE camera_event_id=$1 AND checksum=$2 AND model_version=$3 AND canonical AND state IN('queued','running','complete') FOR UPDATE",[e.id,asset.checksum,IMAGE_VERSION])).rows[0];
 if(!row){const previous=(await c.query('SELECT id FROM image_reviews WHERE camera_event_id=$1 AND checksum=$2 AND model_version=$3 ORDER BY created_at DESC LIMIT 1',[e.id,asset.checksum,IMAGE_VERSION])).rows[0];if(previous&&(b.retryOf!==previous.id||!b.reason))throw new AppError(409,'IMAGE_RETRY_CONFIRM','失败复核须明确引用原复核ID并填写重试原因');const user=(await c.query('SELECT auth_version FROM users WHERE id=$1',[a.id])).rows[0];row=(await c.query('INSERT INTO image_reviews(object_id,camera_event_id,asset_id,checksum,model_version,created_by,request_key,auth_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[e.object_id,e.id,asset.id,asset.checksum,IMAGE_VERSION,a.id,key,user.auth_version])).rows[0];await enqueue(c,{kind:'image.review',businessKey:'image-review:'+row.id,payload:{reviewId:row.id},dueAt:new Date().toISOString()});}
 await c.query('INSERT INTO image_review_requests(actor_id,request_key,review_id,content_hash) VALUES($1,$2,$3,$4)',[a.id,key,row.id,hash]);return row;
}
async function reviewActor(c:PoolClient,r:any){const u=(await c.query('SELECT role,enabled,auth_version FROM users WHERE id=$1',[r.created_by])).rows[0];if(!u?.enabled||r.auth_version==null||u.auth_version!==r.auth_version)throw new AppError(403,'IMAGE_AUTH_CHANGED','图片执行主体或授权已变更');const a:Actor={id:r.created_by,role:u.role,enabled:true,mfaVerified:true};await scope(c,a,r.object_id,'record');await scope(c,a,r.object_id,'read','media',r.asset_id);return a;}
export async function runImageReview(pool:Pool,id:string,store:PrivateStore=configuredStore(),detect=infer,lease?:JobLease){
 return withLease(pool,'image-review:'+id,lease,async current=>{
 const r=await transaction(async c=>{await assertLease(c,current);const row=(await c.query("SELECT * FROM image_reviews WHERE id=$1 AND state='queued' FOR UPDATE",[id])).rows[0];if(!row)return null;await c.query("UPDATE image_reviews SET state='running',execution_token=$2 WHERE id=$1",[id,current.leaseToken]);return row;},pool);if(!r)return;
 let result:Record<string,unknown>|null=null,error:string|null=null;
 try{const m=await database(async c=>{await assertLease(c,current);await reviewActor(c,r);return (await c.query("SELECT storage_key,mime,checksum FROM media_assets WHERE id=$1 AND ingest_state='complete'",[r.asset_id])).rows[0];},pool);if(!m)throw new AppError(409,'IMAGE_PENDING','原件未完整保存');const bytes=await store.get(m.storage_key);if(checksum(bytes)!==r.checksum)throw new AppError(503,'MEDIA_INTEGRITY','复核原件校验失败');await database(async c=>{await assertLease(c,current);await reviewActor(c,r);},pool);result=await detect({kind:'image',mime:m.mime,base64:bytes.toString('base64')});if(!Array.isArray(result.detections)||result.detections.some((d:any)=>typeof d.label!=='string'||!Number.isFinite(d.score)||d.score<0||d.score>1))throw new AppError(502,'IMAGE_OUTPUT_INVALID','图片模型输出无效');}
 catch(e){if(e instanceof AppError&&e.code==='LEASE_LOST')throw e;error=e instanceof AppError?e.code:'IMAGE_MODEL_FAILED';result=null;}
 await transaction(async c=>{await assertLease(c,current);try{await reviewActor(c,r);}catch{error='IMAGE_AUTH_CHANGED';result=null;}const state=error==='IMAGE_AUTH_CHANGED'||error==='ACCESS_DENIED'||error?.includes('SCOPE')?'access_revoked':error?'failed':'complete';const saved=await c.query('UPDATE image_reviews SET state=$2,result=$3,error_code=$4,completed_at=now() WHERE id=$1 AND execution_token=$5 RETURNING id',[id,state,result,error,current.leaseToken]);if(!saved.rowCount)throw new AppError(409,'LEASE_LOST','执行版本失效');const e=(await c.query('SELECT alert_id FROM camera_events WHERE id=$1',[r.camera_event_id])).rows[0];await c.query('INSERT INTO alert_events(alert_id,event_type,occurred_at,note,evidence) VALUES($1,$2,now(),$3,$4)',[e.alert_id,'image_review',error?'自动复核未完成，继续人工判断':'图片模型结果已追加，不覆盖人工判断或处置状态',JSON.stringify([{kind:'image_review',id,model:IMAGE_VERSION}])]);},pool);
 });
}
function sampleInput(b:Record<string,unknown>,objectId:string){const nullable=(v:unknown)=>v===undefined||v===null?null:typeof v==='boolean'?v:(()=>{throw new AppError(400,'SAMPLE_BOOLEAN','环节结果须为布尔值或未知');})();if(typeof b.expectedTrigger!=='boolean')throw new AppError(400,'SAMPLE_EXPECTATION','须登记预期触发条件');return {objectId,deviceId:b.deviceId,cameraEventId:b.cameraEventId||null,reviewId:b.reviewId||null,scene:choice(b.scene,['day','night','rain_fog'] as const,'场景'),sourceRef:text(b.sourceRef,'独立录像或现场测试依据',2000),occurredAt:time(b.occurredAt),target:choice(b.target,['person','vehicle','absent','unknown'] as const,'预定目标'),expectedTrigger:b.expectedTrigger,cameraTriggered:nullable(b.cameraTriggered),platformReceived:nullable(b.platformReceived),personReceived:nullable(b.personReceived)};}
export async function recordFieldSample(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.deviceId);const d=(await c.query('SELECT * FROM devices WHERE id=$1',[b.deviceId])).rows[0];if(!d)throw new AppError(404,'DEVICE_NOT_FOUND','设备不存在');await scope(c,a,d.object_id,'record');const input=sampleInput(b,d.object_id),key=text(b.requestKey,'样本标识',120),hash=payloadHash(input);await lockKey(c,a,'image-sample',key);const prior=(await c.query('SELECT * FROM image_field_samples WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(prior){const old=prior.content_hash??payloadHash(sampleInput({deviceId:prior.device_id,cameraEventId:prior.camera_event_id,reviewId:prior.review_id,scene:prior.scene,sourceRef:prior.source_ref,occurredAt:prior.occurred_at.toISOString(),target:prior.target,expectedTrigger:prior.expected_trigger,cameraTriggered:prior.camera_triggered,platformReceived:prior.platform_received,personReceived:prior.person_received},prior.object_id));sameHash(old,hash);return {id:prior.id,state:'already_recorded'};}
 if(input.cameraEventId){uuid(input.cameraEventId);const e=(await c.query('SELECT device_id FROM camera_events WHERE id=$1',[input.cameraEventId])).rows[0];if(e?.device_id!==d.id)throw new AppError(422,'SAMPLE_SCOPE','事件与抽查设备不匹配');}if(input.reviewId){uuid(input.reviewId);const r=(await c.query('SELECT camera_event_id,object_id FROM image_reviews WHERE id=$1',[input.reviewId])).rows[0];if(r?.object_id!==d.object_id||r.camera_event_id!==input.cameraEventId)throw new AppError(422,'SAMPLE_SCOPE','复核与样本事件不匹配');}
 return (await c.query('INSERT INTO image_field_samples(object_id,device_id,camera_event_id,review_id,scene,source_ref,occurred_at,target,expected_trigger,camera_triggered,platform_received,person_received,created_by,request_key,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id',[d.object_id,d.id,input.cameraEventId,input.reviewId,input.scene,input.sourceRef,input.occurredAt,input.target,input.expectedTrigger,input.cameraTriggered,input.platformReceived,input.personReceived,a.id,key,hash])).rows[0];
}
export async function labelSample(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const r=(await c.query('SELECT * FROM image_field_samples WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!r)throw new AppError(404,'SAMPLE_NOT_FOUND','样本不存在');await scope(c,a,r.object_id,'review','image_sample',r.id);if(r.created_by===a.id)throw new AppError(403,'INDEPENDENT_LABEL_REQUIRED','采样者不能标注自己的样本，请由独立审核人判断');let labels:string[]|null;
 if('humanLabels' in b){if(b.humanLabels===null)labels=null;else{if(!Array.isArray(b.humanLabels)||b.humanLabels.length>2||new Set(b.humanLabels).size!==b.humanLabels.length)throw new AppError(400,'SAMPLE_LABELS','标签只能为人/车辆，不重复；无法判断传null');labels=b.humanLabels.map(x=>choice(x,['person','vehicle'] as const,'目标')).sort();}}
 else{const label=choice(b.humanLabel,['person','vehicle','person_vehicle','absent','unknown'] as const,'独立人工标注');labels=label==='unknown'?null:label==='absent'?[]:label==='person_vehicle'?['person','vehicle']:[label];}
 if(r.labelled_at){if(r.labelled_by!==a.id||payloadHash(r.human_labels)!==payloadHash(labels))throw new AppError(409,'SAMPLE_LABELLED','标注不覆盖，修订另建样本');return {id:r.id};}
 const legacy=labels===null?'unknown':labels.length===0?'absent':labels.length===2?'person_vehicle':labels[0];await c.query('UPDATE image_field_samples SET human_label=$2,human_labels=$3,labelled_by=$4,labelled_at=now() WHERE id=$1',[r.id,legacy,labels,a.id]);return {id:r.id};
}
export function imageSceneQuality(samples:any[],scene:string){const values=samples.filter(s=>s.scene===scene),evaluated=values.filter(s=>s.labelled_at&&s.human_labels!==null&&s.model_state==='complete');const matrix=(target:'person'|'vehicle')=>{let tp=0,fp=0,fn=0,tn=0;for(const s of evaluated){const truth=s.human_labels.includes(target),prediction=(s.model_result?.detections??[]).some((d:any)=>d.score>=.5&&(target==='person'?d.label==='person':['car','truck','bus','motorcycle','bicycle'].includes(d.label)));if(truth&&prediction)tp++;else if(!truth&&prediction)fp++;else if(truth)fn++;else tn++;}return {tp,fp,fn,tn,precision:tp+fp?tp/(tp+fp):null,recall:tp+fn?tp/(tp+fn):null};};return {scene,sampleCount:values.length,expectedEvents:values.filter(s=>s.expected_trigger).length,notTriggered:values.filter(s=>s.expected_trigger&&s.camera_triggered===false).length,notReceived:values.filter(s=>s.camera_triggered===true&&s.platform_received===false).length,personNotReceived:values.filter(s=>s.platform_received===true&&s.person_received===false).length,unknownStages:values.filter(s=>s.camera_triggered===null||s.platform_received===null||s.person_received===null).length,unknownLabels:values.filter(s=>s.labelled_at&&s.human_labels===null).length,unlabelled:values.filter(s=>!s.labelled_at).length,modelIncomplete:values.filter(s=>s.model_state!=='complete').length,modelCompleted:values.filter(s=>s.model_state==='complete').length,evaluated: evaluated.length,person:matrix('person'),vehicle:matrix('vehicle'),state:'未完成现场效果验收'};}
export async function listImageReviews(c:PoolClient,a:Actor){const v=await visible(c,a,'image_review'),sampleScope=await visible(c,a,'image_sample'),reviews=(await c.query('SELECT * FROM image_reviews WHERE object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR id=ANY($2)) ORDER BY created_at DESC LIMIT 200',[v.objects,v.resources])).rows,samples=(await c.query('SELECT s.*,r.state AS model_state,r.result AS model_result FROM image_field_samples s LEFT JOIN image_reviews r ON r.id=s.review_id WHERE s.object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR s.id=ANY($2)) ORDER BY s.created_at DESC LIMIT 1001',[sampleScope.objects,sampleScope.resources])).rows,selected=samples.slice(0,1000);return {reviews,samples:selected.map(s=>s.labelled_at?s:{...s,model_result:null}),scenes:['day','night','rain_fog'].map(scene=>imageSceneQuality(selected,scene)),limited:samples.length>1000,evaluationScope:'最近1000条已授权样本；未标注/未知/未完成不计模型精度，现场标准仍须签认',automaticFiltering:false};}
