import type {Pool,PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {choice,text,time} from '../../platform/validation';
import {uuid} from '../identity/common';
import {scope,visible,lockKey} from '../field/common';
import {transaction,database} from '../../db/pool';
import {enqueue,type JobLease} from '../jobs/repository';
import {assertLease,withLease} from '../jobs/execution';
import {configuredStore,type PrivateStore,checksum} from '../media/storage';
import {IMAGE_VERSION,infer} from '../models/process';
export async function queueReview(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.cameraEventId);const e=(await c.query('SELECT * FROM camera_events WHERE id=$1 FOR SHARE',[b.cameraEventId])).rows[0];if(!e?.asset_id||e.image_state!=='complete')throw new AppError(409,'IMAGE_PENDING','告警图片尚未完整入库');await scope(c,a,e.object_id,'record');const key=text(b.requestKey,'复核提交标识',120),asset=(await c.query('SELECT * FROM media_assets WHERE id=$1',[e.asset_id])).rows[0];await lockKey(c,a,'image-review',key);const old=(await c.query('SELECT * FROM image_reviews WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(old){if(old.camera_event_id!==e.id)throw new AppError(409,'REQUEST_KEY_CONFLICT','复核标识对应其他事件');return old;}const row=(await c.query('INSERT INTO image_reviews(object_id,camera_event_id,asset_id,checksum,model_version,created_by,request_key,auth_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[e.object_id,e.id,e.asset_id,asset.checksum,IMAGE_VERSION,a.id,key,(await c.query('SELECT auth_version FROM users WHERE id=$1',[a.id])).rows[0].auth_version])).rows[0];await enqueue(c,{kind:'image.review',businessKey:'image-review:'+row.id,payload:{reviewId:row.id},dueAt:new Date().toISOString()});return row;}
async function reviewActor(c:PoolClient,r:any){const u=(await c.query('SELECT role,enabled,auth_version FROM users WHERE id=$1',[r.created_by])).rows[0];if(!u?.enabled||r.auth_version==null||u.auth_version!==r.auth_version)throw new AppError(403,'IMAGE_AUTH_CHANGED','图片执行主体或授权已变更');const a:Actor={id:r.created_by,role:u.role,enabled:true,mfaVerified:true};await scope(c,a,r.object_id,'record');await scope(c,a,r.object_id,'read','media',r.asset_id);return a;}
export async function runImageReview(pool:Pool,id:string,store:PrivateStore=configuredStore(),detect=infer,lease?:JobLease){
 return withLease(pool,'image-review:'+id,lease,async current=>{
 const r=await transaction(async c=>{await assertLease(c,current);const row=(await c.query("SELECT * FROM image_reviews WHERE id=$1 AND state='queued' FOR UPDATE",[id])).rows[0];if(!row)return null;await c.query("UPDATE image_reviews SET state='running',execution_token=$2 WHERE id=$1",[id,current.leaseToken]);return row;},pool);if(!r)return;
 let result:Record<string,unknown>|null=null,error:string|null=null;
 try{const m=await database(async c=>{await assertLease(c,current);await reviewActor(c,r);return (await c.query("SELECT storage_key,mime,checksum FROM media_assets WHERE id=$1 AND ingest_state='complete'",[r.asset_id])).rows[0];},pool);if(!m)throw new AppError(409,'IMAGE_PENDING','原件未完整保存');const bytes=await store.get(m.storage_key);if(checksum(bytes)!==r.checksum)throw new AppError(503,'MEDIA_INTEGRITY','复核原件校验失败');await database(async c=>{await assertLease(c,current);await reviewActor(c,r);},pool);result=await detect({kind:'image',mime:m.mime,base64:bytes.toString('base64')});if(!Array.isArray(result.detections)||result.detections.some((d:any)=>typeof d.label!=='string'||!Number.isFinite(d.score)||d.score<0||d.score>1))throw new AppError(502,'IMAGE_OUTPUT_INVALID','图片模型输出无效');}
 catch(e){if(e instanceof AppError&&e.code==='LEASE_LOST')throw e;error=e instanceof AppError?e.code:'IMAGE_MODEL_FAILED';result=null;}
 await transaction(async c=>{await assertLease(c,current);try{await reviewActor(c,r);}catch{error='IMAGE_AUTH_CHANGED';result=null;}const state=error==='IMAGE_AUTH_CHANGED'||error==='ACCESS_DENIED'||error?.includes('SCOPE')?'access_revoked':error?'failed':'complete';const saved=await c.query('UPDATE image_reviews SET state=$2,result=$3,error_code=$4,completed_at=now() WHERE id=$1 AND execution_token=$5 RETURNING id',[id,state,result,error,current.leaseToken]);if(!saved.rowCount)throw new AppError(409,'LEASE_LOST','执行版本失效');const e=(await c.query('SELECT alert_id FROM camera_events WHERE id=$1',[r.camera_event_id])).rows[0];await c.query('INSERT INTO alert_events(alert_id,event_type,occurred_at,note,evidence) VALUES($1,$2,now(),$3,$4)',[e.alert_id,'image_review',error?'自动复核未完成，继续人工判断':'图片模型结果已追加，不覆盖人工判断或处置状态',JSON.stringify([{kind:'image_review',id,model:IMAGE_VERSION}])]);},pool);
 });
}
export async function recordFieldSample(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.deviceId);const d=(await c.query('SELECT * FROM devices WHERE id=$1',[b.deviceId])).rows[0];if(!d)throw new AppError(404,'DEVICE_NOT_FOUND','设备不存在');await scope(c,a,d.object_id,'record');const nullable=(v:unknown)=>v===undefined||v===null?null:typeof v==='boolean'?v:(()=>{throw new AppError(400,'SAMPLE_BOOLEAN','各环节结果必须是布尔值或未知');})();if(b.cameraEventId){uuid(b.cameraEventId);const e=(await c.query('SELECT device_id FROM camera_events WHERE id=$1',[b.cameraEventId])).rows[0];if(e?.device_id!==d.id)throw new AppError(422,'SAMPLE_SCOPE','事件与抽查设备不匹配');}if(b.reviewId){uuid(b.reviewId);const r=(await c.query('SELECT camera_event_id,object_id FROM image_reviews WHERE id=$1',[b.reviewId])).rows[0];if(r?.object_id!==d.object_id||r.camera_event_id!==b.cameraEventId)throw new AppError(422,'SAMPLE_SCOPE','复核与样本事件不匹配');}
 const key=text(b.requestKey,'样本标识',120);if(typeof b.expectedTrigger!=='boolean')throw new AppError(400,'SAMPLE_EXPECTATION','应先登记预期触发条件');return(await c.query('INSERT INTO image_field_samples(object_id,device_id,camera_event_id,review_id,scene,source_ref,occurred_at,target,expected_trigger,camera_triggered,platform_received,person_received,created_by,request_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(created_by,request_key) DO NOTHING RETURNING id',[d.object_id,d.id,b.cameraEventId??null,b.reviewId??null,choice(b.scene,['day','night','rain_fog'] as const,'场景'),text(b.sourceRef,'独立录像或现场测试依据',2000),time(b.occurredAt),choice(b.target,['person','vehicle','absent','unknown'] as const,'预定目标'),b.expectedTrigger,nullable(b.cameraTriggered),nullable(b.platformReceived),nullable(b.personReceived),a.id,key])).rows[0]??{state:'already_recorded'};}
export async function labelSample(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const r=(await c.query('SELECT * FROM image_field_samples WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!r)throw new AppError(404,'SAMPLE_NOT_FOUND','样本不存在');await scope(c,a,r.object_id,'review','image_sample',r.id);if(r.labelled_at)throw new AppError(409,'SAMPLE_LABELLED','既有独立标注不覆盖，修订须另建样本');await c.query('UPDATE image_field_samples SET human_label=$2,labelled_by=$3,labelled_at=now() WHERE id=$1',[r.id,choice(b.humanLabel,['person','vehicle','absent','unknown'] as const,'独立人工标注'),a.id]);return {id:r.id};}
export async function listImageReviews(c:PoolClient,a:Actor){const v=await visible(c,a,'image_review'),reviews=(await c.query('SELECT * FROM image_reviews WHERE object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR id=ANY($2)) ORDER BY created_at DESC LIMIT 200',[v.objects,v.resources])).rows,samples=a.role==='expert'?[]:(await c.query('SELECT s.*,r.state AS model_state,r.result AS model_result FROM image_field_samples s LEFT JOIN image_reviews r ON r.id=s.review_id WHERE s.object_id=ANY($1::uuid[]) ORDER BY s.created_at DESC LIMIT 1000',[v.objects])).rows;
 return {reviews,samples,scenes:['day','night','rain_fog'].map(scene=>{const values=samples.filter(s=>s.scene===scene);return {scene,sampleCount:values.length,expectedEvents:values.filter(s=>s.expected_trigger).length,notTriggered:values.filter(s=>s.expected_trigger&&s.camera_triggered===false).length,notReceived:values.filter(s=>s.camera_triggered===true&&s.platform_received===false).length,personNotReceived:values.filter(s=>s.platform_received===true&&s.person_received===false).length,unknownStages:values.filter(s=>s.camera_triggered===null||s.platform_received===null||s.person_received===null).length,modelCompleted:values.filter(s=>s.model_state==='complete').length,state:'未完成现场效果验收'};}),automaticFiltering:false};}
