import {randomInt,createHmac,timingSafeEqual} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {database,transaction} from '../../db/pool';
import {configuredSms} from '../../adapters/aliyun/messaging';
import {encryptSecret,decryptSecret} from './mfa';
import {requireAdmin} from './management';
import {audit,digest,newToken,now,invalidCredentials,uuid,type IdentityOptions} from './common';
import {text} from '../../platform/validation';
import {beginAuthentication} from './session';
export const SMS_COOKIE='agri_sms_browser';
export interface SmsProvider{send(phone:string,code:string,id:string):Promise<{accepted:boolean;requestId:string|null}>}
const phoneValue=(v:string)=>{if(!/^1\d{10}$/.test(v))throw invalidCredentials();return v;};
function otpHash(id:string,code:string,key:string|undefined){const secret=key??process.env.IDENTITY_ENCRYPTION_KEY;if(!secret||!/^[a-f0-9]{64}$/.test(secret))throw new AppError(503,'IDENTITY_KEY_REQUIRED','身份密钥未配置');return createHmac('sha256',Buffer.from(secret,'hex')).update(id+':'+code).digest('hex');}
export async function bindExpertPhone(c:PoolClient,a:Actor,b:Record<string,unknown>){await requireAdmin(c,a);uuid(b.userId);const phone=phoneValue(String(b.phone));if(b.confirmIdentity!==true||(await c.query("SELECT 1 FROM users WHERE id=$1 AND enabled AND role='expert'",[b.userId])).rowCount!==1)throw new AppError(422,'EXPERT_PHONE','先核实已开通专家本人手机号');await c.query('INSERT INTO expert_phones(user_id,phone_hash,encrypted_phone,evidence,verified_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id) DO UPDATE SET phone_hash=excluded.phone_hash,encrypted_phone=excluded.encrypted_phone,evidence=excluded.evidence,verified_by=excluded.verified_by,updated_at=now()',[b.userId,otpHash('expert-phone',phone,undefined),encryptSecret(phone,b.userId+':expert-phone'),text(b.evidence,'本人及短信登录用途核验依据',2000),a.id]);await c.query('UPDATE users SET auth_version=auth_version+1 WHERE id=$1',[b.userId]);await audit(c,a.id,'expert_phone_verified',b.userId);return {userId:b.userId,verified:true};}
export async function bindWecomMember(c:PoolClient,a:Actor,b:Record<string,unknown>){await requireAdmin(c,a);uuid(b.userId);if(b.confirmIdentity!==true)throw new AppError(422,'MEMBER_IDENTITY','须核对企业与成员对应本人');const corp=text(b.corpId,'企业编号',100),member=text(b.memberId,'成员编号',100);if(!/^[A-Za-z0-9_.@-]+$/.test(corp+member))throw new AppError(422,'MEMBER_ID','成员标识无效');if(!(await c.query('SELECT 1 FROM users WHERE id=$1 AND enabled',[b.userId])).rowCount)throw new AppError(422,'MEMBER_USER','须先开通人员账号');const evidence=text(b.evidence,'本人映射核验依据',2000);await c.query('UPDATE users SET wecom_corp_id=$2,wecom_user_id=$3,wecom_identity_evidence=$4 WHERE id=$1',[b.userId,corp,member,evidence]);await audit(c,a.id,'wecom_member_verified',b.userId);return {userId:b.userId,verified:true};}
export async function requestExpertSms(phone:string,provider:SmsProvider=configuredSms(),options:IdentityOptions={}){
 phone=phoneValue(phone);const at=now(options),token=newToken(),browserToken=newToken(),code=String(randomInt(1000000)).padStart(6,'0');
 const input=await transaction(async c=>{await c.query("SELECT pg_advisory_xact_lock(hashtextextended('sms-send-quota',0))");const hash=otpHash('expert-phone',phone,options.encryptionKey),recent=(await c.query("SELECT count(*) AS hourly,max(created_at) AS latest FROM sms_challenges WHERE phone_hash=$1 AND created_at>$2::timestamptz-interval '1 hour'",[hash,at])).rows[0],daily=Number((await c.query("SELECT count(*) FROM sms_challenges WHERE created_at>$1::timestamptz-interval '24 hours'",[at])).rows[0].count),cap=Number(process.env.SMS_DAILY_LIMIT??200);if(recent.latest&&at.getTime()-recent.latest.getTime()<60000||Number(recent.hourly)>=5||daily>=cap||!Number.isInteger(cap)||cap<1||cap>10000)throw new AppError(429,'SMS_LIMITED','请求过于频繁，请稍后再试');const u=(await c.query("SELECT u.id,u.auth_version,p.encrypted_phone FROM users u JOIN expert_phones p ON p.user_id=u.id WHERE p.phone_hash=$1 AND u.enabled AND u.role='expert'",[hash])).rows[0],r=(await c.query('INSERT INTO sms_challenges(token_hash,browser_hash,phone_hash,user_id,auth_version,otp_hash,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[digest(token),digest(browserToken),hash,u?.id??null,u?.auth_version??null,otpHash(token,code,options.encryptionKey),at,new Date(at.getTime()+300000)])).rows[0];return {id:r.id,u};},options.pool);
 if(input.u){const still=await database(async c=>{const u=(await c.query("SELECT auth_version,enabled,role FROM users WHERE id=$1",[input.u.id])).rows[0],p=(await c.query('SELECT phone_hash FROM expert_phones WHERE user_id=$1',[input.u.id])).rows[0];return u?.enabled&&u.role==='expert'&&u.auth_version===input.u.auth_version&&p?.phone_hash===otpHash('expert-phone',phone,options.encryptionKey);},options.pool);if(still){await transaction(c=>c.query('UPDATE sms_challenges SET attempted_at=$2 WHERE id=$1',[input.id,now(options)]).then(()=>{}),options.pool);let result:{accepted:boolean;requestId:string|null}|null=null;try{result=await provider.send(decryptSecret(input.u.encrypted_phone,input.u.id+':expert-phone',options.encryptionKey),code,input.id);}catch{}await transaction(c=>c.query('UPDATE sms_challenges SET state=$2,provider_request_id=$3 WHERE id=$1',[input.id,result?result.accepted?'accepted':'failed':'unknown',result?.requestId??null]).then(()=>{}),options.pool);}}
 return {token,browserToken,message:'若号码对应已开通专家，将收到5分钟验证码；请在当前浏览器完成。'};
}
export async function verifyExpertSms(token:string,browserToken:string,code:string,options:IdentityOptions={}){
 if(!/^[a-f0-9]{64}$/.test(token)||!/^[a-f0-9]{64}$/.test(browserToken)||!/^\d{6}$/.test(code))throw invalidCredentials();const at=now(options);
 const r=await transaction(async c=>{const x=(await c.query('SELECT * FROM sms_challenges WHERE token_hash=$1 FOR UPDATE',[digest(token)])).rows[0];if(!x||x.consumed_at||x.expires_at<=at||x.browser_hash!==digest(browserToken)||x.failures>=5||x.state!=='accepted')return invalidCredentials();if(!timingSafeEqual(Buffer.from(x.otp_hash,'hex'),Buffer.from(otpHash(token,code,options.encryptionKey),'hex'))){await c.query('UPDATE sms_challenges SET failures=failures+1 WHERE id=$1',[x.id]);return invalidCredentials();}const u=(await c.query("SELECT * FROM users WHERE id=$1 AND enabled AND role='expert' FOR UPDATE",[x.user_id])).rows[0],p=(await c.query('SELECT phone_hash FROM expert_phones WHERE user_id=$1',[x.user_id])).rows[0];if(!u||u.auth_version!==x.auth_version||p?.phone_hash!==x.phone_hash)return invalidCredentials();await c.query('UPDATE sms_challenges SET consumed_at=$2 WHERE id=$1',[x.id,at]);await audit(c,u.id,'expert_sms_verified');return beginAuthentication(c,u,at);},options.pool);if(r instanceof AppError)throw r;return r;
}
