import {randomUUID} from 'node:crypto';import {AppError} from '../../platform/error';import {text,time,integer} from '../../platform/validation';import {uuid} from '../../modules/identity/common';import {payloadHash} from '../../modules/field/common';
export const FH2_CONTRACT='flighthub-public-v2-task-media-2026-10-02';export const FH2_HOST='https://es-flight-api-cn.djigate.com';
const fail=(code:string)=>new AppError(502,code,'司空只读响应未通过核对，请检查接口版本、项目权限及文件状态');
const optionalTime=(v:unknown)=>v===undefined||v===null||v===''?null:time(v,'厂家元数据时间');
const optionalCount=(v:unknown)=>v===undefined||v===null?null:integer(v,'厂家文件计数',0);
export function mediaMime(type:string,suffix:string){const s=suffix.replace(/^\./,'').toLowerCase();if(type==='video'&&s==='mp4')return 'video/mp4';if(type!=='image')return null;return ({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',tif:'image/tiff',tiff:'image/tiff'} as Record<string,string>)[s]??null;}
export function normalizeSnapshot(input:any,media:any,taskId:string){
 uuid(taskId);if(input?.uuid!==taskId)throw fail('FH2_TASK_ID');const task={id:taskId,name:input.name?text(input.name,'任务名称',1000):null,dockSn:text(input.sn,'机场SN',120),status:text(input.status,'任务状态',100),type:input.task_type?text(input.task_type,'任务类型',100):null,plannedStart:optionalTime(input.begin_at),plannedEnd:optionalTime(input.end_at),actualStart:null,actualEnd:null,expectedFiles:optionalCount(input.folder_info?.expected_file_count),uploadedFiles:optionalCount(input.folder_info?.uploaded_file_count)};
 if(!media||!Array.isArray(media.list)||media.list.length>10000)throw fail('FH2_MEDIA_SCHEMA');const seen=new Set<string>();const resources=media.list.map((r:any)=>{uuid(r.uuid);if(seen.has(r.uuid))throw fail('FH2_RESOURCE_ID');seen.add(r.uuid);const type=text(r.file_type,'厂家文件类别',100),suffix=typeof r.suffix==='string'&&r.suffix.length<=30?r.suffix:'';return {externalId:r.uuid,name:r.name?text(r.name,'厂家文件名',1000):null,fileType:type,suffix,size:r.size===undefined||r.size===null?null:integer(r.size,'厂家文件字节数',0,Number.MAX_SAFE_INTEGER),createdAt:optionalTime(r.create_at),updatedAt:optionalTime(r.update_at),sourceRevision:typeof r.update_at==='string'&&r.update_at?r.update_at:null,capturedAt:null,mime:mediaMime(type,suffix),originalUrl:typeof r.original_url==='string'&&r.original_url.length<=8192?r.original_url:null};});
 const limitations:string[]=[];if(resources.length>=10000)limitations.push('FH2_MEDIA_API_LIMIT');if(!resources.length)limitations.push('FH2_NO_MEDIA');if(task.expectedFiles===null||task.uploadedFiles===null)limitations.push('FH2_COUNTS_UNKNOWN');else{if(task.uploadedFiles<task.expectedFiles)limitations.push('FH2_UPLOAD_INCOMPLETE');if(task.uploadedFiles>resources.length)limitations.push('FH2_MEDIA_LIST_INCOMPLETE');}
 const publicMetadata={task,resources:resources.map((r:any)=>{const {originalUrl,...metadata}=r;return metadata;}),limitations};return {task,resources,limitations,publicMetadata,metadataHash:payloadHash(publicMetadata)};
}
export async function readTaskSnapshot(projectId:string,taskId:string,token:string,fetcher:typeof fetch=fetch,onAttempt?:(stage:'task'|'media')=>Promise<void>){
 uuid(projectId);uuid(taskId);if(typeof token!=='string'||token.length<16||token.length>16384||/[\r\n\s]/.test(token))throw new AppError(503,'FH2_NOT_CONFIGURED','司空组织令牌未配置');const raws:{stage:string;bytes:Buffer}[]=[];
 async function get(stage:'task'|'media',url:URL){await onAttempt?.(stage);const controller=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;const deadline=new Promise<never>((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(fail('FH2_TIMEOUT'));},15000);});let reader:ReadableStreamDefaultReader<Uint8Array>|undefined;
 try{return await Promise.race([(async()=>{const r=await fetcher(url,{method:'GET',redirect:'error',signal:controller.signal,headers:{'X-User-Token':token,'X-Project-Uuid':projectId,'X-Request-Id':randomUUID(),'X-Language':'zh',Accept:'application/json'}});if(r.status!==200)throw fail('FH2_HTTP');if(!(r.headers.get('Content-Type')??'').includes('application/json'))throw fail('FH2_JSON');reader=r.body?.getReader();if(!reader)throw fail('FH2_JSON');let n=0;const parts:Uint8Array[]=[];while(true){const b=await reader.read();if(b.done)break;n+=b.value.length;if(n>5242880)throw fail('FH2_RESPONSE_LIMIT');parts.push(b.value);}const bytes=Buffer.concat(parts);raws.push({stage,bytes});let body:any;try{body=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{throw fail('FH2_JSON');}if(body?.code!==0||!body.data||typeof body.data!=='object')throw fail('FH2_API_ERROR');return body.data;})(),deadline]);}catch(e){throw e instanceof AppError?e:fail(controller.signal.aborted?'FH2_TIMEOUT':'FH2_NETWORK');}finally{clearTimeout(timer);await reader?.cancel().catch(()=>{});reader?.releaseLock();}}
 try{const detail=new URL('/openapi/v2.0/flight-task/'+taskId,FH2_HOST);detail.searchParams.set('workspace_id',projectId);const task=await get('task',detail),media=await get('media',new URL('/openapi/v2.0/flight-task/'+taskId+'/media',FH2_HOST));return {...normalizeSnapshot(task,media,taskId),raws};}catch(e){if(e instanceof AppError)Object.assign(e,{raws});throw e;}
}
