import type {PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {choice,text,time,integer} from '../../platform/validation';
import {uuid} from '../identity/common';
import {scope,visible,arrayIds,lockKey,payloadHash,sameHash} from '../field/common';
import {createTask} from '../tasks/service';
import {describeWeather} from '../weather/presentation';
import {calendarWindows} from '../calendars/service';
export async function createBriefing(c:PoolClient,a:Actor,b:Record<string,unknown>){
 const ids=arrayIds(b.objectIds,20);if(!ids.length)throw new AppError(400,'BRIEFING_SCOPE','请选择简报范围');for(const id of ids)await scope(c,a,id,'record');const from=time(b.from),to=time(b.to),period=choice(b.period,['daily','weekly','monthly'] as const,'报告周期'),key=text(b.requestKey,'报告标识',120);if(from>=to||Date.parse(to)-Date.parse(from)>31*86400000)throw new AppError(400,'BRIEFING_PERIOD','报告时间须为正且不超过31天');const hash=payloadHash({ids,from,to,period});await lockKey(c,a,'briefing',key);const prior=(await c.query('SELECT * FROM briefings WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(prior){sameHash(prior.input_hash,hash);return prior;}
 const r=(await c.query('INSERT INTO briefings(created_by,request_key,input_hash,period,from_at,to_at,review_due_at) VALUES($1,$2,$3,$4,$5,$6,now()+interval \'4 hours\') RETURNING *',[a.id,key,hash,period,from,to])).rows[0];
 async function item(objectId:string,kind:string,refs:unknown[],sources:unknown[],description:string,limitations:string[]){await c.query('INSERT INTO briefing_items(briefing_id,object_id,kind,fact_refs,source_refs,original_text,limitations) VALUES($1,$2,$3,$4,$5,$6,$7)',[r.id,objectId,kind,JSON.stringify(refs),JSON.stringify(sources),description,JSON.stringify(limitations)]);}
 for(const id of ids){const metrics=(await c.query(`SELECT DISTINCT ON(definition_id,window_start,window_end) * FROM metric_results WHERE object_id=$1 AND window_start>=$2 AND window_start<$3 ORDER BY definition_id,window_start,window_end,version DESC`,[id,from,to])).rows;
 if(!metrics.length)await item(id,'data_gap',[],[],'本周期没有已计算指标，暂不能判断。',['缺少专业审核定义、有效样本或本周期计算结果']);for(const m of metrics)await item(id,'metric',[{kind:'metric',id:m.id}],[],m.status==='usable'?'程序指标：'+m.value+' '+m.unit:'程序指标暂不能判断。',[...m.limitations,...(m.version>1?['历史重算版本，单独复核']:[])]);
 const alerts=(await c.query("SELECT id,title,state,data_quality FROM alerts WHERE object_id=$1 AND state<>'closed' ORDER BY opened_at LIMIT 500",[id])).rows;for(const alert of alerts)await item(id,'alert',[{kind:'alert',id:alert.id}],[],alert.title+'；当前'+(alert.state==='open'?'待核查':'已恢复但仍待核查关闭'),['简报审阅不代替实时告警处置']);
 const weather=(await c.query("SELECT id,kind,valid_to,content FROM weather_records WHERE object_id=$1 AND kind IN('forecast','warning') AND valid_from<$3 AND valid_to>$2 ORDER BY published_at DESC LIMIT 20",[id,from,to])).rows;if(!weather.length)await item(id,'weather_gap',[],[],'没有适用的天气预报或预警。',['天气风险暂不能判断']);for(const w of weather)await item(id,'weather',[{kind:'weather',id:w.id}],[],'天气'+(w.kind==='forecast'?'预报':'预警')+'：'+describeWeather(w.content),[w.valid_to<=new Date()?'天气信息已过有效时段':'预报不能当作现场实况']);
 const windows=await calendarWindows(c,a,id,new Date(to));if(!windows.length)await item(id,'calendar_gap',[],[],'无已审核且匹配批次的当前农事时间窗。',['不自动推定阶段，不给出用量']);for(const w of windows)await item(id,'calendar',[{kind:'batch',id:w.batchId}],[{kind:'calendar',id:w.calendarId}],String(w.title)+'：'+w.instructions,w.limitations);
 const tasks=(await c.query("SELECT id,title,state FROM field_tasks WHERE object_id=$1 AND state NOT IN('reviewed','cancelled') ORDER BY created_at LIMIT 500",[id])).rows;for(const task of tasks)await item(id,'task',[{kind:'task',id:task.id}],[],task.title+'；状态'+task.state,['未反馈不表示已到场或已执行']);
 }
 return r;
}
export async function reviewItem(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const key=text(b.requestKey,'审阅标识',120);await lockKey(c,a,'briefing-review',key);const item=(await c.query('SELECT * FROM briefing_items WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!item)throw new AppError(404,'BRIEFING_ITEM_NOT_FOUND','简报事项不存在');await scope(c,a,item.object_id,'review','briefing_item',item.id);const decision=choice(b.decision,['adopted','modified','rejected'] as const,'审阅决定'),reason=text(b.reason,'审阅或驳回理由',2000),value=decision==='modified'?text(b.text,'人工修改内容',4000):item.original_text,hash=payloadHash({id:item.id,decision,reason,text:value});const previous=(await c.query('SELECT * FROM briefing_reviews WHERE actor_id=$1 AND request_key=$2',[a.id,key])).rows[0];if(previous){sameHash(previous.content_hash,hash);return {id:item.id,decision:item.decision};}if(integer(b.version,'事项版本')!==item.version)throw new AppError(409,'VERSION_CONFLICT','事项已被其他人审阅，请刷新');if(item.task_id)throw new AppError(409,'BRIEFING_TASK_EXISTS','已转任务的事项需另建修订，不覆盖历史审批');await c.query('INSERT INTO briefing_reviews(item_id,decision,text,reason,actor_id,request_key,content_hash) VALUES($1,$2,$3,$4,$5,$6,$7)',[item.id,decision,value,reason,a.id,key,hash]);await c.query('UPDATE briefing_items SET decision=$2,reviewed_text=$3,review_reason=$4,reviewer_id=$5,reviewed_at=now(),version=version+1 WHERE id=$1',[item.id,decision,value,reason,a.id]);return {id:item.id,decision};}
export async function toTaskDraft(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const i=(await c.query('SELECT * FROM briefing_items WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!i)throw new AppError(404,'BRIEFING_ITEM_NOT_FOUND','事项不存在');await scope(c,a,i.object_id,'record');if(!['adopted','modified'].includes(i.decision))throw new AppError(409,'BRIEFING_NOT_ADOPTED','事项须先由专业人员采纳或修改');if(i.task_id)return {id:i.task_id,state:'draft',alreadyCreated:true};const task=await createTask(c,a,{objectId:i.object_id,title:text(b.title,'任务标题',200),instructions:i.reviewed_text+'\n限制：'+i.limitations.join('；'),kind:'farm_work',requestKey:'briefing-item:'+i.id});await c.query('UPDATE briefing_items SET task_id=$2 WHERE id=$1',[i.id,task.id]);return task;}
export async function listBriefings(c:PoolClient,a:Actor){const v=await visible(c,a,'briefing_item');const items=(await c.query('SELECT * FROM briefing_items WHERE object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR id=ANY($2)) ORDER BY briefing_id,kind,id LIMIT 500',[v.objects,v.resources])).rows;const ids=[...new Set(items.map(i=>i.briefing_id))];return {items,briefings:(await c.query('SELECT *,review_due_at<now() AND state=\'pending_review\' AS overdue FROM briefings WHERE id=ANY($1::uuid[]) ORDER BY created_at DESC LIMIT 50',[ids])).rows,limitations:['程序生成的简报保持待审，模型故障不阻塞实时告警','老板版、工人版和专家版仍保留数据缺口']};}
export async function publishBriefing(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.briefingId);uuid(b.recipientId);const ids=arrayIds(b.itemIds,200),key=text(b.requestKey,'发布标识',120);if(!ids.length||b.confirm!==true)throw new AppError(400,'PUBLICATION_CONFIRM','请选择事项并确认接收人及范围');const expiry=time(b.expiresAt);if(Date.parse(expiry)<=Date.now()||Date.parse(expiry)-Date.now()>31*86400000)throw new AppError(400,'PUBLICATION_EXPIRY','分享期限须在未来31天内');const recipient=(await c.query('SELECT role,enabled FROM users WHERE id=$1',[b.recipientId])).rows[0];if(!recipient?.enabled||!['owner','worker','expert','technician'].includes(recipient.role))throw new AppError(422,'PUBLICATION_RECIPIENT','接收角色不可用');const items=(await c.query('SELECT * FROM briefing_items WHERE id=ANY($1::uuid[]) AND briefing_id=$2 FOR SHARE',[ids,b.briefingId])).rows;if(items.length!==ids.length||items.some(i=>i.decision==='draft'))throw new AppError(409,'PUBLICATION_REVIEW','不能发布未经审阅事项');const receiver:Actor={id:b.recipientId,role:recipient.role,enabled:true,mfaVerified:true};for(const i of items){await scope(c,a,i.object_id,'share');await scope(c,a,i.object_id,'read');await import('../identity/access').then(m=>m.assertAccess(c,receiver,{objectId:i.object_id,action:'read',at:new Date().toISOString()}));}
 await lockKey(c,a,'briefing-publish',key);const hash=payloadHash({briefingId:b.briefingId,recipientId:b.recipientId,ids,expiry}),old=(await c.query('SELECT * FROM briefing_publications WHERE confirmed_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(old){sameHash(old.content_hash,hash);return {id:old.id,url:'/api/v1/briefings/publications/'+old.id,state:'recorded_not_sent'};}
 const r=(await c.query('INSERT INTO briefing_publications(briefing_id,recipient_id,role_version,item_ids,confirmed_by,expires_at,request_key,content_hash,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[b.briefingId,b.recipientId,recipient.role,ids,a.id,expiry,key,hash,JSON.stringify(items.filter(i=>i.decision!=='rejected').map(i=>({id:i.id,text:i.reviewed_text,limitations:i.limitations,decision:i.decision,objectId:i.object_id})))])).rows[0];if(recipient.role==='expert')for(const i of items)await c.query("INSERT INTO resource_grants(user_id,object_id,resource_type,resource_id,expires_at,created_by) VALUES($1,$2,'briefing_item',$3,$4,$5)",[b.recipientId,i.object_id,i.id,expiry,a.id]);return {id:r.id,url:'/api/v1/briefings/publications/'+r.id,state:'recorded_not_sent',message:'已记录确认范围，尚未发送任何外部消息；原始数据及附件须单独授权'};
}
export async function readPublication(c:PoolClient,a:Actor,id:string){uuid(id);const p=(await c.query('SELECT * FROM briefing_publications WHERE id=$1 AND recipient_id=$2 AND revoked_at IS NULL AND expires_at>now()',[id,a.id])).rows[0];if(!p)throw new AppError(403,'PUBLICATION_SCOPE','发布范围不存在、已撤回、到期或不属于此账号');const items=(await c.query('SELECT * FROM briefing_items WHERE id=ANY($1::uuid[])',[p.item_ids])).rows;for(const i of items)await scope(c,a,i.object_id,'read','briefing_item',i.id);return {roleVersion:p.role_version,items:p.snapshot,pending:'数据缺口和待确认事项保留'};}
export async function remindOverdue(c:PoolClient){const rows=(await c.query("SELECT b.id,b.created_by FROM briefings b WHERE b.review_due_at<=now() AND EXISTS(SELECT 1 FROM briefing_items i WHERE i.briefing_id=b.id AND i.decision='draft') LIMIT 100")).rows;await c.query("UPDATE briefing_reminders SET state='pending' WHERE state='standby' AND briefing_id IN(SELECT id FROM briefings WHERE review_due_at<=now())");for(const r of rows)await c.query('INSERT INTO briefing_reminders(briefing_id,recipient_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[r.id,r.created_by]);return {pendingReminders:rows.length,externalSent:false};}
export async function requestBriefingExplanation(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.briefingId);const items=(await c.query('SELECT * FROM briefing_items WHERE briefing_id=$1 ORDER BY id',[b.briefingId])).rows;if(!items.length)throw new AppError(404,'BRIEFING_NOT_FOUND','简报不存在或没有事项');for(const i of items){await scope(c,a,i.object_id,'read');await scope(c,a,i.object_id,'record');}const {requestAssistant}=await import('../assistant/service'),r=await requestAssistant(c,a,{objectIds:[...new Set(items.map(i=>i.object_id))],question:'解释本期简报已有事实与审核资料；保留每个程序事项和数据限制，不执行派单或外发。',requestKey:'briefing-explanation:'+b.briefingId+':'+payloadHash(items.map(i=>({id:i.id,version:i.version}))).slice(0,16)});await c.query('INSERT INTO briefing_explanation_runs(briefing_id,run_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[b.briefingId,r.id]);return {...r,message:'模型解释独立追加；原程序事项仍须逐条审阅'};}
