'use client';
import {useRef,useState,type FormEvent} from 'react';
import {Field} from '@/components/platform/fields';
type Preview={roleVersion:string;items:{id:string;text:string;limitations:string[]}[]};
export default function PublicationForm({briefingId,onSaved}:{briefingId:string;onSaved:()=>void}){
 const [preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const key=useRef<string|null>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,isPreview=((e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement)?.value==='preview';setBusy(true);setError('');setMessage('');try{const v=Object.fromEntries(new FormData(form));key.current??=crypto.randomUUID();const r=await fetch('/api/v1/briefings/publications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({briefingId,recipientId:v.recipientId,itemIds:JSON.parse(String(v.itemIds)),expiresAt:new Date(String(v.expiresAt)).toISOString(),requestKey:key.current,preview:isPreview,confirm:v.confirm==='on'})}),data=await r.json();if(!r.ok)throw Error(data.message);if(isPreview)setPreview(data);else{setMessage('已登记访问范围，尚未发送消息。');key.current=null;setPreview(null);onSaved();}}catch(e){setError(e instanceof Error?e.message:'确认未完成');}finally{setBusy(false);}}
 return <form className="business-form" onSubmit={submit}><Field name="recipientId" label="接收人账号ID"/><label>已审阅事项ID列表<textarea name="itemIds" required/></label><Field name="expiresAt" label="访问截止时间" type="datetime-local"/><label><input name="confirm" type="checkbox" required/>已确认接收人、事项及有效期；资料与附件另行授权</label><button value="preview" formNoValidate disabled={busy}>预览接收版本</button><button value="publish" disabled={busy}>记录确认范围</button>{preview&&<section aria-label="接收版本预览"><h3>{({owner:'老板',technician:'技术员',worker:'工人',expert:'专家'})[preview.roleVersion as 'owner']}版预览</h3>{preview.items.map(i=><div key={i.id}><p>{i.text}</p><p className="hint">限制：{i.limitations.join('；')||'仍须核查适用性'}</p></div>)}</section>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</form>;
}
