'use client';
import ObjectWorkspace from '@/components/phase3/object-workspace';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';import ExportButton from '@/components/phase4/export-button';import MultiPick from '@/components/phase4/multi-pick';
type Row=Record<string,any>;const opt=(ids:string[],names:string[])=>ids.map((id,i)=>({id,name:names[i]}));
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function Work({objectId}:{objectId:string}){const {data,error,reload}=useApi<Row>('/api/v1/business/overview?objectId='+objectId);if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取费用…</p>;
 const common={stableKey:true,onSaved:()=>void reload()},hidden=<input type="hidden" name="objectId" value={objectId}/>,expenses=data.expenses.map((r:Row)=>({id:r.id,name:r.voucher+' / '+r.payer+' / '+(r.amount_cny??'金额未知')+' / '+r.current_eligibility})),claims=data.claims.map((r:Row)=>({id:r.id,name:r.beneficiary+' / '+r.category+' / '+r.state}));
 return <div className="stack"><p>当前对象累计登记费用：{data.summary.registered_cny??'未知'}元；金额未知{data.summary.unknown_amounts}项；人工登记净实付：{data.summary.recorded_paid_cny??'尚无记录'}元。以上不是会计利润或完整财务报表。</p><p className="hint">明细最近200条，汇总覆盖当前对象全部记录。不同发票或主体别名是否属于同一支出仍须人工核对。</p>
 <details><summary>登记费用或更正</summary><ActionForm path="/api/v1/business/expenses" {...common} times={['occurredAt']}>{hidden}<Pick name="category" label="费用类别" options={opt(['material','service','remediation','research','other'],['材料','服务','补作','科研','其他'])}/><Field name="quantity" label="计费数量（未知留空）" required={false}/><Field name="unit" label="计费单位（与原单一致）" required={false}/><Field name="unitPrice" label="单价元（未知留空）" required={false}/><Field name="amountCny" label="金额元（未知留空）" required={false}/><Field name="payer" label="付款主体"/><Field name="payee" label="收款主体"/><Field name="voucher" label="费用凭证号"/><Field name="occurredAt" label="费用实际发生时间" type="datetime-local"/><Pick name="linkKind" label="关联业务类型" options={opt(['manual','input_purchase','protection_execution','machine_order','research_protocol','research_result'],['人工原单','投入品采购','植保实际作业','农机服务单','科研协议','科研结果'])}/><Field name="linkId" label="关联业务记录ID（人工原单留空）" required={false}/><Field name="evidence" label="用途和原始凭据依据"/><Pick name="supersedesId" label="更正原费用（可选）" options={expenses} required={false}/></ActionForm></details>
 <details><summary>独立核实费用</summary><ActionForm path="/api/v1/business/reviews" {...common}><Pick name="id" label="待核实费用" options={expenses}/><Pick name="action" label="费用审核动作" options={opt(['approve','withdraw'],['独立核实通过','撤回核实'])}/><Field name="evidence" label="费用核实依据"/></ActionForm></details>
 <details><summary>登记实际付款或冲销</summary><ActionForm path="/api/v1/business/payments" {...common} times={['occurredAt']}><Pick name="expenseId" label="对应费用" options={expenses}/><Pick name="direction" label="记录方向" options={opt(['pay','reverse'],['实际付款','原付款全额冲销'])}/><Field name="amountCny" label="本次金额元"/><Field name="voucher" label="实际付款或冲销凭证号"/><Field name="occurredAt" label="实际付款或冲销时间" type="datetime-local"/><Pick name="reversesId" label="冲销原付款（付款时留空）" options={data.payments.filter((r:Row)=>r.direction==='pay').map((r:Row)=>({id:r.id,name:r.voucher+' / '+r.amount_cny}))} required={false}/><Field name="evidence" label="实际收付依据"/></ActionForm></details>
 <details><summary>登记补贴申请台账</summary><ActionForm path="/api/v1/business/claims" {...common} times={['periodFrom','periodTo']} multiFields={['expenseIds']}>{hidden}<Pick name="category" label="补贴分类" options={opt(['purchase','replacement','service'],['购置补贴','报废更新','社会化服务'])}/><Field name="policyRef" label="具体政策、地区和资料来源"/><Field name="policyVersion" label="政策版本"/><Field name="beneficiary" label="受益主体"/><Field name="periodFrom" label="申请期间开始" type="datetime-local"/><Field name="periodTo" label="申请期间结束（不含）" type="datetime-local"/><MultiPick name="expenseIds" label="关联已核费用" options={expenses} required/><Field name="amountCny" label="申请金额元"/><Field name="evidence" label="申请范围与凭证依据"/></ActionForm></details>
 <details><summary>登记补贴审核、受理与到账</summary><ActionForm path="/api/v1/business/events" {...common} times={['occurredAt']}><Pick name="id" label="补贴台账" options={claims}/><Pick name="action" label="补贴记录动作" options={opt(['review','submit','award','received','refund','reject','withdraw','correct'],['内部独立复核','登记真实受理','登记真实批准','登记实际到账','原到账全额退回','登记拒绝','撤回台账','更正原外部事实时间'])}/><Field name="amountCny" label="批准、到账或退回金额元（其他动作留空）" required={false}/><Field name="externalRef" label="实际受理、审批或收付凭证号" required={false}/><Pick name="reversesId" label="需退回的原到账（其他动作留空）" options={data.events.filter((r:Row)=>r.action==='received').map((r:Row)=>({id:r.id,name:r.external_ref+' / '+r.amount_cny}))} required={false}/><Field name="occurredAt" label="外部事实实际发生时间（未知留空；内部操作按保存时间）" type="datetime-local" required={false}/><Pick name="correctsId" label="时间更正对应原事实（其他动作留空）" options={data.events.filter((r:Row)=>['submit','award','received','refund','reject'].includes(r.action)).map((r:Row)=>({id:r.id,name:r.action+' / '+r.external_ref}))} required={false}/><Field name="evidence" label="本次实际依据"/></ActionForm></details>
 <StockTable rows={data.expenses} columns={[[ 'voucher','凭证'],['category','类别'],['amount_cny','登记金额元'],['payer','付款主体'],['current_eligibility','当前核实'],['version','版本']]}/><StockTable rows={data.payments} columns={[[ 'direction','方向'],['amount_cny','实付/冲销元'],['voucher','实际凭证'],['occurred_at','发生时间']]}/><StockTable rows={data.claims} columns={[[ 'category','分类'],['beneficiary','主体'],['amount_cny','申请元'],['awarded_cny','批准元'],['state','状态'],['policy_version','政策版本']]}/><StockTable rows={data.events} columns={[[ 'action','动作'],['amount_cny','金额元'],['external_ref','实际外部凭证'],['effective_occurred_at','实际发生时间（含更正）'],['created_at','录入时间'],['evidence','依据']]}/><ExportButton path={'/api/v1/business/export?objectId='+objectId} name="费用与补贴关系"/></div>;}
