import {randomUUID} from 'node:crypto';import type {Pool,PoolClient} from 'pg';import type {Actor} from '../../src/platform/types';import type {PrivateStore} from '../../src/modules/media/storage';import {phase4Fixture} from './phase4';import {permit,actorFixture} from './fixtures';import {transaction} from '../../src/db/pool';import {syntheticAsset} from './agronomy';import {releaseTestLot} from './stock';
import {registerEnergyMeter,reviewEnergyMeter,recordEnergyReading} from '../../src/modules/energy/service';import {registerCircularBatch,receiveCircularMaterial,processCircularMaterial} from '../../src/modules/circular/service';import {createLot,createLocation} from '../../src/modules/inventory/catalog';
import {recordMachineContract,reviewMachineContract} from '../../src/modules/machinery/contracts';import {bindMachine,createMachineOrder,dispatchMachineOrder} from '../../src/modules/machinery/orders';import {importMachineEvidence,recordMachineEvidence,reviewMachineOrder} from '../../src/modules/machinery/evidence';
import {recordExpense,reviewExpense,recordPayment} from '../../src/modules/finance/expenses';import {createSubsidyClaim,subsidyEvent} from '../../src/modules/finance/subsidies';
import {createResearchProtocol,reviewResearchProtocol} from '../../src/modules/research/protocols';import {recordResearchObservation} from '../../src/modules/research/observations';import {createResearchResult,reviewResearchResult} from '../../src/modules/research/results';import {queueManagementReport,runManagement} from '../../src/modules/management/calculate';import {shareResource,revokeResource} from '../../src/modules/field/shares';import {claimJob} from '../../src/modules/jobs/repository';
const key=()=>randomUUID(),now=()=>new Date().toISOString(),future=()=>new Date(Date.now()+86400000).toISOString(),past=()=>new Date(Date.now()-86400000).toISOString();
export async function seedPhase4(pool:Pool,store:PrivateStore,actor:Actor,objectId:string){
 if((await pool.query('SELECT current_database() name')).rows[0].name!=='agri_test')throw Error('只允许隔离测试库');
 const f=await phase4Fixture(pool,{actor,objectId}),a=f.actor,tx=<T>(fn:(c:PoolClient)=>Promise<T>)=>transaction(fn,pool);
 const meter=await tx(c=>registerEnergyMeter(c,a,{objectId,deviceId:f.machineId,name:'合成恢复能源表',purpose:'load',maxGapSeconds:7200,sourceRef:'仅合成倍率1',requestKey:key()}));await tx(c=>reviewEnergyMeter(c,f.reviewer,{id:meter.id,action:'approve',evidence:'合成独立核实',requestKey:key()}));const energyFrom=new Date(Date.now()-3600000).toISOString(),energyTo=now();for(const [observedAt,value] of [[energyFrom,'100'],[energyTo,'112']])await tx(c=>recordEnergyReading(c,a,{meterId:meter.id,metric:'consumption_kwh',observedAt,value,quality:'valid',sourceKind:'manual',evidence:'合成读数',requestKey:key()}));
 const location=await tx(c=>createLocation(c,a,{objectId,code:'P4-CIRC-W',name:'合成四期仓位',requestKey:key()}));const lots:any[]=[];for(const code of ['P4-CIRC-IN','P4-CIRC-OUT']){const l=await tx(c=>createLot(c,a,{objectId,code,product:'合成循环物料',kind:'input',unit:'kg',basis:'wet',source:'仅恢复测试',requestKey:key()}));await tx(c=>registerCircularBatch(c,a,{lotId:l.id,materialKind:'compost',originRef:'合成来源',requestKey:key()}));lots.push(l);}
 await tx(c=>receiveCircularMaterial(c,a,{lotId:lots[0].id,locationId:location.id,grossKg:'12',tareKg:'2',netKg:'10',moisturePct:'40',basis:'wet',voucher:'P4-WEIGH',occurredAt:now(),evidence:'合成称量',requestKey:key()}));await releaseTestLot(pool,a,objectId,lots[0].id);await tx(c=>processCircularMaterial(c,a,{objectId,code:'P4-TREAT',processKind:'treatment',inputs:[{lotId:lots[0].id,locationId:location.id,quantity:'10'}],outputs:[{lotId:lots[1].id,locationId:location.id,quantity:'9'}],reason:'合成损耗1kg',occurredAt:now(),evidence:'合成处理',requestKey:key()}));
 const contract=await tx(c=>recordMachineContract(c,a,{objectId,provider:'合成接入方',accountRef:'仅授权引用',fieldsRef:'字段v1',exportRef:'标准JSON',migrationRef:'历史导出',exitRef:'数据取回',validUntil:future(),sourceRef:'合成五项答复',requestKey:key()}));await tx(c=>reviewMachineContract(c,f.reviewer,{id:contract.id,action:'approve',evidence:'合成审核',requestKey:key()}));const binding=await tx(c=>bindMachine(c,a,{objectId,machineDeviceId:f.machineId,terminalDeviceId:f.terminalId,validFrom:past(),validUntil:future(),evidence:'合成安装对应',requestKey:key()}));
 const order=await tx(c=>createMachineOrder(c,a,{objectId,contractId:contract.id,bindingId:binding.id,title:'合成恢复服务单',operation:'工程测试',boundary:{type:'Polygon',coordinates:[[[114,30],[114.001,30],[114.001,30.001],[114,30.001],[114,30]]]},startsAt:new Date(Date.now()-3600000).toISOString(),endsAt:new Date(Date.now()+3600000).toISOString(),quantity:'1',unit:'job',sourceRef:'仅恢复测试',requestKey:key()}));await tx(c=>dispatchMachineOrder(c,a,{id:order.id,evidence:'合成人工派单',requestKey:key()}));
 const asset=await syntheticAsset(pool,a,objectId,store,'rgb'),track=[{at:new Date(Date.now()-1200000).toISOString(),lng:114.0001,lat:30.0001},{at:new Date(Date.now()-600000).toISOString(),lng:114.0002,lat:30.0002}];
 const importRow={externalId:'P4-TRACK',orderId:order.id,kind:'track',track,passed:true,occurredAt:now(),evidence:'合成实际轨迹',assetIds:[asset.id]};await tx(c=>importMachineEvidence(c,a,{objectId,contractId:contract.id,sourceRef:'合成终端文件',rows:[importRow],requestKey:key()}));
 for(const kind of ['work_order','arrival','spotcheck'])await tx(c=>recordMachineEvidence(c,a,{orderId:order.id,kind,passed:true,occurredAt:now(),evidence:'合成验收证据',assetIds:[asset.id],requestKey:key()}));await tx(c=>reviewMachineOrder(c,f.reviewer,{orderId:order.id,action:'accept',evidence:'合成独立验收',requestKey:key()}));
 const expense=await tx(c=>recordExpense(c,a,{objectId,category:'service',quantity:'1',unit:'job',unitPrice:'100',amountCny:'100',payer:'合成四期付款方',payee:'合成服务方',voucher:'P4-COST',occurredAt:now(),linkKind:'machine_order',linkId:order.id,evidence:'合成服务费用',requestKey:key()}));await tx(c=>reviewExpense(c,f.reviewer,{id:expense.id,action:'approve',evidence:'合成独立费用核实',requestKey:key()}));await tx(c=>recordPayment(c,a,{expenseId:expense.id,direction:'pay',amountCny:'30',voucher:'P4-PAY',occurredAt:now(),evidence:'合成实际付款登记',requestKey:key()}));
 const claim=await tx(c=>createSubsidyClaim(c,a,{objectId,category:'service',policyRef:'合成政策，未判断实际资格',policyVersion:'test-v1',beneficiary:'合成主体',periodFrom:past(),periodTo:future(),expenseIds:[expense.id],amountCny:'50',evidence:'合成申请',requestKey:key()}));await tx(c=>subsidyEvent(c,f.reviewer,{id:claim.id,action:'review',evidence:'合成内部复核',requestKey:key()}));await tx(c=>subsidyEvent(c,a,{id:claim.id,action:'submit',externalRef:'P4-ACCEPTED',evidence:'合成受理记录',requestKey:key()}));await tx(c=>subsidyEvent(c,f.reviewer,{id:claim.id,action:'award',amountCny:'40',externalRef:'P4-AWARD',evidence:'合成批准记录',requestKey:key()}));const receipt=await tx(c=>subsidyEvent(c,a,{id:claim.id,action:'received',amountCny:'20',externalRef:'P4-RECEIPT',evidence:'合成到账记录',requestKey:key()}));const correctedAt=new Date(Date.now()-60000).toISOString();await tx(c=>subsidyEvent(c,f.reviewer,{id:claim.id,action:'correct',correctsId:receipt.id,occurredAt:correctedAt,evidence:'合成实际日期补核',requestKey:key()}));
 const plots:{objectId:string;label:string;group:string}[]=[];for(const group of ['control','treatment']){const id=key();await pool.query("INSERT INTO objects(id,parent_id,code,name,kind,source,created_by) VALUES($1::uuid,$2,$1::text,$3,'field','合成恢复小区',$4)",[id,objectId,'四期'+group,a.id]);for(const person of [a,f.reviewer])await permit(pool,person.id,id,['read','record','review','export']);plots.push({objectId:id,label:'合成'+group,group});}
 const protocol=await tx(c=>createResearchProtocol(c,a,{objectId,title:'合成恢复试验',question:'旧快照能否回读',baseline:'合成基线',plots,metrics:[{code:'height',name:'株高',unit:'cm',method:'合成尺量',expectedSamples:2}],startsAt:past(),endsAt:future(),testingPlan:'合成第三方计划，未委托',stopRules:'工程完成即停',sourceRef:'合成协议',requestKey:key()}));await tx(c=>reviewResearchProtocol(c,f.reviewer,{id:protocol.id,action:'approve',evidence:'合成独立审核',requestKey:key()}));
 const obs=await tx(c=>recordResearchObservation(c,a,{protocolId:protocol.id,plotObjectId:plots[0].objectId,metric:'height',sampleKey:'P4-OBS',value:'10',observedAt:now(),method:'合成尺量',kind:'lab_report',agency:'合成检测机构，不是实际机构',reportRef:'P4-SYNTH-LAB',assetIds:[asset.id],evidence:'仅合成报告记录与图片',requestKey:key()}));
 const result=await tx(c=>createResearchResult(c,a,{protocolId:protocol.id,title:'合成固定结果',claim:'仅证明恢复链',claimLevel:'self_reported',sourceRef:'工程测试',requestKey:key()}));await tx(c=>reviewResearchResult(c,f.reviewer,{id:result.id,action:'approve',evidence:'合成独立结果审阅',requestKey:key()}));await tx(c=>recordResearchObservation(c,a,{protocolId:protocol.id,plotObjectId:plots[0].objectId,metric:'height',sampleKey:'P4-OBS',value:'11',observedAt:obs.observed_at.toISOString(),method:'合成尺量',kind:'field',assetIds:[asset.id],evidence:'合成更正保留旧结果',supersedesId:obs.id,requestKey:key()}));
 const researchExpense=await tx(c=>recordExpense(c,a,{objectId,category:'research',amountCny:'5',payer:'合成四期科研主体',payee:'合成第三方',voucher:'P4-RESEARCH-COST',occurredAt:now(),linkKind:'research_protocol',linkId:protocol.id,evidence:'合成协议任务经费',requestKey:key()}));
 const report=await tx(c=>queueManagementReport(c,a,{objectId,fromAt:past(),toAt:future(),sourceRef:'合成管理快照',requestKey:key()}));await runManagement(pool,report.id);const pending=await tx(c=>queueManagementReport(c,a,{objectId,fromAt:past(),toAt:future(),sourceRef:'合成中断任务',requestKey:key()})),oldLease=await claimJob(pool,'phase4-interrupted',new Date(),{businessKey:'management:'+pending.id});if(!oldLease)throw Error('未取得合成租约');await pool.query("UPDATE management_reports SET state='running',execution_token=$2 WHERE id=$1",[pending.id,oldLease.leaseToken]);await pool.query("UPDATE jobs SET lease_until=clock_timestamp()-interval '1 second' WHERE id=$1",[oldLease.id]);
 const expert=await actorFixture(pool,'expert');await permit(pool,expert.id,objectId,['read']);const grant=await tx(c=>shareResource(c,a,{objectId,recipientId:expert.id,resourceType:'research_result',resourceId:result.id,expiresAt:future()}));await tx(c=>revokeResource(c,a,{id:grant.id}));
 return {f,meter,energyFrom,energyTo,location,lots,contract,binding,order,expense,researchExpense,claim,receipt,correctedAt,protocol,result,report,pending,oldLease,expert,asset,plots,importRow};
}
