'use client';
import ObjectWorkspace from '@/components/phase3/object-workspace';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';import ExportButton from '@/components/phase4/export-button';import MultiPick from '@/components/phase4/multi-pick';
type Row=Record<string,any>;const opt=(ids:string[],names:string[])=>ids.map((id,i)=>({id,name:names[i]}));
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function Work({objectId}:{objectId:string}){const {data,error,reload}=useApi<Row>('/api/v1/machinery/overview?objectId='+objectId);if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取农机资料…</p>;
 const common={stableKey:true,onSaved:()=>void reload()},hidden=<input type="hidden" name="objectId" value={objectId}/>,contracts=data.contracts.map((r:Row)=>({id:r.id,name:r.provider+' / 版本'+r.version})),bindings=data.bindings.map((r:Row)=>({id:r.id,name:(data.devices.find((d:Row)=>d.id===r.machine_device_id)?.name??'机具')+' / '+r.valid_from+(r.revoked_at?' / 已解绑':'')})),orders=data.orders.map((r:Row)=>({id:r.id,name:r.title+' / '+r.state}));
 return <div className="stack"><p className="hint">每类显示最近200条。真实厂家接口尚未实现；标准JSON导入需要先核实五项书面答复。</p>
 <details><summary>登记五项接入答复</summary><ActionForm path="/api/v1/machinery/contracts" {...common} times={['validUntil']}>{hidden}<Field name="provider" label="平台或服务方"/>{[['accountRef','账户授权说明（勿填密码）'],['fieldsRef','字段与单位资料'],['exportRef','接口或导出说明'],['migrationRef','历史迁移说明'],['exitRef','退出与数据取回说明']].map(([name,label])=><Field key={name} name={name} label={label} required={false}/>)}<Field name="validUntil" label="资料许可有效至" type="datetime-local"/><Field name="sourceRef" label="书面答复来源"/><Pick name="supersedesId" label="修订原资料（可选）" options={contracts} required={false}/></ActionForm><ActionForm path="/api/v1/machinery/contract-reviews" {...common}><Pick name="id" label="接入资料版本" options={contracts}/><Pick name="action" label="资料审核动作" options={opt(['approve','withdraw'],['独立核实通过','撤回核实'])}/><Field name="evidence" label="资料审核依据"/></ActionForm></details>
 <details><summary>绑定机具与终端</summary><ActionForm path="/api/v1/machinery/bindings" {...common} times={['validFrom','validUntil']}>{hidden}<Pick name="machineDeviceId" label="已核机具" options={data.devices}/><Pick name="terminalDeviceId" label="已核定位终端" options={data.devices}/><Field name="validFrom" label="安装生效时间" type="datetime-local"/><Field name="validUntil" label="绑定有效至" type="datetime-local"/><Field name="evidence" label="安装对应依据"/></ActionForm><ActionForm path="/api/v1/machinery/unbind" {...common}><Pick name="id" label="需解绑记录" options={bindings}/><Field name="evidence" label="解绑原因"/></ActionForm></details>
 <details><summary>建立服务单与人工派单</summary><ActionForm path="/api/v1/machinery/orders" {...common} times={['startsAt','endsAt']} jsonFields={['boundary']}>{hidden}<Pick name="contractId" label="服务接入资料" options={contracts}/><Pick name="bindingId" label="机具终端绑定" options={bindings}/><Field name="title" label="服务单名称"/><Field name="operation" label="作业种类"/><label>已核作业边界GeoJSON<textarea name="boundary" required placeholder='{"type":"Polygon","coordinates":[...]}'/></label><Field name="startsAt" label="作业窗口开始" type="datetime-local"/><Field name="endsAt" label="作业窗口结束" type="datetime-local"/><Field name="quantity" label="计划计费数量"/><Pick name="unit" label="计划计费单位" options={opt(['mu','ha','hour','job'],['亩','公顷','小时','次'])}/><Field name="sourceRef" label="计划和边界依据"/><Pick name="supersedesId" label="修订原草稿（可选）" options={orders} required={false}/></ActionForm><ActionForm path="/api/v1/machinery/dispatch" {...common} label="确认人工派单"><Pick name="id" label="待派服务单" options={orders}/><Field name="evidence" label="本次派单依据"/></ActionForm><ActionForm path="/api/v1/machinery/cancel" {...common} label="取消服务单"><Pick name="id" label="需取消服务单" options={orders}/><Field name="evidence" label="取消原因"/></ActionForm></details>
 <details><summary>登记实际作业证据</summary><ActionForm path="/api/v1/machinery/evidence" {...common} times={['occurredAt']} booleans={['passed']} jsonFields={['track']} multiFields={['assetIds']}><Pick name="orderId" label="实际服务单" options={orders}/><Pick name="kind" label="证据类别" options={opt(['track','work_order','arrival','spotcheck'],['实际轨迹','作业单','到户确认','抽查'])}/><Field name="occurredAt" label="证据实际发生时间" type="datetime-local"/><Field name="evidence" label="原单、实际数量、确认人和依据"/><MultiPick name="assetIds" label="已入库原件（可选）" options={data.media}/><label>标准轨迹行（非轨迹证据填空数组）<textarea name="track" defaultValue="[]" placeholder='[{"at":"带时区ISO时间","lng":114,"lat":30}]'/></label><label><input type="checkbox" name="passed"/>已核对该类证据有效</label><Pick name="supersedesId" label="更正原证据（可选）" options={data.evidence.map((r:Row)=>({id:r.id,name:r.kind+' / 版本'+r.version+' / '+r.evidence}))} required={false}/></ActionForm></details>
 <details><summary>独立业务验收</summary><ActionForm path="/api/v1/machinery/reviews" {...common}><Pick name="orderId" label="待验收服务单" options={orders}/><Pick name="action" label="服务验收动作" options={opt(['accept','withdraw'],['独立验收通过','撤回验收'])}/><Field name="evidence" label="业务验收依据"/></ActionForm></details>
 <details><summary>导入标准农机证据文件</summary><p>每行包含externalId、orderId、kind、passed、occurredAt、evidence、assetIds、track。每批最多100行/1MiB；成功行按契约、来源和外部号跨账号防重。</p><ActionForm path="/api/v1/machinery/imports" {...common} jsonFields={['rows']}>{hidden}<Pick name="contractId" label="导入所用契约" options={contracts}/><Field name="sourceRef" label="稳定文件来源"/><label>标准JSON行数组<textarea name="rows" required/></label></ActionForm></details>
 <StockTable rows={data.orders} columns={[[ 'title','服务单'],['operation','作业'],['quantity','计划量'],['unit','单位'],['state','派单状态'],['current_acceptance','当前验收'],['id','导入引用']]}/><StockTable rows={data.evidence} columns={[[ 'kind','证据类别'],['passed','人员已核'],['version','版本'],['occurred_at','发生时间'],['evidence','原始依据']]}/><ExportButton path={'/api/v1/machinery/export?objectId='+objectId} name="农机服务关系"/></div>;}
