'use client';
import {useEffect,useRef,useState} from 'react';
import type {Viewer,Entity,Cartesian2} from 'cesium';
declare global{interface Window{Cesium?:typeof import('cesium');CESIUM_BASE_URL?:string}}
let engine:Promise<typeof import('cesium')>|undefined;
function loadCesium():Promise<typeof import('cesium')>{if(window.Cesium)return Promise.resolve(window.Cesium);if(!engine)engine=new Promise<typeof import('cesium')>((resolve,reject)=>{window.CESIUM_BASE_URL='/vendor/cesium/';if(!document.querySelector('link[data-cesium]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/vendor/cesium/Widgets/widgets.css';link.dataset.cesium='true';document.head.append(link);}const script=document.createElement('script');script.src='/vendor/cesium/Cesium.js';script.async=true;script.onload=()=>window.Cesium?resolve(window.Cesium):reject(Error('三维引擎未就绪'));script.onerror=()=>reject(Error('本地三维引擎加载失败'));document.head.append(script);}).catch(e=>{engine=undefined;throw e;});return engine!;}
function overlays(viewer:Viewer,data:any){const C=window.Cesium!;viewer.entities.removeAll();for(const o of data.map.items){if(!o.geometry)continue;const polygons=o.geometry.type==='Polygon'?[o.geometry.coordinates]:o.geometry.type==='MultiPolygon'?o.geometry.coordinates:[];for(const polygon of polygons)for(const ring of polygon){viewer.entities.add({name:o.name,polyline:{positions:C.Cartesian3.fromDegreesArray(ring.flatMap((p:number[])=>[p[0],p[1]])),width:2,material:C.Color.fromCssColorString('#90b877'),clampToGround:false}});}}
 for(const d of data.map.devices){const e=data.elevations.find((e:any)=>e.device_id===d.id&&e.position_id===d.position_id&&e.verified&&e.ellipsoid_height!==null);if(!e||!d.geometry)continue;const [lng,lat]=d.geometry.coordinates;viewer.entities.add({id:'device:'+d.id,name:d.name,position:C.Cartesian3.fromDegrees(lng,lat,Number(e.ellipsoid_height)),point:{pixelSize:9,color:C.Color.fromCssColorString('#f4c664'),outlineColor:C.Color.BLACK,outlineWidth:1,disableDepthTestDistance:Number.POSITIVE_INFINITY},label:{text:d.name,font:'13px sans-serif',fillColor:C.Color.WHITE,showBackground:true,pixelOffset:new C.Cartesian2(0,-21),disableDepthTestDistance:Number.POSITIVE_INFINITY}});}
 for(const p of data.scene.patches){const polygons=p.geometry.type==='Polygon'?[p.geometry.coordinates]:p.geometry.coordinates;for(const poly of polygons)viewer.entities.add({name:p.note,polygon:{hierarchy:C.Cartesian3.fromDegreesArray(poly[0].flatMap((v:number[])=>[v[0],v[1]])),material:C.Color.ORANGE.withAlpha(.35),outline:true,outlineColor:C.Color.ORANGE}});}
 viewer.scene.requestRender();
}
export default function CesiumView({data}:{data:any}){const container=useRef<HTMLDivElement>(null),viewerRef=useRef<Viewer|null>(null),latest=useRef(data),[state,setState]=useState('正在准备本地三维引擎…'),[selected,setSelected]=useState('');latest.current=data;
 useEffect(()=>{let disposed=false,viewer:Viewer|undefined,removeRendered:(()=>void)|undefined;void(async()=>{const C=await loadCesium();if(disposed)return;C.Ion.defaultAccessToken='';viewer=new C.Viewer(container.current!,{baseLayer:false,baseLayerPicker:false,geocoder:false,homeButton:false,sceneModePicker:false,animation:false,timeline:false,fullscreenButton:false,selectionIndicator:false,infoBox:false,showRenderLoopErrors:false,navigationHelpButton:false,skyBox:false,skyAtmosphere:false,terrainProvider:new C.EllipsoidTerrainProvider(),requestRenderMode:true,maximumRenderTimeChange:Infinity,contextOptions:{webgl:{alpha:false}}});viewerRef.current=viewer;viewer.resolutionScale=Math.min(1,1/(window.devicePixelRatio||1));viewer.scene.globe.baseColor=C.Color.fromCssColorString('#e1e7d6');viewer.scene.backgroundColor=C.Color.fromCssColorString('#e7eee3');overlays(viewer,latest.current);
  const resource='/api/v1/terrain/scenes/'+data.scene.id+'/resources/'+data.scene.root_path.split('/').map(encodeURIComponent).join('/');setState('正在核对并加载私有模型…');const tileset=await C.Cesium3DTileset.fromUrl(resource,{maximumScreenSpaceError:24,cacheBytes:268435456,maximumCacheOverflowBytes:134217728,showCreditsOnScreen:true});if(disposed){tileset.destroy();return;}setState('模型结构已读取，正在绘制瓦片…');viewer.scene.primitives.add(tileset);viewer.scene.requestRender();let loaded=0,loadFailed=false;viewer.scene.renderError.addEventListener(()=>{loadFailed=true;if(!disposed)setState('当前设备无法继续绘制，请关闭三维后返回二维资料。');});tileset.tileLoad.addEventListener(()=>{loaded++;viewer?.scene.requestRender();});tileset.tileFailed.addEventListener(()=>{loadFailed=true;if(!disposed)setState('部分瓦片读取失败或授权已失效，请重新核对场景。');});removeRendered=viewer.scene.postRender.addEventListener(()=>{if(!disposed&&!loadFailed&&loaded>0&&tileset.tilesLoaded){setState('三维模型已加载');removeRendered?.();removeRendered=undefined;}});viewer.screenSpaceEventHandler.setInputAction((event:{position:Cartesian2})=>{const picked=viewer!.scene.pick(event.position);const entity=picked?.id as Entity|undefined;setSelected(entity?.name??'');},C.ScreenSpaceEventType.LEFT_CLICK);viewer.camera.viewBoundingSphere(tileset.boundingSphere,new C.HeadingPitchRange(0,-.7,Math.max(tileset.boundingSphere.radius*3,30)));viewer.camera.lookAtTransform(C.Matrix4.IDENTITY);viewer.scene.requestRender();
 })().catch(()=>{if(!disposed)setState('三维暂不可用：请核对WebGL、模型格式与当前授权，二维资料仍可查看。');});return()=>{disposed=true;removeRendered?.();viewerRef.current=null;if(viewer&&!viewer.isDestroyed())viewer.destroy();};},[data.scene.id,data.scene.root_path]);
 useEffect(()=>{if(viewerRef.current&&window.Cesium)overlays(viewerRef.current,data);},[data]);
 return <section className="terrain-stage"><div className="terrain-stage-bar"><strong>{data.scene.name} · 版本{data.scene.version}</strong><span className={'terrain-badge '+(data.usable?'reviewed':'')}>{data.usable?'测绘资料核验通过':'仅供展示'}</span></div><div className="terrain-viewer" ref={container} aria-label="三维场景"/><p role="status" className="terrain-status">{state}{selected?' · '+selected:''}</p><p className="hint">鼠标拖动旋转/平移，滚轮缩放。对象边界线依参考椭球绘制，不表示实测高程；只绘制有已核椭球高的设备点位。橙色为排除区域。</p></section>;
}
