'use client';
import {useState} from 'react';
import {useApi} from '@/components/platform/use-api';
import ActionForm from '@/components/platform/action-form';
import {Field,Pick} from '@/components/platform/fields';
type Geometry={type:string;coordinates:number[][][]|number[][][][]|number[]};
type Data={items:{id:string;name:string;code:string;version:number;boundary_status:string;geometry:Geometry|null}[];devices:{id:string;name:string;object_id:string;verified:boolean;geometry:Geometry|null}[];limitations:string[]};
export default function MapPanel(){const map=useApi<Data>('/api/v1/map'),[zoom,setZoom]=useState(1);if(map.error)return <p className="form-error">{map.error}</p>;if(!map.data)return <p>正在读取地图…</p>;const all:number[][]=[];function rings(g:Geometry):number[][][]{return g.type==='Polygon'?g.coordinates as number[][][]:g.type==='MultiPolygon'?(g.coordinates as number[][][][]).flat():[];}for(const o of map.data.items)if(o.geometry)for(const ring of rings(o.geometry))all.push(...ring);for(const d of map.data.devices)if(d.geometry)all.push(d.geometry.coordinates as number[]);const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),dx=Math.max(.0001,maxX-minX),dy=Math.max(.0001,maxY-minY),project=(p:number[])=>[(p[0]-minX)/dx*850+25,450-(p[1]-minY)/dy*400];
 return <><p className="hint">WGS84二维边界与定位；未核实边界用虚线表示。地图邻近不代表归属或水力连通。</p>{all.length?<><label>缩放<input type="range" min="1" max="3" step=".1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/></label><div className="map-window"><svg className="farm-map" viewBox={`${450-450/zoom} ${250-250/zoom} ${900/zoom} ${500/zoom}`} role="img" aria-label="对象边界和设备位置"><rect width="900" height="500" fill="#edf3e5"/>{map.data.items.map(o=>o.geometry&&<a key={o.id} href={'/objects/'+o.id}><path d={rings(o.geometry).map(r=>'M'+r.map(p=>project(p).join(',')).join(' L')+' Z').join(' ')} fill={o.boundary_status==='verified'?'#b9d4ad':'#d9dbcd'} fillRule="evenodd" stroke="#28543d" strokeWidth="2" strokeDasharray={o.boundary_status==='verified'?undefined:'6 4'}><title>{o.name} · {o.boundary_status==='verified'?'已核边界':'草稿边界'}</title></path></a>)}{map.data.devices.map(d=>d.geometry&&<a key={d.id} href={'/objects/'+d.object_id}><circle cx={project(d.geometry.coordinates as number[])[0]} cy={project(d.geometry.coordinates as number[])[1]} r="5" fill={d.verified?'#28543d':'#c28d37'}><title>{d.name}</title></circle></a>)}</svg></div></>:<p className="empty-state">尚无已登记坐标，未生成虚构地图。</p>}<ul>{map.data.items.map(o=><li key={o.id}><a href={'/objects/'+o.id}>{o.name} · {o.code}</a>；版本{o.version}；{o.geometry?'边界已登记':'缺少边界坐标'}</li>)}</ul>
 <details><summary>登记边界版本</summary><ActionForm path="/api/v1/map" numbers={['version','sourceCrs']} jsonFields={['geometry']} onSaved={()=>void map.reload()}><Pick name="objectId" label="对象" options={map.data.items}/><Field name="version" label="当前对象版本" type="number"/><Field name="sourceCrs" label="来源EPSG坐标系（4326、4490、3857）" type="number"/><label>Polygon或MultiPolygon GeoJSON<textarea name="geometry" required rows={6}/></label><Pick name="status" label="边界状态" options={[{id:'draft',name:'草稿'},{id:'verified',name:'经专业确认'}]}/><Field name="source" label="边界来源和确认依据"/></ActionForm></details></>;
}
