export interface Sample{id:string;sampledAt:string;value:number|null;unit:string;valid:boolean}
export interface Definition{formula:'mean'|'min'|'max'|'coverage'|'duration'|'gdd';inputUnit:string;unit:string;intervalMs:number;maxGapMs:number;minimumCoverage:number;threshold:number|null;comparison:'lt'|'gt';timezone:'Asia/Shanghai'|'UTC';baseTemperature:number|null;capTemperature:number|null;species:string|null;stage:string|null;variety:string|null;startDate:string|null}
export function compute(def:Definition,input:Sample[],from:string,to:string,cutoff=new Date()){
 const start=Date.parse(from),requestedEnd=Date.parse(to),end=Math.min(requestedEnd,cutoff.getTime()),limitations:string[]=[];
 if(end<=start)throw new Error('INVALID_WINDOW');if(end<requestedEnd)limitations.push('统计窗口尚未结束，截至本次计算时点');
 const applicable=input.filter(s=>Date.parse(s.sampledAt)>=start&&Date.parse(s.sampledAt)<end),valid=applicable.filter(s=>s.valid&&s.value!==null&&Number.isFinite(s.value)&&s.unit===def.inputUnit).sort((a,b)=>Date.parse(a.sampledAt)-Date.parse(b.sampledAt)||a.id.localeCompare(b.id)),expected=Math.ceil((end-start)/def.intervalMs),slots=new Map<number,Sample>();for(const s of valid){const slot=Math.floor((Date.parse(s.sampledAt)-start)/def.intervalMs);if(!slots.has(slot))slots.set(slot,s);}const samples=valid,coverage=Math.min(1,slots.size/expected);
 let largestGap=samples.length?Math.max(Date.parse(samples[0].sampledAt)-start,end-Date.parse(samples.at(-1)!.sampledAt)):end-start;for(let i=1;i<samples.length;i++)largestGap=Math.max(largestGap,Date.parse(samples[i].sampledAt)-Date.parse(samples[i-1].sampledAt));
 if(coverage<def.minimumCoverage)limitations.push('有效采样槽完整率不足，缺测不计正常');if(largestGap>def.maxGapMs)limitations.push('存在超出定义的连续缺测，不跨缺测推定异常持续');if(applicable.some(s=>s.unit!==def.inputUnit))limitations.push('部分输入单位与定义不一致');
 const values=samples.map(s=>s.value!),sum=values.reduce((n,x)=>n+x,0);let observed:number|null=null;
 if(values.length){switch(def.formula){case'mean':observed=sum/values.length;break;case'min':observed=Math.min(...values);break;case'max':observed=Math.max(...values);break;case'coverage':observed=coverage;break;case'duration':{let ms=0;const matched=(n:number)=>def.comparison==='lt'?n<def.threshold!:n>def.threshold!,blockers=applicable.filter(s=>!s.valid||s.value===null||s.unit!==def.inputUnit).map(s=>Date.parse(s.sampledAt)).sort((a,b)=>a-b);let blocker=0;for(let i=1;i<samples.length;i++){const previous=Date.parse(samples[i-1].sampledAt),current=Date.parse(samples[i].sampledAt),gap=current-previous;while(blocker<blockers.length&&blockers[blocker]<=previous)blocker++;if(gap<=def.maxGapMs&&(blocker>=blockers.length||blockers[blocker]>=current)&&matched(samples[i-1].value!)&&matched(samples[i].value!))ms+=gap;}observed=ms/60000;break;}case'gdd':{const offset=def.timezone==='Asia/Shanghai'?8*3600000:0;if((start+offset)%86400000!==0||(end+offset)%86400000!==0)limitations.push('积温要求完整本地日窗口，当前仅有部分日期');if(!def.startDate||start!==Date.parse(def.startDate))limitations.push('积温窗口未从已审核起算日期开始');const days=new Map<string,number[]>();for(const s of samples){const day=new Date(Date.parse(s.sampledAt)+offset).toISOString().slice(0,10);days.set(day,[...(days.get(day)??[]),s.value!]);}let total=0;for(const values of days.values()){if(values.length/(86400000/def.intervalMs)<def.minimumCoverage)limitations.push('有日期未达到逐日完整率');const mean=values.reduce((n,x)=>n+x,0)/values.length;total+=Math.max(0,Math.min(def.capTemperature??Infinity,mean)-def.baseTemperature!);}if(days.size<Math.ceil((end-start)/86400000))limitations.push('存在整日缺测，积温不能补成0');observed=total;break;}}}
 const status=(!samples.length||limitations.some(s=>!s.startsWith('统计窗口'))) ?'insufficient':'usable';return {value:status==='usable'?observed:null,observedValue:observed,status,coverage,limitations:[...new Set(limitations)],evidenceIds:samples.map(s=>s.id),statisticsEnd:new Date(end).toISOString()};
}
