import type {PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {choice,text,time,integer,finite} from '../../platform/validation';
import {uuid} from '../identity/common';
import {existingObject,scope,visible,payloadHash} from '../field/common';
import {compute,type Definition} from './calculate';
export async function saveDefinition(c:PoolClient,a:Actor,b:Record<string,unknown>){
 const o=await existingObject(c,a,b,'configure');uuid(b.pointId);const p=(await c.query('SELECT metric,unit FROM points WHERE id=$1',[b.pointId])).rows[0];if(!p||!(await c.query('SELECT 1 FROM point_bindings WHERE point_id=$1 AND object_id=$2 AND verified AND valid_from<=now() AND(valid_to IS NULL OR valid_to>now())',[b.pointId,o.id])).rowCount)throw new AppError(422,'METRIC_POINT','输入测点尚未与此对象核实绑定');
 const s=b.specification as Record<string,unknown>;if(!s||typeof s!=='object')throw new AppError(400,'METRIC_DEFINITION','需要指标定义');const formula=choice(s.formula,['mean','min','max','coverage','duration','gdd'] as const,'公式'),interval=integer(s.intervalMs,'采样间隔',1000,86400000),gap=integer(s.maxGapMs,'最大缺测间隔',interval,31*86400000),coverage=finite(s.minimumCoverage,'最低完整率');if(coverage<0||coverage>1)throw new AppError(400,'METRIC_COVERAGE','完整率应在0至1');
 const spec:Definition={formula,inputUnit:text(s.inputUnit,'输入单位',40),unit:text(s.unit,'结果单位',40),intervalMs:interval,maxGapMs:gap,minimumCoverage:coverage,threshold:formula==='duration'?finite(s.threshold,'阈值'):null,comparison:choice(s.comparison??'lt',['lt','gt'] as const,'比较'),timezone:choice(s.timezone,['Asia/Shanghai','UTC'] as const,'时区'),baseTemperature:formula==='gdd'?finite(s.baseTemperature,'积温基温'):null,capTemperature:formula==='gdd'&&s.capTemperature!=null?finite(s.capTemperature,'积温封顶温度'):null,species:s.species?text(s.species,'物种',100):null,stage:s.stage?text(s.stage,'阶段',100):null,variety:s.variety?text(s.variety,'品种',100):null,startDate:formula==='gdd'?time(s.startDate):null};
 if(spec.inputUnit!==p.unit||(['mean','min','max'].includes(formula)&&spec.unit!==p.unit)||(formula==='duration'&&spec.unit!=='min')||(formula==='coverage'&&spec.unit!=='ratio')||(formula==='gdd'&&(!['°C','℃','C'].includes(p.unit)||spec.unit!=='°C·d'||spec.intervalMs>86400000)))throw new AppError(422,'METRIC_UNIT','公式与输入或输出单位不一致，不做未经审核的换算');
 const name=text(b.name,'指标名称',200);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['metric:'+o.id+':'+name]);const version=Number((await c.query('SELECT COALESCE(max(version),0) AS n FROM metric_definitions WHERE object_id=$1 AND name=$2',[o.id,name])).rows[0].n)+1;return(await c.query('INSERT INTO metric_definitions(object_id,point_id,name,version,specification,source_ref,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[o.id,b.pointId,name,version,spec,text(b.sourceRef,'公式与参数依据',3000),a.id])).rows[0];
}
export async function reviewDefinition(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const r=(await c.query('SELECT * FROM metric_definitions WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!r)throw new AppError(404,'DEFINITION_NOT_FOUND','指标定义不存在');await scope(c,a,r.object_id,'review','definition',r.id);if(b.retire===true){await c.query('UPDATE metric_definitions SET retired_at=now() WHERE id=$1',[r.id]);return {id:r.id,status:'retired'};}if(r.retired_at)throw new AppError(409,'DEFINITION_RETIRED','已撤回定义须新建修订');await c.query('UPDATE metric_definitions SET approved_by=$2,approved_at=COALESCE(approved_at,now()) WHERE id=$1',[r.id,a.id]);return {id:r.id,status:'approved'};}
export async function calculateMetric(c:PoolClient,a:Actor,b:Record<string,unknown>,cutoff=new Date()){
 uuid(b.definitionId);const d=(await c.query('SELECT * FROM metric_definitions WHERE id=$1 FOR SHARE',[b.definitionId])).rows[0];if(!d)throw new AppError(404,'DEFINITION_NOT_FOUND','指标定义不存在');await scope(c,a,d.object_id,'read','definition',d.id);if(!d.approved_at||d.retired_at)throw new AppError(422,'DEFINITION_UNAPPROVED','指标定义须先经专业审核且未撤回');const from=time(b.from),to=time(b.to);if(from>=to||Date.parse(to)-Date.parse(from)>366*86400000||Date.parse(from)>=cutoff.getTime())throw new AppError(400,'METRIC_WINDOW','统计窗口无效或超过366天');const spec=d.specification as Definition;
 const samples=(await c.query(`SELECT o.id,o.sampled_at,o.value::float8,o.unit,o.quality,o.origin,o.received_at,h.conflicted,h.canonical_id FROM observations o JOIN observation_heads h ON h.id=o.head_id
 WHERE o.point_id=$1 AND o.object_id=$2 AND o.sampled_at>=$3 AND o.sampled_at<$4 AND o.sampled_at<=$5 ORDER BY o.sampled_at,o.id LIMIT 100001`,[d.point_id,d.object_id,from,to,cutoff])).rows;if(samples.length>100000)throw new AppError(422,'METRIC_TOO_LARGE','样本超过单次计算上限，请缩短统计窗口');
 const result=compute(spec,samples.map(s=>({id:s.id,sampledAt:s.sampled_at.toISOString(),value:s.value,unit:s.unit,valid:s.quality==='valid'&&!s.conflicted&&s.canonical_id===s.id})),from,to,cutoff);
 if(samples.some(s=>s.origin==='history'&&s.received_at>new Date(to)))result.limitations.push('本结果包含窗口结束后的历史补传，只解释对应历史时段');let status=result.status;if(spec.species||spec.stage||spec.variety){const batch=(await c.query("SELECT * FROM production_batches b WHERE object_id=$1 AND verified AND started_at<=$2 AND(ended_at IS NULL OR ended_at>=$3) AND NOT EXISTS(SELECT 1 FROM production_batches n WHERE n.supersedes_id=b.id) ORDER BY started_at DESC LIMIT 1",[d.object_id,from,to])).rows[0];if(!batch||(spec.species&&batch.species!==spec.species)||(spec.stage&&batch.stage!==spec.stage)||(spec.variety&&batch.variety!==spec.variety)){status='incomparable';result.limitations.push('物种、品种或阶段无法证明适用，不能推算提前天数');}}
 const hash=payloadHash({definitionId:d.id,from,to,statisticsEnd:result.statisticsEnd,samples:samples.map(s=>({id:s.id,value:s.value,quality:s.quality,conflicted:s.conflicted,canonical:s.canonical_id}))});await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['metric-result:'+d.id+':'+from+':'+to]);const prior=(await c.query('SELECT * FROM metric_results WHERE definition_id=$1 AND window_start=$2 AND window_end=$3 AND input_hash=$4',[d.id,from,to,hash])).rows[0];if(prior)return prior;const version=Number((await c.query('SELECT COALESCE(max(version),0) AS n FROM metric_results WHERE definition_id=$1 AND window_start=$2 AND window_end=$3',[d.id,from,to])).rows[0].n)+1;
 return(await c.query('INSERT INTO metric_results(object_id,definition_id,definition_version,window_start,window_end,value,observed_value,unit,status,coverage,limitations,evidence_ids,input_hash,version) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *',[d.object_id,d.id,d.version,from,to,status==='usable'?result.value:null,result.observedValue,spec.unit,status,result.coverage,JSON.stringify(result.limitations),result.evidenceIds,hash,version])).rows[0];
}
export async function listAnalysis(c:PoolClient,a:Actor){const v=await visible(c,a,'metric');return {definitions:(await c.query('SELECT * FROM metric_definitions WHERE object_id=ANY($1::uuid[]) AND ($2::boolean=false OR id IN(SELECT resource_id FROM resource_grants WHERE user_id=$3 AND resource_type=\'definition\' AND revoked_at IS NULL AND expires_at>now())) ORDER BY name,version DESC LIMIT 200',[v.objects,a.role==='expert',a.id])).rows,items:(await c.query('SELECT * FROM metric_results WHERE object_id=ANY($1::uuid[]) AND ($2::uuid[] IS NULL OR id=ANY($2)) ORDER BY calculated_at DESC LIMIT 200',[v.objects,v.resources])).rows};}
