'use client';
import ResourceShare from '@/components/phase3/resource-share';
import {useEffect} from 'react';import ObjectWorkspace from '@/components/phase3/object-workspace';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';
type Row=Record<string,any>;const options=(pairs:[string,string][])=>pairs.map(([id,name])=>({id,name}));
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function Work({objectId}:{objectId:string}){
 const {data,error,reload}=useApi<Row>('/api/v1/agronomy/overview?objectId='+objectId);
 const pending=!!data&&[...data.crops,...data.spectral].some((r:Row)=>['queued','running'].includes(r.state));
 useEffect(()=>{if(!pending)return;const timer=setInterval(()=>void reload(),5000);return()=>clearInterval(timer);},[pending,reload]);
 if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取农情资料…</p>;
 const common={stableKey:true,onSaved:()=>void reload()},hidden=<input type="hidden" name="objectId" value={objectId}/>,media=data.media.map((r:Row)=>({id:r.id,name:r.name+' / '+r.mime})),devices=data.devices.map((r:Row)=>({id:r.id,name:r.name})),analyses=data.crops.map((r:Row)=>({id:r.id,name:r.state+' / '+r.created_at})),schedules=data.schedules.map((r:Row)=>({id:r.id,name:(r.enabled?'已启用':'已停用')+' / '+r.interval_minutes+'分钟'})),notices=data.notices.map((r:Row)=>({id:r.id,name:r.title+' / 版本'+r.version+' / '+r.state}));
 const evidence=<Field name="evidence" label="核实依据"/>;
 return <div className="stack"><p className="hint">每类最近100条；影像列表最多200项。先到<a href="/imagery">监控与航次</a>导入私有原件。</p><button className="secondary" onClick={()=>void reload()}>刷新分析进度</button>
 <details><summary>分析作物照片</summary><ActionForm path="/api/v1/agronomy/crops" {...common} booleans={['evaluationMode']}><Pick name="assetId" label="照片原件" options={media.filter((r:Row)=>!r.name.includes('image/tiff'))}/><Field name="flightId" label="关联航次（可选）" required={false}/><label><input type="checkbox" name="evaluationMode" disabled={!data.evaluationEnabled}/>运行本地候选模型实验{!data.evaluationEnabled&&'（部署开关未启用）'}</label></ActionForm><p>默认计算图像特征；绿色比例不是作物长势或产量。候选模型不自动派单、开设备或开具处方。</p></details>
 <section><h2>照片结果与人工修正</h2>{data.crops.length?data.crops.map((r:Row)=><article className="rule-card" key={r.id}><p>{r.state} · {r.captured_at??'采集时间未取得'} · {r.error_code??''}</p>{r.result&&<><p>绿色像素比例{(r.result.greenFraction*100).toFixed(1)}% · 分析尺寸{r.result.analysisSize.join('×')}</p>{r.result.candidates&&<StockTable rows={r.result.candidates} columns={[[ 'label','候选'],['score','模型匹配分数']]}/>} {r.result.limitations.map((s:string)=><p className="hint" key={s}>{s}</p>)}</>}</article>):<p className="empty-state">尚无照片分析。</p>}
 <ActionForm path="/api/v1/agronomy/labels" {...common} times={['observedAt']}><Pick name="analysisId" label="需要修正的图片分析" options={analyses}/><Pick name="label" label="现场判断" options={options([['canopy','作物冠层'],['lodging','倒伏'],['waterlogging','积水'],['bare','裸地'],['unknown','无法判断']])}/><Field name="observedAt" label="实际观察时间" type="datetime-local"/>{evidence}</ActionForm><StockTable rows={data.labels} columns={[[ 'label','人工判断'],['evidence','现场依据'],['observed_at','观察时刻']]}/><p className="hint">独立标注样本{data.evaluation.independentlyLabelled}，一致数量{data.evaluation.matches}。{data.evaluation.scope}。现场效果仍未签验。</p></section>
 <details><summary>定时抓图计划</summary><p>只使用已核只读摄像通道；接口关闭、资料未核或结果未知时会记录原因。</p><ActionForm path="/api/v1/agronomy/schedules" {...common} times={['nextAt']} numbers={['intervalMinutes']} booleans={['enabled','evaluationMode']}><Pick name="deviceId" label="已核摄像通道" options={devices}/><Field name="intervalMinutes" label="间隔分钟（15至10080）" type="number"/><Field name="nextAt" label="首次计划时刻" type="datetime-local"/><Field name="sourceRef" label="抓图范围与时段依据"/><label><input name="enabled" type="checkbox"/>启用此计划</label><label><input name="evaluationMode" type="checkbox" disabled={!data.evaluationEnabled}/>同时运行已启用的模型实验</label></ActionForm><ActionForm path="/api/v1/agronomy/schedule-toggle" {...common} booleans={['enabled']}><Pick name="id" label="抓图计划" options={schedules}/><label><input type="checkbox" name="enabled"/>保持启用（不勾选为停用）</label></ActionForm><StockTable rows={data.captures} columns={[[ 'window_at','计划窗口'],['state','抓图衔接'],['error_code','未完成原因']]}/></details>
 <details><summary>多光谱反射率产品与分区</summary><p>接收已拼接、已辐射校正、北向WGS84 GeoTIFF。原始DN只归档；波段索引从0开始。不同投影或校正比例须先在专业工具处理。</p><ActionForm path="/api/v1/agronomy/spectral" {...common} times={['capturedAt']} jsonFields={['rawAssetIds','bands','calibration','breaks']}><Pick name="assetId" label="反射率GeoTIFF" options={media.filter((r:Row)=>r.name.includes('image/tiff'))}/><label>对应原航片ID数组<textarea name="rawAssetIds" defaultValue="[]"/></label><Field name="flightId" label="来源航次（可选）" required={false}/><Field name="capturedAt" label="实际采集时间" type="datetime-local"/><Field name="sourceRef" label="来源链及未取得文件说明"/><Field name="processor" label="拼接与辐射校正工具、版本"/><Pick name="indexKind" label="指数类型" options={options([['NDVI','NDVI'],['NDRE','NDRE']])}/><label>已核波段映射<textarea name="bands" placeholder='{"red":0,"nir":1,"redEdge":2}' required/></label><label>已核反射率校正<textarea name="calibration" placeholder='{"state":"reflectance","scale":1,"offset":0,"evidence":"填写实际校正依据"}' required/></label><label>专业选择的指数分界点（最多4个）<textarea name="breaks" placeholder='[]' required/></label></ActionForm></details>
 <section><h2>多光谱成果</h2>{data.spectral.length?data.spectral.map((r:Row)=><article className="rule-card" key={r.id}><h3>{r.index_kind} · 版本{r.version}</h3><p>{r.state} · {r.error_code??''} · {r.source_ref}</p>{r.result&&<><p>有效像素{r.result.validPixels}，无数据{r.result.noDataPixels}；均值{Number(r.result.mean).toFixed(4)}。仅作为指数统计。</p><StockTable rows={r.result.zones} columns={[[ 'class','分区'],['count','像素数'],['fraction','有效像素比例']]}/>{r.preview_asset_id&&<img src={'/api/v1/media/'+r.preview_asset_id} alt="按已声明断点生成的指数分区预览" style={{maxWidth:'100%',maxHeight:350}}/>}{r.index_asset_id&&<p><a href={'/api/v1/media/'+r.index_asset_id}>下载带地理参考的指数GeoTIFF</a></p>}{r.result.limitations.map((s:string)=><p className="hint" key={s}>{s}</p>)}</>}</article>):<p className="empty-state">尚无指数产品。</p>}</section>
 <details><summary>农业通知与病虫害预报</summary><ActionForm path="/api/v1/agronomy/notices" {...common} times={['publishedAt','validFrom','validUntil']}>{hidden}<Field name="title" label="通知标题"/><Field name="agency" label="来源机构"/><Field name="sourceRef" label="原链接或文号"/><Field name="publishedAt" label="来源发布日期" type="datetime-local"/><Field name="validFrom" label="适用开始" type="datetime-local"/><Field name="validUntil" label="适用截止" type="datetime-local"/><Field name="crop" label="适用作物"/><Field name="region" label="适用区域"/><label>来源正文<textarea name="body" required/></label><Pick name="supersedesId" label="修订原通知（可选）" options={notices} required={false}/></ActionForm><ActionForm path="/api/v1/agronomy/notice-review" {...common}><Pick name="id" label="待核通知" options={notices}/><Pick name="action" label="通知审核动作" options={options([['approve','审核适用'],['withdraw','撤回']])}/>{evidence}</ActionForm><StockTable rows={data.notices} columns={[[ 'title','通知'],['agency','来源'],['state','审核状态'],['current','当前是否适用'],['valid_until','有效截止']]}/></details>
 <details><summary>流量或水量依据</summary><ActionForm path="/api/v1/agronomy/flows" {...common} times={['fromAt','toAt','validUntil']}>{hidden}<Field name="deviceId" label="关联设备（可选）" required={false}/><Field name="pointId" label="关联测点（可选）" required={false}/><Field name="fromAt" label="观测起点" type="datetime-local"/><Field name="toAt" label="观测终点" type="datetime-local"/><Field name="value" label="值（未知留空）" required={false}/><Pick name="unit" label="观测单位" options={options([['m3/s','流量m³/s'],['m3','时段水量m³']])}/><Pick name="sourceKind" label="流量来源" options={options([['measured','实测'],['calibrated','率定估算'],['model','模型推算']])}/><Field name="basisRef" label="实测、率定或模型依据"/><Field name="basisVersion" label="依据版本"/><Field name="applicability" label="适用范围"/><Field name="validUntil" label="依据有效截止" type="datetime-local"/></ActionForm><StockTable rows={data.flows} columns={[[ 'value','数值'],['unit','单位'],['source_kind','来源'],['basis_ref','依据'],['valid_until','有效截止']]}/><p className="hint">开度不能直接换算为流量。超过依据有效期的记录只作历史资料。</p></details>
 <ResourceShare objectId={objectId} resources={[...data.crops.map((r:Row)=>({id:r.id,type:'crop_analysis',name:'照片分析 / '+r.created_at,url:'/agronomy/crops/'+r.id})),...data.spectral.map((r:Row)=>({id:r.id,type:'spectral_product',name:r.index_kind+' / 版本'+r.version,url:'/agronomy/spectral/'+r.id})),...data.notices.map((r:Row)=>({id:r.id,type:'agronomy_notice',name:r.title+' / 版本'+r.version,url:'/agronomy/notices/'+r.id}))]}/>
 </div>;
}

