'use client';
import {useState} from 'react';import ObjectWorkspace from '@/components/phase3/object-workspace';import ResourceShare from '@/components/phase3/resource-share';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';import ExportButton from '@/components/phase4/export-button';import MultiPick from '@/components/phase4/multi-pick';
type Row=Record<string,any>;const opt=(ids:string[],names:string[])=>ids.map((id,i)=>({id,name:names[i]}));
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function ProtocolForm({objectId,objects,protocols,reload}:{objectId:string;objects:Row[];protocols:Row[];reload:()=>Promise<void>}){
 const [control,setControl]=useState<string[]>([]),[treatment,setTreatment]=useState<string[]>([]),empty={code:'',name:'',unit:'',method:'',expectedSamples:''},[metrics,setMetrics]=useState([empty]);
 const plots=[...control.map(id=>({objectId:id,group:'control',label:objects.find(r=>r.id===id)?.name??id})),...treatment.map(id=>({objectId:id,group:'treatment',label:objects.find(r=>r.id===id)?.name??id}))];
 return <ActionForm path="/api/v1/research/protocols" stableKey times={['startsAt','endsAt']} jsonFields={['plots','metrics']} onSaved={()=>{setControl([]);setTreatment([]);setMetrics([empty]);void reload();}}><input type="hidden" name="objectId" value={objectId}/><Field name="title" label="试验协议名称"/><Field name="question" label="要回答的研究问题"/><Field name="baseline" label="基线与原始依据"/><label>对照小区（可多选）<select multiple required value={control} onChange={e=>setControl(Array.from(e.target.selectedOptions,o=>o.value))}>{objects.map(o=><option value={o.id} key={o.id}>{o.name} · {o.code}</option>)}</select></label><label>处理小区（可多选）<select multiple required value={treatment} onChange={e=>setTreatment(Array.from(e.target.selectedOptions,o=>o.value))}>{objects.map(o=><option value={o.id} key={o.id}>{o.name} · {o.code}</option>)}</select></label><input type="hidden" name="plots" value={JSON.stringify(plots)}/><p className="hint">同一对象不能同时作为处理和对照。先在配置管理登记小区并取得授权；未知边界不用于面积推断。</p>
 {metrics.map((m,index)=><fieldset key={index}><legend>观察指标 {index+1}</legend>{[['code','指标代号（小写字母、数字、下划线）'],['name','指标名称'],['unit','指标单位'],['method','统一观测方法'],['expectedSamples','每小区计划观测条数']].map(([key,label])=><label key={key}>{label}<input required type={key==='expectedSamples'?'number':'text'} min={key==='expectedSamples'?1:undefined} value={m[key as keyof typeof m]} onChange={e=>setMetrics(old=>old.map((x,i)=>i===index?{...x,[key]:e.target.value}:x))}/></label>)}{metrics.length>1&&<button type="button" onClick={()=>setMetrics(old=>old.filter((_,i)=>i!==index))}>移除此指标</button>}</fieldset>)}<button type="button" disabled={metrics.length>=20} onClick={()=>setMetrics(old=>[...old,{...empty}])}>添加观察指标</button><input type="hidden" name="metrics" value={JSON.stringify(metrics.map(m=>({...m,expectedSamples:Number(m.expectedSamples)})))}/>
 <Field name="startsAt" label="试验窗口开始" type="datetime-local"/><Field name="endsAt" label="试验窗口结束" type="datetime-local"/><Field name="testingPlan" label="第三方检测机构、方法、范围与计划"/><Field name="stopRules" label="停止或调整条件"/><Field name="sourceRef" label="协议来源与版本依据"/><Pick name="supersedesId" label="修订原协议（可选）" options={protocols.map(r=>({id:r.id,name:r.title+' / 版本'+r.version}))} required={false}/></ActionForm>;
}
function Work({objectId}:{objectId:string}){
 const {data,error,reload}=useApi<Row>('/api/v1/research/overview?objectId='+objectId),[selected,setSelected]=useState(''),[metricCode,setMetricCode]=useState('');
 if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取科研资料…</p>;
 const active=data.protocols.find((p:Row)=>p.id===selected)??data.protocols[0],metric=active?.metrics.find((m:Row)=>m.code===metricCode)??active?.metrics[0],common={stableKey:true,onSaved:()=>void reload()},results=data.results.map((r:Row)=>({id:r.id,name:r.title+' / 版本'+r.version}));
 return <div className="stack"><p className="hint">协议和明细最多显示最近200条；新观测前须独立审核协议。固定结果保留当时输入，重新生成不会覆盖旧版本。</p><details><summary>建立试验协议与小区</summary><ProtocolForm objectId={objectId} objects={data.plots} protocols={data.protocols} reload={reload}/></details>
 <label>当前操作协议<select value={active?.id??''} onChange={e=>{setSelected(e.target.value);setMetricCode('');}}><option value="">请选择</option>{data.protocols.map((p:Row)=><option value={p.id} key={p.id}>{p.title} / 版本{p.version}</option>)}</select></label>
 {active&&<div key={active.id} className="stack"><details><summary>独立审核当前协议</summary><ActionForm path="/api/v1/research/reviews" {...common}><input type="hidden" name="id" value={active.id}/><Pick name="action" label="协议审核动作" options={opt(['approve','withdraw'],['独立核实通过','撤回协议'])}/><Field name="evidence" label="协议审核依据"/></ActionForm></details>
 <details><summary>登记观测或第三方报告</summary><label>本次观察指标<select value={metric?.code??''} onChange={e=>setMetricCode(e.target.value)}>{active.metrics.map((m:Row)=><option key={m.code} value={m.code}>{m.name} / {m.unit}</option>)}</select></label><ActionForm path="/api/v1/research/observations" {...common} times={['observedAt']} multiFields={['assetIds']}><input type="hidden" name="protocolId" value={active.id}/><input type="hidden" name="metric" value={metric.code}/><input type="hidden" name="method" value={metric.method}/><Pick name="plotObjectId" label="观测小区" options={active.plots.map((p:Row)=>({id:p.objectId,name:p.label+' / '+(p.group==='control'?'对照':'处理')}))}/><Field name="sampleKey" label="稳定观察记录号"/><p>统一方法：{metric.method}；单位：{metric.unit}。重复时点的独立记录请使用不同观察号。</p><Field name="value" label="观测值（未知留空，0需实测）" required={false}/><Field name="missingReason" label="缺测原因（未知值必填）" required={false}/><Field name="observedAt" label="实际观测时间" type="datetime-local"/><Pick name="kind" label="观测资料性质" options={opt(['field','lab_report'],['现场原始记录','第三方检测报告'])}/><Field name="agency" label="出具机构（报告必填）" required={false}/><Field name="reportRef" label="报告编号与版本（报告必填）" required={false}/><MultiPick name="assetIds" label="照片或报告原件（报告必选）" options={data.media}/><Pick name="supersedesId" label="更正原观察（可选）" options={data.observations.filter((r:Row)=>r.protocol_id===active.id&&r.current).map((r:Row)=>({id:r.id,name:r.sample_key+' / '+r.metric+' / '+r.observed_at}))} required={false}/><Field name="evidence" label="观测或更正原始依据"/></ActionForm></details>
 <details><summary>生成固定结果证据包</summary><ActionForm path="/api/v1/research/results" {...common}><input type="hidden" name="protocolId" value={active.id}/><Field name="title" label="结果证据包名称"/><Field name="claim" label="成果说明、缺口与限制"/><Pick name="claimLevel" label="成果证据性质" options={opt(['verifiable','official','self_reported'],['可核实','官方口径','自报'])}/><Field name="sourceRef" label="成果来源或正式口径依据"/></ActionForm></details></div>}
 <details><summary>独立审阅结果</summary><ActionForm path="/api/v1/research/result-reviews" {...common}><Pick name="id" label="待审结果版本" options={results}/><Pick name="action" label="成果审核动作" options={opt(['approve','withdraw'],['登记独立审阅通过','撤回审阅'])}/><Field name="evidence" label="成果审核依据与限制"/></ActionForm></details>
 <StockTable rows={data.protocols} columns={[[ 'title','协议'],['version','版本'],['starts_at','开始'],['ends_at','结束'],['id','经费关联用协议ID']]}/><StockTable rows={data.observations} columns={[[ 'sample_key','观察号'],['metric','指标'],['value','值'],['unit','单位'],['kind','资料性质'],['current','当前版本'],['missing_reason','缺口']]}/>
 {data.results.map((r:Row)=><p key={r.id}><a href={'/research/results/'+r.id}>{r.title} · 版本{r.version}</a> · {r.sourcesCurrent?'引用未更正':'已有更正或撤回，保留历史'} · 结果ID {r.id}</p>)}
 <section><h2>关联经费</h2><p>在<a href="/business">费用与补贴</a>登记费用，关联本协议或结果ID；费用和实际付款分别记录。</p>{data.expenses===null?<p>当前角色不展示经营明细。</p>:<StockTable rows={data.expenses} columns={[[ 'voucher','费用凭证'],['amount_cny','登记金额元'],['link_kind','关联类型'],['evidence','用途与依据']]}/>}</section>
 <ResourceShare objectId={objectId} resources={[...data.protocols.map((r:Row)=>({id:r.id,type:'research_protocol',name:r.title+' / 协议'+r.version,url:'/research/protocols/'+r.id})),...data.results.map((r:Row)=>({id:r.id,type:'research_result',name:r.title+' / 结果'+r.version,url:'/research/results/'+r.id}))]}/><ExportButton path={'/api/v1/research/export?objectId='+objectId} name="科研试验证据包"/></div>;
}
