import type {PoolClient} from 'pg';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {text,time} from '../../platform/validation';
import {uuid} from '../identity/common';
import {scope,visible,payloadHash,sameHash,stamp} from '../field/common';
import {enqueue} from '../jobs/repository';
export async function receiveCameraEvent(c:PoolClient,a:Actor,b:Record<string,unknown>){
 uuid(b.deviceId);const d=(await c.query('SELECT * FROM devices WHERE id=$1 FOR SHARE',[b.deviceId])).rows[0];if(!d||!d.verified)throw new AppError(422,'DEVICE_UNVERIFIED','请先核实设备、通道与对象映射');await scope(c,a,d.object_id,'record');
 const externalId=text(b.externalEventId,'厂商事件ID',200),contract=text(b.contractVersion,'消息契约版本',200),occurred=time(b.occurredAt),eventType=text(b.eventType,'厂家事件类型',100),payload={eventType,occurredAt:occurred,deviceId:d.id,contractVersion:contract};
 await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['camera:'+d.source_id+':'+externalId]);const hash=payloadHash(payload),prior=(await c.query('SELECT * FROM camera_events WHERE source_id=$1 AND external_event_id=$2',[d.source_id,externalId])).rows[0];if(prior){sameHash(prior.payload_hash,hash);return prior;}
 const alert=(await c.query("INSERT INTO alerts(object_id,correlation_key,kind,title,severity,opened_at,data_quality) VALUES($1,$2,'camera',$3,'warning',$4,'needs_human_review') RETURNING id",[d.object_id,'camera:'+d.source_id+':'+externalId,'监控事件待人工核查 · '+eventType,occurred])).rows[0];
 const row=(await c.query('INSERT INTO camera_events(object_id,device_id,source_id,external_event_id,contract_version,occurred_at,event_type,payload,payload_hash,alert_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[d.object_id,d.id,d.source_id,externalId,contract,occurred,eventType,payload,hash,alert.id])).rows[0];
 const event=(await c.query("INSERT INTO domain_events(event_type,version,object_id,occurred_at,recorded_at,payload) VALUES('alert.opened',1,$1,$2,now(),$3) RETURNING id",[d.object_id,occurred,{alertId:alert.id,cameraEventId:row.id}])).rows[0];
 await c.query("INSERT INTO alert_events(alert_id,event_type,occurred_at,note) VALUES($1,'opened',$2,'摄像头事件已保存，图片待获取；模型与人工判断独立')",[alert.id,occurred]);await enqueue(c,{kind:'notification.plan',businessKey:'notification:'+event.id,payload:{eventId:event.id,alertId:alert.id,change:'opened'},dueAt:stamp(),priority:90});return row;
}
export async function attachCameraImage(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);uuid(b.assetId);const e=(await c.query('SELECT * FROM camera_events WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!e)throw new AppError(404,'CAMERA_EVENT_NOT_FOUND','监控事件不存在');await scope(c,a,e.object_id,'record');const asset=(await c.query('SELECT * FROM media_assets WHERE id=$1',[b.assetId])).rows[0];if(asset?.object_id!==e.object_id||asset.ingest_state!=='complete'||!asset.mime.startsWith('image/'))throw new AppError(422,'CAMERA_IMAGE','请关联同一对象的完整图片');if(e.asset_id&&e.asset_id!==asset.id)throw new AppError(409,'CAMERA_IMAGE_CONFLICT','原事件已有图片，不静默替换');await c.query("UPDATE camera_events SET asset_id=$2,image_state='complete',image_error=NULL WHERE id=$1",[e.id,asset.id]);return {id:e.id,alertId:e.alert_id,imageState:'complete'};}
export async function listCameraEvents(c:PoolClient,a:Actor){const v=await visible(c,a,'camera_event');return {items:(await c.query('SELECT e.*,(SELECT r.image_state FROM ezviz_receipts r WHERE r.camera_event_id=e.id ORDER BY r.received_at DESC LIMIT 1) AS provider_image_state FROM camera_events e WHERE e.object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR e.id=ANY($2)) ORDER BY e.occurred_at DESC LIMIT 200',[v.objects,v.resources])).rows};}
export async function getCameraCapability(c:PoolClient,a:Actor,id:string,operation:string){uuid(id);const d=(await c.query('SELECT * FROM devices WHERE id=$1',[id])).rows[0];if(!d)throw new AppError(404,'DEVICE_NOT_FOUND','设备不存在');await scope(c,a,d.object_id,'read','camera',id);if(!['live','playback','capture','preset'].includes(operation))throw new AppError(400,'INVALID_CAMERA_OPERATION','监控入口无效');const contract=(await c.query('SELECT * FROM camera_capabilities WHERE device_id=$1 AND verified',[id])).rows[0];if(!contract||contract.capabilities[operation]!==true)throw new AppError(503,'CAMERA_CONTRACT_REQUIRED','此机型的监控能力和只读接入尚未验证；可继续使用厂家原入口');return {deviceId:id,operation,contractVersion:contract.contract_version,state:'adapter_not_connected'};}
