'use client';
import {useState} from 'react';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';
type Row=Record<string,any>;
const opt=(pairs:[string,string][])=>pairs.map(([id,name])=>({id,name}));
function Ids({name,label,items}:{name:string;label:string;items:Row[]}){const [ids,setIds]=useState<string[]>([]);return <><label>{label}<select multiple aria-label={label} value={ids} onChange={e=>setIds([...e.target.selectedOptions].map(o=>o.value))}>{items.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><input type="hidden" name={name} value={JSON.stringify(ids)}/></>;}
function PublicFields(){const [values,setValues]=useState<Row>({});const fields=[['productName','公开产品名称'],['batchLabel','公开批次标签'],['province','产区省'],['city','产区市'],['county','产区县区'],['harvestMonth','采收月份YYYY-MM'],['productionSummary','公开生产摘要'],['testSummary','公开检测摘要'],['limitations','查询范围与限制']];return <>{fields.map(([key,label])=><label key={key}>{label}<input required value={values[key]??''} maxLength={key.endsWith('Summary')||key==='limitations'?1000:120} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}<input type="hidden" name="content" value={JSON.stringify(values)}/></>;}
export default function TracePanel(){
 const refs=useApi<{items:Row[]}>('/api/v1/references?kind=object'),[selected,setSelected]=useState(''),id=selected||refs.data?.items[0]?.id||'';
 return <><label>当前质量对象<select aria-label="当前质量对象" value={id} onChange={e=>setSelected(e.target.value)}><option value="">请选择</option>{refs.data?.items.map(r=><option key={r.id} value={r.id}>{r.name} · {r.code}</option>)}</select></label>{refs.error&&<p role="alert">{refs.error}</p>}{id?<Quality key={id} objectId={id}/>:<p>先登记对象与批次并取得授权。</p>}</>;
}
function Quality({objectId}:{objectId:string}){
 const {data,error,reload}=useApi<Row>('/api/v1/traceability/overview?objectId='+objectId),[queryId,setQueryId]=useState('');
 if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;
 if(!data)return <p role="status">正在读取质量资料…</p>;
 const lots=data.lots.map((r:Row)=>({id:r.id,name:r.product+' / '+r.state+' / 版本'+r.version,code:r.code})),samples=data.samples.map((r:Row)=>({id:r.id,name:r.sample_code+' / '+r.stage})),reports=data.tests.map((r:Row)=>({id:r.id,name:r.report_ref+' / '+r.result})),credentials=data.credentials.map((r:Row)=>({id:r.id,name:r.subject+' / '+r.product+' / '+r.kind})),cases=data.cases.map((r:Row)=>({id:r.id,name:r.title+' / 待追回'+r.remaining})),cards=data.cards.map((r:Row)=>({id:r.id,name:r.content.productName+' / 版本'+r.version+' / '+r.state}));
 const common={stableKey:true,onSaved:()=>void reload()},evidence=<Field name="evidence" label="核实或操作依据"/>,lotPick=<Pick name="lotId" label="质量批次" options={lots}/>;
 return <div className="stack"><p className="hint">每类最多显示最近200条；库存操作见<a href="/inventory">库存与批次</a>。放行与客户内容须独立审核。</p>
 <StockTable rows={data.lots} columns={[[ 'product','产品'],['code','批号'],['state','审核状态'],['current_eligibility','当前可用性'],['version','当前版本']]}/>
 <details><summary>登记样品与检测</summary><h3>样品</h3><ActionForm path="/api/v1/traceability/samples" {...common} times={['sampledAt']}>{lotPick}<Field name="sampleCode" label="样品号"/><Pick name="stage" label="取样阶段" options={opt([['raw','原料/采收'],['finished','加工成品']])}/><Field name="sampledAt" label="实际取样时间" type="datetime-local"/><Field name="source" label="取样来源"/></ActionForm><h3>检测报告</h3><ActionForm path="/api/v1/traceability/tests" {...common} times={['testedAt','validUntil']}><Pick name="sampleId" label="检测样品" options={samples}/><Field name="method" label="检测方法"/><Pick name="result" label="检测结论" options={opt([['pass','通过'],['fail','未通过'],['inconclusive','无法判断']])}/><Field name="reportRef" label="报告编号及依据"/><Field name="testedAt" label="实际检测时间" type="datetime-local"/><Field name="validUntil" label="报告适用截止" type="datetime-local"/><Pick name="supersedesId" label="更正原检测（可选）" options={reports} required={false}/></ActionForm><StockTable rows={data.tests} columns={[[ 'report_ref','报告'],['method','方法'],['result','结论'],['tested_at','检测时间'],['valid_until','适用截止']]}/></details>
 <details><summary>凭证与资质</summary><ActionForm path="/api/v1/traceability/credentials" {...common} times={['validFrom','validUntil']} booleans={['verified']}>{lotPick}<Pick name="kind" label="凭证类型" options={opt([['certificate','合格证'],['certification','认证'],['brand','区域品牌授权']])}/><Field name="subject" label="授权或出证主体"/><Field name="product" label="凭证适用产品"/><Field name="validFrom" label="有效开始" type="datetime-local"/><Field name="validUntil" label="有效截止" type="datetime-local"/>{evidence}<label><input type="checkbox" name="verified"/>已实际核实主体、产品和期限（需要审核权限）</label></ActionForm><StockTable rows={data.credentials} columns={[[ 'subject','主体'],['product','适用产品'],['kind','类型'],['valid_until','到期'],['verified','是否核实']]}/></details>
 <details><summary>质量状态审核</summary><ActionForm path="/api/v1/traceability/decisions" {...common} numbers={['expectedVersion']} jsonFields={['testIds','credentialIds']}>{lotPick}<Field name="expectedVersion" label="当前批次版本" type="number"/><Pick name="toState" label="审核后的状态" options={opt([['pending','待检'],['available','放行可用'],['returned','退回'],['recalled','召回'],['blocked','暂禁使用']])}/><Ids name="testIds" label="放行依据报告（可多选）" items={reports}/><Ids name="credentialIds" label="本次审核凭证（可多选）" items={credentials}/>{evidence}</ActionForm><StockTable rows={data.decisions} columns={[[ 'from_state','原状态'],['to_state','审核状态'],['version','版本'],['evidence','依据'],['created_at','审核时刻']]}/></details>
 <details><summary>双向追查</summary><ActionForm path="/api/v1/traceability/queries" {...common}>{lotPick}<Pick name="direction" label="追查方向" options={opt([['forward','向前看产出与交接'],['backward','向后查来源与加工']])}/></ActionForm><label>历史查询版本<select aria-label="历史查询版本" value={queryId} onChange={e=>setQueryId(e.target.value)}><option value="">选择已保存查询</option>{data.queries.map((r:Row)=><option key={r.id} value={r.id}>{r.direction} · 版本{r.version} · {r.created_at}</option>)}</select></label>{queryId&&<TraceResult id={queryId}/>}</details>
 <details><summary>质量问题与处置</summary><ActionForm path="/api/v1/traceability/cases" {...common}>{lotPick}<Field name="title" label="问题说明"/><Field name="targetQuantity" label="本案影响数量（按批次单位）"/>{evidence}</ActionForm><ActionForm path="/api/v1/traceability/case-events" {...common} times={['occurredAt']}><Pick name="caseId" label="问题案件" options={cases}/><Pick name="action" label="处置动作" options={opt([['notice','记录实际通知凭证'],['recover','记录实际追回'],['dispose','记录实际处置'],['close','审核结案']])}/><Field name="quantity" label="本次数量（通知或结案留空）" required={false}/><Field name="occurredAt" label="实际处置时间" type="datetime-local"/>{evidence}</ActionForm><StockTable rows={data.cases} columns={[[ 'title','问题'],['target_quantity','影响量'],['recovered','已追回'],['disposed','已处置'],['remaining','待追回'],['state','状态']]}/></details>
 <details><summary>客户查询页</summary><p>先填写公开草稿，再由另一名审核人员发布。仅显示省市县和审核内容，不上传内部编号、精确位置或私有原件地址。</p><ActionForm path="/api/v1/traceability/cards" {...common} times={['validUntil']} jsonFields={['content','credentialIds']}>{lotPick}<PublicFields/><Ids name="credentialIds" label="公开摘要依据凭证（可多选）" items={credentials}/><Field name="validUntil" label="客户页有效截止" type="datetime-local"/></ActionForm><ActionForm path="/api/v1/traceability/card-review" {...common}><Pick name="id" label="客户页面版本" options={cards}/><Pick name="action" label="页面审核操作" options={opt([['approve','审核发布'],['revoke','撤回']])}/>{evidence}</ActionForm><ul>{data.cards.map((r:Row)=><li key={r.id}>{r.content.productName} · 版本{r.version} · {r.state} · <a href={'/trace/'+r.code} target="_blank" rel="noreferrer">查看客户页</a>（草稿/撤回/质量失效时不可访问）</li>)}</ul></details>
 </div>;
}
function TraceResult({id}:{id:string}){const {data,error,loading}=useApi<Row>('/api/v1/traceability/query?id='+id);if(error)return <p role="alert">{error}</p>;if(loading||!data)return <p>正在读取查询…</p>;const s=data.snapshot;
 async function download(){const response=await fetch('/api/v1/traceability/query-export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({queryId:id})});const output=await response.json();if(!response.ok){alert(output.message??'导出未完成');return;}const url=URL.createObjectURL(new Blob([JSON.stringify(output,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='批次追查版本'+data!.version+'.json';link.click();URL.revokeObjectURL(url);}
 return <section><h3>查询版本{data.version}</h3>{s.limitations.map((v:string)=><p className="hint" key={v}>{v}</p>)}<StockTable rows={s.nodes} columns={[[ 'code','批号'],['product','品名'],['state','状态'],['identities','身份映射']]}/><StockTable rows={s.edges} columns={[[ 'from','输入批次'],['to','输出批次'],['documentId','转换单据']]}/><StockTable rows={s.handoffs} columns={[[ 'direction','收发方向'],['party','主体'],['quantity','数量'],['occurred_at','时间']]}/><button onClick={()=>void download()}>下载本次权限内追查结果</button></section>;
}

