'use client';
import {useApi} from '@/components/platform/use-api';
import ActionForm from '@/components/platform/action-form';
import {Field,Pick,type Option} from '@/components/platform/fields';
type Task={id:string;object_id:string;title:string;instructions:string;version:number;state:string;kind:string;due_at:string|null;assignee_id:string|null;claimed_by:string|null};
const states:Record<string,string>={draft:'草稿',dispatched:'已人工派发',claimed:'已领取',reported:'已反馈待复核',reviewed:'已复核',cancelled:'已取消'};
export default function TasksPanel(){const data=useApi<{items:Task[];events:{task_id:string;action:string;payload:{note:string}}[];reports:{task_id:string;observation:string;judgment:string;action_taken:string}[];irrigation:{task_id:string;step:string;details:string}[]}>('/api/v1/tasks'),cal=useApi<{items:{id:string;name:string;version:number;approved_at:string|null;retired_at:string|null}[]}>('/api/v1/calendars'),objects=useApi<{items:Option[]}>('/api/v1/objects?limit=200'),me=useApi<{actor:{id:string};scopes:{action:string;objectIds:string[]}[]}>('/api/v1/me');const reload=()=>void data.reload();
 return <><p className="hint">草稿须有权人员确认执行人后派发；领取不等于到场，反馈和复核分别记录。</p>{data.error&&<p className="form-error">{data.error}</p>}<details><summary>新建任务草稿</summary><ActionForm path="/api/v1/tasks" stableKey onSaved={reload} label="保存任务草稿"><Pick name="objectId" label="任务对象" options={objects.data?.items??[]}/><Field name="title" label="任务标题"/><Field name="instructions" label="工作内容、依据和注意事项"/><Pick name="kind" label="任务类型" options={[{id:'inspection',name:'巡查'},{id:'farm_work',name:'农事作业'},{id:'irrigation',name:'人工灌排'}]}/></ActionForm></details>
 {data.data?.items.map(t=><section className="rule-card" key={t.id}><h2>{t.title} · {states[t.state]}</h2><p>{t.instructions}</p><p className="hint">版本{t.version}；{t.due_at?'截止 '+new Date(t.due_at).toLocaleString():'未设截止时间'}</p>{t.state==='draft'&&<ActionForm path="/api/v1/tasks" method="PATCH" stableKey numbers={['version']} booleans={['confirm']} onSaved={reload} label="确认并正式派发"><input type="hidden" name="id" value={t.id}/><input type="hidden" name="version" value={t.version}/><input type="hidden" name="action" value="dispatch"/><Field name="assigneeId" label="执行人账号ID（账号配置中核对）"/><Field name="note" label="派单依据"/><label><input name="confirm" type="checkbox" required/>已核对对象、内容和执行人，确认正式派发</label></ActionForm>}{t.state==='dispatched'&&t.assignee_id===me.data?.actor.id&&<TaskAction t={t} action="claim" label="领取任务" reload={reload}/>}{t.state==='claimed'&&t.claimed_by===me.data?.actor.id&&<><ActionForm path="/api/v1/tasks" method="PATCH" stableKey numbers={['version']} times={['occurredAt']} onSaved={reload} label="提交现场反馈"><input type="hidden" name="id" value={t.id}/><input type="hidden" name="version" value={t.version}/><input type="hidden" name="action" value="report"/><Field name="occurredAt" label="实际发生时间" type="datetime-local"/><Field name="observation" label="现场观测"/><Field name="judgment" label="人工判断（未知须说明）"/><Field name="actionTaken" label="实际动作或未执行原因"/><Field name="note" label="反馈说明"/></ActionForm><TaskAction t={t} action="handover" label="交班并解除领取" reload={reload}/></>}{t.state==='reported'&&<TaskAction t={t} action="review" label="专业复核" reload={reload}/>}
 {t.kind==='irrigation'&&<details><summary>人工灌排台账</summary><ul>{data.data!.irrigation.filter(x=>x.task_id===t.id).map((x,i)=><li key={i}>{x.step}：{x.details}</li>)}</ul><ActionForm path="/api/v1/irrigation" times={['occurredAt']} onSaved={reload} label="登记灌排步骤"><input type="hidden" name="taskId" value={t.id}/><Pick name="step" label="步骤" options={[{id:'application',name:'申请'},{id:'confirmation',name:'人工确认'},{id:'execution',name:'实际执行'},{id:'result',name:'结果'},{id:'not_executed',name:'未执行及原因'}]}/><Field name="occurredAt" label="发生时间" type="datetime-local"/><Field name="details" label="现场记录"/></ActionForm></details>}
 <ul>{data.data!.reports.filter(r=>r.task_id===t.id).map((r,i)=><li key={i}>观测：{r.observation}；判断：{r.judgment}；动作：{r.action_taken}</li>)}{data.data!.events.filter(r=>r.task_id===t.id).map((r,i)=><li key={'e'+i}>{r.action}：{r.payload.note}</li>)}</ul></section>)}
 <h2>农事日历版本</h2>{cal.error&&<p className="form-error">{cal.error}</p>}{cal.data?.items.map(v=><section className="rule-card" key={v.id}><h2>{v.name} · 版本{v.version}</h2><p>{v.retired_at?'已撤回':v.approved_at?'已专业审核':'草稿，不用于分析'}</p>{!v.retired_at&&<ActionForm path="/api/v1/calendars" method="PATCH" booleans={['retire']} onSaved={()=>void cal.reload()} label="保存日历审核"><input type="hidden" name="id" value={v.id}/><label><input type="checkbox" name="retire"/>撤回此版本（不勾选为审核通过）</label></ActionForm>}</section>)}<details><summary>录入专业日历新版本</summary><ActionForm path="/api/v1/calendars" jsonFields={['items']} times={['effectiveFrom']} onSaved={()=>void cal.reload()}><Pick name="objectId" label="日历对象" options={objects.data?.items??[]}/><Field name="name" label="日历名称"/><Field name="species" label="物种"/><Field name="variety" label="品种" required={false}/><Field name="stage" label="生产阶段"/><Field name="sourceRef" label="专业规程或专家依据"/><Field name="effectiveFrom" label="生效时间" type="datetime-local"/><label>事项JSON（startDay、endDay、title、instructions）<textarea name="items" required rows={5}/></label></ActionForm></details></>;
}
function TaskAction({t,action,label,reload}:{t:Task;action:string;label:string;reload:()=>void}){return <ActionForm path="/api/v1/tasks" method="PATCH" stableKey numbers={['version']} onSaved={reload} label={label}><input type="hidden" name="id" value={t.id}/><input type="hidden" name="version" value={t.version}/><input type="hidden" name="action" value={action}/><Field name="note" label={label+'依据'}/></ActionForm>;}
