'use client';
import ResourceShare from '@/components/phase3/resource-share';
import {useState} from 'react';
import ActionForm from '@/components/platform/action-form';
import {Field,Pick} from '@/components/platform/fields';
import {useApi} from '@/components/platform/use-api';
type Row=Record<string,any>;
const choices=(items:string[])=>items.map(id=>({id,name:({input:'投入品',harvest:'采收',processed:'加工品',kg:'千克',L:'升',piece:'件',as_is:'原样',wet:'湿基',dry:'干基',receipt:'入库',issue:'领用',transfer:'调拨',return:'退货',downgrade:'降级',adjust:'盘点差异',reverse:'冲销',dispatch:'发货',in:'入/增加',out:'出/减少',add:'装入',remove:'拆出'} as Row)[id]??id}));
export function StockTable({rows,columns}:{rows:Row[];columns:[string,string][]}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('');
 const labels:Record<string,string>={pending:'待检',available:'已审核可用',returned:'退回',recalled:'召回',blocked:'受限/依赖未就绪',draft:'草稿',approved:'已审核',withdrawn:'已撤回',revoked:'已撤回',queued:'排队',running:'处理中',complete:'已完成',failed:'未完成',unknown:'未知',open:'未结案',closed:'已结案',receipt:'收货/入库',dispatch:'发货',harvest:'采收',issue:'领用',transfer:'调拨',return:'退货',adjust:'盘点差异',reverse:'冲销',transformation:'加工转换',pass:'通过',fail:'未通过',inconclusive:'无法判断',measured:'实测',calibrated:'率定估算',model:'模型推算',canopy:'作物冠层',lodging:'倒伏候选',waterlogging:'积水候选',bare:'裸地',request:'申请',device_received:'设备收到',electrical:'电气动作',mechanical:'机械到位',effect:'实际效果',observed:'已观测',not_observed:'未观测到',platform_record:'平台登记',field_observation:'现场观测',vendor_receipt:'外部设备回执',allowed:'许可已核',denied:'禁止',remote:'远程',manual:'手动',active:'保护生效',clear:'已核未触发'};
 function value(r:Row,k:string){const v=r[k];if(v===null||v===undefined)return '未登记';if(typeof v==='boolean')return v?'是':'否';if(typeof v==='object')return JSON.stringify(v);return labels[String(v)]??String(v);}
 const shown=rows.filter(r=>columns.some(([k])=>value(r,k).toLowerCase().includes(query.toLowerCase())));
 if(sort)shown.sort((a,b)=>value(a,sort).localeCompare(value(b,sort),'zh-CN',{numeric:true}));
 return rows.length?<div className="data-list"><div className="list-toolbar"><label>筛选当前记录<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>排序字段<select value={sort} onChange={e=>setSort(e.target.value)}><option value="">原始顺序</option>{columns.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><span>{shown.length}/{rows.length}条</span></div><div className="table-wrap"><table><thead><tr>{columns.map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{shown.map((r,i)=><tr key={r.id??i}>{columns.map(([k,l])=><td key={k} data-label={l}>{value(r,k)}</td>)}</tr>)}</tbody></table></div></div>:<p className="empty-state">当前没有记录。</p>;
}

export default function InventoryPanel(){
 const refs=useApi<{items:Row[]}>('/api/v1/references?kind=object'),[selected,setSelected]=useState('');
 const objectId=selected||refs.data?.items[0]?.id||'';
 return <><label>当前库存对象<select value={objectId} onChange={e=>setSelected(e.target.value)}><option value="">请选择对象</option>{refs.data?.items.map(r=><option key={r.id} value={r.id}>{r.name} · {r.code}</option>)}</select></label>{refs.error&&<p role="alert">{refs.error}</p>}{objectId?<ObjectStock key={objectId} objectId={objectId}/>:<p>先在配置管理登记对象并取得授权。</p>}</>;
}
function ObjectStock({objectId}:{objectId:string}){
 const {data,error,loading,reload}=useApi<Row>('/api/v1/inventory/overview?objectId='+objectId),[kind,setKind]=useState('receipt'),[exportError,setExportError]=useState('');
 if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;
 if(!data)return <p role="status">正在读取库存…</p>;
 const lots=data.lots.map((r:Row)=>({id:r.id,name:r.product+' / '+r.unit+' / '+r.basis,code:r.code})),locations=data.locations.map((r:Row)=>({id:r.id,name:r.name,code:r.code})),docs=data.documents.map((r:Row)=>({id:r.id,name:r.kind+' / '+r.evidence,code:r.id.slice(0,8)}));
 const hidden=<input type="hidden" name="objectId" value={objectId}/>,at=<Field name="occurredAt" label="实际发生时间" type="datetime-local"/>,evidence=<Field name="evidence" label="操作依据"/>;
 const common={stableKey:true,onSaved:()=>void reload()};
 async function download(){setExportError('');try{const r=await fetch('/api/v1/inventory/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({objectId})}),body=await r.json();if(!r.ok)throw Error(body.message);const url=URL.createObjectURL(new Blob([JSON.stringify(body,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='库存批次导出.json';a.click();URL.revokeObjectURL(url);}catch(e){setExportError(e instanceof Error?e.message:'导出失败');}}
 return <div className="stack">{loading&&<p role="status">正在刷新…</p>}<p className="hint">每类最多显示最近200条。kg、L、件及干湿口径分别核算；缺资料不会自动填0。</p>
 <section><h2>当前仓位余额</h2><StockTable rows={data.balances} columns={[[ 'product','品名'],['code','批号'],['location_name','仓位'],['quantity','数量'],['unit','单位'],['basis','口径']]}/></section>
 <details><summary>登记仓位</summary><ActionForm path="/api/v1/inventory/locations" {...common}>{hidden}<Field name="code" label="仓位编号"/><Field name="name" label="仓位名称"/></ActionForm></details>
 <details><summary>登记批次</summary><ActionForm path="/api/v1/inventory/lots" {...common} jsonFields={['identities']}>{hidden}<Field name="code" label="全局库存批号"/><Field name="product" label="品名"/><Pick name="kind" label="批次类型" options={choices(['input','harvest','processed'])}/><Pick name="unit" label="库存单位" options={choices(['kg','L','piece'])}/><Pick name="basis" label="数量口径" options={choices(['as_is','wet','dry'])}/><Field name="productionBatchId" label="生产批次编号（可选）" required={false}/><Field name="source" label="来源依据"/><label>其他批号映射（可选）<textarea name="identities" defaultValue='{}'/></label></ActionForm></details>
 <details><summary>库存操作</summary><ActionForm path="/api/v1/inventory/movements" {...common} times={['occurredAt']}>{hidden}<label>库存动作<select name="kind" aria-label="库存动作" value={kind} onChange={e=>setKind(e.target.value)}>{choices(['receipt','harvest','issue','transfer','return','downgrade','adjust','reverse']).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>{kind==='reverse'?<Pick name="reversesId" label="待冲销单据" options={docs}/>:<><Pick name="lotId" label="库存批次" options={lots}/><Pick name="locationId" label="当前仓位" options={locations}/><Field name="quantity" label="实际数量"/>{kind==='transfer'&&<Pick name="toLocationId" label="目标仓位" options={locations}/>} {kind==='downgrade'&&<Pick name="targetLotId" label="降级后待检批次" options={lots}/>} {['return','adjust'].includes(kind)&&<Pick name="direction" label="数量方向" options={choices(['in','out'])}/>}</>}{at}{evidence}<Field name="reason" label="差异、降级或冲销原因" required={false}/><Field name="grossWeight" label="毛重kg（未知留空）" required={false}/><Field name="netWeight" label="净重kg（未知留空）" required={false}/><Field name="count" label="件数（未知留空）" required={false}/><Field name="moisture" label="含水率百分比（未知留空）" required={false}/></ActionForm></details>
 <details><summary>采购凭证</summary><ActionForm path="/api/v1/inventory/purchases" {...common} times={['occurredAt']}><Pick name="lotId" label="投入品批次" options={lots}/><Field name="supplier" label="供应主体"/><Field name="voucher" label="采购凭证号与依据"/><Field name="quantity" label="采购数量"/>{at}</ActionForm><StockTable rows={data.purchases} columns={[[ 'supplier','供应方'],['voucher','凭证'],['quantity','采购量'],['occurred_at','发生时间']]}/></details>
 <details><summary>实际施用</summary><ActionForm path="/api/v1/inventory/applications" {...common} times={['occurredAt']}><Pick name="lotId" label="施用批次" options={lots}/><Pick name="issueDocumentId" label="领用单" options={docs.filter((r:Row)=>r.name.startsWith('issue'))}/><Field name="quantity" label="实际施用量"/><Field name="farmRecordId" label="关联农事记录（可选）" required={false}/>{at}{evidence}</ActionForm><StockTable rows={data.applications} columns={[[ 'quantity','施用量'],['evidence','依据'],['occurred_at','发生时间']]}/></details>
 <details><summary>采收加工转换</summary><p>先登记待检输出批次；输入输出行填写批次、仓位和数量。不同口径或非零差额须审核权限和计量依据。</p><ActionForm path="/api/v1/inventory/transformations" {...common} times={['occurredAt']} jsonFields={['inputs','outputs']}>{hidden}<input type="hidden" name="kind" value="processing"/><Field name="code" label="长期转换编号"/><label>输入行<textarea name="inputs" required placeholder='[{"lotId":"批次ID","locationId":"仓位ID","quantity":"10"}]'/></label><label>输出行<textarea name="outputs" required placeholder='[{"lotId":"新批次ID","locationId":"仓位ID","quantity":"9"}]'/></label>{at}{evidence}<Field name="reason" label="损耗、计量或口径差异依据" required={false}/></ActionForm></details>
 <details><summary>装箱与拆分</summary><ActionForm path="/api/v1/inventory/packages" {...common} times={['occurredAt']}>{hidden}<Field name="code" label="物流包装码"/><Pick name="lotId" label="包装批次" options={lots}/><Pick name="action" label="包装动作" options={choices(['add','remove'])}/><Field name="quantity" label="本次装拆数量"/>{at}{evidence}</ActionForm><StockTable rows={data.packageEvents} columns={[[ 'package_id','包装记录'],['action','动作'],['quantity','数量'],['evidence','依据']]}/></details>
 <details><summary>发货与收货确认</summary><h3>记录发货</h3><ActionForm path="/api/v1/inventory/handoffs" {...common} times={['occurredAt']}><input type="hidden" name="direction" value="dispatch"/><Pick name="lotId" label="发货批次" options={lots}/><Pick name="locationId" label="发货仓位" options={locations}/><Field name="party" label="发货主体"/><Field name="quantity" label="发货数量"/>{at}{evidence}</ActionForm><h3>记录实际签收</h3><ActionForm path="/api/v1/inventory/handoffs" {...common} times={['occurredAt']}><input type="hidden" name="direction" value="receipt"/><Pick name="dispatchId" label="原发货记录" options={data.handoffs.filter((r:Row)=>r.direction==='dispatch').map((r:Row)=>({id:r.id,name:r.party+' / '+r.quantity+' / '+r.occurred_at}))}/><Field name="party" label="收货主体"/><Field name="quantity" label="本次实收量"/>{at}{evidence}</ActionForm><StockTable rows={data.handoffs} columns={[[ 'direction','方向'],['party','主体'],['quantity','数量'],['occurred_at','实际时间'],['evidence','依据']]}/></details>
 <details open><summary>批次与单据</summary><StockTable rows={data.lots} columns={[[ 'code','批号'],['product','品名'],['state','审核状态'],['current_eligibility','当前可用性'],['unit','单位'],['basis','口径'],['id','导入用批次ID']]}/><StockTable rows={data.locations} columns={[[ 'name','仓位'],['id','导入用仓位ID']]}/><StockTable rows={data.documents} columns={[[ 'kind','动作'],['occurred_at','发生时间'],['evidence','依据'],['metadata','差异与数量说明']]}/></details>
 <ResourceShare objectId={objectId} resources={data.lots.map((r:Row)=>({id:r.id,type:'stock_lot',name:r.product+' / '+r.code,url:'/inventory/lots/'+r.id}))}/><button onClick={()=>void download()}>导出当前对象库存与关系</button>{exportError&&<p role="alert">{exportError}</p>}</div>;
}

