'use client';
import {useState,type FormEvent} from 'react';import ObjectWorkspace from '@/components/phase3/object-workspace';import ActionForm from '@/components/platform/action-form';import {Field,Pick} from '@/components/platform/fields';import {useApi} from '@/components/platform/use-api';import {StockTable} from '../inventory/panel';import ExportButton from '@/components/phase4/export-button';
type Row=Record<string,any>;const kinds=[['generation_kwh','累计发电kWh'],['consumption_kwh','累计用电kWh'],['charge_kwh','累计充电kWh'],['discharge_kwh','累计放电kWh'],['power_kw','功率kW'],['soc_pct','电量SOC%'],['soh_pct','健康度SOH%']].map(([id,name])=>({id,name}));
export default function Panel(){return <ObjectWorkspace>{id=><Work objectId={id}/>}</ObjectWorkspace>;}
function Work({objectId}:{objectId:string}){
 const {data,error,reload}=useApi<Row>('/api/v1/energy/overview?objectId='+objectId),[summary,setSummary]=useState<Row|null>(null),[problem,setProblem]=useState('');
 if(error)return <><p role="alert">{error}</p><button onClick={()=>void reload()}>重试读取</button></>;if(!data)return <p>正在读取能源资料…</p>;
 const common={stableKey:true,onSaved:()=>void reload()},hidden=<input type="hidden" name="objectId" value={objectId}/>,meters=data.meters.map((r:Row)=>({id:r.id,name:r.name+(r.verified?' / 已核实':' / 未核实')}));
 async function calculate(e:FormEvent<HTMLFormElement>){e.preventDefault();setProblem('');setSummary(null);try{const b=Object.fromEntries(new FormData(e.currentTarget));for(const name of ['fromAt','toAt'])b[name]=new Date(String(b[name])).toISOString();const r=await fetch('/api/v1/energy/summary?'+new URLSearchParams(b as Record<string,string>)),d=await r.json();if(!r.ok)throw Error(d.message);setSummary(d);}catch(err){setProblem(err instanceof Error?err.message:'计算未完成');}}
 return <div className="stack"><p className="hint">每类显示最近200条。{data.unitNote}</p>
 <details><summary>登记能源计量档案</summary><ActionForm path="/api/v1/energy/meters" {...common} numbers={['maxGapSeconds']}>{hidden}<Pick name="deviceId" label="物理设备" options={data.devices}/><Field name="name" label="档案名称"/><Pick name="purpose" label="能源用途" options={[{id:'generation',name:'发电'},{id:'load',name:'用电负载'},{id:'storage',name:'储能'}]}/><Field name="capacityKwh" label="额定容量kWh（未知留空）" required={false}/><Field name="maxGapSeconds" label="已核连续观测最大间隔秒" type="number"/><Pick name="oxygenPointId" label="溶解氧等环境参考测点（可选，按契约核实）" options={data.points.map((p:Row)=>({id:p.id,name:p.name+' / '+p.metric+' / '+p.unit}))} required={false}/><Pick name="supersedesId" label="修订原档案（可选）" options={meters} required={false}/><Field name="sourceRef" label="型号、计量单位和倍率换算依据"/></ActionForm></details>
 <details><summary>独立核实能源档案</summary><ActionForm path="/api/v1/energy/reviews" {...common}><Pick name="id" label="待核实档案" options={meters}/><Pick name="action" label="核实动作" options={[{id:'approve',name:'独立核实通过'},{id:'withdraw',name:'撤回核实'}]}/><Field name="evidence" label="核实依据"/></ActionForm></details>
 <details><summary>记录能源观测</summary><ActionForm path="/api/v1/energy/readings" {...common} times={['observedAt']} booleans={['reset']}><Pick name="meterId" label="能源档案" options={meters}/><Pick name="metric" label="指标与单位" options={kinds}/><Field name="value" label="已核换算后的观测值（未知留空）" required={false}/><Field name="observedAt" label="实际观测时间" type="datetime-local"/><Pick name="quality" label="数据质量" options={[{id:'valid',name:'有效'},{id:'suspect',name:'可疑'},{id:'missing',name:'缺测'}]}/><Pick name="sourceKind" label="来源方式" options={[{id:'manual',name:'人工记录'},{id:'file',name:'文件抄录'}]}/><Pick name="operatingState" label="运行状态" options={['charging','discharging','idle','unknown'].map((id,i)=>({id,name:['充电','放电','闲置','未知'][i]}))}/><Field name="alarmNote" label="异常状态说明（可留空）" required={false}/><label><input name="reset" type="checkbox"/>本时点发生计量复位</label><Pick name="supersedesId" label="更正原观测（可选）" options={data.readings.filter((r:Row)=>r.current).map((r:Row)=>({id:r.id,name:r.metric+' / '+r.observed_at+' / '+(r.value??'未知')}))} required={false}/><Field name="evidence" label="原始值、单位换算与观测依据"/></ActionForm></details>
 <details><summary>核算累计电量区间</summary><form className="business-form" onSubmit={calculate}><Pick name="meterId" label="统计档案" options={meters}/><Pick name="metric" label="累计指标" options={kinds.slice(0,4)}/><Field name="fromAt" label="区间开始" type="datetime-local"/><Field name="toAt" label="区间结束" type="datetime-local"/><button>计算区间差分</button></form>{problem&&<p role="alert">{problem}</p>}{summary&&<><p>完整区间电量：{summary.energyKwh??'暂不能判断'} kWh；已知连续片段：{summary.knownSegmentKwh??'未知'} kWh。</p>{summary.gaps.map((g:string)=><p key={g}>{g}</p>)}<p>算法：{summary.algorithmVersion}；输入{summary.inputIds.length}条。</p><p>{summary.referenceGap}</p>{summary.environmentalReference&&<><p>环境参考：{summary.environmentalReference.point.name} / {summary.environmentalReference.point.unit}；状态：{summary.environmentalReference.dataState}</p><StockTable rows={summary.environmentalReference.items} columns={[['sampled_at','采样时间'],['value','原观测值'],['unit','单位'],['quality','质量']]}/></>}</>}</details>
 <StockTable rows={data.meters} columns={[[ 'name','档案'],['purpose','用途'],['verified','当前核实'],['source_ref','计量依据']]}/><StockTable rows={data.readings} columns={[[ 'metric','指标'],['value','值'],['quality','质量'],['observed_at','发生时间'],['current','当前版本'],['evidence','依据']]}/><ExportButton path={'/api/v1/energy/export?objectId='+objectId} name="能源记录"/></div>;
}
