import {posix} from 'node:path';
import {AppError} from '../../platform/error';

export const TERRAIN_LIMITS={files:1000,totalBytes:2147483648,tileBytes:67108864,jsonBytes:2097152,totalJsonBytes:16777216,depth:64};
const bad=(code:string,message:string)=>new AppError(422,code,message);
export function resourcePath(value:unknown){if(typeof value!=='string'||!value||value.length>400||value.includes('\\')||/[\x00-\x1f?#:%]/.test(value)||value.startsWith('/')||value.split('/').some(s=>!s||s==='.'||s==='..'))throw bad('TERRAIN_PATH','模型包路径必须是目录内明确相对文件');return value;}
export function resolveResource(from:string,uri:string){
 if(uri.startsWith('data:')){if(!/^data:(application\/octet-stream|image\/(png|jpeg|webp));base64,[A-Za-z0-9+/=]+$/.test(uri))throw bad('TERRAIN_DATA_URI','只支持嵌入的二进制或已核位图');return null;}
 try{uri=decodeURIComponent(uri);}catch{throw bad('TERRAIN_PATH','资源URI编码无效');}
 if(/^[a-z][a-z0-9+.-]*:/i.test(uri)||uri.startsWith('//')||uri.startsWith('/'))throw bad('TERRAIN_EXTERNAL_RESOURCE','模型不能引用外部地址或绕过平台授权');
 if(/[\\\x00-\x1f?#%]/.test(uri))throw bad('TERRAIN_PATH','资源路径含未允许字符');const resolved=posix.normalize(posix.join(posix.dirname(from),uri));return resourcePath(resolved);
}
const extensions=new Set(['CESIUM_RTC','KHR_draco_mesh_compression','KHR_mesh_quantization','KHR_materials_unlit','KHR_texture_transform','KHR_texture_basisu','EXT_meshopt_compression','EXT_mesh_features','EXT_structural_metadata']);
function jsonBody(bytes:Buffer){if(bytes.length>TERRAIN_LIMITS.jsonBytes)throw bad('TERRAIN_JSON_LIMIT','单份模型JSON超过2MiB');try{const data=JSON.parse(bytes.toString('utf8'));if(!data||typeof data!=='object'||Array.isArray(data))throw Error();return data;}catch(e){throw e instanceof AppError?e:bad('TERRAIN_JSON','模型JSON不完整');}}
function inspectJson(data:any,path:string){const references:string[]=[];let nodes=0;const walk=(v:any,depth:number)=>{if(depth>TERRAIN_LIMITS.depth||++nodes>100000)throw bad('TERRAIN_COMPLEXITY','模型JSON层级或节点超限');if(!v||typeof v!=='object')return;if(v.transform&&(!Array.isArray(v.transform)||v.transform.length!==16||v.transform.some((n:unknown)=>typeof n!=='number'||!Number.isFinite(n)||Math.abs(n)>1e9)))throw bad('TERRAIN_TRANSFORM','模型变换矩阵无效');if(v.boundingVolume){const b=v.boundingVolume,keys=['box','sphere','region'].filter(k=>b[k]!==undefined);if(keys.length!==1)throw bad('TERRAIN_BOUNDS','模型包围体不明确');const k=keys[0],n=b[k];if(!Array.isArray(n)||n.length!==({box:12,sphere:4,region:6} as Record<string,number>)[k]||n.some((x:unknown)=>typeof x!=='number'||!Number.isFinite(x)||Math.abs(x)>1e9)||k==='sphere'&&n[3]<=0||k==='region'&&(Math.abs(n[0])>Math.PI||Math.abs(n[2])>Math.PI||Math.abs(n[1])>Math.PI/2||Math.abs(n[3])>Math.PI/2||n[1]>=n[3]||n[4]>n[5]))throw bad('TERRAIN_BOUNDS','模型包围体维度、范围或数值无效');}if(v.extensions&&Object.keys(v.extensions).some(k=>!extensions.has(k)))throw bad('TERRAIN_EXTENSION','模型使用了未核实扩展');if(v.implicitTiling||v.extensions?.['3DTILES_implicit_tiling'])throw bad('TERRAIN_FORMAT','首版需显式分块，请在原加工工具转换隐式分块');for(const field of ['extensionsRequired','extensionsUsed'])if(v[field]){if(!Array.isArray(v[field])||v[field].some((s:unknown)=>typeof s!=='string'||!extensions.has(s)))throw bad('TERRAIN_EXTENSION','模型扩展未经本期核实，请转换为受支持格式');}for(const [key,x]of Object.entries(v)){if(['accesstoken','refreshtoken','apikey','clientsecret','secretkey','authorization','password'].includes(key.toLowerCase().replace(/[_-]/g,'')))throw bad('TERRAIN_CREDENTIAL','模型元数据含传输凭据，不能作为场景资源发布');if(/(?:uri|url)$/i.test(key)&&typeof x==='string'){const target=resolveResource(path,x);if(target)references.push(target);}else if(x&&typeof x==='object')walk(x,depth+1);}};walk(data,0);return references;}
function glb(bytes:Buffer,path:string){if(bytes.length<20||bytes.toString('ascii',0,4)!=='glTF'||bytes.readUInt32LE(4)!==2||bytes.readUInt32LE(8)!==bytes.length)throw bad('TERRAIN_GLB','GLB头部/版本/长度不符');let offset=12,json:any;for(let part=0;offset<bytes.length;part++){if(offset+8>bytes.length)throw bad('TERRAIN_GLB','GLB分块不完整');const length=bytes.readUInt32LE(offset),type=bytes.readUInt32LE(offset+4);if(offset+8+length>bytes.length||length%4)throw bad('TERRAIN_GLB','GLB分块长度无效');if(part===0){if(type!==0x4e4f534a)throw bad('TERRAIN_GLB','GLB第一块必须是JSON');json=jsonBody(bytes.subarray(offset+8,offset+8+length));}offset+=8+length;}if(json?.asset?.version!=='2.0')throw bad('TERRAIN_GLB','只支持glTF2');return {references:inspectJson(json,path),jsonBytes:Buffer.byteLength(JSON.stringify(json))};}
export function inspectResource(path:string,bytes:Buffer){
 resourcePath(path);if(!bytes.length||bytes.length>TERRAIN_LIMITS.tileBytes)throw bad('TERRAIN_FILE_LIMIT','单个瓦片或资源须在64MiB以内');
 const ext=posix.extname(path).toLowerCase();let references:string[]=[],jsonBytes=0,isTileset=false;
 if(ext==='.json'||ext==='.gltf'){const j=jsonBody(bytes);isTileset=!!j.root;if(isTileset){if(!['1.0','1.1'].includes(j.asset?.version)||!j.root.boundingVolume||!Number.isFinite(j.geometricError)||j.geometricError<=0)throw bad('TERRAIN_TILESET','tileset版本、包围体或顶层LOD误差无效；顶层LOD误差须大于零，不是测量精度');}else if(ext==='.gltf'&&j.asset?.version!=='2.0')throw bad('TERRAIN_GLTF','只支持glTF2');references=inspectJson(j,path);jsonBytes=bytes.length;}
 else if(ext==='.glb'){const r=glb(bytes,path);references=r.references;jsonBytes=r.jsonBytes;}
 else if(ext==='.b3dm'){if(bytes.length<28||bytes.toString('ascii',0,4)!=='b3dm'||bytes.readUInt32LE(4)!==1||bytes.readUInt32LE(8)!==bytes.length)throw bad('TERRAIN_B3DM','b3dm头部/版本/长度不符');const a=bytes.readUInt32LE(12),b=bytes.readUInt32LE(16),c=bytes.readUInt32LE(20),d=bytes.readUInt32LE(24),start=28+a+b+c+d;if(start>=bytes.length)throw bad('TERRAIN_B3DM','b3dm内容不完整');if(a){references.push(...inspectJson(jsonBody(bytes.subarray(28,28+a)),path));jsonBytes+=a;}if(c){references.push(...inspectJson(jsonBody(bytes.subarray(28+a+b,28+a+b+c)),path));jsonBytes+=c;}const r=glb(bytes.subarray(start),path);references.push(...r.references);jsonBytes+=r.jsonBytes;}
 else if(!['.bin','.png','.jpg','.jpeg','.webp','.ktx2'].includes(ext))throw bad('TERRAIN_FORMAT','不支持此模型资源格式，请在原加工工具转换');
 return {path,references:[...new Set(references)],jsonBytes,isTileset};
}
export function checkGraph(entries:ReturnType<typeof inspectResource>[],rootPath:string){
 const all=new Map(entries.map(e=>[e.path,e]));if(!all.get(rootPath)?.isTileset)throw bad('TERRAIN_ROOT','根文件必须是有效tileset JSON');const visiting=new Set<string>(),done=new Set<string>();const visit=(path:string,depth:number)=>{if(depth>TERRAIN_LIMITS.depth||visiting.has(path))throw bad('TERRAIN_CYCLE','包内引用循环或层级超限');if(done.has(path))return;const e=all.get(path);if(!e)throw bad('TERRAIN_RESOURCE_MISSING','模型引用的文件不在已核清单');visiting.add(path);for(const ref of e.references)visit(ref,depth+1);visiting.delete(path);done.add(path);};visit(rootPath,0);if(done.size!==entries.length)throw bad('TERRAIN_UNUSED_RESOURCE','清单含根模型未引用的文件，请只登记本次包的实际依赖');if(entries.reduce((n,e)=>n+e.jsonBytes,0)>TERRAIN_LIMITS.totalJsonBytes)throw bad('TERRAIN_JSON_LIMIT','模型JSON总量超过16MiB');return {resources:done.size,format:'explicit-3d-tiles',externalResources:false};
}
export function validatePackage(files:{path:string;bytes:Buffer}[],rootPath='tileset.json'){if(files.length>TERRAIN_LIMITS.files||new Set(files.map(f=>f.path)).size!==files.length||files.reduce((n,f)=>n+f.bytes.length,0)>TERRAIN_LIMITS.totalBytes)throw bad('TERRAIN_PACKAGE_LIMIT','文件数、重复路径或总量超限');return checkGraph(files.map(f=>inspectResource(f.path,f.bytes)),rootPath);}
