import type {Pool,PoolClient} from 'pg';import type {Actor} from '../../platform/types';import {randomUUID} from 'node:crypto';
import {AppError} from '../../platform/error';import {text,time,choice} from '../../platform/validation';import {database,transaction} from '../../db/pool';
import {scope,visible,lockKey,payloadHash,sameHash} from '../field/common';import {uuid} from '../identity/common';import {enqueue,type JobLease} from '../jobs/repository';import {withLease,assertLease} from '../jobs/execution';
import {configuredStore,checksum,type PrivateStore} from '../media/storage';import {streamMedia} from '../media/uploads';import {normalizePolygon} from '../map/geometry';import {resourcePath,TERRAIN_LIMITS,inspectResource,checkGraph} from './package';

export async function sceneAccess(c:PoolClient,a:Actor,id:string,action:'read'|'record'|'review'='read'){
 uuid(id);const row=(await c.query('SELECT * FROM terrain_scenes WHERE id=$1',[id])).rows[0];if(!row)throw new AppError(404,'TERRAIN_NOT_FOUND','场景不存在');await scope(c,a,row.object_id,action,'terrain_scene',id,row.captured_at?.toISOString());if(row.state==='withdrawn')throw new AppError(403,'TERRAIN_WITHDRAWN','场景已撤回，后续访问失效');return row;
}
export async function registerScene(c:PoolClient,a:Actor,b:Record<string,unknown>){
 if(b.expectedActorId!==undefined&&b.expectedActorId!==a.id)throw new AppError(403,'ACCOUNT_CHANGED','登录账号已变化，请重新核对资料归属');uuid(b.objectId);await scope(c,a,b.objectId,'record');await scope(c,a,b.objectId,'configure');await scope(c,a,b.objectId,'read');if(b.renderCrs!=='EPSG:4978')throw new AppError(422,'TERRAIN_RENDER_CRS','请先核实模型已转换到WGS84 ECEF；不能猜测位置或高程转换');
 const name=text(b.name,'场景名称',160),root=resourcePath(b.rootPath),key=text(b.requestKey,'登记标识',120);if(!Array.isArray(b.resources)||!b.resources.length||b.resources.length>TERRAIN_LIMITS.files)throw new AppError(422,'TERRAIN_PACKAGE_LIMIT','模型包需要1至1000份资源');
 const resources=b.resources.map((r:any)=>{uuid(r.assetId);return {path:resourcePath(r.path),assetId:r.assetId};});if(new Set(resources.map(r=>r.path)).size!==resources.length||!resources.some(r=>r.path===root))throw new AppError(422,'TERRAIN_MANIFEST','清单路径重复或缺根文件');
 if(b.flightId){uuid(b.flightId);const f=(await c.query('SELECT object_id FROM flights WHERE id=$1',[b.flightId])).rows[0];if(f?.object_id!==b.objectId)throw new AppError(422,'TERRAIN_FLIGHT','航次不属于场景对象');}
 const patches:unknown[]=[];if(b.patches!==undefined&&!Array.isArray(b.patches))throw new AppError(400,'TERRAIN_PATCHES','修补区须为面与说明的列表');if(((b.patches as unknown[]|undefined)?.length??0)>100)throw new AppError(422,'TERRAIN_PATCHES','一次最多100个明确修补区');
 for(const p of (b.patches??[]) as any[]){const shape=await normalizePolygon(c,p.geometry,4326);patches.push({geometry:(await c.query('SELECT ST_AsGeoJSON($1::geometry)::jsonb AS g',[shape])).rows[0].g,kind:choice(p.kind,['flattened_water','repair','canopy','unmeasured'] as const,'区域性质'),note:text(p.note,'修补或缺测说明',2000)});}
 const input={objectId:b.objectId,flightId:b.flightId??null,name,root,resources,capturedAt:b.capturedAt?time(b.capturedAt):null,sourceCrs:text(b.sourceCrs,'原资料坐标基准（未核实须注明）',200),surveyCrs:text(b.surveyCrs??b.sourceCrs,'核验用米制测量平面基准',200),verticalDatum:text(b.verticalDatum,'原垂直基准（未核实须注明）',200),conversionRef:text(b.conversionRef,'转到ECEF的方法/版本及依据',2000),sourceRef:text(b.sourceRef,'采集与加工依据',2000),surfaceState:choice(b.surfaceState,['unknown','bare_ground','canopy','water','mixed'] as const,'地面覆盖'),patches,repairsDeclared:b.repairsDeclared===true,supersedesId:b.supersedesId||null};
 await lockKey(c,a,'terrain-register',key);const hash=payloadHash(input),old=(await c.query('SELECT id,state,input_hash FROM terrain_scenes WHERE created_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(old){sameHash(old.input_hash,hash);return {id:old.id,state:old.state};}
 await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['terrain-version:'+b.objectId+':'+name]);const previous=(await c.query('SELECT id,version FROM terrain_scenes WHERE object_id=$1 AND name=$2 ORDER BY version DESC LIMIT 1',[b.objectId,name])).rows[0];if((previous?.id??null)!==input.supersedesId)throw new AppError(409,'TERRAIN_VERSION','已有同名版本，请明确引用当前版本追加修订');
 const media=new Map<string,any>();let total=0;for(const r of resources){await scope(c,a,b.objectId,'read','media',r.assetId);const m=(await c.query("SELECT * FROM media_assets WHERE id=$1 AND object_id=$2 AND ingest_state='complete'",[r.assetId,b.objectId])).rows[0];if(!m||Number(m.byte_length)>TERRAIN_LIMITS.tileBytes)throw new AppError(422,'TERRAIN_ASSET','资源未完整保存、对象不符或单文件超过64MiB');total+=Number(m.byte_length);media.set(r.path,m);}if(total>TERRAIN_LIMITS.totalBytes)throw new AppError(422,'TERRAIN_PACKAGE_LIMIT','模型包超过2GiB');
 const auth=(await c.query('SELECT auth_version FROM users WHERE id=$1',[a.id])).rows[0].auth_version,id=randomUUID();await c.query(`INSERT INTO terrain_scenes(id,object_id,flight_id,name,version,supersedes_id,root_path,captured_at,source_crs,survey_crs,vertical_datum,conversion_ref,source_ref,surface_state,patches,repairs_declared,created_by,auth_version,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20)`,[id,b.objectId,input.flightId,name,(previous?.version??0)+1,input.supersedesId,root,input.capturedAt,input.sourceCrs,input.surveyCrs,input.verticalDatum,input.conversionRef,input.sourceRef,input.surfaceState,JSON.stringify(patches),input.repairsDeclared,a.id,auth,key,hash]);
 for(const r of resources){const m=media.get(r.path);await c.query('INSERT INTO terrain_resources(scene_id,path,asset_id,checksum,byte_length,mime) VALUES($1,$2,$3,$4,$5,$6)',[id,r.path,r.assetId,m.checksum,m.byte_length,m.mime]);}
 await enqueue(c,{kind:'terrain.validate',businessKey:'terrain:'+id,payload:{sceneId:id},dueAt:new Date().toISOString(),priority:10});return {id,state:'validating'};
}
async function actorFor(c:PoolClient,r:any){const u=(await c.query('SELECT role,enabled,auth_version FROM users WHERE id=$1',[r.created_by])).rows[0];if(!u?.enabled||u.auth_version!==r.auth_version)throw new AppError(403,'TERRAIN_AUTH_CHANGED','包核验主体或授权已改变');const a:Actor={id:r.created_by,role:u.role,enabled:true,mfaVerified:true};await sceneAccess(c,a,r.id,'record');await sceneAccess(c,a,r.id);return a;}
export async function validateScene(pool:Pool,id:string,lease?:JobLease,store:PrivateStore=configuredStore()){
 return withLease(pool,'terrain:'+id,lease,async job=>{let error:string|null=null;try{const input=await database(async c=>{await assertLease(c,job);const r=(await c.query("SELECT * FROM terrain_scenes WHERE id=$1 AND state='validating'",[id])).rows[0];if(!r)return null;const a=await actorFor(c,r),resources=(await c.query('SELECT r.*,m.storage_key FROM terrain_resources r JOIN media_assets m ON m.id=r.asset_id WHERE scene_id=$1 ORDER BY path',[id])).rows;for(const x of resources)await scope(c,a,r.object_id,'read','media',x.asset_id);return {r,resources};},pool);if(!input)return;const parsed=[];
  for(const r of input.resources){await database(async c=>{await assertLease(c,job);const a=await actorFor(c,input.r);await scope(c,a,input.r.object_id,'read','media',r.asset_id);},pool);let bytes:Buffer;if(store.open){const parts:Buffer[]=[];let length=0;for await(const p of await store.open(r.storage_key)){length+=p.length;if(length>Number(r.byte_length)||length>TERRAIN_LIMITS.tileBytes)throw new AppError(422,'TERRAIN_ASSET_SIZE','原件长度与清单不符');parts.push(Buffer.from(p));}bytes=Buffer.concat(parts);}else bytes=await store.get(r.storage_key);if(bytes.length!==Number(r.byte_length)||checksum(bytes)!==r.checksum)throw new AppError(503,'TERRAIN_INTEGRITY','模型原件SHA或长度不符');parsed.push(inspectResource(r.path,bytes));}
  const result=checkGraph(parsed,input.r.root_path);await transaction(async c=>{await assertLease(c,job);const a=await actorFor(c,input.r);for(const r of input.resources)await scope(c,a,input.r.object_id,'read','media',r.asset_id);await c.query("UPDATE terrain_scenes SET state='ready',validation=$2,completed_at=now() WHERE id=$1 AND state='validating'",[id,JSON.stringify(result)]);},pool);
 }catch(e){if(e instanceof AppError&&e.code==='LEASE_LOST')throw e;error=e instanceof AppError?e.code:'TERRAIN_VALIDATION_FAILED';}if(error)await transaction(async c=>{await assertLease(c,job);await c.query("UPDATE terrain_scenes SET state='failed',error_code=$2,completed_at=now() WHERE id=$1 AND state='validating'",[id,error]);},pool);});
}
export async function withdrawScene(c:PoolClient,a:Actor,b:Record<string,unknown>){uuid(b.id);const r=(await c.query('SELECT * FROM terrain_scenes WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!r)throw new AppError(404,'TERRAIN_NOT_FOUND','场景不存在');await scope(c,a,r.object_id,'record');await scope(c,a,r.object_id,'configure');const reason=text(b.reason,'撤回或土建变更原因',2000);if(r.state==='withdrawn'){if(r.withdraw_reason!==reason)throw new AppError(409,'TERRAIN_WITHDRAW_REASON','原撤回记录不覆盖');return {id:r.id,state:'withdrawn'};}await c.query("UPDATE terrain_scenes SET state='withdrawn',withdrawn_at=now(),withdraw_reason=$2 WHERE id=$1",[r.id,reason]);return {id:r.id,state:'withdrawn'};}
export async function listScenes(c:PoolClient,a:Actor){const v=await visible(c,a,'terrain_scene');return {items:(await c.query('SELECT id,object_id,flight_id,name,version,supersedes_id,root_path,captured_at,source_crs,survey_crs,vertical_datum,conversion_ref,source_ref,surface_state,patches,repairs_declared,state,validation,error_code,created_at,withdrawn_at,withdraw_reason FROM terrain_scenes WHERE object_id=ANY($1::uuid[]) AND($2::uuid[] IS NULL OR id=ANY($2)) ORDER BY created_at DESC LIMIT 100',[v.objects,v.resources])).rows,limits:TERRAIN_LIMITS};}
export async function readSceneResource(pool:Pool,a:Actor,sceneId:string,path:string,range:string|null,store:PrivateStore=configuredStore()){
 path=resourcePath(path);const r=await database(async c=>{const s=await sceneAccess(c,a,sceneId);if(s.state!=='ready')throw new AppError(409,'TERRAIN_NOT_READY','模型包尚未通过结构核验');const r=(await c.query('SELECT * FROM terrain_resources WHERE scene_id=$1 AND path=$2',[sceneId,path])).rows[0];if(!r)throw new AppError(404,'TERRAIN_RESOURCE_MISSING','资源不在本次固定包内');return r;},pool);
 const stream=await streamMedia(pool,a,r.asset_id,range,store,async(c,m)=>{const s=await sceneAccess(c,a,sceneId);if(s.state!=='ready'||s.object_id!==m.object_id||m.checksum!==r.checksum)throw new AppError(403,'TERRAIN_RESOURCE_SCOPE','场景、原件或授权已改变');});
 return {...stream,mime:/\.(json|gltf)$/i.test(path)?'application/json':/\.png$/i.test(path)?'image/png':/\.jpe?g$/i.test(path)?'image/jpeg':'application/octet-stream'};
}
