import {readFile,readdir,writeFile} from 'node:fs/promises';import {join,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {PROJECT_ROOT} from '../tests/support/artifacts';import {atomicJson} from './quality-state';
const statuses=new Set(['running','passed','failed','blocked','incomplete','interrupted']);
const stepIds=new Set(['typecheck','unit','environment','build','database','browser-http','monitor','archive','coverage','retrieval','assistant','restore-phase1','restore-phase2','restore-phase3','restore-phase4','release-upgrade','stability','release-manifest']);
const reasons=new Set(['INTERRUPTED','TIMEOUT','PROCESS_START_FAILED','STEP_EXECUTION_FAILED','PREFLIGHT_FAILED','DEPENDENCY_NOT_PASSED','TESTS_NOT_FULLY_EXECUTED','TEST_FILES_MISSING','ISOLATED_WORKTREE_REQUIRED','TEST_DATABASE_IDENTITY_REQUIRED','TEST_CONTAINER_IDENTITY_REQUIRED','TEST_CONTAINER_PORT_MISMATCH','TEST_INSTANCE_MISMATCH','TEST_CONTAINER_UNAVAILABLE','TEST_DATABASE_UNAVAILABLE','DEVELOPMENT_ACCESS_NOT_ALLOWED','MODEL_FILES_MISSING','CHROMIUM_MISSING','PYTHON_MISSING']);
export function publicSummary(report:any) {
 const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{40,64}$/.test(v)?v:null;
 return {schemaVersion:'public-check-summary-v1',profile:['quick','core','delivery'].includes(report.profile)?report.profile:'diagnostic',passed:report.passed===true,finished:report.state==='finished',sourceCommit:hash(report.source?.commit),sourceSha256:hash(report.source?.sha256),sourceUnchanged:report.source?.unchanged===true,historyUnchanged:report.history?.unchanged===true,
  steps:(report.steps??[]).map((s:any)=>({id:stepIds.has(s.id)?s.id:'redacted',status:statuses.has(s.status)?s.status:'unknown',durationMs:Number.isFinite(s.durationMs)?s.durationMs:null,exitCode:Number.isInteger(s.exitCode)?s.exitCode:null,reason:reasons.has(s.reason)?s.reason:null,tests:s.tests?Object.fromEntries(['total','passed','failed','skipped','cancelled','todo'].map(k=>[k,Number.isSafeInteger(s.tests[k])&&s.tests[k]>=0?s.tests[k]:null])):null})),
  possibleFlakySteps:(report.rerun?.recoveredSteps??[]).filter((s:unknown)=>stepIds.has(s as string)),productionAccepted:false};
}
export async function writePublicSummaries() {const root=join(PROJECT_ROOT,'.local/验证记录');let count=0;for(const dir of await readdir(root,{withFileTypes:true}).catch(()=>[])){if(!dir.isDirectory())continue;const folder=join(root,dir.name);let report;try{report=JSON.parse(await readFile(join(folder,'运行记录.json'),'utf8'));}catch{continue;}
 const safe=publicSummary(report);await atomicJson(join(folder,'公开摘要.json'),safe);await writeFile(join(folder,'公开摘要.md'),'# 工程检查摘要\n\n范围：'+safe.profile+'；通过：'+safe.passed+'。\n\n| 步骤 | 状态 | 耗时毫秒 |\n|---|---|---|\n'+safe.steps.map((s:any)=>`| ${s.id} | ${s.status} | ${s.durationMs??'未记录'} |`).join('\n')+'\n\n不包含私有日志、原件、转储或凭据；不代表生产验收。\n',{mode:0o600});count++;}return count;}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))console.log(JSON.stringify({publicSummaries:await writePublicSummaries()}));
