import assert from 'node:assert/strict';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import {withDb} from '../tests/support/db';import {actorFixture,objectFixture,permit} from '../tests/support/fixtures';import {transaction,database} from '../src/db/pool';import {createDocument,reviewDocument} from '../src/modules/knowledge/service';import {requestAssistant,runAssistant,listAssistant,saveModelPolicy,runReadTool} from '../src/modules/assistant/service';import {PROMPT_VERSION} from '../src/modules/assistant/validate';import {EMBEDDING_VERSION} from '../src/modules/models/process';import {payloadHash} from '../src/modules/field/common';import {AppError} from '../src/platform/error';
const args=process.argv.slice(2),value=(name:string,fallback:string)=>args.includes(name)?args[args.indexOf(name)+1]:fallback,datasetPath=value('--dataset','tests/evaluations/一期助手工程评测集.json'),mode=value('--mode','fixture');
assert(['fixture','http'].includes(mode),'mode只能fixture或http');const dataset=JSON.parse(await readFile(datasetPath,'utf8'));assert(typeof dataset.version==='string'&&Array.isArray(dataset.questions)&&dataset.questions.length>0&&dataset.questions.length<=100);assert(Number.isInteger(dataset.repeatCount)&&dataset.repeatCount>=1&&dataset.repeatCount<=5);const datasetHash=payloadHash(dataset),standards=structuredClone(dataset.frozenStandards);assert(standards.behaviorPassRateMinimum>=0&&standards.behaviorPassRateMinimum<=1);
if(mode==='http'){assert(args.includes('--allow-real-model')&&process.env.MODEL_EXTERNAL_ENABLED==='1','真实模型须显式允许并由部署环境启用');assert(dataset.dataUsageApprovalRef&&dataset.noPersonalInformationConfirmed===true,'须提供已批准资料范围/许可且完成个人信息检查');assert(process.env.PLATFORM_EVAL_BASE_URL&&process.env.PLATFORM_EVAL_COOKIE,'真实评测必须通过已有平台账号和真实预算账本，不创建替身生产资料');assert(Array.isArray(dataset.objectIds)&&dataset.objectIds.length>0,'真实评测须明确已授权对象');}
async function platformCase(q:any){const base=new URL(process.env.PLATFORM_EVAL_BASE_URL!);assert(base.protocol==='https:'||base.protocol==='http:'&&base.hostname==='127.0.0.1','评测只连接HTTPS平台或本机测试入口');assert(!base.username&&!base.password);const headers={'Content-Type':'application/json',Cookie:process.env.PLATFORM_EVAL_COOKIE!,Origin:base.origin};const started=performance.now(),request=await fetch(new URL('/api/v1/assistant',base),{method:'POST',headers,body:JSON.stringify({objectIds:q.objectIds??dataset.objectIds,question:q.question,requestKey:'eval:'+datasetHash.slice(0,32)+':'+q.id+':'+randomUUID()}),signal:AbortSignal.timeout(15000)});const created=await request.json();if(!request.ok)return {state:request.status===403?'access_denied':'request_failed',model:null,usage:null,elapsedMs:performance.now()-started,costCny:null};
 for(let n=0;n<120;n++){const response=await fetch(new URL('/api/v1/assistant',base),{headers,cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('平台认证或读取失败，未输出凭据');const list=await response.json(),r=list.items?.find((r:any)=>r.id===created.id);if(r&&!['queued','running'].includes(r.state))return {state:r.result?.sourceInactive?'source_inactive':r.state,runId:r.id,model:r.model,usage:r.usage,elapsedMs:performance.now()-started,costCny:null,answerHash:payloadHash(r.result),evidenceCount:r.result?.evidence?.length??0,promptVersion:r.prompt_version,retrievalVersion:r.retrieval_version};await new Promise(resolve=>setTimeout(resolve,1000));}return {state:'evaluation_pending',runId:created.id,model:null,usage:null,elapsedMs:performance.now()-started,costCny:null};}
const runId='助手质量_'+new Date().toISOString().replace(/[:.]/g,'-')+'_'+randomUUID().slice(0,6),rows:any[]=[];
for(let repeat=1;repeat<=dataset.repeatCount;repeat++)for(const q of dataset.questions){
 const result=mode==='http'?await platformCase(q):await withDb(async pool=>{const tech=await actorFixture(pool,'technician'),worker=await actorFixture(pool,'worker'),objectId=await objectFixture(pool,tech.id),outside=await objectFixture(pool,tech.id);await permit(pool,tech.id,objectId,['read','configure','review']);await permit(pool,worker.id,objectId,['read']);const docs:string[]=[];
  if(q.scenario!=='none')for(const x of dataset.documents){const d=await transaction(c=>createDocument(c,tech,{objectIds:[objectId],title:x.title,body:x.body,version:dataset.version,sourceRef:'dataset:'+datasetHash+':'+x.key,format:'markdown',evidenceNature:dataset.evidenceNature}),pool);await transaction(c=>reviewDocument(c,tech,{id:d.id}),pool);docs.push(d.id);}
  if(q.scenario==='sql'){let code='not_rejected';try{await database(c=>runReadTool(c,worker,'sql',{objectId}),pool);}catch(e){code=e instanceof AppError?e.code:'unexpected_error';}return {state:code==='TOOL_NOT_ALLOWED'?'tool_not_allowed':code,model:null,usage:null,elapsedMs:0,costCny:null};}
  if(q.scenario==='unauthorized'){let code='not_rejected';try{await transaction(c=>requestAssistant(c,worker,{objectIds:[outside],question:q.question,requestKey:randomUUID()}),pool);}catch(e){code=e instanceof AppError?e.code:'unexpected_error';}return {state:code==='ACCESS_DENIED'?'access_denied':code,model:null,usage:null,elapsedMs:0,costCny:null};}
  await transaction(c=>saveModelPolicy(c,tech,{objectId,externalEnabled:true,allowBackup:false,maxMonthTokens:q.scenario==='budget'?1:mode==='http'?dataset.maxMonthTokens:1000000,maxMonthCalls:mode==='http'?dataset.maxMonthCalls:100,approvedScope:mode==='http'?dataset.dataUsageApprovalRef:'仅合成provider工程评测，不外发'}),pool);
  const run=await transaction(c=>requestAssistant(c,worker,{objectIds:[objectId],question:q.question,requestKey:randomUUID()}),pool),provider=mode==='http'?undefined:async(ctx:Record<string,unknown>)=>{if(q.scenario==='timeout')throw new AppError(503,'MODEL_TIMEOUT','合成超时');const e=(ctx.evidence as any[])[0];return {output:{claims:[{text:'先人工核查，保留数据限制',evidenceIds:[q.scenario==='invalid_output'?'unauthorized':e?.chunkId],metricIds:[],limitations:e?.evidenceNature?[e.evidenceNature]:[]}]},model:'fixture-no-external-model',usage:{inputTokens:10,outputTokens:10},truncated:false};};
  const started=performance.now();await runAssistant(pool,run.id,provider);if(q.scenario==='withdraw')for(const id of docs)await transaction(c=>reviewDocument(c,tech,{id,withdraw:true}),pool);const r=(await database(c=>listAssistant(c,worker),pool)).items[0],costs=(await pool.query("SELECT amount FROM usage_events WHERE category='model'")).rows;return {state:r.result?.sourceInactive?'source_inactive':r.state,model:r.model,usage:r.usage,elapsedMs:performance.now()-started,costCny:costs.length&&costs.every(c=>c.amount!==null)?costs.reduce((n,c)=>n+Number(c.amount),0):null,answerHash:payloadHash(r.result),evidenceCount:r.result?.evidence?.length??0};
 });rows.push({questionId:q.id,repeat,scenario:q.scenario,expectedState:q.expectedState,...result,behaviorPassed:result.state===q.expectedState,semanticQuality:'requires_independent_human_review'});
}
const passRate=rows.filter(r=>r.behaviorPassed).length/rows.length,report={runId,checkedAt:new Date().toISOString(),datasetPath,datasetVersion:dataset.version,datasetHash,standards,mode,promptVersion:PROMPT_VERSION,retrievalVersion:'zh-bigram-rrf-v1',embeddingVersion:EMBEDDING_VERSION,rows,behaviorPassRate:passRate,behaviorPassed:passRate>=standards.behaviorPassRateMinimum,actualExternalModelCalls:rows.some(r=>r.model&&r.model!=='fixture-no-external-model'),httpModeRequested:mode==='http',professionalQualityAccepted:false,humanReviewTemplate:rows.map(r=>({questionId:r.questionId,repeat:r.repeat,evidenceSupported:null,requiredLimitsPreserved:null,agronomicSemanticsCorrect:null,taskBoundariesPreserved:null,reviewer:null,reason:null})),limits:['fixture仅验证真实代码工程分支，不代表Kimi/DeepSeek语义质量','http须使用已批准专业资料、真实账单与独立评分，不由结构校验签农业结论','每题每轮结果和冻结hash保留，不覆盖失败轮次']};await mkdir('docs/evaluations',{recursive:true});await writeFile('docs/evaluations/'+runId+'.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({runId,questions:rows.length,behaviorPassRate:passRate,behaviorPassed:report.behaviorPassed,professionalQualityAccepted:false}));if(!report.behaviorPassed)process.exitCode=1;
