import {postgresTest as postgres} from '../tests/support/postgres';
import {artifactPath,artifactDirectory} from '../tests/support/artifacts';
import assert from 'node:assert/strict';import {randomUUID,randomBytes,createHash} from 'node:crypto';import {mkdir,readFile,writeFile,rm} from 'node:fs/promises';import {resolve} from 'node:path';import {generate} from 'otplib';
import {withDb} from '../tests/support/db';import {seedTerrain} from '../tests/support/terrain';import {objectFixture,actorFixture,permit} from '../tests/support/fixtures';import {database,transaction} from '../src/db/pool';import {canonicalJson} from '../src/platform/json';import {localStore,checksum,streamChecksum} from '../src/modules/media/storage';import {backupMedia} from '../src/modules/media/uploads';import {saveSurvey,saveElevation} from '../src/modules/terrain/survey';import {reviewTerrain,terrainSnapshot} from '../src/modules/terrain/review';import {saveHydraulicLink,terrainProfile} from '../src/modules/terrain/links';import {registerScene,validateScene,readSceneResource} from '../src/modules/terrain/scenes';import {saveSource,saveDevice} from '../src/modules/registry/devices';import {savePosition} from '../src/modules/map/service';import {shareResource,revokeResource} from '../src/modules/field/shares';import {hashPassword} from '../src/modules/identity/password';import {login,enrollment,finishMfa,resolveSession} from '../src/modules/identity/session';import {claimJob} from '../src/modules/jobs/repository';import {reconcileExecutions,assertLease} from '../src/modules/jobs/execution';
const sha=(x:Buffer|string)=>createHash('sha256').update(x).digest('hex');
async function snapshot(pool:any,schema:string){const out:Record<string,{rows:number;sha:string}>={};for(const {tablename:t}of(await pool.query('SELECT tablename FROM pg_tables WHERE schemaname=$1 ORDER BY tablename',[schema])).rows){assert(/^[a-z_0-9]+$/.test(t));const rows=(await pool.query(`SELECT to_jsonb(t) AS data FROM "${schema}"."${t}" t ORDER BY to_jsonb(t)::text`)).rows.map((r:any)=>r.data);out[t]={rows:rows.length,sha:sha(canonicalJson(rows))};}return out;}

const directory=artifactDirectory('恢复/二期');await mkdir(directory,{recursive:true,mode:0o700});
try{const report=await withDb(async pool=>{const store=localStore(resolve(directory,'source'),resolve(directory,'backup')),f=await seedTerrain(pool,store),schema=(await pool.query('SELECT current_schema() AS s')).rows[0].s;assert(/^test_[a-f0-9]{32}$/.test(schema));const key=randomBytes(32).toString('hex'),password=randomBytes(24).toString('hex');await pool.query('UPDATE users SET password_hash=$2 WHERE id=$1',[f.actor.id,await hashPassword(password)]);const authOptions={pool,encryptionKey:key},challenge=await login(f.actor.id,password,authOptions);assert.equal(challenge.kind,'mfa');const factor=await enrollment(challenge.token,authOptions),session=await finishMfa(challenge.token,await generate({secret:factor.secret}),authOptions);
 const points:string[]=[];for(let i=0;i<3;i++){const r=await transaction(c=>saveSurvey(c,f.actor,{sceneId:f.scene.id,pointKey:'RESTORE-'+i,purpose:i?'check':'control',independent:i>0,coordinateUnits:'m',planarConfirmed:true,lng:114+i*.001,lat:30,surveyE:i*10,surveyN:0,surveyH:10-i,modelE:i*10+.1,modelN:0,modelH:10-i+.1,horizontalCrs:'EPSG:4547',verticalDatum:'合成实测基准',measuredAt:new Date().toISOString(),sourceRef:i?'合成独立测量'+i:'合成控制点',requestKey:randomUUID()}),pool);points.push(r.id);}
 await transaction(c=>reviewTerrain(c,f.actor,{sceneId:f.scene.id,decision:'accepted',requiredChecks:2,maxHorizontalError:.2,maxVerticalError:.2,datumConfirmed:true,independentConfirmed:true,groundCoverageConfirmed:true,purpose:'合成恢复测点几何',evidence:'合成测试阈值，不是专业标准',reviewDueAt:new Date(Date.now()+86400000).toISOString(),requestKey:randomUUID()}),pool);
 const other=await objectFixture(pool,f.actor.id);await permit(pool,f.actor.id,other,['read','record','review']);const link=await transaction(c=>saveHydraulicLink(c,f.actor,{sceneId:f.scene.id,fromObjectId:f.objectId,toObjectId:other,name:'合成恢复连接',direction:'forward',verified:true,evidence:'非现场关系',reviewDueAt:new Date(Date.now()+86400000).toISOString(),requestKey:randomUUID()}),pool);
 await transaction(async c=>{const source=await saveSource(c,f.actor,{objectId:f.objectId,code:'RESTORE-GEO',name:'合成测量设备',provider:'synthetic'}),device=await saveDevice(c,f.actor,{objectId:f.objectId,sourceId:source.id,externalId:'geo-restore',name:'合成高程设备',kind:'physical',source:'软件恢复测试'}),p=await savePosition(c,f.actor,{deviceId:device.id,lng:114,lat:30,verified:true,source:'合成实测位置'});await saveElevation(c,f.actor,{positionId:p.id,surveyHeight:10,ellipsoidHeight:40,verticalDatum:'合成实测基准',referencePoint:'合成安装点',conversionRef:'合成椭球高',measuredAt:new Date().toISOString(),sourceRef:'非真实测量',verified:true,requestKey:randomUUID()});},pool);
 const expert=await actorFixture(pool,'expert');await permit(pool,expert.id,f.objectId,['read']);const grant=await transaction(c=>shareResource(c,f.actor,{objectId:f.objectId,recipientId:expert.id,resourceType:'terrain_scene',resourceId:f.scene.id,expiresAt:new Date(Date.now()+3600000).toISOString()}),pool);await transaction(c=>revokeResource(c,f.actor,{id:grant.id}),pool);
 const pending=await transaction(c=>registerScene(c,f.actor,{...f.input,name:'合成中断后恢复',requestKey:randomUUID()}),pool),oldLease=await claimJob(pool,'restore-old',new Date(),{businessKey:'terrain:'+pending.id});assert(oldLease);await pool.query("UPDATE jobs SET lease_until=now()-interval '1 second' WHERE id=$1",[oldLease.id]);
 const media=(await pool.query('SELECT id,storage_key,checksum,byte_length FROM media_assets')).rows;for(const m of media)await backupMedia(pool,m.id,undefined,store);const before=await snapshot(pool,schema),started=Date.now(),dump=postgres('pg_dump',['--schema',schema,'--format','custom','--no-owner','--no-acl']);await writeFile(resolve(directory,'隔离库.dump'),dump,{mode:0o600});await writeFile(resolve(directory,'独立身份密钥.env'),'IDENTITY_ENCRYPTION_KEY='+key+'\n',{mode:0o600});assert.equal(dump.subarray(0,5).toString(),'PGDMP');await rm(resolve(directory,'source'),{recursive:true,force:true});await pool.query('DROP SCHEMA "'+schema+'" CASCADE');postgres('pg_restore',['--no-owner','--no-acl','--exit-on-error'],await readFile(resolve(directory,'隔离库.dump')));assert.deepEqual(await snapshot(pool,schema),before);
 for(const m of media){const bytes=await store.get(m.storage_key,true);assert.equal(checksum(bytes),m.checksum);await store.put(m.storage_key,bytes);const stream=await readSceneResource(pool,f.actor,f.scene.id,f.resources.find(r=>r.assetId===m.id)!.path,null,store);assert.equal((await streamChecksum(stream.stream)).checksum,m.checksum);}
 const fresh=await login(f.actor.id,password,authOptions);assert.equal(fresh.kind,'mfa');const logged=await finishMfa(fresh.token,session.recoveryCodes![0],authOptions),actor=await resolveSession(logged.token,authOptions);assert.equal(actor.id,f.actor.id);await assert.rejects(()=>readSceneResource(pool,expert,f.scene.id,'model.glb',null,store),{status:403});assert.equal((await database(c=>terrainSnapshot(c,actor,f.scene.id),pool)).usable,true);assert.equal((await database(c=>terrainProfile(c,actor,{sceneId:f.scene.id,linkId:link.id,pointIds:points}),pool)).elevationDifferenceM,-2);
 await reconcileExecutions(pool);await assert.rejects(()=>database(c=>assertLease(c,oldLease),pool),{code:'LEASE_LOST'});await validateScene(pool,pending.id,undefined,store);assert.equal((await pool.query('SELECT state FROM terrain_scenes WHERE id=$1',[pending.id])).rows[0].state,'ready');const names=['terrain_scenes','terrain_resources','terrain_surveys','terrain_reviews','device_elevations','hydraulic_links'];for(const n of names)assert(before[n].rows>0);return {checkedAt:new Date().toISOString(),environment:'agri_test随机schema及合成模型',tablesVerified:Object.keys(before).length,newNonemptyTables:Object.fromEntries(names.map(n=>[n,before[n].rows])),assetsVerified:media.length,dumpSha:sha(dump),databaseAndRowHashesEqual:true,identityAndPermissionsRestored:true,revokedSceneRemainsDenied:true,approvedMeasurementsRestored:true,interruptedLocalJobSafelyResumed:true,elapsedMs:Date.now()-started,productionTerrainAccepted:false,productionDisasterRecoveryAccepted:false};});await writeFile(resolve(directory,'恢复实测.json'),JSON.stringify(report,null,2),{mode:0o600});await writeFile(artifactPath('验收/2c/二期非空恢复实测.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));}catch(e){await writeFile(resolve(directory,'失败诊断.json'),JSON.stringify({code:(e as any)?.code,message:(e as any)?.message,stack:(e as any)?.stack},null,2),{mode:0o600});console.error('二期隔离恢复未通过；私有诊断已保留，未操作开发库。');process.exitCode=1;}
