import assert from 'node:assert/strict';import {randomBytes,createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {mkdir,readFile,writeFile,rm} from 'node:fs/promises';import {resolve} from 'node:path';import {generate} from 'otplib';
import {withDb,requireTestDatabaseUrl} from '../tests/support/db';import {seedTerrain} from '../tests/support/terrain';import {seedPhase3} from '../tests/support/phase3';import {database} from '../src/db/pool';import {canonicalJson} from '../src/platform/json';import {localStore,checksum} from '../src/modules/media/storage';import {backupMedia} from '../src/modules/media/uploads';import {readMedia} from '../src/modules/media/service';import {hashPassword} from '../src/modules/identity/password';import {login,enrollment,finishMfa,resolveSession} from '../src/modules/identity/session';import {balance} from '../src/modules/inventory/ledger';import {stockDetail} from '../src/modules/inventory/queries';import {dispatchStatus} from '../src/modules/inventory/handoffs';import {assertLotReleased} from '../src/modules/traceability/quality';import {readTrace} from '../src/modules/traceability/trace';import {publicCard} from '../src/modules/traceability/public';import {runCrop} from '../src/modules/agronomy/crops';import {assertLease} from '../src/modules/jobs/execution';
const sha=(v:Buffer|string)=>createHash('sha256').update(v).digest('hex');
async function snapshot(pool:any,schema:string){const out:Record<string,{rows:number;sha:string}>={};for(const {tablename:t}of(await pool.query('SELECT tablename FROM pg_tables WHERE schemaname=$1 ORDER BY tablename',[schema])).rows){assert(/^[a-z_0-9]+$/.test(t));const data=(await pool.query('SELECT to_jsonb(t) AS d FROM "'+schema+'"."'+t+'" t ORDER BY to_jsonb(t)::text')).rows.map((r:any)=>r.d);out[t]={rows:data.length,sha:sha(canonicalJson(data))};}return out;}
function postgres(tool:string,args:string[],input?:Buffer){const u=new URL(requireTestDatabaseUrl());assert.equal(u.username,'agri_tester');return execFileSync('docker',['exec','-i','-e','PGPASSWORD','liangzihu-farm-db',tool,'--host','127.0.0.1','--username','agri_tester','--dbname','agri_test',...args],{input,env:{...process.env,PGPASSWORD:decodeURIComponent(u.password)},stdio:['pipe','pipe','pipe'],timeout:60000,maxBuffer:67108864});}
const directory=resolve('.local/三期恢复',new Date().toISOString().replace(/[:.]/g,'-'));await mkdir(directory,{recursive:true,mode:0o700});
try{
 const report=await withDb(async pool=>{
 const schema=(await pool.query('SELECT current_schema() AS s')).rows[0].s;assert(/^test_[a-f0-9]{32}$/.test(schema));const store=localStore(resolve(directory,'source'),resolve(directory,'backup')),legacy=await seedTerrain(pool,store);
 const encryptionKey=randomBytes(32).toString('hex'),password=randomBytes(24).toString('hex');await pool.query('UPDATE users SET password_hash=$2 WHERE id=$1',[legacy.actor.id,await hashPassword(password)]);const authOptions={pool,encryptionKey},challenge=await login(legacy.actor.id,password,authOptions);assert.equal(challenge.kind,'mfa');const factor=await enrollment(challenge.token,authOptions),session=await finishMfa(challenge.token,await generate({secret:factor.secret}),authOptions);
 const f=await seedPhase3(pool,store,legacy.actor,legacy.objectId),media=(await pool.query("SELECT id,storage_key,checksum,byte_length FROM media_assets WHERE ingest_state='complete'")).rows;
 for(const asset of media)await backupMedia(pool,asset.id,undefined,store);
 const before=await snapshot(pool,schema),newTables:string[]=[];for(const file of ['035_stock.sql','036_quality_trace.sql','037_protection.sql','038_agronomy.sql']){const sql=await readFile('db/migrations/'+file,'utf8');for(const match of sql.matchAll(/^CREATE TABLE (\w+)/gm))newTables.push(match[1]);}
 assert.equal(newTables.length,39);for(const name of newTables)assert(before[name]?.rows>0,name+'必须非空');
 const started=Date.now(),dump=postgres('pg_dump',['--schema',schema,'--format','custom','--no-owner','--no-acl']);assert.equal(dump.subarray(0,5).toString(),'PGDMP');await writeFile(resolve(directory,'隔离库.dump'),dump,{mode:0o600});await writeFile(resolve(directory,'独立身份密钥.env'),'IDENTITY_ENCRYPTION_KEY='+encryptionKey+'\n',{mode:0o600});
 await rm(resolve(directory,'source'),{recursive:true,force:true});await pool.query('DROP SCHEMA "'+schema+'" CASCADE');postgres('pg_restore',['--no-owner','--no-acl','--exit-on-error'],await readFile(resolve(directory,'隔离库.dump')));assert.deepEqual(await snapshot(pool,schema),before);
 for(const asset of media){const bytes=await store.get(asset.storage_key,true);assert.equal(checksum(bytes),asset.checksum);await store.put(asset.storage_key,bytes);}
 const loginAgain=await login(legacy.actor.id,password,authOptions);assert.equal(loginAgain.kind,'mfa');const restored=await finishMfa(loginAgain.token,session.recoveryCodes![0],authOptions),actor=await resolveSession(restored.token,authOptions);assert.equal(actor.id,legacy.actor.id);
 for(const asset of media){const content=await database(c=>readMedia(c,actor,asset.id,store),pool);assert.equal(checksum(content.bytes),asset.checksum);}
 assert.equal(await database(c=>balance(c,f.input.id,f.location.id),pool),'70');assert.equal(await database(c=>balance(c,f.output.id,f.location.id),pool),'16');
 assert.equal((await database(c=>dispatchStatus(c,f.dispatch.id),pool)).outstanding,'2');
 await assert.rejects(()=>database(c=>stockDetail(c,f.expert,f.input.id),pool),{status:403});await assert.rejects(()=>database(c=>publicCard(c,f.card.code),pool),{status:404});await assert.rejects(()=>database(c=>assertLotReleased(c,f.input.id),pool),{code:'QUALITY_NOT_CURRENT'});await database(c=>assertLotReleased(c,f.output.id),pool);
 const query=await database(c=>readTrace(c,actor,f.query.id),pool);assert.equal(query.snapshot.edges.length,1);
 assert.equal((await pool.query('SELECT dispatched FROM control_requests WHERE id=$1',[f.control.id])).rows[0].dispatched,false);
 assert.equal((await pool.query('SELECT state FROM spectral_products WHERE id=$1',[f.spectral.id])).rows[0].state,'complete');
 await assert.rejects(()=>database(c=>assertLease(c,f.oldLease),pool),{code:'LEASE_LOST'});await runCrop(pool,f.pending.id,undefined,store);assert.equal((await pool.query('SELECT state FROM crop_analyses WHERE id=$1',[f.pending.id])).rows[0].state,'complete');
 return {checkedAt:new Date().toISOString(),environment:'agri_test随机schema；全部为合成记录和像素',tablesVerified:Object.keys(before).length,newNonemptyTables:Object.fromEntries(newTables.map(n=>[n,before[n].rows])),all39NewTablesNonempty:true,assetsVerified:media.length,dumpSha:sha(dump),databaseAndRowHashesEqual:true,identityMfaRecoveryAndPermissionsRestored:true,stockBalancesAndPartialReceiptRestored:true,revokedExpertAccessDenied:true,revokedCustomerCardDenied:true,openQualityCaseStillBlocks:true,traceVersionAndEdgesRestored:true,spectralArtifactsReadBack:true,controlStillNotDispatched:true,interruptedCropJobResumedWithNewLease:true,elapsedMs:Date.now()-started,productionAcceptance:false,productionDisasterRecoveryAccepted:false};
 });
 await writeFile(resolve(directory,'恢复实测.json'),JSON.stringify(report,null,2),{mode:0o600});await mkdir('docs/acceptance/3c',{recursive:true});await writeFile('docs/acceptance/3c/三期非空恢复实测.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}catch(e){await writeFile(resolve(directory,'失败诊断.json'),JSON.stringify({code:(e as any)?.code,message:(e as any)?.message,stack:(e as any)?.stack},null,2),{mode:0o600});console.error('三期隔离恢复未通过，私有诊断已保存；未操作开发库。');process.exitCode=1;}

