import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {verifyWebhook,normalizeAlarm} from '../../src/adapters/ezviz/webhook';
const now=new Date('2026-10-02T00:00:00Z'),secret='syntheticSecret1234',body={header:{deviceId:'SN123',channelNo:1,messageId:'test-1',messageTime:now.getTime(),type:'ys.alarm'},body:{alarmId:'alarm-1',alarmTime:'2026-10-02T08:00:00',alarmType:'10000',channel:1,devSerial:'SN123',crypt:0,checksum:'NEVER_STORE_DEVICE_PASSWORD',pictureList:[{id:'pic-1',url:'https://media.example.com/p?isEncrypted=0&signature=private'}]}};
function signed(raw:Buffer,t=String(now.getTime())){return new Headers({t,Signature:createHmac('sha1',secret).update(raw).update(t).digest('hex'),message_type:'ys.alarm'});}
test('萤石签名使用原字节+t，篡改/缺签名/过期/未来拒绝，密钥和消息不进入错误',()=>{const raw=Buffer.from(JSON.stringify(body,null,2));const result=verifyWebhook(raw,signed(raw),secret,now);assert.equal(result.message.header.messageId,'test-1');assert.throws(()=>verifyWebhook(Buffer.from(JSON.stringify(body)),signed(raw),secret,now),{code:'EZVIZ_SIGNATURE'});assert.throws(()=>verifyWebhook(raw,new Headers(),secret,now),{code:'EZVIZ_SIGNATURE'});for(const t of [now.getTime()-300001,now.getTime()+300001])assert.throws(()=>verifyWebhook(raw,signed(raw,String(t)),secret,now),{code:'EZVIZ_SIGNATURE_TIME'});assert(!JSON.stringify(result).includes('NEVER_STORE_DEVICE_PASSWORD'));});
test('萤石接收限制UTF-8/JSON/大小/深度并去除已识别凭据',()=>{for(const raw of [Buffer.from('not-json'),Buffer.from([0xff]),Buffer.from('[]')])assert.throws(()=>verifyWebhook(raw,signed(raw),secret,now),{code:'EZVIZ_MESSAGE'});const large=Buffer.alloc(262145);assert.throws(()=>verifyWebhook(large,signed(large),secret,now),{code:'EZVIZ_BODY_LIMIT'});const raw=Buffer.from(JSON.stringify({...body,body:{...body.body,extra:{accessToken:'PRIVATE_TOKEN',password:'PRIVATE_PASSWORD'}}}));assert(!JSON.stringify(verifyWebhook(raw,signed(raw),secret,now)).includes('PRIVATE_'));});
test('新消息告警时间固定偏移且设备/通道明确，推送时间不代替发生时间',()=>{const r=normalizeAlarm(verifyWebhook(Buffer.from(JSON.stringify(body)),signed(Buffer.from(JSON.stringify(body))),secret,now).message,480);assert.equal(r.kind,'alarm');if(r.kind==='alarm'){assert.equal(r.occurredAt,now.toISOString());assert.equal(r.channel,1);assert.equal(r.pictures[0].plaintext,true);}const altered=structuredClone(body);altered.body.alarmTime='2026-02-30T08:00:00';assert.equal(normalizeAlarm(altered,480).kind,'pending');altered.body.alarmTime='';assert.equal(normalizeAlarm(altered,480).kind,'pending');});
test('厂家设备/通道矛盾、ISAPI或未知负载保留待契约，不猜旧SDK字段',()=>{for(const change of [{devSerial:'OTHER'},{channel:0}])assert.equal(normalizeAlarm({...body,body:{...body.body,...change}},480).kind,'pending');assert.deepEqual(normalizeAlarm({...body,header:{...body.header,type:'ys.open.isapi'},body:{payload:'<EventNotificationAlert/>'}},480),{kind:'pending',reason:'EZVIZ_ISAPI_CONTRACT'});assert.equal(normalizeAlarm({...body,header:{...body.header,type:'ys.unknown'}},480).kind,'pending');});
test('图片仅明确未加密才安排；crypt/URL矛盾或缺标记保持待核',()=>{assert.equal(normalizeAlarm({...body,body:{...body.body,pictureList:[{}]}},480).kind,'alarm');for(const [crypt,url]of [[1,'https://media.example.com/p?isEncrypted=0'],[0,'https://media.example.com/p?isEncrypted=1'],[0,'https://media.example.com/p'],[0,'https://media.example.com/p?isEncrypted=0&isEncrypt=1']]){const r=normalizeAlarm({...body,body:{...body.body,crypt,pictureList:[{id:'p',url}]}},480);assert.equal(r.kind,'alarm');if(r.kind==='alarm')assert.equal(r.pictures[0].plaintext,false);}});
