import test from 'node:test';import assert from 'node:assert/strict';
import {compute,type Definition} from '../../src/modules/analysis/calculate';
import {terms,chunkMarkdown} from '../../src/modules/knowledge/chunks';
import {redact,validateAnswer} from '../../src/modules/assistant/validate';
import {comparisonAllowed} from '../../src/modules/weather/service';
const d:Definition={formula:'mean',inputUnit:'mg/L',unit:'mg/L',intervalMs:60000,maxGapMs:120000,minimumCoverage:.9,threshold:null,comparison:'lt',timezone:'UTC',baseTemperature:null,capTemperature:null,species:null,stage:null,variety:null,startDate:null};
const from='2026-09-01T00:00:00Z',to='2026-09-01T00:04:00Z',at=new Date(to);
const samples=[0,1,2,3].map((i)=>({id:String(i),sampledAt:new Date(Date.parse(from)+i*60000).toISOString(),value:i,unit:'mg/L',valid:true}));
test('C01有效零保留，固定窗口均值极值完整率可复算',()=>{assert.equal(compute(d,samples,from,to,at).value,1.5);assert.equal(compute({...d,formula:'min'},samples,from,to,at).value,0);assert.equal(compute({...d,formula:'max'},samples,from,to,at).value,3);assert.equal(compute({...d,formula:'coverage',unit:'ratio'},samples,from,to,at).value,1);});
test('C01缺测与无效不补0，不跨缺测累计连续超标',()=>{const r=compute({...d,formula:'duration',unit:'min',threshold:5,maxGapMs:60000},samples.filter(s=>s.id!=='1'),from,to,at);assert.equal(r.value,null);assert.equal(r.observedValue,1);assert.equal(r.status,'insufficient');assert(r.limitations.some(x=>x.includes('缺测')));const invalid=compute(d,samples.map(s=>({...s,valid:false})),from,to,at);assert.equal(invalid.value,null);assert.equal(invalid.coverage,0);});
test('C01审核积温从起算日逐日累加，部分日期不冒充完整日',()=>{const g={...d,formula:'gdd' as const,inputUnit:'°C',unit:'°C·d',intervalMs:3600000,maxGapMs:7200000,baseTemperature:10,startDate:from},values=Array.from({length:48},(_,i)=>({id:String(i),sampledAt:new Date(Date.parse(from)+i*3600000).toISOString(),value:20,unit:'°C',valid:true})),end='2026-09-03T00:00:00Z';assert.equal(compute(g,values,from,end,new Date(end)).value,20);assert.equal(compute(g,values,from,end,new Date('2026-09-02T01:00:00Z')).status,'insufficient');});
test('C02中文农业关键词和跨段表格的表头单位保留',()=>{assert(terms('小龙虾溶解氧不足，检查氨氮').includes('溶解氧'));const chunks=chunkMarkdown('# 水质\n| 指标 | 单位 | 限制 |\n|---|---|---|\n'+Array.from({length:20},()=> '| 溶解氧 | mg/L | 未经现场复核不采用 |').join('\n'),180);assert(chunks.length>1);assert(chunks.every(c=>c.text.includes('mg/L')||c.text.includes('单位')));});
test('C03输入脱敏、越权引用、虚构数字、遗漏限制和工具注入均拦截',()=>{assert(!redact('张三 电话13800138000，经度114.123456，纬度30.123456',['张三']).includes('13800138000'));const evidence:any=[{chunkId:'c',text:'参考值5 mg/L'}],facts=[{id:'m',objectCode:'O1',status:'insufficient',value:null,unit:'mg/L',limitations:['暂不能判断']}];assert.equal(validateAnswer({claims:[{text:'暂不能判断',evidenceIds:['c'],metricIds:['m'],limitations:['暂不能判断']}]},evidence,facts).valid,true);for(const out of [{claims:[{text:'可以确定正常',evidenceIds:['secret'],metricIds:['m'],limitations:[]}]},{sql:'DELETE',claims:[]},{claims:[{text:'参考值99',evidenceIds:['c'],metricIds:[],limitations:[]}]}])assert.equal(validateAnswer(out,evidence,facts).valid,false);});
test('C01不同站点、品种、起算日或缺条件不推比较结论',()=>{const l={metric:'temperature',unit:'°C',statistic:'daily_mean',station:'S1',period:'same_day',coverage:1,species:'水稻',variety:'V1',stage:'育苗',startDate:'09-01'};assert(comparisonAllowed(l,{...l}));assert(!comparisonAllowed(l,{...l,station:'S2'}));assert(!comparisonAllowed(l,{...l,variety:undefined}));});

test('C03日期数字可以追溯到对应窗口，不能借未引用指标的数字冒充来源',()=>{const facts=[{id:'f',objectCode:'O1',status:'usable',value:7,unit:'mg/L',limitations:[],windowStart:'2026-10-01T00:00:00Z'}],evidence:any=[{chunkId:'e',text:'先人工核查'}];assert.equal(validateAnswer({claims:[{text:'O1在2026-10-01窗口观测7 mg/L',evidenceIds:[],metricIds:['f'],limitations:[]}]},evidence,facts).valid,true);assert.equal(validateAnswer({claims:[{text:'观测7 mg/L',evidenceIds:['e'],metricIds:[],limitations:[]}]},evidence,facts).valid,false);});

test('C01同一采样槽内的有效极值不丢弃，持续计算不能跳过中间无效或正常样本',()=>{const def={...d,formula:'duration' as const,unit:'min',minimumCoverage:0,threshold:5},base=samples.map(s=>({...s,value:1})),middle={id:'middle',sampledAt:'2026-09-01T00:00:30Z',value:1,unit:'mg/L',valid:false};assert.equal(compute(def,[...base,middle],from,to,at).observedValue,2);assert.equal(compute(def,[...base,{...middle,valid:true,value:8}],from,to,at).observedValue,2);assert.equal(compute({...d,formula:'max'},[...samples,{...middle,valid:true,value:8}],from,to,at).observedValue,8);});


test('C03引用资料必须保留已登记的证据性质与限制',()=>{const e:any=[{chunkId:'source',text:'先人工核查',evidenceNature:'合成工程样本，未经现场验证'}],claim={text:'先人工核查',evidenceIds:['source'],metricIds:[],limitations:[] as string[]};assert.equal(validateAnswer({claims:[claim]},e,[]).valid,false);assert.equal(validateAnswer({claims:[{...claim,limitations:[e[0].evidenceNature]}]},e,[]).valid,true);});
