import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {PassThrough} from 'node:stream';
import type {IncomingMessage,ClientRequest} from 'node:http';
import type {RequestOptions} from 'node:https';
import {downloadRemoteMedia,validateRemoteUrl,type DownloadDependencies} from '../../src/modules/media/remote-download';
const host='media.example.com',settings={allowedHosts:[host,'cdn.example.com'],maxBytes:1024,timeoutMs:1000};
const resolver=async()=>[{address:'8.8.8.8',family:4}];
function replies(rows:{status?:number;headers?:Record<string,string>;chunks?:Buffer[];hang?:boolean}[],observed:{url:string;options:RequestOptions}[]=[]):DownloadDependencies['requester']{return (url,options,callback)=>{observed.push({url:url.toString(),options});const row=rows.shift()!;assert(row,'意外的额外请求');const req=new EventEmitter() as ClientRequest;req.destroy=(e?:Error)=>{queueMicrotask(()=>req.emit('error',e??new Error()));return req;};req.end=(()=>{queueMicrotask(()=>{const res=new PassThrough() as unknown as IncomingMessage;res.statusCode=row.status??200;res.headers=row.headers??{};callback(res);if(!row.hang){for(const b of row.chunks??[Buffer.from('original')])(res as unknown as PassThrough).write(b);(res as unknown as PassThrough).end();}});return req;}) as ClientRequest['end'];return req;};}
test('远程原件URL只允许精确HTTPS域名，不允许令牌账户、IP、片段和非标准端口',()=>{for(const u of ['http://'+host+'/a','https://u:p@'+host+'/a','https://127.0.0.1/a','https://'+host+':444/a','https://'+host+'/a#token','https://'+host+'.evil.com/a','https://localhost/a'])assert.throws(()=>validateRemoteUrl(u,settings.allowedHosts),{code:'MEDIA_REMOTE_URL'});assert.equal(validateRemoteUrl('https://'+host+'/a?signature=private',settings.allowedHosts).hostname,host);});
test('远程原件DNS拒绝任一内网/保留地址及映射IPv6，不发送HTTP',async()=>{for(const address of ['127.0.0.1','10.0.0.1','169.254.169.254','192.168.0.1','100.64.0.1','192.0.2.1','224.0.0.1','::1','::ffff:8.8.8.8','fc00::1','2001:db8::1','2002:0808:0808::1'])await assert.rejects(()=>downloadRemoteMedia('https://'+host+'/a',settings,{resolver:async()=>[{address:'8.8.8.8',family:4},{address,family:address.includes(':')?6:4}],requester:()=>{throw new Error('不应请求');}}),{code:'MEDIA_REMOTE_ADDRESS'});});
test('逐跳校验DNS和白名单、HTTPS连接固定IP且不携带应用凭据',async()=>{const observed:{url:string;options:RequestOptions}[]=[],bytes=await downloadRemoteMedia('https://'+host+'/a?signature=private',settings,{resolver,requester:replies([{status:302,headers:{location:'https://cdn.example.com/f'}},{chunks:[Buffer.from('a'),Buffer.from('b')]}],observed)});assert.equal(bytes.toString(),'ab');assert.equal(observed.length,2);assert.equal(observed[0].options.agent,false);assert.equal(observed[0].options.rejectUnauthorized,true);assert.equal(observed[0].options.servername,host);assert.deepEqual(observed[0].options.headers,{'Accept-Encoding':'identity'});const lookup=observed[0].options.lookup as Function;lookup(host,{all:true},(e:unknown,r:unknown)=>{assert.equal(e,null);assert.deepEqual(r,[{address:'8.8.8.8',family:4}]);});await assert.rejects(()=>downloadRemoteMedia('https://'+host+'/a',settings,{resolver,requester:replies([{status:302,headers:{location:'https://evil.example/f?secret=private'}}])}),{code:'MEDIA_REMOTE_URL'});let n=0;await assert.rejects(()=>downloadRemoteMedia('https://'+host+'/a',settings,{resolver:async()=>++n===1?resolver():[{address:'10.0.0.1',family:4}],requester:replies([{status:302,headers:{location:'/new'}}])}),{code:'MEDIA_REMOTE_ADDRESS'});});
test('拒绝压缩、非成功响应、截断和声明/实际超限，不暴露远端错误正文',async()=>{const cases:[Record<string,unknown>,string][]=[[{headers:{'content-encoding':'gzip'}},'MEDIA_REMOTE_ENCODING'],[{status:403,chunks:[Buffer.from('signature=private')]},'MEDIA_REMOTE_HTTP'],[{headers:{'content-length':'2048'}},'MEDIA_REMOTE_SIZE'],[{headers:{'content-length':'9'},chunks:[Buffer.from('short')]},'MEDIA_REMOTE_TRUNCATED'],[{chunks:[Buffer.alloc(1025)]},'MEDIA_REMOTE_SIZE']];for(const [row,code]of cases)await assert.rejects(()=>downloadRemoteMedia('https://'+host+'/a?signature=private',settings,{resolver,requester:replies([row])}),e=>{assert.equal((e as any).code,code);assert(!String(e).includes('private'));return true;});});
test('整次DNS和下载超时、重定向次数均有上限',async()=>{await assert.rejects(()=>downloadRemoteMedia('https://'+host+'/a',{...settings,timeoutMs:20},{resolver:async()=>new Promise(()=>{}),requester:replies([])}),{code:'MEDIA_REMOTE_TIMEOUT'});await assert.rejects(()=>downloadRemoteMedia('https://'+host+'/a',{...settings,timeoutMs:20},{resolver,requester:replies([{hang:true}])}),{code:'MEDIA_REMOTE_TIMEOUT'});await assert.rejects(()=>downloadRemoteMedia('https://'+host+'/a',settings,{resolver,requester:replies(Array.from({length:4},()=>({status:302,headers:{location:'/a'}})))}),{code:'MEDIA_REMOTE_REDIRECTS'});});
