'use client';
import {useEffect} from 'react';
import {useApi} from '@/components/platform/use-api';
import ActionForm from '@/components/platform/action-form';
import {Field,Pick,type Option} from '@/components/platform/fields';
type Connection={id:string;object_id:string;source_id:string;source_name:string;version:number;settings:{host:string;latitude:number;longitude:number;days:number};location_evidence:string;evidence:string;readonly_confirmed:boolean;enabled:boolean;limit_month_requests:number};
type Run={id:string;connection_id:string;state:string;error_code:string|null;created_at:string;completed_at:string|null;attempted_at:string|null};
const labels:Record<string,string>={queued:'待执行',running:'正在读取',succeeded:'预报已同步',no_data:'成功返回空数据，暂不能判断',failed:'读取失败',blocked:'条件不足，未写入预报',unknown:'原请求结果未知，需核实'};
export default function WeatherConnections(){const me=useApi<{scopes:{action:string;objectIds:string[]}[]}>('/api/v1/me');if(me.error)return <p className="form-error">{me.error}</p>;if(!me.data)return null;const cfg=me.data.scopes.find(s=>s.action==='configure')?.objectIds??[],record=me.data.scopes.find(s=>s.action==='record')?.objectIds??[];return cfg.length?<Panel cfg={cfg} record={record}/>:null;}
function Panel({cfg,record}:{cfg:string[];record:string[]}){const data=useApi<{connections:Connection[];runs:Run[];globalReadsEnabled:boolean;credentialsConfigured:boolean}>('/api/v1/connections/weather'),objects=useApi<{items:Option[]}>('/api/v1/objects?limit=200'),sources=useApi<(Option&{object_id:string;provider:string;verified:boolean})[]>('/api/v1/sources');useEffect(()=>{if(data.data?.runs.some(r=>r.state==='queued'||r.state==='running')){const timer=setInterval(()=>void data.reload(),3000);return()=>clearInterval(timer);}},[data.data]);const error=data.error||objects.error||sources.error;if(error)return <p className="form-error">{error}</p>;
 return <details><summary>只读天气连接与同步</summary><p className="hint">只读天气连接单独启用，使用已确认网格位置。签名凭据由部署人员放入私有环境，不在此表填写。</p>{data.data&&<p>全局读取：{data.data.globalReadsEnabled?'已启用':'关闭'}；账户签名：{data.data.credentialsConfigured?'已配置，尚须账户联调':'未配置'}。</p>}
 <h2>现有连接</h2>{data.data?.connections.map(c=><section className="rule-card" key={c.id}><h2>{c.source_name} · {c.enabled?'启用':'停用'} · 版本{c.version}</h2><p>{c.location_evidence}；每月请求尝试上限{c.limit_month_requests}。</p>{record.includes(c.object_id)&&<ActionForm path="/api/v1/connections/weather/sync" stableKey numbers={['version']} onSaved={()=>void data.reload()} label="请求一次只读同步"><input type="hidden" name="connectionId" value={c.id}/><input type="hidden" name="version" value={c.version}/><p>只读取预报；任务执行前后再次检查权限与版本，失败不自动换来源。</p></ActionForm>}<details><summary>修改配置与启停</summary><ConnectionForm connection={c} objects={objects.data?.items.filter(o=>cfg.includes(o.id))??[]} sources={sources.data??[]} saved={()=>void data.reload()}/></details><ul>{data.data!.runs.filter(r=>r.connection_id===c.id).map(r=><li key={r.id}>{labels[r.state]??r.state}；{new Date(r.created_at).toLocaleString()}；{r.attempted_at?'已尝试请求，费用待账单核对':'未尝试请求'}{r.error_code?'；'+r.error_code:''}</li>)}</ul></section>)}
 <details><summary>登记新天气连接</summary><ConnectionForm objects={objects.data?.items.filter(o=>cfg.includes(o.id))??[]} sources={sources.data??[]} saved={()=>void data.reload()}/></details></details>;
}
function ConnectionForm({connection:c,objects,sources,saved}:{connection?:Connection;objects:Option[];sources:(Option&{object_id:string;provider:string;verified:boolean})[];saved:()=>void}){return <ActionForm path="/api/v1/connections/weather" numbers={['version','latitude','longitude','days','limitMonthRequests']} booleans={['enabled','readOnlyConfirmed']} onSaved={saved} label="保存天气连接">{c?<><input type="hidden" name="id" value={c.id}/><input type="hidden" name="version" value={c.version}/><input type="hidden" name="objectId" value={c.object_id}/><input type="hidden" name="sourceId" value={c.source_id}/></>:<><Pick name="objectId" label="连接对象" options={objects}/><Pick name="sourceId" label="已核实的qweather来源" options={sources.filter(s=>s.provider==='qweather'&&s.verified)}/><p className="hint">来源尚未登记时，先在配置管理中登记本对象的qweather来源并核实。</p></>}
 <label>账户专用HTTPS域名<input name="host" type="url" defaultValue={c?.settings.host} required placeholder="控制台分配的域名"/></label><label>已确认网格纬度<input name="latitude" type="number" step=".01" min="-90" max="90" defaultValue={c?.settings.latitude} required/></label><label>已确认网格经度<input name="longitude" type="number" step=".01" min="-180" max="180" defaultValue={c?.settings.longitude} required/></label><label>预报天数<input name="days" type="number" min="1" max="10" defaultValue={c?.settings.days??7} required/></label><label>每月请求尝试上限<input name="limitMonthRequests" type="number" min="1" max="100000" defaultValue={c?.limit_month_requests} required/></label><label>网格位置及适用对象确认依据<textarea name="locationEvidence" defaultValue={c?.location_evidence} required/></label><label>账户只读权限与数据使用许可依据<textarea name="evidence" defaultValue={c?.evidence} required/></label><label><input type="checkbox" name="readOnlyConfirmed" defaultChecked={c?.readonly_confirmed}/>已确认只读权限、地点和数据使用范围</label><label><input type="checkbox" name="enabled" defaultChecked={c?.enabled}/>启用此连接（全局读取开关仍单独控制）</label></ActionForm>;}
