import type {Pool,PoolClient} from 'pg';
import {randomUUID} from 'node:crypto';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {text,integer,choice} from '../../platform/validation';
import {transaction,database} from '../../db/pool';
import {uuid,audit} from '../identity/common';
import {scope,existingObject,sameHash} from '../field/common';
import {listAccessibleObjects} from '../identity/access';
import {encryptSecret,decryptSecret} from '../identity/mfa';
import {enqueue,type JobLease} from '../jobs/repository';
import {receiveCameraEvent} from '../cameras/service';
import {requestRemoteImport} from '../media/remote-import';
import {verifyWebhook,normalizeAlarm,EZVIZ_WEBHOOK_CONTRACT,type Message} from '../../adapters/ezviz/webhook';
interface Binding{deviceId:string;deviceSerial:string;channel:number}
interface Settings{bindings:Binding[];offsetMinutes:number;clockEvidence:string;imageMime:string;autoImages:boolean}
async function testOnly(c:PoolClient){if((await c.query('SELECT current_database() AS n')).rows[0].n!=='agri_test')throw new AppError(403,'EZVIZ_TEST_ONLY','替身环境或无租约执行只允许隔离测试库');}
async function device(c:PoolClient,id:string){uuid(id);return(await c.query('SELECT d.*,p.serial_number AS parent_serial,p.verified AS parent_verified FROM devices d LEFT JOIN devices p ON p.id=d.parent_device_id WHERE d.id=$1 FOR SHARE OF d',[id])).rows[0];}
async function checkBinding(c:PoolClient,r:any,b:Binding){const d=await device(c,b.deviceId),parent=d?.kind==='camera_channel'?(await c.query('SELECT * FROM devices WHERE id=$1 FOR SHARE',[d.parent_device_id])).rows[0]:null,serial=d?.kind==='camera_channel'?parent?.serial_number:d?.serial_number;if(!d?.verified||d.source_id!==r.source_id||d.object_id!==r.object_id||serial!==b.deviceSerial||(d.kind==='camera_channel'&&(!parent?.verified||parent.source_id!==r.source_id||parent.object_id!==r.object_id)))throw new AppError(409,'EZVIZ_BINDING','设备/通道、上级序列号或来源映射尚未核实');return d;}
async function actor(c:PoolClient,id:string,version?:number):Promise<Actor>{uuid(id);const u=(await c.query('SELECT role,enabled,auth_version FROM users WHERE id=$1 FOR SHARE',[id])).rows[0];if(!u?.enabled||(version!==undefined&&u.auth_version!==version))throw new AppError(403,'EZVIZ_ACTOR','执行人员账号或身份已变更');return {id,role:u.role,enabled:true,mfaVerified:true};}
async function connection(c:PoolClient,id:string){uuid(id);const r=(await c.query('SELECT e.*,s.provider,s.verified AS source_verified,s.object_id AS source_object,s.contract_ref FROM ezviz_connections e JOIN data_sources s ON s.id=e.source_id WHERE e.id=$1 FOR SHARE OF e,s',[id])).rows[0];if(!r)throw new AppError(404,'EZVIZ_CONNECTION','消息连接不存在');return r;}
async function enabled(c:PoolClient,r:any,env:NodeJS.ProcessEnv){if(env.EZVIZ_WEBHOOK_ENABLED!=='1')throw new AppError(503,'EZVIZ_DISABLED','厂家消息接收全局关闭');if(!r.enabled)throw new AppError(409,'EZVIZ_CONNECTION_DISABLED','消息连接停用');if(!r.source_verified||r.provider!=='ezviz'||r.source_object!==r.object_id||!r.contract_ref||!r.readonly_confirmed||!r.reminder_handover_confirmed)throw new AppError(409,'EZVIZ_SOURCE','来源、只读范围或提醒交接尚未确认');const a=await actor(c,r.processor_id,r.processor_auth_version);await scope(c,a,r.object_id,'read');await scope(c,a,r.object_id,'record');return a;}
export async function saveEzvizConnection(c:PoolClient,a:Actor,b:Record<string,unknown>){
 const o=await existingObject(c,a,b,'configure');uuid(b.sourceId);uuid(b.processorId);const s=(await c.query('SELECT * FROM data_sources WHERE id=$1 FOR SHARE',[b.sourceId])).rows[0];if(s?.object_id!==o.id||s.provider!=='ezviz'||!s.verified||!s.contract_ref)throw new AppError(422,'EZVIZ_SOURCE','请先核实同对象ezviz来源及接口资料');
 const p=await actor(c,b.processorId);await scope(c,p,o.id,'read');await scope(c,p,o.id,'record');const offset=integer(b.offsetMinutes,'已确认设备时区偏移',-840,840);if(!Array.isArray(b.bindings)||!b.bindings.length||b.bindings.length>200)throw new AppError(400,'EZVIZ_BINDING','映射须包含1至200个已核实设备/通道');
 const bindings:Binding[]=b.bindings.map((x:any)=>{uuid(x.deviceId);return {deviceId:x.deviceId,deviceSerial:text(x.deviceSerial,'厂家序列号',120),channel:integer(x.channel,'厂家通道号',0,65535)};});if(new Set(bindings.map(x=>x.deviceSerial+':'+x.channel)).size!==bindings.length||new Set(bindings.map(x=>x.deviceId)).size!==bindings.length)throw new AppError(400,'EZVIZ_BINDING','同一设备或厂家序列号/通道映射不能重复');for(const binding of bindings)await checkBinding(c,{source_id:b.sourceId,object_id:o.id},binding);
 const settings:Settings={bindings,offsetMinutes:offset,clockEvidence:text(b.clockEvidence,'设备时钟核实依据',2000),imageMime:choice(b.imageMime,['image/jpeg','image/png','image/webp','image/tiff'] as const,'已确认图片格式'),autoImages:b.autoImages===true},readonly=b.readOnlyConfirmed===true,handover=b.appReminderHandoverConfirmed===true,on=b.enabled===true,evidence=text(b.evidence,'只读范围及原提醒交接依据',3000);if(on&&(!readonly||!handover))throw new AppError(422,'EZVIZ_CONFIRM','启用前须确认只读范围及原APP提醒交接');const auth=(await c.query('SELECT auth_version FROM users WHERE id=$1',[p.id])).rows[0].auth_version;let row;
 if(b.id){uuid(b.id);const old=(await c.query('SELECT * FROM ezviz_connections WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!old||old.object_id!==o.id||old.source_id!==b.sourceId)throw new AppError(409,'EZVIZ_CONNECTION_SCOPE','连接来源或对象不可改写');if(integer(b.version,'连接版本')!==old.version)throw new AppError(409,'VERSION_CONFLICT','连接已变更，请刷新');row=(await c.query('UPDATE ezviz_connections SET version=version+1,settings=$2,processor_id=$3,processor_auth_version=$4,readonly_confirmed=$5,reminder_handover_confirmed=$6,enabled=$7,evidence=$8,configured_by=$9,configured_at=now() WHERE id=$1 RETURNING *',[old.id,settings,p.id,auth,readonly,handover,on,evidence,a.id])).rows[0];}
 else{row=(await c.query('INSERT INTO ezviz_connections(object_id,source_id,settings,processor_id,processor_auth_version,readonly_confirmed,reminder_handover_confirmed,enabled,evidence,configured_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(source_id) DO NOTHING RETURNING *',[o.id,b.sourceId,settings,p.id,auth,readonly,handover,on,evidence,a.id])).rows[0];if(!row)throw new AppError(409,'EZVIZ_CONNECTION_EXISTS','来源已有消息连接，请修改当前版本');}
 await c.query('INSERT INTO ezviz_connection_versions(connection_id,version,snapshot,actor_id) VALUES($1,$2,$3,$4)',[row.id,row.version,row,a.id]);await audit(c,a.id,'ezviz_connection_configured',row.id);return row;
}
export async function receiveEzvizWebhook(c:PoolClient,id:string,raw:Buffer,headers:Headers,env:NodeJS.ProcessEnv=process.env){
 if(env!==process.env)await testOnly(c);if(env.EZVIZ_WEBHOOK_ENABLED!=='1')throw new AppError(503,'EZVIZ_DISABLED','厂家消息接收全局关闭');const verified=verifyWebhook(raw,headers,env.EZVIZ_WEBHOOK_SECRET??''),r=await connection(c,id);await enabled(c,r,env);const h=verified.message.header,messageId=String(h.messageId);
 await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['ezviz-message:'+id+':'+messageId]);const prior=(await c.query('SELECT content_hash FROM ezviz_receipts WHERE connection_id=$1 AND message_id=$2',[id,messageId])).rows[0];if(prior){sameHash(prior.content_hash,verified.contentHash);return {messageId};}
 const receiptId=randomUUID(),encrypted=encryptSecret(JSON.stringify(verified.message),'ezviz-receipt:'+receiptId,env.IDENTITY_ENCRYPTION_KEY),channel=typeof h.channelNo==='number'&&Number.isInteger(h.channelNo)&&h.channelNo>=0&&h.channelNo<=65535?h.channelNo:null,pushed=typeof h.messageTime==='number'&&Number.isSafeInteger(h.messageTime)&&h.messageTime>0&&h.messageTime<8640000000000000?new Date(h.messageTime).toISOString():null;
 await c.query('INSERT INTO ezviz_receipts(id,connection_id,configuration_version,object_id,source_id,source_contract_ref,processor_id,processor_auth_version,message_id,message_type,device_serial,channel_no,pushed_at,signature_at,raw_sha256,content_hash,encrypted_message) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)',[receiptId,id,r.version,r.object_id,r.source_id,r.contract_ref,r.processor_id,r.processor_auth_version,messageId,h.type,h.deviceId,channel,pushed,verified.signatureTime,verified.rawHash,verified.contentHash,encrypted]);
 await enqueue(c,{kind:'camera.receive',businessKey:'camera-receive:'+receiptId,payload:{receiptId},dueAt:new Date().toISOString(),priority:95});return {messageId};
}
interface RunOptions{env?:NodeJS.ProcessEnv;lease?:JobLease}
async function lease(c:PoolClient,id:string,o:RunOptions,kind='camera.receive'){if(o.lease&&!(await c.query("SELECT 1 FROM jobs WHERE id=$1 AND lease_token=$2 AND state='running' AND lease_until>clock_timestamp() AND kind=$4 AND payload->>'receiptId'=$3 FOR SHARE",[o.lease.id,o.lease.leaseToken,id,kind])).rowCount)throw new AppError(409,'EZVIZ_LEASE','消息处理租约失效');}
async function current(c:PoolClient,r:any,env:NodeJS.ProcessEnv){const cfg=await connection(c,r.connection_id),a=await enabled(c,cfg,env);if(cfg.version!==r.configuration_version||cfg.contract_ref!==r.source_contract_ref||cfg.processor_id!==r.processor_id||cfg.processor_auth_version!==r.processor_auth_version)throw new AppError(409,'EZVIZ_CONFIGURATION_CHANGED','来源、执行人员或连接版本已改变，旧消息等待核对');return {cfg,a};}
export async function runEzvizReceipt(pool:Pool,id:string,o:RunOptions={}){
 uuid(id);if(o.env||!o.lease)await database(testOnly,pool);const env=o.env??process.env;
 try{
 await transaction(async c=>{const r=(await c.query('SELECT * FROM ezviz_receipts WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r||r.state!=='queued')return null;await lease(c,id,o);const {cfg,a}=await current(c,r,env),m=JSON.parse(decryptSecret(r.encrypted_message,'ezviz-receipt:'+id,env.IDENTITY_ENCRYPTION_KEY)) as Message,alarm=normalizeAlarm(m,cfg.settings.offsetMinutes);
 if(alarm.kind==='pending'){await c.query("UPDATE ezviz_receipts SET state='awaiting_contract',error_code=$2,processed_at=now() WHERE id=$1",[id,alarm.reason]);return null;}
 const binding=(cfg.settings as Settings).bindings.find(x=>x.deviceSerial===alarm.deviceSerial&&x.channel===alarm.channel);if(!binding){await c.query("UPDATE ezviz_receipts SET state='awaiting_contract',error_code='EZVIZ_UNMAPPED_CHANNEL',processed_at=now() WHERE id=$1",[id]);return null;}await checkBinding(c,cfg,binding);
 const event=await receiveCameraEvent(c,a,{deviceId:binding.deviceId,externalEventId:'ezviz:'+alarm.alarmId,contractVersion:EZVIZ_WEBHOOK_CONTRACT,occurredAt:alarm.occurredAt,eventType:alarm.eventType});await lease(c,id,o);await current(c,r,env);
 const image=alarm.pictures[0]??null,imageState=!image?'none':!image.plaintext?'encrypted':!cfg.settings.autoImages?'disabled':'pending';await c.query("UPDATE ezviz_receipts SET state='processed',camera_event_id=$2,image_state=$3,error_code=NULL,processed_at=now() WHERE id=$1",[id,event.id,imageState]);if(imageState==='pending')await enqueue(c,{kind:'camera.image',businessKey:'camera-image:'+id,payload:{receiptId:id},dueAt:new Date().toISOString(),priority:40});
 },pool);
 }catch(e){await pool.query("UPDATE ezviz_receipts SET state=$2,error_code=$3,processed_at=now() WHERE id=$1 AND state='queued'",[id,e instanceof AppError&&(e.status===403||e.status===409||e.code==='EZVIZ_DISABLED')?'blocked':'failed',e instanceof AppError?e.code:'EZVIZ_PROCESS_FAILED']);}
}
export async function runEzvizImage(pool:Pool,id:string,o:RunOptions={}){
 uuid(id);if(o.env||!o.lease)await database(testOnly,pool);const env=o.env??process.env;
 try{await transaction(async c=>{const r=(await c.query('SELECT * FROM ezviz_receipts WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r||r.state!=='processed'||r.image_state!=='pending')return;await lease(c,id,o,'camera.image');const {cfg,a}=await current(c,r,env),message=JSON.parse(decryptSecret(r.encrypted_message,'ezviz-receipt:'+id,env.IDENTITY_ENCRYPTION_KEY)) as Message,alarm=normalizeAlarm(message,cfg.settings.offsetMinutes);if(alarm.kind!=='alarm'||!alarm.pictures[0]?.plaintext)throw new AppError(409,'EZVIZ_IMAGE_CONTRACT','图片契约或明文状态未核实');
 await requestRemoteImport(c,a,{targetKind:'camera_event',targetId:r.camera_event_id,requestKey:'ezviz-image:'+id,url:alarm.pictures[0].url,name:'告警原图'+(cfg.settings.imageMime==='image/png'?'.png':cfg.settings.imageMime==='image/jpeg'?'.jpg':cfg.settings.imageMime==='image/webp'?'.webp':'.tiff'),mime:cfg.settings.imageMime,evidence:'已核实萤石消息原件，来源契约 '+cfg.contract_ref,readOnlyConfirmed:true,plaintextConfirmed:true},env);await lease(c,id,o,'camera.image');await c.query("UPDATE ezviz_receipts SET image_state='queued',image_error=NULL WHERE id=$1",[id]);},pool);}catch(e){await pool.query("UPDATE ezviz_receipts SET image_state='failed',image_error=$2 WHERE id=$1 AND state='processed' AND image_state='pending'",[id,e instanceof AppError?e.code:'EZVIZ_IMAGE_FAILED']);}
}
export async function listEzvizConnections(c:PoolClient,a:Actor){const ids=await listAccessibleObjects(c,a,'configure'),connections=(await c.query('SELECT e.*,s.name AS source_name FROM ezviz_connections e JOIN data_sources s ON s.id=e.source_id WHERE e.object_id=ANY($1::uuid[]) ORDER BY e.configured_at DESC',[ids])).rows,rows=(await c.query(`SELECT r.id,r.connection_id,r.message_id,r.message_type,r.state,r.error_code,r.received_at,r.pushed_at,r.processed_at,r.camera_event_id,r.image_state,r.image_error,e.alert_id,m.state AS import_state,m.error_code AS import_error FROM ezviz_receipts r LEFT JOIN camera_events e ON e.id=r.camera_event_id LEFT JOIN remote_media_imports m ON m.requested_by=r.processor_id AND m.request_key='ezviz-image:'||r.id::text WHERE r.object_id=ANY($1::uuid[]) ORDER BY r.received_at DESC LIMIT 200`,[ids])).rows;return {connections:connections.map(r=>({...r,callbackPath:'/api/v1/ingress/ezviz/'+r.id})),receipts:rows.map(r=>({id:r.id,connectionId:r.connection_id,messageId:r.message_id,messageType:r.message_type,state:r.state,errorCode:r.error_code,receivedAt:r.received_at,pushedAt:r.pushed_at,processedAt:r.processed_at,cameraEventId:r.camera_event_id,alertId:r.alert_id,imageState:r.image_state==='queued'&&r.import_state==='complete'?'complete':r.image_state==='queued'&&['failed','blocked','unknown'].includes(r.import_state)?'failed':r.image_state,imageError:r.import_error??r.image_error})),globalEnabled:process.env.EZVIZ_WEBHOOK_ENABLED==='1',signatureConfigured:!!process.env.EZVIZ_WEBHOOK_SECRET};}
