import type {Pool,PoolClient} from 'pg';
import {createCipheriv,randomBytes,createHash} from 'node:crypto';
import type {Actor} from '../../platform/types';
import {AppError} from '../../platform/error';
import {integer,text} from '../../platform/validation';
import {transaction,database} from '../../db/pool';
import {scope,existingObject,lockKey,payloadHash,sameHash} from '../field/common';
import {listAccessibleObjects} from '../identity/access';
import {uuid,audit} from '../identity/common';
import {enqueue,type JobLease} from '../jobs/repository';
import {recordUsage} from '../operations/budget';
import {importWeather} from '../weather/service';
import {configuredCredentials,makeJwt,readDaily,validateSettings,QWEATHER_CONTRACT,type Credentials,type Settings} from '../../adapters/qweather/client';
export async function saveConnection(c:PoolClient,a:Actor,b:Record<string,unknown>){
 const allowed=['id','version','objectId','sourceId','host','latitude','longitude','days','locationEvidence','readOnlyConfirmed','enabled','limitMonthRequests','evidence'];if(Object.keys(b).some(k=>!allowed.includes(k)))throw new AppError(400,'WEATHER_SETTINGS','天气连接只保存公开设置，不接收密钥或其他字段');
 const object=await existingObject(c,a,b,'configure');uuid(b.sourceId);const source=(await c.query('SELECT * FROM data_sources WHERE id=$1 FOR SHARE',[b.sourceId])).rows[0];if(source?.object_id!==object.id||source.provider!=='qweather'||!source.verified)throw new AppError(422,'WEATHER_SOURCE','请先登记并核实此对象的qweather来源');
 const settings=validateSettings({host:String(b.host),latitude:b.latitude as number,longitude:b.longitude as number,days:integer(b.days,'预报天数',1,10)}),limit=integer(b.limitMonthRequests,'每月最大请求尝试',1,100000),location=text(b.locationEvidence,'地点网格确认依据',2000),evidence=text(b.evidence,'只读权限与数据使用许可依据',3000),confirmed=b.readOnlyConfirmed===true,enabled=b.enabled===true;if(enabled&&!confirmed)throw new AppError(422,'WEATHER_READONLY_CONFIRM','启用前须确认只读权限和数据使用范围');
 let id:string;
 if(b.id){uuid(b.id);const old=(await c.query('SELECT * FROM weather_connections WHERE id=$1 FOR UPDATE',[b.id])).rows[0];if(!old||old.object_id!==object.id||old.source_id!==b.sourceId)throw new AppError(422,'CONNECTION_SCOPE','已有连接的对象和来源不能改写');if(integer(b.version,'连接版本')!==old.version)throw new AppError(409,'VERSION_CONFLICT','连接已变更，请刷新后继续');id=old.id;await c.query('UPDATE weather_connections SET version=version+1,settings=$2,location_evidence=$3,evidence=$4,readonly_confirmed=$5,enabled=$6,limit_month_requests=$7,configured_by=$8,configured_at=now() WHERE id=$1',[id,settings,location,evidence,confirmed,enabled,limit,a.id]);}
 else{const r=(await c.query('INSERT INTO weather_connections(object_id,source_id,settings,location_evidence,evidence,readonly_confirmed,enabled,limit_month_requests,configured_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(object_id,source_id) DO NOTHING RETURNING id',[object.id,b.sourceId,settings,location,evidence,confirmed,enabled,limit,a.id])).rows[0];if(!r)throw new AppError(409,'CONNECTION_EXISTS','对象与来源已有连接，请修改其当前版本');id=r.id;}
 const row=(await c.query('SELECT * FROM weather_connections WHERE id=$1',[id])).rows[0];await c.query('INSERT INTO weather_connection_versions(connection_id,version,snapshot,actor_id) VALUES($1,$2,$3,$4)',[id,row.version,row,a.id]);await audit(c,a.id,'weather_connection_configured',id);return row;
}
async function readConnection(c:PoolClient,id:string){uuid(id);const r=(await c.query('SELECT w.*,s.provider,s.verified AS source_verified,s.object_id AS source_object FROM weather_connections w JOIN data_sources s ON s.id=w.source_id WHERE w.id=$1 FOR SHARE OF w,s',[id])).rows[0];if(!r)throw new AppError(404,'CONNECTION_NOT_FOUND','天气连接不存在');return r;}
async function checkConnection(c:PoolClient,a:Actor,r:any,version:number){await scope(c,a,r.object_id,'read');await scope(c,a,r.object_id,'record');if(r.version!==version)throw new AppError(409,'CONNECTION_VERSION_CHANGED','连接已变更，旧请求结果不入库');if(!r.enabled)throw new AppError(409,'CONNECTION_DISABLED','天气连接停用中');if(!r.readonly_confirmed||!r.source_verified||r.provider!=='qweather'||r.source_object!==r.object_id)throw new AppError(409,'WEATHER_SOURCE','来源或只读授权尚未确认');}
export async function requestSync(c:PoolClient,a:Actor,b:Record<string,unknown>){
 uuid(b.connectionId);const r=await readConnection(c,b.connectionId),version=integer(b.version,'连接版本'),key=text(b.requestKey,'同步标识',120);await checkConnection(c,a,r,version);const hash=payloadHash({connectionId:r.id,version});await lockKey(c,a,'weather-sync',key);const prior=(await c.query('SELECT id,state,input_hash FROM weather_sync_runs WHERE requested_by=$1 AND request_key=$2',[a.id,key])).rows[0];if(prior){sameHash(prior.input_hash,hash);return {id:prior.id,state:prior.state};}
 await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['weather-quota:'+r.id]);const quota=(await c.query(`SELECT count(*)::int AS n FROM weather_sync_runs WHERE connection_id=$1 AND ((attempted_at IS NOT NULL AND date_trunc('month',attempted_at AT TIME ZONE 'Asia/Shanghai')=date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')) OR(attempted_at IS NULL AND state IN('queued','running') AND date_trunc('month',created_at AT TIME ZONE 'Asia/Shanghai')=date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')))`,[r.id])).rows[0].n;if(quota>=r.limit_month_requests)throw new AppError(429,'WEATHER_REQUEST_LIMIT','本月请求尝试及待执行请求已达上限');const user=(await c.query('SELECT auth_version FROM users WHERE id=$1',[a.id])).rows[0],run=(await c.query('INSERT INTO weather_sync_runs(connection_id,configuration_version,object_id,requested_by,auth_version,request_key,input_hash) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,state',[r.id,version,r.object_id,a.id,user.auth_version,key,hash])).rows[0];await enqueue(c,{kind:'weather.sync',businessKey:'weather-sync:'+run.id,payload:{runId:run.id},dueAt:new Date().toISOString()});return run;
}
async function currentActor(c:PoolClient,run:any):Promise<Actor>{const u=(await c.query('SELECT role,enabled,auth_version FROM users WHERE id=$1',[run.requested_by])).rows[0];if(!u?.enabled||u.auth_version!==run.auth_version)throw new AppError(403,'WEATHER_ACTOR_CHANGED','发起人账号或身份已改变');return {id:run.requested_by,role:u.role,enabled:true,mfaVerified:true};}
interface Options{credentials?:Credentials;encryptionKey?:string;fetcher?:typeof fetch;lease?:JobLease;env?:NodeJS.ProcessEnv}
async function checkLease(c:PoolClient,runId:string,options:Options){if(options.lease){if(!(await c.query("SELECT 1 FROM jobs WHERE id=$1 AND lease_token=$2 AND state='running' AND lease_until>clock_timestamp() AND kind='weather.sync' AND payload->>'runId'=$3",[options.lease.id,options.lease.leaseToken,runId])).rowCount)throw new AppError(409,'WEATHER_LEASE_LOST','天气任务租约失效，旧执行结果不写入');}}
function seal(bytes:Buffer,id:string,key:string){const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',Buffer.from(key,'hex'),nonce);cipher.setAAD(Buffer.from('weather-response:'+id));const encrypted=Buffer.concat([cipher.update(bytes),cipher.final()]);return Buffer.concat([nonce,cipher.getAuthTag(),encrypted]).toString('base64url');}
export async function runSync(pool:Pool,id:string,options:Options={}){
 uuid(id);const databaseName=(await pool.query('SELECT current_database() AS name')).rows[0].name;if((options.fetcher||options.credentials||options.encryptionKey||!options.lease)&&databaseName!=='agri_test')throw new AppError(403,'WEATHER_TEST_ONLY','替身客户端和无租约调用仅允许隔离测试库');
 const run=await transaction(async c=>{await checkLease(c,id,options);const r=(await c.query('SELECT * FROM weather_sync_runs WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)return null;if(r.state==='running'){await c.query("UPDATE weather_sync_runs SET state='unknown',error_code='WEATHER_PREVIOUS_RESULT_UNKNOWN',completed_at=now() WHERE id=$1",[id]);if(r.attempted_at)await recordUsage(c,{objectId:r.object_id,category:'weather',businessKey:'weather-request:'+r.id,occurredAt:r.attempted_at.toISOString(),units:1,amount:null});return null;}if(r.state!=='queued'){if(r.attempted_at)await recordUsage(c,{objectId:r.object_id,category:'weather',businessKey:'weather-request:'+r.id,occurredAt:r.attempted_at.toISOString(),units:1,amount:null});return null;}await c.query("UPDATE weather_sync_runs SET state='running',started_at=now() WHERE id=$1",[id]);return r;},pool);if(!run)return;
 const env=options.env??process.env;let attempted=false,attemptedAt:string|null=null,responseSha:string|null=null,encrypted:string|null=null;
 try{
 const prepared=await database(async c=>{const a=await currentActor(c,run),r=await readConnection(c,run.connection_id);await checkConnection(c,a,r,run.configuration_version);return {a,connection:r};},pool);
 if(!options.fetcher&&env.QWEATHER_READS_ENABLED!=='1')throw new AppError(503,'WEATHER_READS_DISABLED','全局天气读取关闭，未调用服务');const credentials=options.credentials??configuredCredentials(env);makeJwt(credentials);const key=options.encryptionKey??env.IDENTITY_ENCRYPTION_KEY;if(!key||!/^[a-f0-9]{64}$/.test(key))throw new AppError(503,'WEATHER_ARCHIVE_KEY','天气原响应加密配置缺失');
 await transaction(async c=>{await checkLease(c,id,options);const a=await currentActor(c,run),r=await readConnection(c,run.connection_id);await checkConnection(c,a,r,run.configuration_version);await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['weather-quota:'+r.id]);const used=(await c.query("SELECT count(*)::int AS n FROM weather_sync_runs WHERE connection_id=$1 AND id<>$2 AND((attempted_at IS NOT NULL AND date_trunc('month',attempted_at AT TIME ZONE 'Asia/Shanghai')=date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')) OR(attempted_at IS NULL AND state IN('queued','running') AND date_trunc('month',created_at AT TIME ZONE 'Asia/Shanghai')=date_trunc('month',now() AT TIME ZONE 'Asia/Shanghai')))",[r.id,id])).rows[0].n;if(used>=r.limit_month_requests)throw new AppError(429,'WEATHER_REQUEST_LIMIT','本月请求额度已不足，未再次读取');const changed=await c.query("UPDATE weather_sync_runs SET attempted_at=now() WHERE id=$1 AND state='running' AND attempted_at IS NULL RETURNING id,attempted_at",[id]);if(!changed.rowCount)throw new AppError(409,'WEATHER_PREVIOUS_RESULT_UNKNOWN','原请求结果未知，不重复读取');attemptedAt=changed.rows[0].attempted_at.toISOString();},pool);attempted=true;
 const result=await readDaily(prepared.connection.settings as Settings,credentials,options.fetcher??fetch);responseSha=createHash('sha256').update(result.raw).digest('hex');encrypted=seal(result.raw,id,key);
 await transaction(async c=>{await checkLease(c,id,options);const a=await currentActor(c,run),connection=await readConnection(c,run.connection_id);await checkConnection(c,a,connection,run.configuration_version);if((await c.query('SELECT state FROM weather_sync_runs WHERE id=$1 FOR UPDATE',[id])).rows[0].state!=='running')throw new AppError(409,'WEATHER_PREVIOUS_RESULT_UNKNOWN','请求状态已变为未知，不接收旧执行结果');
 await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['weather-source:'+connection.id+':'+connection.version+':'+result.tag]);const normalized={tag:result.tag,attributions:result.attributions,days:result.days},hash=payloadHash(normalized),prior=(await c.query('SELECT * FROM weather_source_versions WHERE connection_id=$1 AND configuration_version=$2 AND source_tag=$3',[connection.id,connection.version,result.tag])).rows[0];if(prior&&prior.content_hash!==hash)throw new AppError(409,'WEATHER_TAG_CONFLICT','同一源标识返回不同内容，旧预报保留待核');const ids:string[]=prior?.record_ids??[];
 if(!prior){for(const day of result.days){const record=await importWeather(c,a,{objectId:connection.object_id,kind:'forecast',source:'和风天气',sourceVersion:QWEATHER_CONTRACT,stationRef:connection.location_evidence,publishedAt:null,validFrom:day.from,validTo:day.to,content:{schema:'qweather-daily-v1',...day,tag:result.tag,attributions:result.attributions,limitations:['外部预报不代表现场实况','厂家未提供发布时间']},comparisonBasis:{contract:QWEATHER_CONTRACT,connectionId:connection.id,configurationVersion:connection.version,sourceId:connection.source_id},requestKey:'weather:'+connection.id+':'+connection.version+':'+payloadHash({tag:result.tag,from:day.from})});ids.push(record.id);}await c.query('INSERT INTO weather_source_versions(connection_id,configuration_version,source_tag,content_hash,record_ids) VALUES($1,$2,$3,$4,$5)',[connection.id,connection.version,result.tag,hash,ids]);}
 await scope(c,a,connection.object_id,'record');await c.query('UPDATE weather_sync_runs SET state=$2,completed_at=now(),response_sha256=$3,encrypted_response=$4,record_ids=$5 WHERE id=$1',[id,result.days.length?'succeeded':'no_data',responseSha,encrypted,ids]);
 },pool);
 }catch(e){const code=e instanceof AppError?e.code:'WEATHER_SYNC_FAILED',blocked=e instanceof AppError&&(e.status===403||e.status===409||['WEATHER_READS_DISABLED','WEATHER_NOT_CONFIGURED','WEATHER_CREDENTIALS','WEATHER_ARCHIVE_KEY'].includes(code));await pool.query("UPDATE weather_sync_runs SET state=$2,error_code=$3,completed_at=now(),response_sha256=$4,encrypted_response=$5 WHERE id=$1 AND state='running'",[id,code==='WEATHER_PREVIOUS_RESULT_UNKNOWN'||code==='WEATHER_LEASE_LOST'?'unknown':blocked?'blocked':'failed',code,responseSha,encrypted]);}
 finally{if(attempted)await transaction(c=>recordUsage(c,{objectId:run.object_id,category:'weather',businessKey:'weather-request:'+id,occurredAt:attemptedAt!,units:1,amount:null}),pool);}
}
export async function listConnections(c:PoolClient,a:Actor){const ids=await listAccessibleObjects(c,a,'configure'),connections=(await c.query('SELECT w.*,s.name AS source_name FROM weather_connections w JOIN data_sources s ON s.id=w.source_id WHERE w.object_id=ANY($1::uuid[]) ORDER BY w.configured_at DESC LIMIT 200',[ids])).rows;const runs=(await c.query('SELECT id,connection_id,configuration_version,state,created_at,started_at,attempted_at,completed_at,error_code,response_sha256,record_ids FROM weather_sync_runs WHERE object_id=ANY($1::uuid[]) ORDER BY created_at DESC LIMIT 200',[ids])).rows;return {connections,runs,globalReadsEnabled:process.env.QWEATHER_READS_ENABLED==='1',credentialsConfigured:!!(process.env.QWEATHER_PRIVATE_KEY&&process.env.QWEATHER_KEY_ID&&process.env.QWEATHER_DEVELOPER_ID&&process.env.QWEATHER_PROJECT_ID),contract:QWEATHER_CONTRACT};}
